-- 5fb1b9e0e1af0600177097ab Guptas  321 to 545 AD

army['5fb1b9e0e1af0600177097ab']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
      'Forest',
      'Hilly',
    },
    name='Guptas  321 to 545 AD',
    id='5fb1b9e0e1af0600177097ab',
    dateRange={
      startDate=321,
      endDate=545,
    },
  },
  g_base_definitions[g_str_68c995d9579163001588968a_general],
  g_base_definitions[g_str_68c995d9579163001588968a],
  g_base_definitions[g_str_68c995d9579163001588968d_general],
  g_base_definitions[g_str_68c995d9579163001588968d],
  g_base_definitions[g_str_68c995d9579163001588968f],
  g_base_definitions[g_str_68c995d95791630015889691],
  g_base_definitions[g_str_68c995d95791630015889693],
  g_base_definitions[g_str_68c995d95791630015889693_elephant_screen],
  g_base_definitions[g_str_68c995d95791630015889693_shower_shooting],
  g_base_definitions[g_str_68c995d95791630015889697],
  g_base_definitions[g_str_68c995d95791630015889697_elephant_screen],
  g_base_definitions[g_str_68c995d9579163001588969a],
  g_base_definitions[g_str_5fb1b9e0e1af0600177097ab_camp],
  g_base_definitions[g_str_5fb1b9e0e1af0600177097ab_camp_fortified],
  g_base_definitions[g_str_5fb1b9e0e1af0600177097ab_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e0e1af0600177097ab"] = army["5fb1b9e0e1af0600177097ab"]
if nil == armies["India and the Khyber Pass"] then
  armies["India and the Khyber Pass"] ={}
end
armies["India and the Khyber Pass"]["Guptas  321 to 545 AD"] = army["5fb1b9e0e1af0600177097ab"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Guptas  321 to 545 AD"] = army["5fb1b9e0e1af0600177097ab"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e0e1af0600177097ab"] = {}
army_dates["5fb1b9e0e1af0600177097ab"]["321 AD to 545 AD"] = {
  startDate=321,
  endDate=545
}
