-- 5fb1b9d8e1af0600177092d8 Harappan and Pre-Vedic Indian  2700 to 1500 BC

army['5fb1b9d8e1af0600177092d8']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Delta',
    },
    name='Harappan and Pre-Vedic Indian  2700 to 1500 BC',
    id='5fb1b9d8e1af0600177092d8',
    dateRange={
      startDate=-2700,
      endDate=-1500,
    },
  },
  g_base_definitions[g_str_68c995d257916300158883c5_general],
  g_base_definitions[g_str_68c995d257916300158883c5],
  g_base_definitions[g_str_68c995d257916300158883c6_general],
  g_base_definitions[g_str_68c995d257916300158883c6],
  g_base_definitions[g_str_68c995d257916300158883c9_general],
  g_base_definitions[g_str_68c995d257916300158883c9],
  g_base_definitions[g_str_68c995d257916300158883cb],
  g_base_definitions[g_str_68c995d257916300158883cb_shower_shooting],
  g_base_definitions[g_str_68c995d257916300158883ce],
  g_base_definitions[g_str_68c995d257916300158883d0],
  g_base_definitions[g_str_5fb1b9d8e1af0600177092d8_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9d8e1af0600177092d8"] = army["5fb1b9d8e1af0600177092d8"]
if nil == armies["Cradle of Civilization"] then
  armies["Cradle of Civilization"] ={}
end
armies["Cradle of Civilization"]["Harappan and Pre-Vedic Indian  2700 to 1500 BC"] = army["5fb1b9d8e1af0600177092d8"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Harappan and Pre-Vedic Indian  2700 to 1500 BC"] = army["5fb1b9d8e1af0600177092d8"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9d8e1af0600177092d8"] = {}
army_dates["5fb1b9d8e1af0600177092d8"]["2700 BC to 1500 BC"] = {
  startDate=-2700,
  endDate=-1500
}
