-- 5fb1b9eae1af060017709e1e Cuman  1054 to 1394 AD

army['5fb1b9eae1af060017709e1e']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Steppe',
    },
    name='Cuman  1054 to 1394 AD',
    id='5fb1b9eae1af060017709e1e',
    dateRange={
      startDate=1054,
      endDate=1394,
    },
  },
  g_base_definitions[g_str_68c995e2579163001588ae93_general],
  g_base_definitions[g_str_68c995e2579163001588ae93],
  g_base_definitions[g_str_68c995e2579163001588ae95],
  g_base_definitions[g_str_68c995e2579163001588ae98],
  g_base_definitions[g_str_68c995e2579163001588ae9b],
  g_base_definitions[g_str_68c995e2579163001588ae9e],
  g_base_definitions[g_str_5fb1b9eae1af060017709e1e_camp],
  g_base_definitions[g_str_5fb1b9eae1af060017709e1e_camp_fortified],
  g_base_definitions[g_str_5fb1b9eae1af060017709e1e_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eae1af060017709e1e"] = army["5fb1b9eae1af060017709e1e"]
if nil == armies["Russian Princes"] then
  armies["Russian Princes"] ={}
end
armies["Russian Princes"]["Cuman  1054 to 1394 AD"] = army["5fb1b9eae1af060017709e1e"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Cuman  1054 to 1394 AD"] = army["5fb1b9eae1af060017709e1e"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Cuman  1054 to 1394 AD"] = army["5fb1b9eae1af060017709e1e"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eae1af060017709e1e"] = {}
army_dates["5fb1b9eae1af060017709e1e"]["1054 AD to 1394 AD"] = {
  startDate=1054,
  endDate=1394
}
army_dates["5fb1b9eae1af060017709e1e"]["1054 AD to 1239 AD"] = {
  startDate=1054,
  endDate=1239
}
army_dates["5fb1b9eae1af060017709e1e"]["1240 AD to 1269 AD"] = {
  startDate=1240,
  endDate=1269
}
army_dates["5fb1b9eae1af060017709e1e"]["1270 AD to 1394 AD"] = {
  startDate=1270,
  endDate=1394
}
