-- 5fb1b9dce1af060017709557 Massalian  400 to 49 BC

army['5fb1b9dce1af060017709557']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Massalian  400 to 49 BC',
    id='5fb1b9dce1af060017709557',
    dateRange={
      startDate=-400,
      endDate=-49,
    },
  },
  g_base_definitions[g_str_68c995d75791630015888d48_general],
  g_base_definitions[g_str_68c995d75791630015888d48],
  g_base_definitions[g_str_68c995d75791630015888d4a],
  g_base_definitions[g_str_68c995d75791630015888d4c_general],
  g_base_definitions[g_str_68c995d75791630015888d4c],
  g_base_definitions[g_str_68c995d75791630015888d4f],
  g_base_definitions[g_str_68c995d75791630015888d51],
  g_base_definitions[g_str_68c995d75791630015888d53],
  g_base_definitions[g_str_68c995d75791630015888d55],
  g_base_definitions[g_str_5fb1b9dce1af060017709557_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dce1af060017709557"] = army["5fb1b9dce1af060017709557"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Massalian  400 to 49 BC"] = army["5fb1b9dce1af060017709557"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Massalian  400 to 49 BC"] = army["5fb1b9dce1af060017709557"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Massalian  400 to 49 BC"] = army["5fb1b9dce1af060017709557"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dce1af060017709557"] = {}
army_dates["5fb1b9dce1af060017709557"]["400 BC to 49 BC"] = {
  startDate=-400,
  endDate=-49
}
army_dates["5fb1b9dce1af060017709557"]["400 BC to 276 BC"] = {
  startDate=-400,
  endDate=-276
}
army_dates["5fb1b9dce1af060017709557"]["275 BC to 219 BC"] = {
  startDate=-275,
  endDate=-219
}
army_dates["5fb1b9dce1af060017709557"]["218 BC to 124 BC"] = {
  startDate=-218,
  endDate=-124
}
army_dates["5fb1b9dce1af060017709557"]["123 BC to 106 BC"] = {
  startDate=-123,
  endDate=-106
}
army_dates["5fb1b9dce1af060017709557"]["105 BC"] = {
  startDate=-105,
  endDate=-105
}
army_dates["5fb1b9dce1af060017709557"]["104 BC to 100 BC"] = {
  startDate=-104,
  endDate=-100
}
army_dates["5fb1b9dce1af060017709557"]["99 BC to 50 BC"] = {
  startDate=-99,
  endDate=-50
}
army_dates["5fb1b9dce1af060017709557"]["49 BC"] = {
  startDate=-49,
  endDate=-49
}
