-- 5fb1b9ede1af060017709f93 Later Georgian  1121 to 1683 AD

army['5fb1b9ede1af060017709f93']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Hilly',
    },
    name='Later Georgian  1121 to 1683 AD',
    id='5fb1b9ede1af060017709f93',
    dateRange={
      startDate=1121,
      endDate=1683,
    },
  },
  g_base_definitions[g_str_68c995e5579163001588b548_general],
  g_base_definitions[g_str_68c995e5579163001588b548],
  g_base_definitions[g_str_68c995e5579163001588b54b],
  g_base_definitions[g_str_68c995e5579163001588b54d_general],
  g_base_definitions[g_str_68c995e5579163001588b54d],
  g_base_definitions[g_str_68c995e5579163001588b54f],
  g_base_definitions[g_str_68c995e5579163001588b551],
  g_base_definitions[g_str_68c995e5579163001588b553],
  g_base_definitions[g_str_68c995e5579163001588b555],
  g_base_definitions[g_str_68c995e5579163001588b558],
  g_base_definitions[g_str_5fb1b9ede1af060017709f93_camp],
  g_base_definitions[g_str_5fb1b9ede1af060017709f93_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ede1af060017709f93"] = army["5fb1b9ede1af060017709f93"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Later Georgian  1121 to 1683 AD"] = army["5fb1b9ede1af060017709f93"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Later Georgian  1121 to 1683 AD"] = army["5fb1b9ede1af060017709f93"]
if nil == armies["Byzantium in Decay"] then
  armies["Byzantium in Decay"] ={}
end
armies["Byzantium in Decay"]["Later Georgian  1121 to 1683 AD"] = army["5fb1b9ede1af060017709f93"]
if nil == armies["Crusader Kingdoms"] then
  armies["Crusader Kingdoms"] ={}
end
armies["Crusader Kingdoms"]["Later Georgian  1121 to 1683 AD"] = army["5fb1b9ede1af060017709f93"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Georgian  1121 to 1683 AD"] = army["5fb1b9ede1af060017709f93"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ede1af060017709f93"] = {}
army_dates["5fb1b9ede1af060017709f93"]["1121 AD to 1683 AD"] = {
  startDate=1121,
  endDate=1683
}
