-- 5fb1b9dfe1af060017709736 Early Pontic  302 to 111 BC

army['5fb1b9dfe1af060017709736']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Hilly',
    },
    name='Early Pontic  302 to 111 BC',
    id='5fb1b9dfe1af060017709736',
    dateRange={
      startDate=-302,
      endDate=-111,
    },
  },
  g_base_definitions[g_str_68c995d957916300158894eb_general],
  g_base_definitions[g_str_68c995d957916300158894eb],
  g_base_definitions[g_str_68c995d957916300158894ed],
  g_base_definitions[g_str_68c995d957916300158894ef],
  g_base_definitions[g_str_68c995d957916300158894f1],
  g_base_definitions[g_str_68c995d957916300158894f3],
  g_base_definitions[g_str_68c995d957916300158894f3_shower_shooting],
  g_base_definitions[g_str_68c995d957916300158894f6],
  g_base_definitions[g_str_68c995d957916300158894f8],
  g_base_definitions[g_str_68c995d957916300158894fa],
  g_base_definitions[g_str_5fb1b9dfe1af060017709736_camp],
  g_base_definitions[g_str_5fb1b9dfe1af060017709736_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dfe1af060017709736"] = army["5fb1b9dfe1af060017709736"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Early Pontic  302 to 111 BC"] = army["5fb1b9dfe1af060017709736"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Early Pontic  302 to 111 BC"] = army["5fb1b9dfe1af060017709736"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Pontic  302 to 111 BC"] = army["5fb1b9dfe1af060017709736"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dfe1af060017709736"] = {}
army_dates["5fb1b9dfe1af060017709736"]["302 BC to 111 BC"] = {
  startDate=-302,
  endDate=-111
}
