-- 5fb1b9e6e1af060017709b69 Songhai  900 to 1255 AD

army['5fb1b9e6e1af060017709b69']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Dry',
      'Steppe',
    },
    name='Songhai  900 to 1255 AD',
    id='5fb1b9e6e1af060017709b69',
    dateRange={
      startDate=900,
      endDate=1255,
    },
  },
  g_base_definitions[g_str_68c995df579163001588a3ae_general],
  g_base_definitions[g_str_68c995df579163001588a3ae],
  g_base_definitions[g_str_68c995df579163001588a3b0_general],
  g_base_definitions[g_str_68c995df579163001588a3b0],
  g_base_definitions[g_str_68c995df579163001588a3b2],
  g_base_definitions[g_str_68c995df579163001588a3b4],
  g_base_definitions[g_str_68c995df579163001588a3b4_shower_shooting],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b69_camp],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b69_camp_fortified],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b69_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e6e1af060017709b69"] = army["5fb1b9e6e1af060017709b69"]
if nil == armies["Sahel Africa"] then
  armies["Sahel Africa"] ={}
end
armies["Sahel Africa"]["Songhai  900 to 1255 AD"] = army["5fb1b9e6e1af060017709b69"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Songhai  900 to 1255 AD"] = army["5fb1b9e6e1af060017709b69"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e6e1af060017709b69"] = {}
army_dates["5fb1b9e6e1af060017709b69"]["900 AD to 1255 AD"] = {
  startDate=900,
  endDate=1255
}
