-- 5fb1b9e4e1af0600177099de Justinian Decline  560 to 578 AD

army['5fb1b9e4e1af0600177099de']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      3,
      4,
    },
    homeTopographies={
      'Arable',
      'Dry',
      'Hilly',
    },
    name='Justinian Decline  560 to 578 AD',
    id='5fb1b9e4e1af0600177099de',
    dateRange={
      startDate=560,
      endDate=578,
    },
  },
  g_base_definitions[g_str_68c995dd5791630015889e45_general],
  g_base_definitions[g_str_68c995dd5791630015889e45_general_shower_shooting],
  g_base_definitions[g_str_68c995dd5791630015889e45],
  g_base_definitions[g_str_68c995dd5791630015889e45_shower_shooting],
  g_base_definitions[g_str_68c995dd5791630015889e48_general],
  g_base_definitions[g_str_68c995dd5791630015889e48],
  g_base_definitions[g_str_68c995dd5791630015889e4a],
  g_base_definitions[g_str_68c995dd5791630015889e4d],
  g_base_definitions[g_str_68c995dd5791630015889e4d_shower_shooting],
  g_base_definitions[g_str_68c995dd5791630015889e4e],
  g_base_definitions[g_str_68c995dd5791630015889e4e_shower_shooting],
  g_base_definitions[g_str_68c995dd5791630015889e52],
  g_base_definitions[g_str_68c995dd5791630015889e54],
  g_base_definitions[g_str_5fb1b9e4e1af0600177099de_camp],
  g_base_definitions[g_str_5fb1b9e4e1af0600177099de_camp_fortified],
  g_base_definitions[g_str_5fb1b9e4e1af0600177099de_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e4e1af0600177099de"] = army["5fb1b9e4e1af0600177099de"]
if nil == armies["Dark Ages"] then
  armies["Dark Ages"] ={}
end
armies["Dark Ages"]["Justinian Decline  560 to 578 AD"] = army["5fb1b9e4e1af0600177099de"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Justinian Decline  560 to 578 AD"] = army["5fb1b9e4e1af0600177099de"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e4e1af0600177099de"] = {}
army_dates["5fb1b9e4e1af0600177099de"]["560 AD to 578 AD"] = {
  startDate=560,
  endDate=578
}
army_dates["5fb1b9e4e1af0600177099de"]["560 AD to 561 AD"] = {
  startDate=560,
  endDate=561
}
army_dates["5fb1b9e4e1af0600177099de"]["562 AD to 567 AD"] = {
  startDate=562,
  endDate=567
}
army_dates["5fb1b9e4e1af0600177099de"]["568 AD to 578 AD"] = {
  startDate=568,
  endDate=578
}
