-- 5fb1b9e6e1af060017709b50 Lambert Simnel's Rebellion  1487 to 1487 AD

army['5fb1b9e6e1af060017709b50']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
    },
    name='Lambert Simnel\'s Rebellion  1487 to 1487 AD',
    id='5fb1b9e6e1af060017709b50',
    dateRange={
      startDate=1487,
      endDate=1487,
    },
  },
  g_base_definitions[g_str_68c995df579163001588a372_general],
  g_base_definitions[g_str_68c995df579163001588a372_general_mounted],
  g_base_definitions[g_str_68c995df579163001588a372_general_dismounted],
  g_base_definitions[g_str_68c995df579163001588a372],
  g_base_definitions[g_str_68c995df579163001588a372_mounted],
  g_base_definitions[g_str_68c995df579163001588a372_dismounted],
  g_base_definitions[g_str_68c995df579163001588a375],
  g_base_definitions[g_str_68c995df579163001588a375_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995df579163001588a375_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995df579163001588a379],
  g_base_definitions[g_str_68c995df579163001588a379_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995df579163001588a379_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995df579163001588a37c],
  g_base_definitions[g_str_68c995df579163001588a37e],
  g_base_definitions[g_str_68c995df579163001588a380],
  g_base_definitions[g_str_68c995df579163001588a382],
  g_base_definitions[g_str_68c995df579163001588a384],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b50_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e6e1af060017709b50"] = army["5fb1b9e6e1af060017709b50"]
if nil == armies["Embattled Isle"] then
  armies["Embattled Isle"] ={}
end
armies["Embattled Isle"]["Lambert Simnel\'s Rebellion  1487 to 1487 AD"] = army["5fb1b9e6e1af060017709b50"]
if nil == armies["Plate and Handgonne"] then
  armies["Plate and Handgonne"] ={}
end
armies["Plate and Handgonne"]["Lambert Simnel\'s Rebellion  1487 to 1487 AD"] = army["5fb1b9e6e1af060017709b50"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Lambert Simnel\'s Rebellion  1487 to 1487 AD"] = army["5fb1b9e6e1af060017709b50"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e6e1af060017709b50"] = {}
army_dates["5fb1b9e6e1af060017709b50"]["1487 AD"] = {
  startDate=1487,
  endDate=1487
}
