-- 5fb1b9eae1af060017709dab St. George's Night Uprising  1343 to 1345 AD

army['5fb1b9eae1af060017709dab']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      4,
    },
    homeTopographies={
      'Forest',
    },
    name='St. George\'s Night Uprising  1343 to 1345 AD',
    id='5fb1b9eae1af060017709dab',
    dateRange={
      startDate=1343,
      endDate=1345,
    },
    ambush=true,  },
  g_base_definitions[g_str_68c995e2579163001588acd0_general],
  g_base_definitions[g_str_68c995e2579163001588acd0],
  g_base_definitions[g_str_68c995e2579163001588acd2_general],
  g_base_definitions[g_str_68c995e2579163001588acd2_general_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e2579163001588acd2_general_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e2579163001588acd2],
  g_base_definitions[g_str_68c995e2579163001588acd2_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e2579163001588acd2_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e2579163001588acd5_general],
  g_base_definitions[g_str_68c995e2579163001588acd5],
  g_base_definitions[g_str_68c995e2579163001588acd7],
  g_base_definitions[g_str_68c995e2579163001588acd7_shower_shooting],
  g_base_definitions[g_str_68c995e2579163001588acd8],
  g_base_definitions[g_str_68c995e2579163001588acd8_shower_shooting],
  g_base_definitions[g_str_5fb1b9eae1af060017709dab_camp],
  g_base_definitions[g_str_5fb1b9eae1af060017709dab_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eae1af060017709dab"] = army["5fb1b9eae1af060017709dab"]
if nil == armies["Russian Princes"] then
  armies["Russian Princes"] ={}
end
armies["Russian Princes"]["St. George\'s Night Uprising  1343 to 1345 AD"] = army["5fb1b9eae1af060017709dab"]
if nil == armies["Baltic Powers"] then
  armies["Baltic Powers"] ={}
end
armies["Baltic Powers"]["St. George\'s Night Uprising  1343 to 1345 AD"] = army["5fb1b9eae1af060017709dab"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["St. George\'s Night Uprising  1343 to 1345 AD"] = army["5fb1b9eae1af060017709dab"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eae1af060017709dab"] = {}
army_dates["5fb1b9eae1af060017709dab"]["1343 AD to 1345 AD"] = {
  startDate=1343,
  endDate=1345
}
