-- 5fb1b9dae1af0600177093bb Later Mycenaean and Trojan War  1250 to 1190 BC

army['5fb1b9dae1af0600177093bb']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Later Mycenaean and Trojan War  1250 to 1190 BC',
    id='5fb1b9dae1af0600177093bb',
    dateRange={
      startDate=-1250,
      endDate=-1190,
    },
  },
  g_base_definitions[g_str_68c995d357916300158886d3_general],
  g_base_definitions[g_str_68c995d357916300158886d3],
  g_base_definitions[g_str_68c995d357916300158886d5],
  g_base_definitions[g_str_68c995d357916300158886d7],
  g_base_definitions[g_str_68c995d357916300158886d9],
  g_base_definitions[g_str_68c995d357916300158886da],
  g_base_definitions[g_str_68c995d357916300158886dc],
  g_base_definitions[g_str_68c995d357916300158886de],
  g_base_definitions[g_str_68c995d357916300158886de_shower_shooting],
  g_base_definitions[g_str_68c995d357916300158886e1],
  g_base_definitions[g_str_68c995d357916300158886e2],
  g_base_definitions[g_str_68c995d357916300158886e4],
  g_base_definitions[g_str_5fb1b9dae1af0600177093bb_camp],
  g_base_definitions[g_str_5fb1b9dae1af0600177093bb_camp_fortified],
  g_base_definitions[g_str_68c995c45791630015886b82_general],
  g_base_definitions[g_str_68c995c45791630015886b82],
  g_base_definitions[g_str_68c995c45791630015886b84],
  g_base_definitions[g_str_68c995c45791630015886b86],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dae1af0600177093bb"] = army["5fb1b9dae1af0600177093bb"]
if nil == armies["Chariot Supremacy"] then
  armies["Chariot Supremacy"] ={}
end
armies["Chariot Supremacy"]["Later Mycenaean and Trojan War  1250 to 1190 BC"] = army["5fb1b9dae1af0600177093bb"]
if nil == armies["Sea Peoples Invasions"] then
  armies["Sea Peoples Invasions"] ={}
end
armies["Sea Peoples Invasions"]["Later Mycenaean and Trojan War  1250 to 1190 BC"] = army["5fb1b9dae1af0600177093bb"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Mycenaean and Trojan War  1250 to 1190 BC"] = army["5fb1b9dae1af0600177093bb"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dae1af0600177093bb"] = {}
army_dates["5fb1b9dae1af0600177093bb"]["1250 BC to 1190 BC"] = {
  startDate=-1250,
  endDate=-1190
}
