-- 5fb1b9e7e1af060017709bcb Zirid Emirate of Mahdia  1054 to 1152 AD

army['5fb1b9e7e1af060017709bcb']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
      'Dry',
    },
    name='Zirid Emirate of Mahdia  1054 to 1152 AD',
    id='5fb1b9e7e1af060017709bcb',
    dateRange={
      startDate=1054,
      endDate=1152,
    },
  },
  g_base_definitions[g_str_68c995df579163001588a4d7_general],
  g_base_definitions[g_str_68c995df579163001588a4d7],
  g_base_definitions[g_str_68c995df579163001588a4d9_general],
  g_base_definitions[g_str_68c995df579163001588a4d9],
  g_base_definitions[g_str_68c995df579163001588a4db],
  g_base_definitions[g_str_68c995df579163001588a4dd],
  g_base_definitions[g_str_68c995df579163001588a4e0],
  g_base_definitions[g_str_68c995df579163001588a4e2],
  g_base_definitions[g_str_68c995df579163001588a4e2_shower_shooting],
  g_base_definitions[g_str_68c995df579163001588a4e3],
  g_base_definitions[g_str_68c995df579163001588a4e3_shower_shooting],
  g_base_definitions[g_str_5fb1b9e7e1af060017709bcb_camp],
  g_base_definitions[g_str_5fb1b9e7e1af060017709bcb_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e7e1af060017709bcb"] = army["5fb1b9e7e1af060017709bcb"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Zirid Emirate of Mahdia  1054 to 1152 AD"] = army["5fb1b9e7e1af060017709bcb"]
if nil == armies["Spread of Islam"] then
  armies["Spread of Islam"] ={}
end
armies["Spread of Islam"]["Zirid Emirate of Mahdia  1054 to 1152 AD"] = army["5fb1b9e7e1af060017709bcb"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Zirid Emirate of Mahdia  1054 to 1152 AD"] = army["5fb1b9e7e1af060017709bcb"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e7e1af060017709bcb"] = {}
army_dates["5fb1b9e7e1af060017709bcb"]["1054 AD to 1152 AD"] = {
  startDate=1054,
  endDate=1152
}
