-- 5fb1b9dde1af0600177095ce Early Atropatene  320 to 145 BC

army['5fb1b9dde1af0600177095ce']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Hilly',
    },
    name='Early Atropatene  320 to 145 BC',
    id='5fb1b9dde1af0600177095ce',
    dateRange={
      startDate=-320,
      endDate=-145,
    },
  },
  g_base_definitions[g_str_68c995d75791630015888f09_general],
  g_base_definitions[g_str_68c995d75791630015888f09],
  g_base_definitions[g_str_68c995d75791630015888f0d_general],
  g_base_definitions[g_str_68c995d75791630015888f0d],
  g_base_definitions[g_str_68c995d75791630015888f0e],
  g_base_definitions[g_str_68c995d75791630015888f10],
  g_base_definitions[g_str_68c995d75791630015888f12],
  g_base_definitions[g_str_68c995d75791630015888f14],
  g_base_definitions[g_str_68c995d75791630015888f16],
  g_base_definitions[g_str_68c995d75791630015888f16_shower_shooting],
  g_base_definitions[g_str_5fb1b9dde1af0600177095ce_camp],
  g_base_definitions[g_str_5fb1b9dde1af0600177095ce_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dde1af0600177095ce"] = army["5fb1b9dde1af0600177095ce"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Early Atropatene  320 to 145 BC"] = army["5fb1b9dde1af0600177095ce"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Early Atropatene  320 to 145 BC"] = army["5fb1b9dde1af0600177095ce"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Atropatene  320 to 145 BC"] = army["5fb1b9dde1af0600177095ce"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dde1af0600177095ce"] = {}
army_dates["5fb1b9dde1af0600177095ce"]["320 BC to 145 BC"] = {
  startDate=-320,
  endDate=-145
}
