-- 5fb1b9f5e1af06001770a40c Mixtec or Zapotec  1280 to 1400 AD

army['5fb1b9f5e1af06001770a40c']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      2,
      1,
    },
    homeTopographies={
      'Hilly',
    },
    name='Mixtec or Zapotec  1280 to 1400 AD',
    id='5fb1b9f5e1af06001770a40c',
    dateRange={
      startDate=1280,
      endDate=1400,
    },
    ambush=true,  },
  g_base_definitions[g_str_68c995eb579163001588c534_general],
  g_base_definitions[g_str_68c995eb579163001588c534],
  g_base_definitions[g_str_68c995eb579163001588c536_general],
  g_base_definitions[g_str_68c995eb579163001588c536],
  g_base_definitions[g_str_68c995eb579163001588c538],
  g_base_definitions[g_str_68c995eb579163001588c53a],
  g_base_definitions[g_str_5fb1b9f5e1af06001770a40c_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f5e1af06001770a40c"] = army["5fb1b9f5e1af06001770a40c"]
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["Mixtec or Zapotec  1280 to 1400 AD"] = army["5fb1b9f5e1af06001770a40c"]
if nil == armies["Mexico"] then
  armies["Mexico"] ={}
end
armies["Mexico"]["Mixtec or Zapotec  1280 to 1400 AD"] = army["5fb1b9f5e1af06001770a40c"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Mixtec or Zapotec  1280 to 1400 AD"] = army["5fb1b9f5e1af06001770a40c"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f5e1af06001770a40c"] = {}
army_dates["5fb1b9f5e1af06001770a40c"]["1280 AD to 1400 AD"] = {
  startDate=1280,
  endDate=1400
}
