-- 5fb1b9f5e1af06001770a3aa Early Classic Maya  201 to 599 AD

army['5fb1b9f5e1af06001770a3aa']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Forest',
    },
    name='Early Classic Maya  201 to 599 AD',
    id='5fb1b9f5e1af06001770a3aa',
    dateRange={
      startDate=201,
      endDate=599,
    },
    ambush=true,  },
  g_base_definitions[g_str_68c995ea579163001588c482_general],
  g_base_definitions[g_str_68c995ea579163001588c482],
  g_base_definitions[g_str_68c995ea579163001588c484_general],
  g_base_definitions[g_str_68c995ea579163001588c484],
  g_base_definitions[g_str_68c995ea579163001588c485],
  g_base_definitions[g_str_68c995ea579163001588c487],
  g_base_definitions[g_str_5fb1b9f5e1af06001770a3aa_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f5e1af06001770a3aa"] = army["5fb1b9f5e1af06001770a3aa"]
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["Early Classic Maya  201 to 599 AD"] = army["5fb1b9f5e1af06001770a3aa"]
if nil == armies["Mexico"] then
  armies["Mexico"] ={}
end
armies["Mexico"]["Early Classic Maya  201 to 599 AD"] = army["5fb1b9f5e1af06001770a3aa"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Classic Maya  201 to 599 AD"] = army["5fb1b9f5e1af06001770a3aa"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f5e1af06001770a3aa"] = {}
army_dates["5fb1b9f5e1af06001770a3aa"]["201 AD to 599 AD"] = {
  startDate=201,
  endDate=599
}
