-- 5fb1b9f2e1af06001770a226 Three Kingdoms and Western Jin Chinese  189 to 316 AD

army['5fb1b9f2e1af06001770a226']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      0,
      1,
    },
    homeTopographies={
      'Hilly',
      'Arable',
      'Forest',
      'Arable',
      'Arable',
    },
    name='Three Kingdoms and Western Jin Chinese  189 to 316 AD',
    id='5fb1b9f2e1af06001770a226',
    dateRange={
      startDate=189,
      endDate=316,
    },
  },
  g_base_definitions[g_str_68c995e8579163001588bed5_general],
  g_base_definitions[g_str_68c995e8579163001588bed5],
  g_base_definitions[g_str_68c995e8579163001588bed8_general],
  g_base_definitions[g_str_68c995e8579163001588bed8],
  g_base_definitions[g_str_68c995e8579163001588beda_general],
  g_base_definitions[g_str_68c995e8579163001588beda],
  g_base_definitions[g_str_68c995e8579163001588bedd],
  g_base_definitions[g_str_68c995e8579163001588bedf],
  g_base_definitions[g_str_68c995e8579163001588bee1],
  g_base_definitions[g_str_68c995e8579163001588bee3],
  g_base_definitions[g_str_68c995e8579163001588bee5],
  g_base_definitions[g_str_68c995e8579163001588bee7],
  g_base_definitions[g_str_68c995e8579163001588bee7_shower_shooting],
  g_base_definitions[g_str_68c995e8579163001588beea],
  g_base_definitions[g_str_68c995e8579163001588beec],
  g_base_definitions[g_str_68c995e8579163001588beee],
  g_base_definitions[g_str_68c995e8579163001588bef0],
  g_base_definitions[g_str_68c995e8579163001588bef2],
  g_base_definitions[g_str_68c995e8579163001588bef3],
  g_base_definitions[g_str_5fb1b9f2e1af06001770a226_camp],
  g_base_definitions[g_str_5fb1b9f2e1af06001770a226_camp_fortified],
  g_base_definitions[g_str_5fb1b9f2e1af06001770a226_prepared_defenses],
  g_base_definitions[g_str_68c995cf5791630015887fcf],
  g_base_definitions[g_str_68c995cf5791630015887fd1],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f2e1af06001770a226"] = army["5fb1b9f2e1af06001770a226"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Three Kingdoms and Western Jin Chinese  189 to 316 AD"] = army["5fb1b9f2e1af06001770a226"]
if nil == armies["Dark Ages China"] then
  armies["Dark Ages China"] ={}
end
armies["Dark Ages China"]["Three Kingdoms and Western Jin Chinese  189 to 316 AD"] = army["5fb1b9f2e1af06001770a226"]
if nil == armies["Korea and Japan"] then
  armies["Korea and Japan"] ={}
end
armies["Korea and Japan"]["Three Kingdoms and Western Jin Chinese  189 to 316 AD"] = army["5fb1b9f2e1af06001770a226"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Three Kingdoms and Western Jin Chinese  189 to 316 AD"] = army["5fb1b9f2e1af06001770a226"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f2e1af06001770a226"] = {}
army_dates["5fb1b9f2e1af06001770a226"]["189 AD to 316 AD"] = {
  startDate=189,
  endDate=316
}
army_dates["5fb1b9f2e1af06001770a226"]["189 AD to 280 AD"] = {
  startDate=189,
  endDate=280
}
army_dates["5fb1b9f2e1af06001770a226"]["281 AD to 299 AD"] = {
  startDate=281,
  endDate=299
}
army_dates["5fb1b9f2e1af06001770a226"]["300 AD to 316 AD"] = {
  startDate=300,
  endDate=316
}
