-- 5fb1b9e8e1af060017709c95 Burgundian Ordonnance  1471 to 1477 AD

army['5fb1b9e8e1af060017709c95']={
  data={
    invasionRatings={
      4,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Arable',
    },
    name='Burgundian Ordonnance  1471 to 1477 AD',
    id='5fb1b9e8e1af060017709c95',
    dateRange={
      startDate=1471,
      endDate=1477,
    },
  },
  g_base_definitions[g_str_68c995e0579163001588a7e6_general],
  g_base_definitions[g_str_68c995e0579163001588a7e6_general_mounted],
  g_base_definitions[g_str_68c995e0579163001588a7e6_general_dismounted],
  g_base_definitions[g_str_68c995e0579163001588a7e6],
  g_base_definitions[g_str_68c995e0579163001588a7e6_mounted],
  g_base_definitions[g_str_68c995e0579163001588a7e6_dismounted],
  g_base_definitions[g_str_68c995e0579163001588a7e9],
  g_base_definitions[g_str_68c995e0579163001588a7eb],
  g_base_definitions[g_str_68c995e0579163001588a7eb_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e0579163001588a7eb_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e0579163001588a7ee],
  g_base_definitions[g_str_68c995e0579163001588a7ef],
  g_base_definitions[g_str_68c995e0579163001588a7f1],
  g_base_definitions[g_str_68c995e0579163001588a7f3_general],
  g_base_definitions[g_str_68c995e0579163001588a7f3],
  g_base_definitions[g_str_68c995e0579163001588a7f5],
  g_base_definitions[g_str_68c995e0579163001588a7f7],
  g_base_definitions[g_str_68c995e0579163001588a7f9],
  g_base_definitions[g_str_5fb1b9e8e1af060017709c95_camp],
  g_base_definitions[g_str_5fb1b9e8e1af060017709c95_camp_fortified],
  g_base_definitions[g_str_5fb1b9e8e1af060017709c95_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e8e1af060017709c95"] = army["5fb1b9e8e1af060017709c95"]
if nil == armies["Holy Roman Empire"] then
  armies["Holy Roman Empire"] ={}
end
armies["Holy Roman Empire"]["Burgundian Ordonnance  1471 to 1477 AD"] = army["5fb1b9e8e1af060017709c95"]
if nil == armies["Flower of Chivalry"] then
  armies["Flower of Chivalry"] ={}
end
armies["Flower of Chivalry"]["Burgundian Ordonnance  1471 to 1477 AD"] = army["5fb1b9e8e1af060017709c95"]
if nil == armies["Plate and Handgonne"] then
  armies["Plate and Handgonne"] ={}
end
armies["Plate and Handgonne"]["Burgundian Ordonnance  1471 to 1477 AD"] = army["5fb1b9e8e1af060017709c95"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Burgundian Ordonnance  1471 to 1477 AD"] = army["5fb1b9e8e1af060017709c95"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e8e1af060017709c95"] = {}
army_dates["5fb1b9e8e1af060017709c95"]["1471 AD to 1477 AD"] = {
  startDate=1471,
  endDate=1477
}
army_dates["5fb1b9e8e1af060017709c95"]["1471 AD to 1474 AD"] = {
  startDate=1471,
  endDate=1474
}
army_dates["5fb1b9e8e1af060017709c95"]["1475 AD"] = {
  startDate=1475,
  endDate=1475
}
army_dates["5fb1b9e8e1af060017709c95"]["1476 AD to 1477 AD"] = {
  startDate=1476,
  endDate=1477
}
