-- 5fb1b9d9e1af06001770939c Early Hebrew  1250 to 1000 BC

army['5fb1b9d9e1af06001770939c']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      3,
      4,
    },
    homeTopographies={
      'Hilly',
    },
    name='Early Hebrew  1250 to 1000 BC',
    id='5fb1b9d9e1af06001770939c',
    dateRange={
      startDate=-1250,
      endDate=-1000,
    },
    ambush=true,  },
  g_base_definitions[g_str_68c995d35791630015888683_general],
  g_base_definitions[g_str_68c995d35791630015888683],
  g_base_definitions[g_str_68c995d35791630015888685],
  g_base_definitions[g_str_68c995d35791630015888687],
  g_base_definitions[g_str_68c995d35791630015888687_shower_shooting],
  g_base_definitions[g_str_68c995d3579163001588868a],
  g_base_definitions[g_str_68c995d3579163001588868c_general],
  g_base_definitions[g_str_68c995d3579163001588868c],
  g_base_definitions[g_str_68c995d3579163001588868e],
  g_base_definitions[g_str_5fb1b9d9e1af06001770939c_camp],
  g_base_definitions[g_str_5fb1b9d9e1af06001770939c_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9d9e1af06001770939c"] = army["5fb1b9d9e1af06001770939c"]
if nil == armies["Chariot Supremacy"] then
  armies["Chariot Supremacy"] ={}
end
armies["Chariot Supremacy"]["Early Hebrew  1250 to 1000 BC"] = army["5fb1b9d9e1af06001770939c"]
if nil == armies["Sea Peoples Invasions"] then
  armies["Sea Peoples Invasions"] ={}
end
armies["Sea Peoples Invasions"]["Early Hebrew  1250 to 1000 BC"] = army["5fb1b9d9e1af06001770939c"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Hebrew  1250 to 1000 BC"] = army["5fb1b9d9e1af06001770939c"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9d9e1af06001770939c"] = {}
army_dates["5fb1b9d9e1af06001770939c"]["1250 BC to 1000 BC"] = {
  startDate=-1250,
  endDate=-1000
}
