-- 5fb1b9f5e1af06001770a3b8 Toltec-ruled Mayan Citystates  988 to 1461 AD

army['5fb1b9f5e1af06001770a3b8']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Forest',
    },
    name='Toltec-ruled Mayan Citystates  988 to 1461 AD',
    id='5fb1b9f5e1af06001770a3b8',
    dateRange={
      startDate=988,
      endDate=1461,
    },
    ambush=true,  },
  g_base_definitions[g_str_68c995ea579163001588c496_general],
  g_base_definitions[g_str_68c995ea579163001588c496],
  g_base_definitions[g_str_68c995ea579163001588c499],
  g_base_definitions[g_str_68c995ea579163001588c499_shower_shooting],
  g_base_definitions[g_str_68c995ea579163001588c49c_general],
  g_base_definitions[g_str_68c995ea579163001588c49c],
  g_base_definitions[g_str_68c995ea579163001588c49e_general],
  g_base_definitions[g_str_68c995ea579163001588c49e],
  g_base_definitions[g_str_68c995ea579163001588c4a0],
  g_base_definitions[g_str_68c995ea579163001588c4a2],
  g_base_definitions[g_str_5fb1b9f5e1af06001770a3b8_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f5e1af06001770a3b8"] = army["5fb1b9f5e1af06001770a3b8"]
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["Toltec-ruled Mayan Citystates  988 to 1461 AD"] = army["5fb1b9f5e1af06001770a3b8"]
if nil == armies["Mexico"] then
  armies["Mexico"] ={}
end
armies["Mexico"]["Toltec-ruled Mayan Citystates  988 to 1461 AD"] = army["5fb1b9f5e1af06001770a3b8"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Toltec-ruled Mayan Citystates  988 to 1461 AD"] = army["5fb1b9f5e1af06001770a3b8"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f5e1af06001770a3b8"] = {}
army_dates["5fb1b9f5e1af06001770a3b8"]["988 AD to 1461 AD"] = {
  startDate=988,
  endDate=1461
}
