-- 5fb1b9e6e1af060017709b96 Takrur and Wolof  800 to 1600 AD

army['5fb1b9e6e1af060017709b96']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Takrur and Wolof  800 to 1600 AD',
    id='5fb1b9e6e1af060017709b96',
    dateRange={
      startDate=800,
      endDate=1600,
    },
  },
  g_base_definitions[g_str_68c995df579163001588a412_general],
  g_base_definitions[g_str_68c995df579163001588a412],
  g_base_definitions[g_str_68c995df579163001588a414],
  g_base_definitions[g_str_68c995df579163001588a416],
  g_base_definitions[g_str_68c995df579163001588a416_shower_shooting],
  g_base_definitions[g_str_68c995df579163001588a419],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b96_camp],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b96_camp_fortified],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b96_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e6e1af060017709b96"] = army["5fb1b9e6e1af060017709b96"]
if nil == armies["Sahel Africa"] then
  armies["Sahel Africa"] ={}
end
armies["Sahel Africa"]["Takrur and Wolof  800 to 1600 AD"] = army["5fb1b9e6e1af060017709b96"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Takrur and Wolof  800 to 1600 AD"] = army["5fb1b9e6e1af060017709b96"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e6e1af060017709b96"] = {}
army_dates["5fb1b9e6e1af060017709b96"]["800 AD to 1600 AD"] = {
  startDate=800,
  endDate=1600
}
