-- 5fb1b9dce1af06001770953b Apulian, Lucanian, or Bruttian  420 to 203 BC

army['5fb1b9dce1af06001770953b']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Arable',
      'Hilly',
    },
    name='Apulian, Lucanian, or Bruttian  420 to 203 BC',
    id='5fb1b9dce1af06001770953b',
    dateRange={
      startDate=-420,
      endDate=-203,
    },
  },
  g_base_definitions[g_str_68c995d65791630015888cd0_general],
  g_base_definitions[g_str_68c995d65791630015888cd0],
  g_base_definitions[g_str_68c995d65791630015888cd2_general],
  g_base_definitions[g_str_68c995d65791630015888cd2],
  g_base_definitions[g_str_68c995d65791630015888cd4_general],
  g_base_definitions[g_str_68c995d65791630015888cd4],
  g_base_definitions[g_str_68c995d65791630015888cd6],
  g_base_definitions[g_str_68c995d65791630015888cd8],
  g_base_definitions[g_str_68c995d65791630015888cda],
  g_base_definitions[g_str_5fb1b9dce1af06001770953b_camp],
  g_base_definitions[g_str_5fb1b9dce1af06001770953b_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dce1af06001770953b"] = army["5fb1b9dce1af06001770953b"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Apulian, Lucanian, or Bruttian  420 to 203 BC"] = army["5fb1b9dce1af06001770953b"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Apulian, Lucanian, or Bruttian  420 to 203 BC"] = army["5fb1b9dce1af06001770953b"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Apulian, Lucanian, or Bruttian  420 to 203 BC"] = army["5fb1b9dce1af06001770953b"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dce1af06001770953b"] = {}
army_dates["5fb1b9dce1af06001770953b"]["420 BC to 203 BC"] = {
  startDate=-420,
  endDate=-203
}
army_dates["5fb1b9dce1af06001770953b"]["420 BC to 401 BC"] = {
  startDate=-420,
  endDate=-401
}
army_dates["5fb1b9dce1af06001770953b"]["400 BC to 276 BC"] = {
  startDate=-400,
  endDate=-276
}
army_dates["5fb1b9dce1af06001770953b"]["275 BC to 216 BC"] = {
  startDate=-275,
  endDate=-216
}
army_dates["5fb1b9dce1af06001770953b"]["215 BC"] = {
  startDate=-215,
  endDate=-215
}
army_dates["5fb1b9dce1af06001770953b"]["214 BC to 203 BC"] = {
  startDate=-214,
  endDate=-203
}
