-- 5fb1b9e0e1af0600177097b8 Mountain Indian  500 to 170 BC

army['5fb1b9e0e1af0600177097b8']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Hilly',
    },
    name='Mountain Indian  500 to 170 BC',
    id='5fb1b9e0e1af0600177097b8',
    dateRange={
      startDate=-500,
      endDate=-170,
    },
  },
  g_base_definitions[g_str_68c995d957916300158896b5_general],
  g_base_definitions[g_str_68c995d957916300158896b5],
  g_base_definitions[g_str_68c995d957916300158896b8_general],
  g_base_definitions[g_str_68c995d957916300158896b8],
  g_base_definitions[g_str_68c995d957916300158896ba_general],
  g_base_definitions[g_str_68c995d957916300158896ba],
  g_base_definitions[g_str_68c995d957916300158896bc],
  g_base_definitions[g_str_68c995d957916300158896be],
  g_base_definitions[g_str_68c995d957916300158896be_shower_shooting],
  g_base_definitions[g_str_68c995d957916300158896bf],
  g_base_definitions[g_str_68c995d957916300158896bf_shower_shooting],
  g_base_definitions[g_str_68c995d957916300158896c0],
  g_base_definitions[g_str_68c995d957916300158896c0_shower_shooting],
  g_base_definitions[g_str_68c995d957916300158896c3],
  g_base_definitions[g_str_68c995d957916300158896c3_elephant_screen],
  g_base_definitions[g_str_5fb1b9e0e1af0600177097b8_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e0e1af0600177097b8"] = army["5fb1b9e0e1af0600177097b8"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Mountain Indian  500 to 170 BC"] = army["5fb1b9e0e1af0600177097b8"]
if nil == armies["India and the Khyber Pass"] then
  armies["India and the Khyber Pass"] ={}
end
armies["India and the Khyber Pass"]["Mountain Indian  500 to 170 BC"] = army["5fb1b9e0e1af0600177097b8"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Mountain Indian  500 to 170 BC"] = army["5fb1b9e0e1af0600177097b8"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Mountain Indian  500 to 170 BC"] = army["5fb1b9e0e1af0600177097b8"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e0e1af0600177097b8"] = {}
army_dates["5fb1b9e0e1af0600177097b8"]["500 BC to 170 BC"] = {
  startDate=-500,
  endDate=-170
}
