-- 5fb1b9eae1af060017709df3 Post Mongol Russian  1246 to 1455 AD

army['5fb1b9eae1af060017709df3']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Forest',
    },
    name='Post Mongol Russian  1246 to 1455 AD',
    id='5fb1b9eae1af060017709df3',
    dateRange={
      startDate=1246,
      endDate=1455,
    },
  },
  g_base_definitions[g_str_68c995e2579163001588adf8_general],
  g_base_definitions[g_str_68c995e2579163001588adf8_general_shower_shooting],
  g_base_definitions[g_str_68c995e2579163001588adf8],
  g_base_definitions[g_str_68c995e2579163001588adf8_shower_shooting],
  g_base_definitions[g_str_68c995e2579163001588adfb],
  g_base_definitions[g_str_68c995e2579163001588adfd],
  g_base_definitions[g_str_68c995e2579163001588adff],
  g_base_definitions[g_str_68c995e2579163001588adff_shower_shooting],
  g_base_definitions[g_str_68c995e2579163001588ae03],
  g_base_definitions[g_str_68c995e2579163001588ae06],
  g_base_definitions[g_str_5fb1b9eae1af060017709df3_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eae1af060017709df3"] = army["5fb1b9eae1af060017709df3"]
if nil == armies["Russian Princes"] then
  armies["Russian Princes"] ={}
end
armies["Russian Princes"]["Post Mongol Russian  1246 to 1455 AD"] = army["5fb1b9eae1af060017709df3"]
if nil == armies["Baltic Powers"] then
  armies["Baltic Powers"] ={}
end
armies["Baltic Powers"]["Post Mongol Russian  1246 to 1455 AD"] = army["5fb1b9eae1af060017709df3"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Post Mongol Russian  1246 to 1455 AD"] = army["5fb1b9eae1af060017709df3"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eae1af060017709df3"] = {}
army_dates["5fb1b9eae1af060017709df3"]["1246 AD to 1455 AD"] = {
  startDate=1246,
  endDate=1455
}
army_dates["5fb1b9eae1af060017709df3"]["1246 AD to 1250 AD"] = {
  startDate=1246,
  endDate=1250
}
army_dates["5fb1b9eae1af060017709df3"]["1251 AD to 1379 AD"] = {
  startDate=1251,
  endDate=1379
}
army_dates["5fb1b9eae1af060017709df3"]["1380 AD to 1455 AD"] = {
  startDate=1380,
  endDate=1455
}
