-- 5fb1b9e4e1af060017709a75 Viking West Frisia  840 to 885 AD

army['5fb1b9e4e1af060017709a75']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Marsh',
    },
    name='Viking West Frisia  840 to 885 AD',
    id='5fb1b9e4e1af060017709a75',
    dateRange={
      startDate=840,
      endDate=885,
    },
  },
  g_base_definitions[g_str_68c995dd579163001588a043_general],
  g_base_definitions[g_str_68c995dd579163001588a043],
  g_base_definitions[g_str_68c995dd579163001588a045],
  g_base_definitions[g_str_68c995dd579163001588a047],
  g_base_definitions[g_str_68c995dd579163001588a048],
  g_base_definitions[g_str_68c995dd579163001588a04a],
  g_base_definitions[g_str_68c995dd579163001588a04c],
  g_base_definitions[g_str_68c995dd579163001588a04c_shower_shooting],
  g_base_definitions[g_str_5fb1b9e4e1af060017709a75_camp],
  g_base_definitions[g_str_5fb1b9e4e1af060017709a75_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e4e1af060017709a75"] = army["5fb1b9e4e1af060017709a75"]
if nil == armies["Viking Seas"] then
  armies["Viking Seas"] ={}
end
armies["Viking Seas"]["Viking West Frisia  840 to 885 AD"] = army["5fb1b9e4e1af060017709a75"]
if nil == armies["Holy Roman Empire"] then
  armies["Holy Roman Empire"] ={}
end
armies["Holy Roman Empire"]["Viking West Frisia  840 to 885 AD"] = army["5fb1b9e4e1af060017709a75"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Viking West Frisia  840 to 885 AD"] = army["5fb1b9e4e1af060017709a75"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e4e1af060017709a75"] = {}
army_dates["5fb1b9e4e1af060017709a75"]["840 AD to 885 AD"] = {
  startDate=840,
  endDate=885
}
