-- 5fb1b9d9e1af060017709349 Ancient Libyan  3000 to 2160 BC

army['5fb1b9d9e1af060017709349']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Dry',
    },
    name='Ancient Libyan  3000 to 2160 BC',
    id='5fb1b9d9e1af060017709349',
    dateRange={
      startDate=-3000,
      endDate=-2160,
    },
    ambush=true,  },
  g_base_definitions[g_str_68c995d35791630015888563_general],
  g_base_definitions[g_str_68c995d35791630015888563],
  g_base_definitions[g_str_68c995d35791630015888565_general],
  g_base_definitions[g_str_68c995d35791630015888565],
  g_base_definitions[g_str_68c995d35791630015888567],
  g_base_definitions[g_str_5fb1b9d9e1af060017709349_camp],
  g_base_definitions[g_str_5fb1b9d9e1af060017709349_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9d9e1af060017709349"] = army["5fb1b9d9e1af060017709349"]
if nil == armies["Cradle of Civilization"] then
  armies["Cradle of Civilization"] ={}
end
armies["Cradle of Civilization"]["Ancient Libyan  3000 to 2160 BC"] = army["5fb1b9d9e1af060017709349"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Ancient Libyan  3000 to 2160 BC"] = army["5fb1b9d9e1af060017709349"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9d9e1af060017709349"] = {}
army_dates["5fb1b9d9e1af060017709349"]["3000 BC to 2160 BC"] = {
  startDate=-3000,
  endDate=-2160
}
