-- 5fb1b9dee1af060017709685 Hellenistic Spartan  225 to 195 BC

army['5fb1b9dee1af060017709685']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
    },
    name='Hellenistic Spartan  225 to 195 BC',
    id='5fb1b9dee1af060017709685',
    dateRange={
      startDate=-225,
      endDate=-195,
    },
  },
  g_base_definitions[g_str_68c995d85791630015889213_general],
  g_base_definitions[g_str_68c995d85791630015889213],
  g_base_definitions[g_str_68c995d85791630015889215],
  g_base_definitions[g_str_68c995d85791630015889218],
  g_base_definitions[g_str_68c995d8579163001588921b],
  g_base_definitions[g_str_68c995d8579163001588921f],
  g_base_definitions[g_str_68c995d85791630015889221],
  g_base_definitions[g_str_68c995d85791630015889223],
  g_base_definitions[g_str_68c995d85791630015889224],
  g_base_definitions[g_str_5fb1b9dee1af060017709685_camp],
  g_base_definitions[g_str_5fb1b9dee1af060017709685_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dee1af060017709685"] = army["5fb1b9dee1af060017709685"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Hellenistic Spartan  225 to 195 BC"] = army["5fb1b9dee1af060017709685"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Hellenistic Spartan  225 to 195 BC"] = army["5fb1b9dee1af060017709685"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dee1af060017709685"] = {}
army_dates["5fb1b9dee1af060017709685"]["225 BC to 195 BC"] = {
  startDate=-225,
  endDate=-195
}
