-- 5fb1b9ede1af060017709f9c Syrian Caliphate of Baghdad  1092 to 1258 AD

army['5fb1b9ede1af060017709f9c']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
      'Dry',
    },
    name='Syrian Caliphate of Baghdad  1092 to 1258 AD',
    id='5fb1b9ede1af060017709f9c',
    dateRange={
      startDate=1092,
      endDate=1258,
    },
  },
  g_base_definitions[g_str_68c995e5579163001588b55e_general],
  g_base_definitions[g_str_68c995e5579163001588b55e_general_shower_shooting],
  g_base_definitions[g_str_68c995e5579163001588b55e],
  g_base_definitions[g_str_68c995e5579163001588b55e_shower_shooting],
  g_base_definitions[g_str_68c995e5579163001588b561_general],
  g_base_definitions[g_str_68c995e5579163001588b561],
  g_base_definitions[g_str_68c995e5579163001588b563_general],
  g_base_definitions[g_str_68c995e5579163001588b563],
  g_base_definitions[g_str_68c995e5579163001588b565_general],
  g_base_definitions[g_str_68c995e5579163001588b565],
  g_base_definitions[g_str_68c995e5579163001588b567],
  g_base_definitions[g_str_68c995e5579163001588b569],
  g_base_definitions[g_str_68c995e5579163001588b56b],
  g_base_definitions[g_str_68c995e5579163001588b56d],
  g_base_definitions[g_str_68c995e5579163001588b56f],
  g_base_definitions[g_str_5fb1b9ede1af060017709f9c_camp],
  g_base_definitions[g_str_5fb1b9ede1af060017709f9c_camp_pack_train],
  g_base_definitions[g_str_5fb1b9ede1af060017709f9c_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ede1af060017709f9c"] = army["5fb1b9ede1af060017709f9c"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Syrian Caliphate of Baghdad  1092 to 1258 AD"] = army["5fb1b9ede1af060017709f9c"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Syrian Caliphate of Baghdad  1092 to 1258 AD"] = army["5fb1b9ede1af060017709f9c"]
if nil == armies["Byzantium in Decay"] then
  armies["Byzantium in Decay"] ={}
end
armies["Byzantium in Decay"]["Syrian Caliphate of Baghdad  1092 to 1258 AD"] = army["5fb1b9ede1af060017709f9c"]
if nil == armies["Crusader Kingdoms"] then
  armies["Crusader Kingdoms"] ={}
end
armies["Crusader Kingdoms"]["Syrian Caliphate of Baghdad  1092 to 1258 AD"] = army["5fb1b9ede1af060017709f9c"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Syrian Caliphate of Baghdad  1092 to 1258 AD"] = army["5fb1b9ede1af060017709f9c"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ede1af060017709f9c"] = {}
army_dates["5fb1b9ede1af060017709f9c"]["1092 AD to 1258 AD"] = {
  startDate=1092,
  endDate=1258
}
