-- 5fb1b9f2e1af06001770a21d Tuyuhun  285 to 663 AD

army['5fb1b9f2e1af06001770a21d']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
      3,
    },
    homeTopographies={
      'Hilly',
    },
    name='Tuyuhun  285 to 663 AD',
    id='5fb1b9f2e1af06001770a21d',
    dateRange={
      startDate=285,
      endDate=663,
    },
  },
  g_base_definitions[g_str_68c995e8579163001588bec1_general],
  g_base_definitions[g_str_68c995e8579163001588bec1],
  g_base_definitions[g_str_68c995e8579163001588bec3_general],
  g_base_definitions[g_str_68c995e8579163001588bec3],
  g_base_definitions[g_str_68c995e8579163001588bec5],
  g_base_definitions[g_str_68c995e8579163001588bec7_general],
  g_base_definitions[g_str_68c995e8579163001588bec7],
  g_base_definitions[g_str_68c995e8579163001588bec9],
  g_base_definitions[g_str_68c995e8579163001588bec9_shower_shooting],
  g_base_definitions[g_str_68c995e8579163001588becc],
  g_base_definitions[g_str_5fb1b9f2e1af06001770a21d_camp],
  g_base_definitions[g_str_5fb1b9f2e1af06001770a21d_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f2e1af06001770a21d"] = army["5fb1b9f2e1af06001770a21d"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Tuyuhun  285 to 663 AD"] = army["5fb1b9f2e1af06001770a21d"]
if nil == armies["Dark Ages China"] then
  armies["Dark Ages China"] ={}
end
armies["Dark Ages China"]["Tuyuhun  285 to 663 AD"] = army["5fb1b9f2e1af06001770a21d"]
if nil == armies["Middle Kingdom"] then
  armies["Middle Kingdom"] ={}
end
armies["Middle Kingdom"]["Tuyuhun  285 to 663 AD"] = army["5fb1b9f2e1af06001770a21d"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Tuyuhun  285 to 663 AD"] = army["5fb1b9f2e1af06001770a21d"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f2e1af06001770a21d"] = {}
army_dates["5fb1b9f2e1af06001770a21d"]["285 AD to 663 AD"] = {
  startDate=285,
  endDate=663
}
army_dates["5fb1b9f2e1af06001770a21d"]["285 AD to 617 AD"] = {
  startDate=285,
  endDate=617
}
army_dates["5fb1b9f2e1af06001770a21d"]["618 AD to 635 AD"] = {
  startDate=618,
  endDate=635
}
army_dates["5fb1b9f2e1af06001770a21d"]["636 AD"] = {
  startDate=636,
  endDate=636
}
army_dates["5fb1b9f2e1af06001770a21d"]["637 AD to 663 AD"] = {
  startDate=637,
  endDate=663
}
