-- 5fb1b9e6e1af060017709b6f Songhai Empire  1430 to 1591 AD

army['5fb1b9e6e1af060017709b6f']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Dry',
      'Steppe',
    },
    name='Songhai Empire  1430 to 1591 AD',
    id='5fb1b9e6e1af060017709b6f',
    dateRange={
      startDate=1430,
      endDate=1591,
    },
  },
  g_base_definitions[g_str_68c995df579163001588a3bc_general],
  g_base_definitions[g_str_68c995df579163001588a3bc],
  g_base_definitions[g_str_68c995df579163001588a3be_general],
  g_base_definitions[g_str_68c995df579163001588a3be],
  g_base_definitions[g_str_68c995df579163001588a3c0],
  g_base_definitions[g_str_68c995df579163001588a3c2],
  g_base_definitions[g_str_68c995df579163001588a3c4],
  g_base_definitions[g_str_68c995df579163001588a3c4_shower_shooting],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b6f_camp],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b6f_camp_fortified],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b6f_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e6e1af060017709b6f"] = army["5fb1b9e6e1af060017709b6f"]
if nil == armies["Sahel Africa"] then
  armies["Sahel Africa"] ={}
end
armies["Sahel Africa"]["Songhai Empire  1430 to 1591 AD"] = army["5fb1b9e6e1af060017709b6f"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Songhai Empire  1430 to 1591 AD"] = army["5fb1b9e6e1af060017709b6f"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e6e1af060017709b6f"] = {}
army_dates["5fb1b9e6e1af060017709b6f"]["1430 AD to 1591 AD"] = {
  startDate=1430,
  endDate=1591
}
