-- 5fb1b9e9e1af060017709d7d Crusade of Nicopolis  1396 to 1396 AD

army['5fb1b9e9e1af060017709d7d']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Arable',
    },
    name='Crusade of Nicopolis  1396 to 1396 AD',
    id='5fb1b9e9e1af060017709d7d',
    dateRange={
      startDate=1396,
      endDate=1396,
    },
  },
  g_base_definitions[g_str_68c995e1579163001588abf9_general],
  g_base_definitions[g_str_68c995e1579163001588abf9],
  g_base_definitions[g_str_68c995e1579163001588abfb_general],
  g_base_definitions[g_str_68c995e1579163001588abfb],
  g_base_definitions[g_str_68c995e1579163001588abfd_general],
  g_base_definitions[g_str_68c995e1579163001588abfd],
  g_base_definitions[g_str_68c995e1579163001588abff],
  g_base_definitions[g_str_68c995e1579163001588ac01],
  g_base_definitions[g_str_68c995e1579163001588ac04],
  g_base_definitions[g_str_68c995e1579163001588ac04_shower_shooting],
  g_base_definitions[g_str_68c995e1579163001588ac05],
  g_base_definitions[g_str_68c995e1579163001588ac05_shower_shooting],
  g_base_definitions[g_str_68c995e1579163001588ac09],
  g_base_definitions[g_str_68c995e1579163001588ac09_shower_shooting],
  g_base_definitions[g_str_68c995e1579163001588ac0a],
  g_base_definitions[g_str_68c995e1579163001588ac0a_shower_shooting],
  g_base_definitions[g_str_5fb1b9e9e1af060017709d7d_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e9e1af060017709d7d"] = army["5fb1b9e9e1af060017709d7d"]
if nil == armies["Italy and Balkans"] then
  armies["Italy and Balkans"] ={}
end
armies["Italy and Balkans"]["Crusade of Nicopolis  1396 to 1396 AD"] = army["5fb1b9e9e1af060017709d7d"]
if nil == armies["Holy Roman Empire"] then
  armies["Holy Roman Empire"] ={}
end
armies["Holy Roman Empire"]["Crusade of Nicopolis  1396 to 1396 AD"] = army["5fb1b9e9e1af060017709d7d"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Crusade of Nicopolis  1396 to 1396 AD"] = army["5fb1b9e9e1af060017709d7d"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e9e1af060017709d7d"] = {}
army_dates["5fb1b9e9e1af060017709d7d"]["1396 AD"] = {
  startDate=1396,
  endDate=1396
}
