-- 5fb1b9eae1af060017709e10 Volga Bulgar  675 to 1237 AD

army['5fb1b9eae1af060017709e10']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Forest',
    },
    name='Volga Bulgar  675 to 1237 AD',
    id='5fb1b9eae1af060017709e10',
    dateRange={
      startDate=675,
      endDate=1237,
    },
    ambush=true,  },
  g_base_definitions[g_str_68c995e2579163001588ae74_general],
  g_base_definitions[g_str_68c995e2579163001588ae74],
  g_base_definitions[g_str_68c995e2579163001588ae76_general],
  g_base_definitions[g_str_68c995e2579163001588ae76],
  g_base_definitions[g_str_68c995e2579163001588ae78],
  g_base_definitions[g_str_68c995e2579163001588ae78_shower_shooting],
  g_base_definitions[g_str_68c995e2579163001588ae7b],
  g_base_definitions[g_str_5fb1b9eae1af060017709e10_camp],
  g_base_definitions[g_str_5fb1b9eae1af060017709e10_camp_fortified],
  g_base_definitions[g_str_5fb1b9eae1af060017709e10_camp_pack_train],
  g_base_definitions[g_str_5fb1b9eae1af060017709e10_prepared_defenses],
  g_base_definitions[g_str_68c995cc5791630015887a0b_general],
  g_base_definitions[g_str_68c995cc5791630015887a0b],
  g_base_definitions[g_str_68c995cc5791630015887a0d],
  g_base_definitions[g_str_68c995cc5791630015887a0f],
  g_base_definitions[g_str_68c995cc5791630015887a10],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eae1af060017709e10"] = army["5fb1b9eae1af060017709e10"]
if nil == armies["Russian Princes"] then
  armies["Russian Princes"] ={}
end
armies["Russian Princes"]["Volga Bulgar  675 to 1237 AD"] = army["5fb1b9eae1af060017709e10"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Volga Bulgar  675 to 1237 AD"] = army["5fb1b9eae1af060017709e10"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Volga Bulgar  675 to 1237 AD"] = army["5fb1b9eae1af060017709e10"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eae1af060017709e10"] = {}
army_dates["5fb1b9eae1af060017709e10"]["675 AD to 1237 AD"] = {
  startDate=675,
  endDate=1237
}
army_dates["5fb1b9eae1af060017709e10"]["675 AD to 1053 AD"] = {
  startDate=675,
  endDate=1053
}
army_dates["5fb1b9eae1af060017709e10"]["1054 AD to 1182 AD"] = {
  startDate=1054,
  endDate=1182
}
army_dates["5fb1b9eae1af060017709e10"]["1183 AD to 1184 AD"] = {
  startDate=1183,
  endDate=1184
}
army_dates["5fb1b9eae1af060017709e10"]["1185 AD to 1237 AD"] = {
  startDate=1185,
  endDate=1237
}
