-- 5fb1b9f4e1af06001770a35d Later Heian and Kamakura Samurai  1020 to 1300 AD

army['5fb1b9f4e1af06001770a35d']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
      'Hilly',
    },
    name='Later Heian and Kamakura Samurai  1020 to 1300 AD',
    id='5fb1b9f4e1af06001770a35d',
    dateRange={
      startDate=1020,
      endDate=1300,
    },
  },
  g_base_definitions[g_str_68c995ea579163001588c3d4_general],
  g_base_definitions[g_str_68c995ea579163001588c3d4],
  g_base_definitions[g_str_68c995ea579163001588c3d6],
  g_base_definitions[g_str_68c995ea579163001588c3d8],
  g_base_definitions[g_str_68c995ea579163001588c3da],
  g_base_definitions[g_str_68c995ea579163001588c3dc],
  g_base_definitions[g_str_5fb1b9f4e1af06001770a35d_camp],
  g_base_definitions[g_str_5fb1b9f4e1af06001770a35d_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f4e1af06001770a35d"] = army["5fb1b9f4e1af06001770a35d"]
if nil == armies["Korea and Japan"] then
  armies["Korea and Japan"] ={}
end
armies["Korea and Japan"]["Later Heian and Kamakura Samurai  1020 to 1300 AD"] = army["5fb1b9f4e1af06001770a35d"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Heian and Kamakura Samurai  1020 to 1300 AD"] = army["5fb1b9f4e1af06001770a35d"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f4e1af06001770a35d"] = {}
army_dates["5fb1b9f4e1af06001770a35d"]["1020 AD to 1300 AD"] = {
  startDate=1020,
  endDate=1300
}
