-- 5fb1b9dfe1af06001770977d Early Greco-Bactrian  260 to 151 BC

army['5fb1b9dfe1af06001770977d']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Hilly',
      'Steppe',
    },
    name='Early Greco-Bactrian  260 to 151 BC',
    id='5fb1b9dfe1af06001770977d',
    dateRange={
      startDate=-260,
      endDate=-151,
    },
  },
  g_base_definitions[g_str_68c995d957916300158895ff_general],
  g_base_definitions[g_str_68c995d957916300158895ff],
  g_base_definitions[g_str_68c995d95791630015889601],
  g_base_definitions[g_str_68c995d95791630015889603],
  g_base_definitions[g_str_5fb1b9dfe1af06001770977d_camp],
  g_base_definitions[g_str_5fb1b9dfe1af06001770977d_camp_pack_train],
  g_base_definitions[g_str_68c995c75791630015887138],
  g_base_definitions[g_str_68c995c7579163001588713a],
  g_base_definitions[g_str_68c995c7579163001588713c],
  g_base_definitions[g_str_68c995c7579163001588713e],
  g_base_definitions[g_str_68c995c75791630015887140],
  g_base_definitions[g_str_68c995c75791630015887141],
  g_base_definitions[g_str_68c995c75791630015887142],
  g_base_definitions[g_str_68c995c75791630015887144],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dfe1af06001770977d"] = army["5fb1b9dfe1af06001770977d"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Early Greco-Bactrian  260 to 151 BC"] = army["5fb1b9dfe1af06001770977d"]
if nil == armies["India and the Khyber Pass"] then
  armies["India and the Khyber Pass"] ={}
end
armies["India and the Khyber Pass"]["Early Greco-Bactrian  260 to 151 BC"] = army["5fb1b9dfe1af06001770977d"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Greco-Bactrian  260 to 151 BC"] = army["5fb1b9dfe1af06001770977d"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dfe1af06001770977d"] = {}
army_dates["5fb1b9dfe1af06001770977d"]["260 BC to 151 BC"] = {
  startDate=-260,
  endDate=-151
}
