-- 5fb1b9f1e1af06001770a1ba Former Qin  351 to 394 AD

army['5fb1b9f1e1af06001770a1ba']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Dry',
      'Hilly',
      'Arable',
    },
    name='Former Qin  351 to 394 AD',
    id='5fb1b9f1e1af06001770a1ba',
    dateRange={
      startDate=351,
      endDate=394,
    },
  },
  g_base_definitions[g_str_68c995e8579163001588bd82_general],
  g_base_definitions[g_str_68c995e8579163001588bd82],
  g_base_definitions[g_str_68c995e8579163001588bd84_general],
  g_base_definitions[g_str_68c995e8579163001588bd84],
  g_base_definitions[g_str_68c995e8579163001588bd86_general],
  g_base_definitions[g_str_68c995e8579163001588bd86],
  g_base_definitions[g_str_68c995e8579163001588bd88],
  g_base_definitions[g_str_68c995e8579163001588bd89],
  g_base_definitions[g_str_68c995e8579163001588bd8b],
  g_base_definitions[g_str_68c995e8579163001588bd8d],
  g_base_definitions[g_str_68c995e8579163001588bd90],
  g_base_definitions[g_str_68c995e8579163001588bd91],
  g_base_definitions[g_str_68c995e8579163001588bd94],
  g_base_definitions[g_str_68c995e8579163001588bd94_shower_shooting],
  g_base_definitions[g_str_68c995e8579163001588bd99],
  g_base_definitions[g_str_68c995e8579163001588bd9a],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a1ba_camp],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a1ba_camp_fortified],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a1ba_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f1e1af06001770a1ba"] = army["5fb1b9f1e1af06001770a1ba"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Former Qin  351 to 394 AD"] = army["5fb1b9f1e1af06001770a1ba"]
if nil == armies["Dark Ages China"] then
  armies["Dark Ages China"] ={}
end
armies["Dark Ages China"]["Former Qin  351 to 394 AD"] = army["5fb1b9f1e1af06001770a1ba"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Former Qin  351 to 394 AD"] = army["5fb1b9f1e1af06001770a1ba"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f1e1af06001770a1ba"] = {}
army_dates["5fb1b9f1e1af06001770a1ba"]["351 AD to 394 AD"] = {
  startDate=351,
  endDate=394
}
