-- 5fb1b9f2e1af06001770a26d Late Tang and Ten Kingdoms Chinese  755 to 979 AD

army['5fb1b9f2e1af06001770a26d']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Hilly',
      'Arable',
      'Forest',
    },
    name='Late Tang and Ten Kingdoms Chinese  755 to 979 AD',
    id='5fb1b9f2e1af06001770a26d',
    dateRange={
      startDate=755,
      endDate=979,
    },
  },
  g_base_definitions[g_str_68c995e9579163001588bfed_general],
  g_base_definitions[g_str_68c995e9579163001588bfed],
  g_base_definitions[g_str_68c995e9579163001588bff0],
  g_base_definitions[g_str_68c995e9579163001588bff2_general],
  g_base_definitions[g_str_68c995e9579163001588bff2_general_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e9579163001588bff2_general_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e9579163001588bff2],
  g_base_definitions[g_str_68c995e9579163001588bff2_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e9579163001588bff2_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e9579163001588bff5],
  g_base_definitions[g_str_68c995e9579163001588bff5_shower_shooting],
  g_base_definitions[g_str_68c995e9579163001588bff5_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e9579163001588bff5_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e9579163001588bff9],
  g_base_definitions[g_str_68c995e9579163001588bff9_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e9579163001588bff9_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e9579163001588bffa],
  g_base_definitions[g_str_68c995e9579163001588bffa_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e9579163001588bffa_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e9579163001588bffd_general],
  g_base_definitions[g_str_68c995e9579163001588bffd_general_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e9579163001588bffd_general_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e9579163001588bffd],
  g_base_definitions[g_str_68c995e9579163001588bffd_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e9579163001588bffd_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e9579163001588c000],
  g_base_definitions[g_str_68c995e9579163001588c001],
  g_base_definitions[g_str_68c995e9579163001588c003],
  g_base_definitions[g_str_68c995e9579163001588c003_shower_shooting],
  g_base_definitions[g_str_68c995e9579163001588c006],
  g_base_definitions[g_str_68c995e9579163001588c007],
  g_base_definitions[g_str_68c995e9579163001588c00a],
  g_base_definitions[g_str_5fb1b9f2e1af06001770a26d_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f2e1af06001770a26d"] = army["5fb1b9f2e1af06001770a26d"]
if nil == armies["Middle Kingdom"] then
  armies["Middle Kingdom"] ={}
end
armies["Middle Kingdom"]["Late Tang and Ten Kingdoms Chinese  755 to 979 AD"] = army["5fb1b9f2e1af06001770a26d"]
if nil == armies["Southeast Asia"] then
  armies["Southeast Asia"] ={}
end
armies["Southeast Asia"]["Late Tang and Ten Kingdoms Chinese  755 to 979 AD"] = army["5fb1b9f2e1af06001770a26d"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Late Tang and Ten Kingdoms Chinese  755 to 979 AD"] = army["5fb1b9f2e1af06001770a26d"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f2e1af06001770a26d"] = {}
army_dates["5fb1b9f2e1af06001770a26d"]["755 AD to 979 AD"] = {
  startDate=755,
  endDate=979
}
army_dates["5fb1b9f2e1af06001770a26d"]["755 AD to 762 AD"] = {
  startDate=755,
  endDate=762
}
army_dates["5fb1b9f2e1af06001770a26d"]["763 AD to 784 AD"] = {
  startDate=763,
  endDate=784
}
army_dates["5fb1b9f2e1af06001770a26d"]["785 AD to 790 AD"] = {
  startDate=785,
  endDate=790
}
army_dates["5fb1b9f2e1af06001770a26d"]["791 AD to 793 AD"] = {
  startDate=791,
  endDate=793
}
army_dates["5fb1b9f2e1af06001770a26d"]["794 AD to 807 AD"] = {
  startDate=794,
  endDate=807
}
army_dates["5fb1b9f2e1af06001770a26d"]["808 AD to 829 AD"] = {
  startDate=808,
  endDate=829
}
army_dates["5fb1b9f2e1af06001770a26d"]["830 AD to 859 AD"] = {
  startDate=830,
  endDate=859
}
army_dates["5fb1b9f2e1af06001770a26d"]["860 AD to 868 AD"] = {
  startDate=860,
  endDate=868
}
army_dates["5fb1b9f2e1af06001770a26d"]["869 AD to 883 AD"] = {
  startDate=869,
  endDate=883
}
army_dates["5fb1b9f2e1af06001770a26d"]["884 AD to 900 AD"] = {
  startDate=884,
  endDate=900
}
army_dates["5fb1b9f2e1af06001770a26d"]["901 AD to 906 AD"] = {
  startDate=901,
  endDate=906
}
army_dates["5fb1b9f2e1af06001770a26d"]["907 AD to 923 AD"] = {
  startDate=907,
  endDate=923
}
army_dates["5fb1b9f2e1af06001770a26d"]["924 AD to 979 AD"] = {
  startDate=924,
  endDate=979
}
