-- 5fb1b9e0e1af060017709798 Sangam Era Sinhalese  175 BC to 300 AD

army['5fb1b9e0e1af060017709798']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Forest',
    },
    name='Sangam Era Sinhalese  175 BC to 300 AD',
    id='5fb1b9e0e1af060017709798',
    dateRange={
      startDate=-175,
      endDate=300,
    },
  },
  g_base_definitions[g_str_68c995d95791630015889656_general],
  g_base_definitions[g_str_68c995d95791630015889656],
  g_base_definitions[g_str_68c995d95791630015889658],
  g_base_definitions[g_str_68c995d95791630015889658_shower_shooting],
  g_base_definitions[g_str_68c995d9579163001588965b],
  g_base_definitions[g_str_68c995d9579163001588965d],
  g_base_definitions[g_str_68c995d9579163001588965e],
  g_base_definitions[g_str_68c995d95791630015889660],
  g_base_definitions[g_str_5fb1b9e0e1af060017709798_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e0e1af060017709798"] = army["5fb1b9e0e1af060017709798"]
if nil == armies["India and the Khyber Pass"] then
  armies["India and the Khyber Pass"] ={}
end
armies["India and the Khyber Pass"]["Sangam Era Sinhalese  175 BC to 300 AD"] = army["5fb1b9e0e1af060017709798"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Sangam Era Sinhalese  175 BC to 300 AD"] = army["5fb1b9e0e1af060017709798"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e0e1af060017709798"] = {}
army_dates["5fb1b9e0e1af060017709798"]["175 BC to 300 AD"] = {
  startDate=-175,
  endDate=300
}
