-- 5fb1b9dde1af0600177095dc Later Hoplite Spartan  448 to 225 BC

army['5fb1b9dde1af0600177095dc']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Later Hoplite Spartan  448 to 225 BC',
    id='5fb1b9dde1af0600177095dc',
    dateRange={
      startDate=-448,
      endDate=-225,
    },
  },
  g_base_definitions[g_str_68c995d75791630015888f38_general],
  g_base_definitions[g_str_68c995d75791630015888f38],
  g_base_definitions[g_str_68c995d75791630015888f3c],
  g_base_definitions[g_str_68c995d75791630015888f3f],
  g_base_definitions[g_str_68c995d75791630015888f41],
  g_base_definitions[g_str_68c995d75791630015888f43],
  g_base_definitions[g_str_68c995d75791630015888f45],
  g_base_definitions[g_str_68c995d75791630015888f47],
  g_base_definitions[g_str_68c995d75791630015888f49],
  g_base_definitions[g_str_68c995d75791630015888f4d],
  g_base_definitions[g_str_5fb1b9dde1af0600177095dc_camp],
  g_base_definitions[g_str_5fb1b9dde1af0600177095dc_camp_pack_train],
  g_base_definitions[g_str_5fb1b9dde1af0600177095dc_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dde1af0600177095dc"] = army["5fb1b9dde1af0600177095dc"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Later Hoplite Spartan  448 to 225 BC"] = army["5fb1b9dde1af0600177095dc"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Later Hoplite Spartan  448 to 225 BC"] = army["5fb1b9dde1af0600177095dc"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Hoplite Spartan  448 to 225 BC"] = army["5fb1b9dde1af0600177095dc"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dde1af0600177095dc"] = {}
army_dates["5fb1b9dde1af0600177095dc"]["448 BC to 225 BC"] = {
  startDate=-448,
  endDate=-225
}
army_dates["5fb1b9dde1af0600177095dc"]["448 BC to 423 BC"] = {
  startDate=-448,
  endDate=-423
}
army_dates["5fb1b9dde1af0600177095dc"]["422 BC"] = {
  startDate=-422,
  endDate=-422
}
army_dates["5fb1b9dde1af0600177095dc"]["421 BC"] = {
  startDate=-421,
  endDate=-421
}
army_dates["5fb1b9dde1af0600177095dc"]["420 BC to 409 BC"] = {
  startDate=-420,
  endDate=-409
}
army_dates["5fb1b9dde1af0600177095dc"]["408 BC"] = {
  startDate=-408,
  endDate=-408
}
army_dates["5fb1b9dde1af0600177095dc"]["407 BC to 404 BC"] = {
  startDate=-407,
  endDate=-404
}
army_dates["5fb1b9dde1af0600177095dc"]["403 BC to 400 BC"] = {
  startDate=-403,
  endDate=-400
}
army_dates["5fb1b9dde1af0600177095dc"]["399 BC to 383 BC"] = {
  startDate=-399,
  endDate=-383
}
army_dates["5fb1b9dde1af0600177095dc"]["382 BC to 381 BC"] = {
  startDate=-382,
  endDate=-381
}
army_dates["5fb1b9dde1af0600177095dc"]["380 BC to 355 BC"] = {
  startDate=-380,
  endDate=-355
}
army_dates["5fb1b9dde1af0600177095dc"]["354 BC to 329 BC"] = {
  startDate=-354,
  endDate=-329
}
army_dates["5fb1b9dde1af0600177095dc"]["328 BC to 225 BC"] = {
  startDate=-328,
  endDate=-225
}
