-- 5fb1b9ece1af060017709efc Khawarij Rebellions  658 to 896 AD

army['5fb1b9ece1af060017709efc']={
  data={
    invasionRatings={
      4,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Dry',
    },
    name='Khawarij Rebellions  658 to 896 AD',
    id='5fb1b9ece1af060017709efc',
    dateRange={
      startDate=658,
      endDate=896,
    },
  },
  g_base_definitions[g_str_68c995e4579163001588b290],
  g_base_definitions[g_str_68c995e4579163001588b290_light_camelry],
  g_base_definitions[g_str_68c995e4579163001588b293_general],
  g_base_definitions[g_str_68c995e4579163001588b293_general_mounted],
  g_base_definitions[g_str_68c995e4579163001588b293_general_dismounted],
  g_base_definitions[g_str_68c995e4579163001588b293],
  g_base_definitions[g_str_68c995e4579163001588b293_mounted],
  g_base_definitions[g_str_68c995e4579163001588b293_dismounted],
  g_base_definitions[g_str_68c995e4579163001588b296],
  g_base_definitions[g_str_68c995e4579163001588b296_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b296_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b299],
  g_base_definitions[g_str_68c995e4579163001588b299_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b299_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b29c],
  g_base_definitions[g_str_68c995e4579163001588b29c_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b29c_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b29f],
  g_base_definitions[g_str_68c995e4579163001588b29f_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b29f_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1b9ece1af060017709efc_camp],
  g_base_definitions[g_str_5fb1b9ece1af060017709efc_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ece1af060017709efc"] = army["5fb1b9ece1af060017709efc"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Khawarij Rebellions  658 to 896 AD"] = army["5fb1b9ece1af060017709efc"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Khawarij Rebellions  658 to 896 AD"] = army["5fb1b9ece1af060017709efc"]
if nil == armies["Spread of Islam"] then
  armies["Spread of Islam"] ={}
end
armies["Spread of Islam"]["Khawarij Rebellions  658 to 896 AD"] = army["5fb1b9ece1af060017709efc"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Khawarij Rebellions  658 to 896 AD"] = army["5fb1b9ece1af060017709efc"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ece1af060017709efc"] = {}
army_dates["5fb1b9ece1af060017709efc"]["658 AD to 896 AD"] = {
  startDate=658,
  endDate=896
}
