-- 5fb1b9f2e1af06001770a25f Early Tang Chinese  618 to 755 AD

army['5fb1b9f2e1af06001770a25f']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Hilly',
      'Arable',
      'Forest',
    },
    name='Early Tang Chinese  618 to 755 AD',
    id='5fb1b9f2e1af06001770a25f',
    dateRange={
      startDate=618,
      endDate=755,
    },
  },
  g_base_definitions[g_str_68c995e8579163001588bfb7],
  g_base_definitions[g_str_68c995e8579163001588bfb9_general],
  g_base_definitions[g_str_68c995e8579163001588bfb9],
  g_base_definitions[g_str_68c995e8579163001588bfbb],
  g_base_definitions[g_str_68c995e8579163001588bfbd],
  g_base_definitions[g_str_68c995e8579163001588bfbf],
  g_base_definitions[g_str_68c995e8579163001588bfbf_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e8579163001588bfbf_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e8579163001588bfc0],
  g_base_definitions[g_str_68c995e8579163001588bfc0_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e8579163001588bfc0_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e8579163001588bfc1],
  g_base_definitions[g_str_68c995e8579163001588bfc1_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e8579163001588bfc1_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e8579163001588bfc4],
  g_base_definitions[g_str_68c995e8579163001588bfc4_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e8579163001588bfc4_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e8579163001588bfc4_shower_shooting],
  g_base_definitions[g_str_68c995e8579163001588bfc5],
  g_base_definitions[g_str_68c995e8579163001588bfc5_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e8579163001588bfc5_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e8579163001588bfc5_shower_shooting],
  g_base_definitions[g_str_68c995e8579163001588bfc9],
  g_base_definitions[g_str_68c995e8579163001588bfc9_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e8579163001588bfc9_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e8579163001588bfcc],
  g_base_definitions[g_str_68c995e8579163001588bfce],
  g_base_definitions[g_str_68c995e8579163001588bfd0],
  g_base_definitions[g_str_5fb1b9f2e1af06001770a25f_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f2e1af06001770a25f"] = army["5fb1b9f2e1af06001770a25f"]
if nil == armies["Middle Kingdom"] then
  armies["Middle Kingdom"] ={}
end
armies["Middle Kingdom"]["Early Tang Chinese  618 to 755 AD"] = army["5fb1b9f2e1af06001770a25f"]
if nil == armies["Southeast Asia"] then
  armies["Southeast Asia"] ={}
end
armies["Southeast Asia"]["Early Tang Chinese  618 to 755 AD"] = army["5fb1b9f2e1af06001770a25f"]
if nil == armies["Korea and Japan"] then
  armies["Korea and Japan"] ={}
end
armies["Korea and Japan"]["Early Tang Chinese  618 to 755 AD"] = army["5fb1b9f2e1af06001770a25f"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Tang Chinese  618 to 755 AD"] = army["5fb1b9f2e1af06001770a25f"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f2e1af06001770a25f"] = {}
army_dates["5fb1b9f2e1af06001770a25f"]["618 AD to 755 AD"] = {
  startDate=618,
  endDate=755
}
army_dates["5fb1b9f2e1af06001770a25f"]["618 AD to 659 AD"] = {
  startDate=618,
  endDate=659
}
army_dates["5fb1b9f2e1af06001770a25f"]["660 AD to 668 AD"] = {
  startDate=660,
  endDate=668
}
army_dates["5fb1b9f2e1af06001770a25f"]["669 AD to 755 AD"] = {
  startDate=669,
  endDate=755
}
