-- 5fb1b9e7e1af060017709c0b Aragon  1340 to 1479 AD

army['5fb1b9e7e1af060017709c0b']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Aragon  1340 to 1479 AD',
    id='5fb1b9e7e1af060017709c0b',
    dateRange={
      startDate=1340,
      endDate=1479,
    },
  },
  g_base_definitions[g_str_68c995df579163001588a5d6_general],
  g_base_definitions[g_str_68c995df579163001588a5d6],
  g_base_definitions[g_str_68c995df579163001588a5d8],
  g_base_definitions[g_str_68c995df579163001588a5da],
  g_base_definitions[g_str_68c995df579163001588a5dc],
  g_base_definitions[g_str_68c995df579163001588a5dc_shower_shooting],
  g_base_definitions[g_str_68c995df579163001588a5dd],
  g_base_definitions[g_str_68c995df579163001588a5dd_shower_shooting],
  g_base_definitions[g_str_68c995df579163001588a5de],
  g_base_definitions[g_str_68c995df579163001588a5de_shower_shooting],
  g_base_definitions[g_str_68c995df579163001588a5e1],
  g_base_definitions[g_str_68c995df579163001588a5e3],
  g_base_definitions[g_str_68c995df579163001588a5e5],
  g_base_definitions[g_str_68c995df579163001588a5e8],
  g_base_definitions[g_str_5fb1b9e7e1af060017709c0b_camp],
  g_base_definitions[g_str_5fb1b9e7e1af060017709c0b_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e7e1af060017709c0b"] = army["5fb1b9e7e1af060017709c0b"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Aragon  1340 to 1479 AD"] = army["5fb1b9e7e1af060017709c0b"]
if nil == armies["Plate and Handgonne"] then
  armies["Plate and Handgonne"] ={}
end
armies["Plate and Handgonne"]["Aragon  1340 to 1479 AD"] = army["5fb1b9e7e1af060017709c0b"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Aragon  1340 to 1479 AD"] = army["5fb1b9e7e1af060017709c0b"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e7e1af060017709c0b"] = {}
army_dates["5fb1b9e7e1af060017709c0b"]["1340 AD to 1479 AD"] = {
  startDate=1340,
  endDate=1479
}
