-- 5fb1b9d9e1af060017709313 Early Kassites, Nairi, or Hurrians  1779 to 950 BC

army['5fb1b9d9e1af060017709313']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Hilly',
    },
    name='Early Kassites, Nairi, or Hurrians  1779 to 950 BC',
    id='5fb1b9d9e1af060017709313',
    dateRange={
      startDate=-1779,
      endDate=-950,
    },
  },
  g_base_definitions[g_str_68c995d3579163001588849c_general],
  g_base_definitions[g_str_68c995d3579163001588849c],
  g_base_definitions[g_str_68c995d3579163001588849e_general],
  g_base_definitions[g_str_68c995d3579163001588849e],
  g_base_definitions[g_str_68c995d3579163001588849f_general],
  g_base_definitions[g_str_68c995d3579163001588849f],
  g_base_definitions[g_str_68c995d357916300158884a1],
  g_base_definitions[g_str_68c995d357916300158884a4],
  g_base_definitions[g_str_68c995d357916300158884a6],
  g_base_definitions[g_str_68c995d357916300158884a6_shower_shooting],
  g_base_definitions[g_str_68c995d357916300158884a9],
  g_base_definitions[g_str_5fb1b9d9e1af060017709313_camp],
  g_base_definitions[g_str_5fb1b9d9e1af060017709313_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9d9e1af060017709313"] = army["5fb1b9d9e1af060017709313"]
if nil == armies["Chariot Supremacy"] then
  armies["Chariot Supremacy"] ={}
end
armies["Chariot Supremacy"]["Early Kassites, Nairi, or Hurrians  1779 to 950 BC"] = army["5fb1b9d9e1af060017709313"]
if nil == armies["Sea Peoples Invasions"] then
  armies["Sea Peoples Invasions"] ={}
end
armies["Sea Peoples Invasions"]["Early Kassites, Nairi, or Hurrians  1779 to 950 BC"] = army["5fb1b9d9e1af060017709313"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Kassites, Nairi, or Hurrians  1779 to 950 BC"] = army["5fb1b9d9e1af060017709313"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9d9e1af060017709313"] = {}
army_dates["5fb1b9d9e1af060017709313"]["1779 BC to 950 BC"] = {
  startDate=-1779,
  endDate=-950
}
