-- 5fb1b9f5e1af06001770a39a Oaxaca  500 BC to 1100 AD

army['5fb1b9f5e1af06001770a39a']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      2,
      0,
      1,
    },
    homeTopographies={
      'Hilly',
    },
    name='Oaxaca  500 BC to 1100 AD',
    id='5fb1b9f5e1af06001770a39a',
    dateRange={
      startDate=-500,
      endDate=1100,
    },
    ambush=true,  },
  g_base_definitions[g_str_68c995ea579163001588c46d_general],
  g_base_definitions[g_str_68c995ea579163001588c46d],
  g_base_definitions[g_str_68c995ea579163001588c46f],
  g_base_definitions[g_str_68c995ea579163001588c471],
  g_base_definitions[g_str_68c995ea579163001588c473],
  g_base_definitions[g_str_68c995ea579163001588c475],
  g_base_definitions[g_str_5fb1b9f5e1af06001770a39a_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f5e1af06001770a39a"] = army["5fb1b9f5e1af06001770a39a"]
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["Oaxaca  500 BC to 1100 AD"] = army["5fb1b9f5e1af06001770a39a"]
if nil == armies["Mexico"] then
  armies["Mexico"] ={}
end
armies["Mexico"]["Oaxaca  500 BC to 1100 AD"] = army["5fb1b9f5e1af06001770a39a"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Oaxaca  500 BC to 1100 AD"] = army["5fb1b9f5e1af06001770a39a"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f5e1af06001770a39a"] = {}
army_dates["5fb1b9f5e1af06001770a39a"]["500 BC to 1100 AD"] = {
  startDate=-500,
  endDate=1100
}
