-- 5fb1b9e7e1af060017709bc4 Muslim North Africa and Sicily  801 to 1160 AD

army['5fb1b9e7e1af060017709bc4']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
      'Dry',
      'Hilly',
    },
    name='Muslim North Africa and Sicily  801 to 1160 AD',
    id='5fb1b9e7e1af060017709bc4',
    dateRange={
      startDate=801,
      endDate=1160,
    },
  },
  g_base_definitions[g_str_68c995df579163001588a4ac_general],
  g_base_definitions[g_str_68c995df579163001588a4ac],
  g_base_definitions[g_str_68c995df579163001588a4af],
  g_base_definitions[g_str_68c995df579163001588a4b1],
  g_base_definitions[g_str_68c995df579163001588a4b3],
  g_base_definitions[g_str_68c995df579163001588a4b6],
  g_base_definitions[g_str_68c995df579163001588a4b8],
  g_base_definitions[g_str_68c995df579163001588a4b8_shower_shooting],
  g_base_definitions[g_str_68c995df579163001588a4b9],
  g_base_definitions[g_str_68c995df579163001588a4b9_shower_shooting],
  g_base_definitions[g_str_68c995df579163001588a4ba],
  g_base_definitions[g_str_68c995df579163001588a4ba_shower_shooting],
  g_base_definitions[g_str_68c995df579163001588a4bf],
  g_base_definitions[g_str_68c995df579163001588a4c2],
  g_base_definitions[g_str_68c995df579163001588a4c2_shower_shooting],
  g_base_definitions[g_str_68c995df579163001588a4c6],
  g_base_definitions[g_str_5fb1b9e7e1af060017709bc4_camp],
  g_base_definitions[g_str_5fb1b9e7e1af060017709bc4_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e7e1af060017709bc4"] = army["5fb1b9e7e1af060017709bc4"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Muslim North Africa and Sicily  801 to 1160 AD"] = army["5fb1b9e7e1af060017709bc4"]
if nil == armies["Spread of Islam"] then
  armies["Spread of Islam"] ={}
end
armies["Spread of Islam"]["Muslim North Africa and Sicily  801 to 1160 AD"] = army["5fb1b9e7e1af060017709bc4"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Muslim North Africa and Sicily  801 to 1160 AD"] = army["5fb1b9e7e1af060017709bc4"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e7e1af060017709bc4"] = {}
army_dates["5fb1b9e7e1af060017709bc4"]["801 AD to 1160 AD"] = {
  startDate=801,
  endDate=1160
}
army_dates["5fb1b9e7e1af060017709bc4"]["801 AD to 826 AD"] = {
  startDate=801,
  endDate=826
}
army_dates["5fb1b9e7e1af060017709bc4"]["827 AD"] = {
  startDate=827,
  endDate=827
}
army_dates["5fb1b9e7e1af060017709bc4"]["828 AD to 957 AD"] = {
  startDate=828,
  endDate=957
}
army_dates["5fb1b9e7e1af060017709bc4"]["958 AD to 959 AD"] = {
  startDate=958,
  endDate=959
}
army_dates["5fb1b9e7e1af060017709bc4"]["960 AD to 1000 AD"] = {
  startDate=960,
  endDate=1000
}
army_dates["5fb1b9e7e1af060017709bc4"]["1001 AD to 1034 AD"] = {
  startDate=1001,
  endDate=1034
}
army_dates["5fb1b9e7e1af060017709bc4"]["1035 AD"] = {
  startDate=1035,
  endDate=1035
}
army_dates["5fb1b9e7e1af060017709bc4"]["1036 AD to 1042 AD"] = {
  startDate=1036,
  endDate=1042
}
army_dates["5fb1b9e7e1af060017709bc4"]["1043 AD to 1160 AD"] = {
  startDate=1043,
  endDate=1160
}
