-- 5fb1b9dde1af060017709649 Thracian Lowland Tribes  700 BC to 46 AD

army['5fb1b9dde1af060017709649']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
    },
    name='Thracian Lowland Tribes  700 BC to 46 AD',
    id='5fb1b9dde1af060017709649',
    dateRange={
      startDate=-700,
      endDate=46,
    },
  },
  g_base_definitions[g_str_68c995d85791630015889104_general],
  g_base_definitions[g_str_68c995d85791630015889104],
  g_base_definitions[g_str_68c995d85791630015889105_general],
  g_base_definitions[g_str_68c995d85791630015889105],
  g_base_definitions[g_str_68c995d85791630015889107_general],
  g_base_definitions[g_str_68c995d85791630015889107],
  g_base_definitions[g_str_68c995d85791630015889109],
  g_base_definitions[g_str_68c995d8579163001588910a_general],
  g_base_definitions[g_str_68c995d8579163001588910a],
  g_base_definitions[g_str_68c995d8579163001588910c_general],
  g_base_definitions[g_str_68c995d8579163001588910c],
  g_base_definitions[g_str_68c995d8579163001588910f],
  g_base_definitions[g_str_68c995d85791630015889111_general],
  g_base_definitions[g_str_68c995d85791630015889111],
  g_base_definitions[g_str_68c995d85791630015889113],
  g_base_definitions[g_str_5fb1b9dde1af060017709649_camp],
  g_base_definitions[g_str_5fb1b9dde1af060017709649_camp_fortified],
  g_base_definitions[g_str_68c995c65791630015886f78],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dde1af060017709649"] = army["5fb1b9dde1af060017709649"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Thracian Lowland Tribes  700 BC to 46 AD"] = army["5fb1b9dde1af060017709649"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Thracian Lowland Tribes  700 BC to 46 AD"] = army["5fb1b9dde1af060017709649"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Thracian Lowland Tribes  700 BC to 46 AD"] = army["5fb1b9dde1af060017709649"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Thracian Lowland Tribes  700 BC to 46 AD"] = army["5fb1b9dde1af060017709649"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Thracian Lowland Tribes  700 BC to 46 AD"] = army["5fb1b9dde1af060017709649"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dde1af060017709649"] = {}
army_dates["5fb1b9dde1af060017709649"]["700 BC to 46 AD"] = {
  startDate=-700,
  endDate=46
}
army_dates["5fb1b9dde1af060017709649"]["700 BC to 449 BC"] = {
  startDate=-700,
  endDate=-449
}
army_dates["5fb1b9dde1af060017709649"]["448 BC to 401 BC"] = {
  startDate=-448,
  endDate=-401
}
army_dates["5fb1b9dde1af060017709649"]["400 BC to 375 BC"] = {
  startDate=-400,
  endDate=-375
}
army_dates["5fb1b9dde1af060017709649"]["374 BC to 357 BC"] = {
  startDate=-374,
  endDate=-357
}
army_dates["5fb1b9dde1af060017709649"]["356 BC to 225 BC"] = {
  startDate=-356,
  endDate=-225
}
army_dates["5fb1b9dde1af060017709649"]["224 BC to 46 AD"] = {
  startDate=-224,
  endDate=46
}
