-- 5fb1b9e6e1af060017709b49 Tudor English  1489 to 1515 AD

army['5fb1b9e6e1af060017709b49']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
    },
    name='Tudor English  1489 to 1515 AD',
    id='5fb1b9e6e1af060017709b49',
    dateRange={
      startDate=1489,
      endDate=1515,
    },
  },
  g_base_definitions[g_str_68c995df579163001588a360_general],
  g_base_definitions[g_str_68c995df579163001588a360_general_mounted],
  g_base_definitions[g_str_68c995df579163001588a360_general_dismounted],
  g_base_definitions[g_str_68c995df579163001588a360],
  g_base_definitions[g_str_68c995df579163001588a360_mounted],
  g_base_definitions[g_str_68c995df579163001588a360_dismounted],
  g_base_definitions[g_str_68c995df579163001588a363],
  g_base_definitions[g_str_68c995df579163001588a363_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995df579163001588a363_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995df579163001588a367],
  g_base_definitions[g_str_68c995df579163001588a367_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995df579163001588a367_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995df579163001588a36a],
  g_base_definitions[g_str_68c995df579163001588a36c],
  g_base_definitions[g_str_68c995df579163001588a36e],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b49_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e6e1af060017709b49"] = army["5fb1b9e6e1af060017709b49"]
if nil == armies["Embattled Isle"] then
  armies["Embattled Isle"] ={}
end
armies["Embattled Isle"]["Tudor English  1489 to 1515 AD"] = army["5fb1b9e6e1af060017709b49"]
if nil == armies["Plate and Handgonne"] then
  armies["Plate and Handgonne"] ={}
end
armies["Plate and Handgonne"]["Tudor English  1489 to 1515 AD"] = army["5fb1b9e6e1af060017709b49"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Tudor English  1489 to 1515 AD"] = army["5fb1b9e6e1af060017709b49"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e6e1af060017709b49"] = {}
army_dates["5fb1b9e6e1af060017709b49"]["1489 AD to 1515 AD"] = {
  startDate=1489,
  endDate=1515
}
