-- 5fb1b9e5e1af060017709aef Edward Bruce in Ireland  1315 to 1318 AD

army['5fb1b9e5e1af060017709aef']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Forest',
    },
    name='Edward Bruce in Ireland  1315 to 1318 AD',
    id='5fb1b9e5e1af060017709aef',
    dateRange={
      startDate=1315,
      endDate=1318,
    },
  },
  g_base_definitions[g_str_68c995de579163001588a1f2_general],
  g_base_definitions[g_str_68c995de579163001588a1f2_general_mounted],
  g_base_definitions[g_str_68c995de579163001588a1f2_general_dismounted],
  g_base_definitions[g_str_68c995de579163001588a1f2],
  g_base_definitions[g_str_68c995de579163001588a1f2_mounted],
  g_base_definitions[g_str_68c995de579163001588a1f2_dismounted],
  g_base_definitions[g_str_68c995de579163001588a1f5_general],
  g_base_definitions[g_str_68c995de579163001588a1f5],
  g_base_definitions[g_str_68c995de579163001588a1f7],
  g_base_definitions[g_str_68c995de579163001588a1f7_mounted],
  g_base_definitions[g_str_68c995de579163001588a1f7_dismounted],
  g_base_definitions[g_str_68c995de579163001588a1fa],
  g_base_definitions[g_str_68c995de579163001588a1fc],
  g_base_definitions[g_str_68c995de579163001588a1fe],
  g_base_definitions[g_str_68c995de579163001588a200],
  g_base_definitions[g_str_5fb1b9e5e1af060017709aef_camp],
  g_base_definitions[g_str_5fb1b9e5e1af060017709aef_camp_fortified],
  g_base_definitions[g_str_5fb1b9e5e1af060017709aef_camp_pack_train],
  g_base_definitions[g_str_5fb1b9e5e1af060017709aef_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e5e1af060017709aef"] = army["5fb1b9e5e1af060017709aef"]
if nil == armies["Embattled Isle"] then
  armies["Embattled Isle"] ={}
end
armies["Embattled Isle"]["Edward Bruce in Ireland  1315 to 1318 AD"] = army["5fb1b9e5e1af060017709aef"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Edward Bruce in Ireland  1315 to 1318 AD"] = army["5fb1b9e5e1af060017709aef"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e5e1af060017709aef"] = {}
army_dates["5fb1b9e5e1af060017709aef"]["1315 AD to 1318 AD"] = {
  startDate=1315,
  endDate=1318
}
