-- 5fb1b9dfe1af060017709776 Massagetae  550 to 150 BC

army['5fb1b9dfe1af060017709776']={
  data={
    invasionRatings={
      4,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Steppe',
    },
    name='Massagetae  550 to 150 BC',
    id='5fb1b9dfe1af060017709776',
    dateRange={
      startDate=-550,
      endDate=-150,
    },
  },
  g_base_definitions[g_str_68c995d957916300158895ed_general],
  g_base_definitions[g_str_68c995d957916300158895ed],
  g_base_definitions[g_str_68c995d957916300158895ef],
  g_base_definitions[g_str_68c995d957916300158895f1],
  g_base_definitions[g_str_68c995d957916300158895f1_shower_shooting],
  g_base_definitions[g_str_68c995d957916300158895f2],
  g_base_definitions[g_str_68c995d957916300158895f2_shower_shooting],
  g_base_definitions[g_str_68c995d957916300158895f5],
  g_base_definitions[g_str_68c995d957916300158895f7],
  g_base_definitions[g_str_68c995d957916300158895f8],
  g_base_definitions[g_str_5fb1b9dfe1af060017709776_camp],
  g_base_definitions[g_str_5fb1b9dfe1af060017709776_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dfe1af060017709776"] = army["5fb1b9dfe1af060017709776"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Massagetae  550 to 150 BC"] = army["5fb1b9dfe1af060017709776"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Massagetae  550 to 150 BC"] = army["5fb1b9dfe1af060017709776"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Massagetae  550 to 150 BC"] = army["5fb1b9dfe1af060017709776"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dfe1af060017709776"] = {}
army_dates["5fb1b9dfe1af060017709776"]["550 BC to 150 BC"] = {
  startDate=-550,
  endDate=-150
}
army_dates["5fb1b9dfe1af060017709776"]["550 BC to 501 BC"] = {
  startDate=-550,
  endDate=-501
}
army_dates["5fb1b9dfe1af060017709776"]["500 BC to 170 BC"] = {
  startDate=-500,
  endDate=-170
}
army_dates["5fb1b9dfe1af060017709776"]["169 BC to 150 BC"] = {
  startDate=-169,
  endDate=-150
}
