-- 5fb1b9e0e1af0600177097b1 Republican Indian  500 to 321 BC

army['5fb1b9e0e1af0600177097b1']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Republican Indian  500 to 321 BC',
    id='5fb1b9e0e1af0600177097b1',
    dateRange={
      startDate=-500,
      endDate=-321,
    },
  },
  g_base_definitions[g_str_68c995d957916300158896a2_general],
  g_base_definitions[g_str_68c995d957916300158896a2],
  g_base_definitions[g_str_68c995d957916300158896a5_general],
  g_base_definitions[g_str_68c995d957916300158896a5_general_mounted],
  g_base_definitions[g_str_68c995d957916300158896a5_general_dismounted],
  g_base_definitions[g_str_68c995d957916300158896a5],
  g_base_definitions[g_str_68c995d957916300158896a5_mounted],
  g_base_definitions[g_str_68c995d957916300158896a5_dismounted],
  g_base_definitions[g_str_68c995d957916300158896a8],
  g_base_definitions[g_str_68c995d957916300158896aa],
  g_base_definitions[g_str_68c995d957916300158896aa_shower_shooting],
  g_base_definitions[g_str_68c995d957916300158896ad_general],
  g_base_definitions[g_str_68c995d957916300158896ad_general_elephant_screen],
  g_base_definitions[g_str_68c995d957916300158896ad],
  g_base_definitions[g_str_68c995d957916300158896ad_elephant_screen],
  g_base_definitions[g_str_5fb1b9e0e1af0600177097b1_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e0e1af0600177097b1"] = army["5fb1b9e0e1af0600177097b1"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Republican Indian  500 to 321 BC"] = army["5fb1b9e0e1af0600177097b1"]
if nil == armies["India and the Khyber Pass"] then
  armies["India and the Khyber Pass"] ={}
end
armies["India and the Khyber Pass"]["Republican Indian  500 to 321 BC"] = army["5fb1b9e0e1af0600177097b1"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Republican Indian  500 to 321 BC"] = army["5fb1b9e0e1af0600177097b1"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e0e1af0600177097b1"] = {}
army_dates["5fb1b9e0e1af0600177097b1"]["500 BC to 321 BC"] = {
  startDate=-500,
  endDate=-321
}
