-- 5fb1b9f0e1af06001770a13b Xirong  2000 to 315 BC

army['5fb1b9f0e1af06001770a13b']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Hilly',
    },
    name='Xirong  2000 to 315 BC',
    id='5fb1b9f0e1af06001770a13b',
    dateRange={
      startDate=-2000,
      endDate=-315,
    },
  },
  g_base_definitions[g_str_68c995e7579163001588bc24_general],
  g_base_definitions[g_str_68c995e7579163001588bc24],
  g_base_definitions[g_str_68c995e7579163001588bc27_general],
  g_base_definitions[g_str_68c995e7579163001588bc27],
  g_base_definitions[g_str_68c995e7579163001588bc29_general],
  g_base_definitions[g_str_68c995e7579163001588bc29],
  g_base_definitions[g_str_68c995e7579163001588bc2b],
  g_base_definitions[g_str_68c995e7579163001588bc2d],
  g_base_definitions[g_str_5fb1b9f0e1af06001770a13b_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f0e1af06001770a13b"] = army["5fb1b9f0e1af06001770a13b"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Xirong  2000 to 315 BC"] = army["5fb1b9f0e1af06001770a13b"]
if nil == armies["Warring States"] then
  armies["Warring States"] ={}
end
armies["Warring States"]["Xirong  2000 to 315 BC"] = army["5fb1b9f0e1af06001770a13b"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Xirong  2000 to 315 BC"] = army["5fb1b9f0e1af06001770a13b"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f0e1af06001770a13b"] = {}
army_dates["5fb1b9f0e1af06001770a13b"]["2000 BC to 315 BC"] = {
  startDate=-2000,
  endDate=-315
}
army_dates["5fb1b9f0e1af06001770a13b"]["2000 BC to 1101 BC"] = {
  startDate=-2000,
  endDate=-1101
}
army_dates["5fb1b9f0e1af06001770a13b"]["1100 BC to 771 BC"] = {
  startDate=-1100,
  endDate=-771
}
army_dates["5fb1b9f0e1af06001770a13b"]["770 BC to 550 BC"] = {
  startDate=-770,
  endDate=-550
}
army_dates["5fb1b9f0e1af06001770a13b"]["549 BC to 315 BC"] = {
  startDate=-549,
  endDate=-315
}
