-- 5fb1b9dbe1af06001770949e Greek Dark Ages  1160 to 665 BC

army['5fb1b9dbe1af06001770949e']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Hilly',
    },
    name='Greek Dark Ages  1160 to 665 BC',
    id='5fb1b9dbe1af06001770949e',
    dateRange={
      startDate=-1160,
      endDate=-665,
    },
  },
  g_base_definitions[g_str_68c995d55791630015888aa1_general],
  g_base_definitions[g_str_68c995d55791630015888aa1],
  g_base_definitions[g_str_68c995d55791630015888aa3_general],
  g_base_definitions[g_str_68c995d55791630015888aa3],
  g_base_definitions[g_str_68c995d55791630015888aa5],
  g_base_definitions[g_str_68c995d55791630015888aa9],
  g_base_definitions[g_str_68c995d55791630015888aac],
  g_base_definitions[g_str_68c995d55791630015888aaf],
  g_base_definitions[g_str_5fb1b9dbe1af06001770949e_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dbe1af06001770949e"] = army["5fb1b9dbe1af06001770949e"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Greek Dark Ages  1160 to 665 BC"] = army["5fb1b9dbe1af06001770949e"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Greek Dark Ages  1160 to 665 BC"] = army["5fb1b9dbe1af06001770949e"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dbe1af06001770949e"] = {}
army_dates["5fb1b9dbe1af06001770949e"]["1160 BC to 665 BC"] = {
  startDate=-1160,
  endDate=-665
}
