-- 5fb1b9e1e1af06001770986a Ancient British  400 BC to 75 AD

army['5fb1b9e1e1af06001770986a']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      1,
      2,
    },
    homeTopographies={
      'Arable',
    },
    name='Ancient British  400 BC to 75 AD',
    id='5fb1b9e1e1af06001770986a',
    dateRange={
      startDate=-400,
      endDate=75,
    },
  },
  g_base_definitions[g_str_68c995da579163001588991c_general],
  g_base_definitions[g_str_68c995da579163001588991c_general_mounted],
  g_base_definitions[g_str_68c995da579163001588991c_general_dismounted],
  g_base_definitions[g_str_68c995da579163001588991c],
  g_base_definitions[g_str_68c995da579163001588991c_mounted],
  g_base_definitions[g_str_68c995da579163001588991c_dismounted],
  g_base_definitions[g_str_68c995da579163001588991f],
  g_base_definitions[g_str_68c995da5791630015889921_general],
  g_base_definitions[g_str_68c995da5791630015889921],
  g_base_definitions[g_str_68c995da5791630015889923],
  g_base_definitions[g_str_68c995da5791630015889924],
  g_base_definitions[g_str_68c995da5791630015889926],
  g_base_definitions[g_str_5fb1b9e1e1af06001770986a_camp],
  g_base_definitions[g_str_5fb1b9e1e1af06001770986a_camp_fortified],
  g_base_definitions[g_str_5fb1b9e1e1af06001770986a_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e1e1af06001770986a"] = army["5fb1b9e1e1af06001770986a"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Ancient British  400 BC to 75 AD"] = army["5fb1b9e1e1af06001770986a"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Ancient British  400 BC to 75 AD"] = army["5fb1b9e1e1af06001770986a"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e1e1af06001770986a"] = {}
army_dates["5fb1b9e1e1af06001770986a"]["400 BC to 75 AD"] = {
  startDate=-400,
  endDate=75
}
army_dates["5fb1b9e1e1af06001770986a"]["400 BC to 26 BC"] = {
  startDate=-400,
  endDate=-26
}
army_dates["5fb1b9e1e1af06001770986a"]["25 BC to 50 AD"] = {
  startDate=-25,
  endDate=50
}
army_dates["5fb1b9e1e1af06001770986a"]["51 AD to 69 AD"] = {
  startDate=51,
  endDate=69
}
army_dates["5fb1b9e1e1af06001770986a"]["70 AD to 75 AD"] = {
  startDate=70,
  endDate=75
}
