-- 5fb1b9eae1af060017709e09 Khazar Decline  966 to 1106 AD

army['5fb1b9eae1af060017709e09']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Steppe',
    },
    name='Khazar Decline  966 to 1106 AD',
    id='5fb1b9eae1af060017709e09',
    dateRange={
      startDate=966,
      endDate=1106,
    },
  },
  g_base_definitions[g_str_68c995e2579163001588ae60_general],
  g_base_definitions[g_str_68c995e2579163001588ae60],
  g_base_definitions[g_str_68c995e2579163001588ae62],
  g_base_definitions[g_str_68c995e2579163001588ae62_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e2579163001588ae62_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e2579163001588ae65],
  g_base_definitions[g_str_68c995e2579163001588ae67],
  g_base_definitions[g_str_68c995e2579163001588ae67_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e2579163001588ae67_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e2579163001588ae6a],
  g_base_definitions[g_str_68c995e2579163001588ae6c],
  g_base_definitions[g_str_5fb1b9eae1af060017709e09_camp],
  g_base_definitions[g_str_5fb1b9eae1af060017709e09_camp_fortified],
  g_base_definitions[g_str_5fb1b9eae1af060017709e09_camp_standard_wagon],
  g_base_definitions[g_str_68c995cc57916300158879fb_general],
  g_base_definitions[g_str_68c995cc57916300158879fb],
  g_base_definitions[g_str_68c995cc57916300158879fd],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eae1af060017709e09"] = army["5fb1b9eae1af060017709e09"]
if nil == armies["Russian Princes"] then
  armies["Russian Princes"] ={}
end
armies["Russian Princes"]["Khazar Decline  966 to 1106 AD"] = army["5fb1b9eae1af060017709e09"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Khazar Decline  966 to 1106 AD"] = army["5fb1b9eae1af060017709e09"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Khazar Decline  966 to 1106 AD"] = army["5fb1b9eae1af060017709e09"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eae1af060017709e09"] = {}
army_dates["5fb1b9eae1af060017709e09"]["966 AD to 1106 AD"] = {
  startDate=966,
  endDate=1106
}
