-- 5fb1b9dce1af0600177095ab Iberians  240 to 20 BC

army['5fb1b9dce1af0600177095ab']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      4,
    },
    homeTopographies={
      'Arable',
    },
    name='Iberians  240 to 20 BC',
    id='5fb1b9dce1af0600177095ab',
    dateRange={
      startDate=-240,
      endDate=-20,
    },
    ambush=true,  },
  g_base_definitions[g_str_68c995d75791630015888e7d_general],
  g_base_definitions[g_str_68c995d75791630015888e7d_general_mounted],
  g_base_definitions[g_str_68c995d75791630015888e7d_general_dismounted],
  g_base_definitions[g_str_68c995d75791630015888e7d],
  g_base_definitions[g_str_68c995d75791630015888e7d_mounted],
  g_base_definitions[g_str_68c995d75791630015888e7d_dismounted],
  g_base_definitions[g_str_68c995d75791630015888e80],
  g_base_definitions[g_str_68c995d75791630015888e82],
  g_base_definitions[g_str_68c995d75791630015888e84],
  g_base_definitions[g_str_68c995d75791630015888e86],
  g_base_definitions[g_str_5fb1b9dce1af0600177095ab_camp],
  g_base_definitions[g_str_5fb1b9dce1af0600177095ab_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dce1af0600177095ab"] = army["5fb1b9dce1af0600177095ab"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Iberians  240 to 20 BC"] = army["5fb1b9dce1af0600177095ab"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Iberians  240 to 20 BC"] = army["5fb1b9dce1af0600177095ab"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Iberians  240 to 20 BC"] = army["5fb1b9dce1af0600177095ab"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dce1af0600177095ab"] = {}
army_dates["5fb1b9dce1af0600177095ab"]["240 BC to 20 BC"] = {
  startDate=-240,
  endDate=-20
}
