-- 5fb1b9e5e1af060017709a7c West Frisia  886 to 1296 AD

army['5fb1b9e5e1af060017709a7c']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Marsh',
    },
    name='West Frisia  886 to 1296 AD',
    id='5fb1b9e5e1af060017709a7c',
    dateRange={
      startDate=886,
      endDate=1296,
    },
  },
  g_base_definitions[g_str_68c995dd579163001588a052_general],
  g_base_definitions[g_str_68c995dd579163001588a052_general_mounted],
  g_base_definitions[g_str_68c995dd579163001588a052_general_dismounted],
  g_base_definitions[g_str_68c995dd579163001588a052],
  g_base_definitions[g_str_68c995dd579163001588a052_mounted],
  g_base_definitions[g_str_68c995dd579163001588a052_dismounted],
  g_base_definitions[g_str_68c995dd579163001588a055],
  g_base_definitions[g_str_68c995dd579163001588a057],
  g_base_definitions[g_str_68c995dd579163001588a059],
  g_base_definitions[g_str_68c995dd579163001588a05b],
  g_base_definitions[g_str_68c995dd579163001588a05c],
  g_base_definitions[g_str_68c995dd579163001588a05e],
  g_base_definitions[g_str_68c995dd579163001588a060],
  g_base_definitions[g_str_68c995dd579163001588a060_shower_shooting],
  g_base_definitions[g_str_5fb1b9e5e1af060017709a7c_camp],
  g_base_definitions[g_str_5fb1b9e5e1af060017709a7c_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e5e1af060017709a7c"] = army["5fb1b9e5e1af060017709a7c"]
if nil == armies["Viking Seas"] then
  armies["Viking Seas"] ={}
end
armies["Viking Seas"]["West Frisia  886 to 1296 AD"] = army["5fb1b9e5e1af060017709a7c"]
if nil == armies["Holy Roman Empire"] then
  armies["Holy Roman Empire"] ={}
end
armies["Holy Roman Empire"]["West Frisia  886 to 1296 AD"] = army["5fb1b9e5e1af060017709a7c"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["West Frisia  886 to 1296 AD"] = army["5fb1b9e5e1af060017709a7c"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e5e1af060017709a7c"] = {}
army_dates["5fb1b9e5e1af060017709a7c"]["886 AD to 1296 AD"] = {
  startDate=886,
  endDate=1296
}
