-- 5fb1b9e1e1af060017709838 Meroitic Kushite  592 BC to 350 AD

army['5fb1b9e1e1af060017709838']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Dry',
    },
    name='Meroitic Kushite  592 BC to 350 AD',
    id='5fb1b9e1e1af060017709838',
    dateRange={
      startDate=-592,
      endDate=350,
    },
  },
  g_base_definitions[g_str_68c995da5791630015889890_general],
  g_base_definitions[g_str_68c995da5791630015889890],
  g_base_definitions[g_str_68c995da5791630015889892_general],
  g_base_definitions[g_str_68c995da5791630015889892],
  g_base_definitions[g_str_68c995da5791630015889894_general],
  g_base_definitions[g_str_68c995da5791630015889894],
  g_base_definitions[g_str_68c995da5791630015889896],
  g_base_definitions[g_str_68c995da5791630015889898],
  g_base_definitions[g_str_68c995da5791630015889898_shower_shooting],
  g_base_definitions[g_str_68c995da579163001588989b],
  g_base_definitions[g_str_5fb1b9e1e1af060017709838_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e1e1af060017709838"] = army["5fb1b9e1e1af060017709838"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Meroitic Kushite  592 BC to 350 AD"] = army["5fb1b9e1e1af060017709838"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Meroitic Kushite  592 BC to 350 AD"] = army["5fb1b9e1e1af060017709838"]
if nil == armies["Assyrian Empire"] then
  armies["Assyrian Empire"] ={}
end
armies["Assyrian Empire"]["Meroitic Kushite  592 BC to 350 AD"] = army["5fb1b9e1e1af060017709838"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Meroitic Kushite  592 BC to 350 AD"] = army["5fb1b9e1e1af060017709838"]
if nil == armies["Pax Romana"] then
  armies["Pax Romana"] ={}
end
armies["Pax Romana"]["Meroitic Kushite  592 BC to 350 AD"] = army["5fb1b9e1e1af060017709838"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Meroitic Kushite  592 BC to 350 AD"] = army["5fb1b9e1e1af060017709838"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e1e1af060017709838"] = {}
army_dates["5fb1b9e1e1af060017709838"]["592 BC to 350 AD"] = {
  startDate=-592,
  endDate=350
}
army_dates["5fb1b9e1e1af060017709838"]["592 BC to 31 BC"] = {
  startDate=-592,
  endDate=-31
}
army_dates["5fb1b9e1e1af060017709838"]["30 BC to 350 AD"] = {
  startDate=-30,
  endDate=350
}
