-- 5fb1b9ece1af060017709ec2 Nobatia or Ballana  30 BC to 550 AD

army['5fb1b9ece1af060017709ec2']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Dry',
    },
    name='Nobatia or Ballana  30 BC to 550 AD',
    id='5fb1b9ece1af060017709ec2',
    dateRange={
      startDate=-30,
      endDate=550,
    },
  },
  g_base_definitions[g_str_68c995e4579163001588b199_general],
  g_base_definitions[g_str_68c995e4579163001588b199],
  g_base_definitions[g_str_68c995e4579163001588b19c_general],
  g_base_definitions[g_str_68c995e4579163001588b19c],
  g_base_definitions[g_str_68c995e4579163001588b19f_general],
  g_base_definitions[g_str_68c995e4579163001588b19f],
  g_base_definitions[g_str_68c995e4579163001588b1a1],
  g_base_definitions[g_str_68c995e4579163001588b1a1_shower_shooting],
  g_base_definitions[g_str_68c995e4579163001588b1a4],
  g_base_definitions[g_str_68c995e4579163001588b1a6],
  g_base_definitions[g_str_68c995e4579163001588b1a6_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b1a6_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b1a9],
  g_base_definitions[g_str_68c995e4579163001588b1a9_light_camelry],
  g_base_definitions[g_str_5fb1b9ece1af060017709ec2_camp],
  g_base_definitions[g_str_5fb1b9ece1af060017709ec2_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ece1af060017709ec2"] = army["5fb1b9ece1af060017709ec2"]
if nil == armies["Pax Romana"] then
  armies["Pax Romana"] ={}
end
armies["Pax Romana"]["Nobatia or Ballana  30 BC to 550 AD"] = army["5fb1b9ece1af060017709ec2"]
if nil == armies["Fall of Rome"] then
  armies["Fall of Rome"] ={}
end
armies["Fall of Rome"]["Nobatia or Ballana  30 BC to 550 AD"] = army["5fb1b9ece1af060017709ec2"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Nobatia or Ballana  30 BC to 550 AD"] = army["5fb1b9ece1af060017709ec2"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ece1af060017709ec2"] = {}
army_dates["5fb1b9ece1af060017709ec2"]["30 BC to 550 AD"] = {
  startDate=-30,
  endDate=550
}
