-- 5fb1b9dde1af0600177095f1 Later Hoplite Thessalian  448 to 225 BC

army['5fb1b9dde1af0600177095f1']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
    },
    name='Later Hoplite Thessalian  448 to 225 BC',
    id='5fb1b9dde1af0600177095f1',
    dateRange={
      startDate=-448,
      endDate=-225,
    },
  },
  g_base_definitions[g_str_68c995d75791630015888fb9_general],
  g_base_definitions[g_str_68c995d75791630015888fb9],
  g_base_definitions[g_str_68c995d75791630015888fbc],
  g_base_definitions[g_str_68c995d75791630015888fbf],
  g_base_definitions[g_str_68c995d75791630015888fc1_general],
  g_base_definitions[g_str_68c995d75791630015888fc1],
  g_base_definitions[g_str_68c995d75791630015888fc3],
  g_base_definitions[g_str_68c995d75791630015888fc5],
  g_base_definitions[g_str_68c995d75791630015888fc7],
  g_base_definitions[g_str_68c995d75791630015888fc9],
  g_base_definitions[g_str_5fb1b9dde1af0600177095f1_camp],
  g_base_definitions[g_str_5fb1b9dde1af0600177095f1_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dde1af0600177095f1"] = army["5fb1b9dde1af0600177095f1"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Later Hoplite Thessalian  448 to 225 BC"] = army["5fb1b9dde1af0600177095f1"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Later Hoplite Thessalian  448 to 225 BC"] = army["5fb1b9dde1af0600177095f1"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Hoplite Thessalian  448 to 225 BC"] = army["5fb1b9dde1af0600177095f1"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dde1af0600177095f1"] = {}
army_dates["5fb1b9dde1af0600177095f1"]["448 BC to 225 BC"] = {
  startDate=-448,
  endDate=-225
}
