-- 5fb1b9e0e1af0600177097d8 Early Kushan  135 to 100 BC

army['5fb1b9e0e1af0600177097d8']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Hilly',
      'Steppe',
    },
    name='Early Kushan  135 to 100 BC',
    id='5fb1b9e0e1af0600177097d8',
    dateRange={
      startDate=-135,
      endDate=-100,
    },
  },
  g_base_definitions[g_str_68c995da5791630015889727],
  g_base_definitions[g_str_68c995da5791630015889728_general],
  g_base_definitions[g_str_68c995da5791630015889728],
  g_base_definitions[g_str_68c995da579163001588972a],
  g_base_definitions[g_str_68c995da579163001588972c],
  g_base_definitions[g_str_68c995da579163001588972e],
  g_base_definitions[g_str_68c995da5791630015889730],
  g_base_definitions[g_str_5fb1b9e0e1af0600177097d8_camp],
  g_base_definitions[g_str_5fb1b9e0e1af0600177097d8_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e0e1af0600177097d8"] = army["5fb1b9e0e1af0600177097d8"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Early Kushan  135 to 100 BC"] = army["5fb1b9e0e1af0600177097d8"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Early Kushan  135 to 100 BC"] = army["5fb1b9e0e1af0600177097d8"]
if nil == armies["India and the Khyber Pass"] then
  armies["India and the Khyber Pass"] ={}
end
armies["India and the Khyber Pass"]["Early Kushan  135 to 100 BC"] = army["5fb1b9e0e1af0600177097d8"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Kushan  135 to 100 BC"] = army["5fb1b9e0e1af0600177097d8"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e0e1af0600177097d8"] = {}
army_dates["5fb1b9e0e1af0600177097d8"]["135 BC to 100 BC"] = {
  startDate=-135,
  endDate=-100
}
