-- 5fb1b9e0e1af0600177097c8 Parthian Subject Provinces  147 BC to 225 AD

army['5fb1b9e0e1af0600177097c8']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
      'Hilly',
    },
    name='Parthian Subject Provinces  147 BC to 225 AD',
    id='5fb1b9e0e1af0600177097c8',
    dateRange={
      startDate=-147,
      endDate=225,
    },
  },
  g_base_definitions[g_str_68c995d957916300158896ff_general],
  g_base_definitions[g_str_68c995d957916300158896ff_general_armored_camelry],
  g_base_definitions[g_str_68c995d957916300158896ff],
  g_base_definitions[g_str_68c995d957916300158896ff_armored_camelry],
  g_base_definitions[g_str_68c995d95791630015889702],
  g_base_definitions[g_str_68c995d95791630015889704],
  g_base_definitions[g_str_68c995d95791630015889704_shower_shooting],
  g_base_definitions[g_str_68c995d95791630015889707],
  g_base_definitions[g_str_68c995d95791630015889707_shower_shooting],
  g_base_definitions[g_str_68c995d95791630015889708],
  g_base_definitions[g_str_68c995d95791630015889708_shower_shooting],
  g_base_definitions[g_str_68c995d9579163001588970b],
  g_base_definitions[g_str_5fb1b9e0e1af0600177097c8_camp],
  g_base_definitions[g_str_5fb1b9e0e1af0600177097c8_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e0e1af0600177097c8"] = army["5fb1b9e0e1af0600177097c8"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Parthian Subject Provinces  147 BC to 225 AD"] = army["5fb1b9e0e1af0600177097c8"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Parthian Subject Provinces  147 BC to 225 AD"] = army["5fb1b9e0e1af0600177097c8"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Parthian Subject Provinces  147 BC to 225 AD"] = army["5fb1b9e0e1af0600177097c8"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e0e1af0600177097c8"] = {}
army_dates["5fb1b9e0e1af0600177097c8"]["147 BC to 225 AD"] = {
  startDate=-147,
  endDate=225
}
