-- 5fb1b9ede1af060017709f4e Qaramita  897 to 1078 AD

army['5fb1b9ede1af060017709f4e']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Dry',
    },
    name='Qaramita  897 to 1078 AD',
    id='5fb1b9ede1af060017709f4e',
    dateRange={
      startDate=897,
      endDate=1078,
    },
  },
  g_base_definitions[g_str_68c995e4579163001588b415_general],
  g_base_definitions[g_str_68c995e4579163001588b415],
  g_base_definitions[g_str_68c995e4579163001588b417],
  g_base_definitions[g_str_68c995e4579163001588b417_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b417_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b41a],
  g_base_definitions[g_str_68c995e4579163001588b41a_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b41a_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b41d_general],
  g_base_definitions[g_str_68c995e4579163001588b41d],
  g_base_definitions[g_str_68c995e4579163001588b41f],
  g_base_definitions[g_str_68c995e4579163001588b421],
  g_base_definitions[g_str_68c995e4579163001588b421_light_camelry],
  g_base_definitions[g_str_68c995e4579163001588b424],
  g_base_definitions[g_str_5fb1b9ede1af060017709f4e_camp],
  g_base_definitions[g_str_5fb1b9ede1af060017709f4e_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ede1af060017709f4e"] = army["5fb1b9ede1af060017709f4e"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Qaramita  897 to 1078 AD"] = army["5fb1b9ede1af060017709f4e"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Qaramita  897 to 1078 AD"] = army["5fb1b9ede1af060017709f4e"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ede1af060017709f4e"] = {}
army_dates["5fb1b9ede1af060017709f4e"]["897 AD to 1078 AD"] = {
  startDate=897,
  endDate=1078
}
