-- 5fb1b9f0e1af06001770a11c Siamese Minor States  1234 to 1518 AD

army['5fb1b9f0e1af06001770a11c']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Forest',
    },
    name='Siamese Minor States  1234 to 1518 AD',
    id='5fb1b9f0e1af06001770a11c',
    dateRange={
      startDate=1234,
      endDate=1518,
    },
    ambush=true,  },
  g_base_definitions[g_str_68c995e7579163001588bbbe_general],
  g_base_definitions[g_str_68c995e7579163001588bbbe],
  g_base_definitions[g_str_68c995e7579163001588bbc1_general],
  g_base_definitions[g_str_68c995e7579163001588bbc1],
  g_base_definitions[g_str_68c995e7579163001588bbc3_general],
  g_base_definitions[g_str_68c995e7579163001588bbc3_general_elephant_screen],
  g_base_definitions[g_str_68c995e7579163001588bbc3],
  g_base_definitions[g_str_68c995e7579163001588bbc3_elephant_screen],
  g_base_definitions[g_str_68c995e7579163001588bbc7],
  g_base_definitions[g_str_68c995e7579163001588bbc8],
  g_base_definitions[g_str_68c995e7579163001588bbcb],
  g_base_definitions[g_str_68c995e7579163001588bbce],
  g_base_definitions[g_str_68c995e7579163001588bbce_shower_shooting],
  g_base_definitions[g_str_5fb1b9f0e1af06001770a11c_camp],
  g_base_definitions[g_str_5fb1b9f0e1af06001770a11c_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f0e1af06001770a11c"] = army["5fb1b9f0e1af06001770a11c"]
if nil == armies["Monsoon Region"] then
  armies["Monsoon Region"] ={}
end
armies["Monsoon Region"]["Siamese Minor States  1234 to 1518 AD"] = army["5fb1b9f0e1af06001770a11c"]
if nil == armies["Southeast Asia"] then
  armies["Southeast Asia"] ={}
end
armies["Southeast Asia"]["Siamese Minor States  1234 to 1518 AD"] = army["5fb1b9f0e1af06001770a11c"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Siamese Minor States  1234 to 1518 AD"] = army["5fb1b9f0e1af06001770a11c"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f0e1af06001770a11c"] = {}
army_dates["5fb1b9f0e1af06001770a11c"]["1234 AD to 1518 AD"] = {
  startDate=1234,
  endDate=1518
}
army_dates["5fb1b9f0e1af06001770a11c"]["1234 AD to 1278 AD"] = {
  startDate=1234,
  endDate=1278
}
army_dates["5fb1b9f0e1af06001770a11c"]["1279 AD to 1431 AD"] = {
  startDate=1279,
  endDate=1431
}
army_dates["5fb1b9f0e1af06001770a11c"]["1432 AD to 1518 AD"] = {
  startDate=1432,
  endDate=1518
}
