-- 5fb1b9f2e1af06001770a207 Xianbei Kingdoms  304 to 431 AD

army['5fb1b9f2e1af06001770a207']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      3,
      1,
    },
    homeTopographies={
      'Hilly',
      'Dry',
    },
    name='Xianbei Kingdoms  304 to 431 AD',
    id='5fb1b9f2e1af06001770a207',
    dateRange={
      startDate=304,
      endDate=431,
    },
  },
  g_base_definitions[g_str_68c995e8579163001588bea3_general],
  g_base_definitions[g_str_68c995e8579163001588bea3],
  g_base_definitions[g_str_68c995e8579163001588bea4_general],
  g_base_definitions[g_str_68c995e8579163001588bea4],
  g_base_definitions[g_str_68c995e8579163001588bea6],
  g_base_definitions[g_str_68c995e8579163001588bea8],
  g_base_definitions[g_str_68c995e8579163001588bea9],
  g_base_definitions[g_str_68c995e8579163001588beac],
  g_base_definitions[g_str_5fb1b9f2e1af06001770a207_camp],
  g_base_definitions[g_str_5fb1b9f2e1af06001770a207_camp_pack_train],
  g_base_definitions[g_str_68c995cf5791630015887f99],
  g_base_definitions[g_str_68c995cf5791630015887f9b],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f2e1af06001770a207"] = army["5fb1b9f2e1af06001770a207"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Xianbei Kingdoms  304 to 431 AD"] = army["5fb1b9f2e1af06001770a207"]
if nil == armies["Dark Ages China"] then
  armies["Dark Ages China"] ={}
end
armies["Dark Ages China"]["Xianbei Kingdoms  304 to 431 AD"] = army["5fb1b9f2e1af06001770a207"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Xianbei Kingdoms  304 to 431 AD"] = army["5fb1b9f2e1af06001770a207"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f2e1af06001770a207"] = {}
army_dates["5fb1b9f2e1af06001770a207"]["304 AD to 431 AD"] = {
  startDate=304,
  endDate=431
}
army_dates["5fb1b9f2e1af06001770a207"]["304 AD to 350 AD"] = {
  startDate=304,
  endDate=350
}
army_dates["5fb1b9f2e1af06001770a207"]["351 AD to 368 AD"] = {
  startDate=351,
  endDate=368
}
army_dates["5fb1b9f2e1af06001770a207"]["369 AD"] = {
  startDate=369,
  endDate=369
}
army_dates["5fb1b9f2e1af06001770a207"]["370 AD to 394 AD"] = {
  startDate=370,
  endDate=394
}
army_dates["5fb1b9f2e1af06001770a207"]["395 AD to 431 AD"] = {
  startDate=395,
  endDate=431
}
