-- 5fb1b9e5e1af060017709a8f Later Magyar  896 to 1003 AD

army['5fb1b9e5e1af060017709a8f']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Steppe',
    },
    name='Later Magyar  896 to 1003 AD',
    id='5fb1b9e5e1af060017709a8f',
    dateRange={
      startDate=896,
      endDate=1003,
    },
  },
  g_base_definitions[g_str_68c995de579163001588a088_general],
  g_base_definitions[g_str_68c995de579163001588a088],
  g_base_definitions[g_str_68c995de579163001588a089_general],
  g_base_definitions[g_str_68c995de579163001588a089],
  g_base_definitions[g_str_68c995de579163001588a08b],
  g_base_definitions[g_str_68c995de579163001588a08d],
  g_base_definitions[g_str_68c995de579163001588a08f],
  g_base_definitions[g_str_68c995de579163001588a091],
  g_base_definitions[g_str_68c995de579163001588a092],
  g_base_definitions[g_str_5fb1b9e5e1af060017709a8f_camp],
  g_base_definitions[g_str_5fb1b9e5e1af060017709a8f_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e5e1af060017709a8f"] = army["5fb1b9e5e1af060017709a8f"]
if nil == armies["Viking Seas"] then
  armies["Viking Seas"] ={}
end
armies["Viking Seas"]["Later Magyar  896 to 1003 AD"] = army["5fb1b9e5e1af060017709a8f"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Magyar  896 to 1003 AD"] = army["5fb1b9e5e1af060017709a8f"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e5e1af060017709a8f"] = {}
army_dates["5fb1b9e5e1af060017709a8f"]["896 AD to 1003 AD"] = {
  startDate=896,
  endDate=1003
}
