-- 5fb1b9f2e1af06001770a247 Chinese Southern Dynasties  317 to 589 AD

army['5fb1b9f2e1af06001770a247']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Forest',
    },
    name='Chinese Southern Dynasties  317 to 589 AD',
    id='5fb1b9f2e1af06001770a247',
    dateRange={
      startDate=317,
      endDate=589,
    },
  },
  g_base_definitions[g_str_68c995e8579163001588bf5c_general],
  g_base_definitions[g_str_68c995e8579163001588bf5c],
  g_base_definitions[g_str_68c995e8579163001588bf5d_general],
  g_base_definitions[g_str_68c995e8579163001588bf5d],
  g_base_definitions[g_str_68c995e8579163001588bf5f],
  g_base_definitions[g_str_68c995e8579163001588bf61],
  g_base_definitions[g_str_68c995e8579163001588bf62],
  g_base_definitions[g_str_68c995e8579163001588bf64],
  g_base_definitions[g_str_68c995e8579163001588bf67],
  g_base_definitions[g_str_68c995e8579163001588bf67_shower_shooting],
  g_base_definitions[g_str_68c995e8579163001588bf6b],
  g_base_definitions[g_str_68c995e8579163001588bf6d],
  g_base_definitions[g_str_68c995e8579163001588bf6d_shower_shooting],
  g_base_definitions[g_str_68c995e8579163001588bf70],
  g_base_definitions[g_str_5fb1b9f2e1af06001770a247_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f2e1af06001770a247"] = army["5fb1b9f2e1af06001770a247"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Chinese Southern Dynasties  317 to 589 AD"] = army["5fb1b9f2e1af06001770a247"]
if nil == armies["Dark Ages China"] then
  armies["Dark Ages China"] ={}
end
armies["Dark Ages China"]["Chinese Southern Dynasties  317 to 589 AD"] = army["5fb1b9f2e1af06001770a247"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Chinese Southern Dynasties  317 to 589 AD"] = army["5fb1b9f2e1af06001770a247"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f2e1af06001770a247"] = {}
army_dates["5fb1b9f2e1af06001770a247"]["317 AD to 589 AD"] = {
  startDate=317,
  endDate=589
}
