-- 5fb1b9dfe1af060017709784 Later Greco-Bactrian  150 to 130 BC

army['5fb1b9dfe1af060017709784']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Hilly',
      'Steppe',
    },
    name='Later Greco-Bactrian  150 to 130 BC',
    id='5fb1b9dfe1af060017709784',
    dateRange={
      startDate=-150,
      endDate=-130,
    },
  },
  g_base_definitions[g_str_68c995d9579163001588960c],
  g_base_definitions[g_str_68c995d9579163001588960e],
  g_base_definitions[g_str_68c995d95791630015889610_general],
  g_base_definitions[g_str_68c995d95791630015889610],
  g_base_definitions[g_str_68c995d95791630015889612],
  g_base_definitions[g_str_5fb1b9dfe1af060017709784_camp],
  g_base_definitions[g_str_5fb1b9dfe1af060017709784_camp_pack_train],
  g_base_definitions[g_str_68c995c75791630015887138],
  g_base_definitions[g_str_68c995c7579163001588713a],
  g_base_definitions[g_str_68c995c7579163001588713c],
  g_base_definitions[g_str_68c995c7579163001588713e],
  g_base_definitions[g_str_68c995c75791630015887140],
  g_base_definitions[g_str_68c995c75791630015887141],
  g_base_definitions[g_str_68c995c75791630015887142],
  g_base_definitions[g_str_68c995c75791630015887144],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dfe1af060017709784"] = army["5fb1b9dfe1af060017709784"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Later Greco-Bactrian  150 to 130 BC"] = army["5fb1b9dfe1af060017709784"]
if nil == armies["India and the Khyber Pass"] then
  armies["India and the Khyber Pass"] ={}
end
armies["India and the Khyber Pass"]["Later Greco-Bactrian  150 to 130 BC"] = army["5fb1b9dfe1af060017709784"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Greco-Bactrian  150 to 130 BC"] = army["5fb1b9dfe1af060017709784"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dfe1af060017709784"] = {}
army_dates["5fb1b9dfe1af060017709784"]["150 BC to 130 BC"] = {
  startDate=-150,
  endDate=-130
}
