-- 5fb1b9f4e1af06001770a31f Later Kofun and Asuka Japanese  501 to 645 AD

army['5fb1b9f4e1af06001770a31f']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
      'Hilly',
    },
    name='Later Kofun and Asuka Japanese  501 to 645 AD',
    id='5fb1b9f4e1af06001770a31f',
    dateRange={
      startDate=501,
      endDate=645,
    },
  },
  g_base_definitions[g_str_68c995ea579163001588c2f9_general],
  g_base_definitions[g_str_68c995ea579163001588c2f9],
  g_base_definitions[g_str_68c995ea579163001588c2fb_general],
  g_base_definitions[g_str_68c995ea579163001588c2fb],
  g_base_definitions[g_str_68c995ea579163001588c2fd_general],
  g_base_definitions[g_str_68c995ea579163001588c2fd],
  g_base_definitions[g_str_68c995ea579163001588c2ff],
  g_base_definitions[g_str_68c995ea579163001588c300],
  g_base_definitions[g_str_68c995ea579163001588c302],
  g_base_definitions[g_str_68c995ea579163001588c302_shower_shooting],
  g_base_definitions[g_str_68c995ea579163001588c305],
  g_base_definitions[g_str_68c995ea579163001588c307],
  g_base_definitions[g_str_5fb1b9f4e1af06001770a31f_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f4e1af06001770a31f"] = army["5fb1b9f4e1af06001770a31f"]
if nil == armies["Korea and Japan"] then
  armies["Korea and Japan"] ={}
end
armies["Korea and Japan"]["Later Kofun and Asuka Japanese  501 to 645 AD"] = army["5fb1b9f4e1af06001770a31f"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Kofun and Asuka Japanese  501 to 645 AD"] = army["5fb1b9f4e1af06001770a31f"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f4e1af06001770a31f"] = {}
army_dates["5fb1b9f4e1af06001770a31f"]["501 AD to 645 AD"] = {
  startDate=501,
  endDate=645
}
