-- 5fb1b9dce1af060017709573 Zama Campaign  202 to 202 BC

army['5fb1b9dce1af060017709573']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
    },
    name='Zama Campaign  202 to 202 BC',
    id='5fb1b9dce1af060017709573',
    dateRange={
      startDate=-202,
      endDate=-202,
    },
  },
  g_base_definitions[g_str_68c995d75791630015888de1_general],
  g_base_definitions[g_str_68c995d75791630015888de1],
  g_base_definitions[g_str_68c995d75791630015888de3_general],
  g_base_definitions[g_str_68c995d75791630015888de3],
  g_base_definitions[g_str_68c995d75791630015888de5],
  g_base_definitions[g_str_68c995d75791630015888de8],
  g_base_definitions[g_str_68c995d75791630015888dea],
  g_base_definitions[g_str_68c995d75791630015888dec],
  g_base_definitions[g_str_68c995d75791630015888dee],
  g_base_definitions[g_str_68c995d75791630015888df0],
  g_base_definitions[g_str_5fb1b9dce1af060017709573_camp],
  g_base_definitions[g_str_5fb1b9dce1af060017709573_camp_fortified],
  g_base_definitions[g_str_5fb1b9dce1af060017709573_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dce1af060017709573"] = army["5fb1b9dce1af060017709573"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Zama Campaign  202 to 202 BC"] = army["5fb1b9dce1af060017709573"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Zama Campaign  202 to 202 BC"] = army["5fb1b9dce1af060017709573"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Zama Campaign  202 to 202 BC"] = army["5fb1b9dce1af060017709573"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dce1af060017709573"] = {}
army_dates["5fb1b9dce1af060017709573"]["202 BC"] = {
  startDate=-202,
  endDate=-202
}
