-- 5fb1b9f1e1af06001770a1a9 Dian and Kunming  295 BC to 45 AD

army['5fb1b9f1e1af06001770a1a9']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      2,
      1,
    },
    homeTopographies={
      'Hilly',
    },
    name='Dian and Kunming  295 BC to 45 AD',
    id='5fb1b9f1e1af06001770a1a9',
    dateRange={
      startDate=-295,
      endDate=45,
    },
  },
  g_base_definitions[g_str_68c995e8579163001588bd4c_general],
  g_base_definitions[g_str_68c995e8579163001588bd4c],
  g_base_definitions[g_str_68c995e8579163001588bd4e_general],
  g_base_definitions[g_str_68c995e8579163001588bd4e],
  g_base_definitions[g_str_68c995e8579163001588bd50],
  g_base_definitions[g_str_68c995e8579163001588bd52],
  g_base_definitions[g_str_68c995e8579163001588bd54],
  g_base_definitions[g_str_68c995e8579163001588bd55],
  g_base_definitions[g_str_68c995e8579163001588bd57],
  g_base_definitions[g_str_68c995e8579163001588bd59],
  g_base_definitions[g_str_68c995e8579163001588bd5b],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a1a9_camp],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a1a9_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f1e1af06001770a1a9"] = army["5fb1b9f1e1af06001770a1a9"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Dian and Kunming  295 BC to 45 AD"] = army["5fb1b9f1e1af06001770a1a9"]
if nil == armies["Southeast Asia"] then
  armies["Southeast Asia"] ={}
end
armies["Southeast Asia"]["Dian and Kunming  295 BC to 45 AD"] = army["5fb1b9f1e1af06001770a1a9"]
if nil == armies["Warring States"] then
  armies["Warring States"] ={}
end
armies["Warring States"]["Dian and Kunming  295 BC to 45 AD"] = army["5fb1b9f1e1af06001770a1a9"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Dian and Kunming  295 BC to 45 AD"] = army["5fb1b9f1e1af06001770a1a9"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f1e1af06001770a1a9"] = {}
army_dates["5fb1b9f1e1af06001770a1a9"]["295 BC to 45 AD"] = {
  startDate=-295,
  endDate=45
}
