-- 5fb1b9ece1af060017709f0d Abbasid Revolt  747 to 750 AD

army['5fb1b9ece1af060017709f0d']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Delta',
      'Dry',
      'Hilly',
    },
    name='Abbasid Revolt  747 to 750 AD',
    id='5fb1b9ece1af060017709f0d',
    dateRange={
      startDate=747,
      endDate=750,
    },
  },
  g_base_definitions[g_str_68c995e4579163001588b2d0_general],
  g_base_definitions[g_str_68c995e4579163001588b2d0_general_mounted],
  g_base_definitions[g_str_68c995e4579163001588b2d0_general_dismounted],
  g_base_definitions[g_str_68c995e4579163001588b2d0],
  g_base_definitions[g_str_68c995e4579163001588b2d0_mounted],
  g_base_definitions[g_str_68c995e4579163001588b2d0_dismounted],
  g_base_definitions[g_str_68c995e4579163001588b2d3],
  g_base_definitions[g_str_68c995e4579163001588b2d6],
  g_base_definitions[g_str_68c995e4579163001588b2d7],
  g_base_definitions[g_str_68c995e4579163001588b2da],
  g_base_definitions[g_str_68c995e4579163001588b2dc_general],
  g_base_definitions[g_str_68c995e4579163001588b2dc],
  g_base_definitions[g_str_5fb1b9ece1af060017709f0d_camp],
  g_base_definitions[g_str_5fb1b9ece1af060017709f0d_camp_fortified],
  g_base_definitions[g_str_5fb1b9ece1af060017709f0d_camp_pack_train],
  g_base_definitions[g_str_5fb1b9ece1af060017709f0d_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ece1af060017709f0d"] = army["5fb1b9ece1af060017709f0d"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Abbasid Revolt  747 to 750 AD"] = army["5fb1b9ece1af060017709f0d"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Abbasid Revolt  747 to 750 AD"] = army["5fb1b9ece1af060017709f0d"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Abbasid Revolt  747 to 750 AD"] = army["5fb1b9ece1af060017709f0d"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ece1af060017709f0d"] = {}
army_dates["5fb1b9ece1af060017709f0d"]["747 AD to 750 AD"] = {
  startDate=747,
  endDate=750
}
