-- 5fb1b9f2e1af06001770a1ee Mai Thuc Loan's revolt  722 to 722 AD

army['5fb1b9f2e1af06001770a1ee']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Forest',
    },
    name='Mai Thuc Loan\'s revolt  722 to 722 AD',
    id='5fb1b9f2e1af06001770a1ee',
    dateRange={
      startDate=722,
      endDate=722,
    },
  },
  g_base_definitions[g_str_68c995e8579163001588be1e_general],
  g_base_definitions[g_str_68c995e8579163001588be1e],
  g_base_definitions[g_str_68c995e8579163001588be20_general],
  g_base_definitions[g_str_68c995e8579163001588be20],
  g_base_definitions[g_str_68c995e8579163001588be22],
  g_base_definitions[g_str_68c995e8579163001588be22_shower_shooting],
  g_base_definitions[g_str_68c995e8579163001588be25],
  g_base_definitions[g_str_68c995e8579163001588be27],
  g_base_definitions[g_str_68c995e8579163001588be29],
  g_base_definitions[g_str_68c995e8579163001588be29_shower_shooting],
  g_base_definitions[g_str_5fb1b9f2e1af06001770a1ee_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f2e1af06001770a1ee"] = army["5fb1b9f2e1af06001770a1ee"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Mai Thuc Loan\'s revolt  722 to 722 AD"] = army["5fb1b9f2e1af06001770a1ee"]
if nil == armies["Southeast Asia"] then
  armies["Southeast Asia"] ={}
end
armies["Southeast Asia"]["Mai Thuc Loan\'s revolt  722 to 722 AD"] = army["5fb1b9f2e1af06001770a1ee"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Mai Thuc Loan\'s revolt  722 to 722 AD"] = army["5fb1b9f2e1af06001770a1ee"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f2e1af06001770a1ee"] = {}
army_dates["5fb1b9f2e1af06001770a1ee"]["722 AD"] = {
  startDate=722,
  endDate=722
}
