-- 5fb1b9e1e1af06001770985d Batavian Revolt  69 to 70 AD

army['5fb1b9e1e1af06001770985d']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Forest',
    },
    name='Batavian Revolt  69 to 70 AD',
    id='5fb1b9e1e1af06001770985d',
    dateRange={
      startDate=69,
      endDate=70,
    },
  },
  g_base_definitions[g_str_68c995da57916300158898f6_general],
  g_base_definitions[g_str_68c995da57916300158898f6_general_mounted],
  g_base_definitions[g_str_68c995da57916300158898f6_general_dismounted],
  g_base_definitions[g_str_68c995da57916300158898f6],
  g_base_definitions[g_str_68c995da57916300158898f6_mounted],
  g_base_definitions[g_str_68c995da57916300158898f6_dismounted],
  g_base_definitions[g_str_68c995da57916300158898f9],
  g_base_definitions[g_str_68c995da57916300158898fb],
  g_base_definitions[g_str_68c995da57916300158898fd_general],
  g_base_definitions[g_str_68c995da57916300158898fd],
  g_base_definitions[g_str_68c995da57916300158898ff],
  g_base_definitions[g_str_68c995da5791630015889901],
  g_base_definitions[g_str_68c995da5791630015889903],
  g_base_definitions[g_str_5fb1b9e1e1af06001770985d_camp],
  g_base_definitions[g_str_5fb1b9e1e1af06001770985d_camp_fortified],
  g_base_definitions[g_str_5fb1b9e1e1af06001770985d_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e1e1af06001770985d"] = army["5fb1b9e1e1af06001770985d"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Batavian Revolt  69 to 70 AD"] = army["5fb1b9e1e1af06001770985d"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Batavian Revolt  69 to 70 AD"] = army["5fb1b9e1e1af06001770985d"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e1e1af06001770985d"] = {}
army_dates["5fb1b9e1e1af06001770985d"]["69 AD to 70 AD"] = {
  startDate=69,
  endDate=70
}
