-- 5fb1b9f0e1af06001770a12f Guifang and Xianyun  1100 to 800 BC

army['5fb1b9f0e1af06001770a12f']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Steppe',
    },
    name='Guifang and Xianyun  1100 to 800 BC',
    id='5fb1b9f0e1af06001770a12f',
    dateRange={
      startDate=-1100,
      endDate=-800,
    },
  },
  g_base_definitions[g_str_68c995e7579163001588bc0b_general],
  g_base_definitions[g_str_68c995e7579163001588bc0b],
  g_base_definitions[g_str_68c995e7579163001588bc0d_general],
  g_base_definitions[g_str_68c995e7579163001588bc0d],
  g_base_definitions[g_str_68c995e7579163001588bc0f],
  g_base_definitions[g_str_68c995e7579163001588bc11],
  g_base_definitions[g_str_5fb1b9f0e1af06001770a12f_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f0e1af06001770a12f"] = army["5fb1b9f0e1af06001770a12f"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Guifang and Xianyun  1100 to 800 BC"] = army["5fb1b9f0e1af06001770a12f"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Guifang and Xianyun  1100 to 800 BC"] = army["5fb1b9f0e1af06001770a12f"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f0e1af06001770a12f"] = {}
army_dates["5fb1b9f0e1af06001770a12f"]["1100 BC to 800 BC"] = {
  startDate=-1100,
  endDate=-800
}
