-- 5fb1b9e1e1af060017709863 Early German Cherusci or Batavian  115 BC to 250 AD

army['5fb1b9e1e1af060017709863']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Forest',
    },
    name='Early German Cherusci or Batavian  115 BC to 250 AD',
    id='5fb1b9e1e1af060017709863',
    dateRange={
      startDate=-115,
      endDate=250,
    },
    ambush=true,  },
  g_base_definitions[g_str_68c995da579163001588990b_general],
  g_base_definitions[g_str_68c995da579163001588990b_general_mounted],
  g_base_definitions[g_str_68c995da579163001588990b_general_dismounted],
  g_base_definitions[g_str_68c995da579163001588990b],
  g_base_definitions[g_str_68c995da579163001588990b_mounted],
  g_base_definitions[g_str_68c995da579163001588990b_dismounted],
  g_base_definitions[g_str_68c995da579163001588990e_general],
  g_base_definitions[g_str_68c995da579163001588990e],
  g_base_definitions[g_str_68c995da5791630015889910],
  g_base_definitions[g_str_68c995da5791630015889912],
  g_base_definitions[g_str_68c995da5791630015889914],
  g_base_definitions[g_str_5fb1b9e1e1af060017709863_camp],
  g_base_definitions[g_str_5fb1b9e1e1af060017709863_camp_fortified],
  g_base_definitions[g_str_5fb1b9e1e1af060017709863_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e1e1af060017709863"] = army["5fb1b9e1e1af060017709863"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Early German Cherusci or Batavian  115 BC to 250 AD"] = army["5fb1b9e1e1af060017709863"]
if nil == armies["Pax Romana"] then
  armies["Pax Romana"] ={}
end
armies["Pax Romana"]["Early German Cherusci or Batavian  115 BC to 250 AD"] = army["5fb1b9e1e1af060017709863"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early German Cherusci or Batavian  115 BC to 250 AD"] = army["5fb1b9e1e1af060017709863"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e1e1af060017709863"] = {}
army_dates["5fb1b9e1e1af060017709863"]["115 BC to 250 AD"] = {
  startDate=-115,
  endDate=250
}
