-- 5fb1b9dde1af06001770960e Later Hoplite Greek Minor Powers  448 to 225 BC

army['5fb1b9dde1af06001770960e']={
  data={
    invasionRatings={
      4,
      1,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
      'Hilly',
    },
    name='Later Hoplite Greek Minor Powers  448 to 225 BC',
    id='5fb1b9dde1af06001770960e',
    dateRange={
      startDate=-448,
      endDate=-225,
    },
  },
  g_base_definitions[g_str_68c995d75791630015889022_general],
  g_base_definitions[g_str_68c995d75791630015889022],
  g_base_definitions[g_str_68c995d75791630015889025],
  g_base_definitions[g_str_68c995d75791630015889027],
  g_base_definitions[g_str_68c995d75791630015889029],
  g_base_definitions[g_str_68c995d7579163001588902b],
  g_base_definitions[g_str_68c995d7579163001588902d],
  g_base_definitions[g_str_68c995d7579163001588902f_general],
  g_base_definitions[g_str_68c995d7579163001588902f],
  g_base_definitions[g_str_68c995d75791630015889032],
  g_base_definitions[g_str_5fb1b9dde1af06001770960e_camp],
  g_base_definitions[g_str_5fb1b9dde1af06001770960e_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dde1af06001770960e"] = army["5fb1b9dde1af06001770960e"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Later Hoplite Greek Minor Powers  448 to 225 BC"] = army["5fb1b9dde1af06001770960e"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Later Hoplite Greek Minor Powers  448 to 225 BC"] = army["5fb1b9dde1af06001770960e"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Hoplite Greek Minor Powers  448 to 225 BC"] = army["5fb1b9dde1af06001770960e"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dde1af06001770960e"] = {}
army_dates["5fb1b9dde1af06001770960e"]["448 BC to 225 BC"] = {
  startDate=-448,
  endDate=-225
}
army_dates["5fb1b9dde1af06001770960e"]["448 BC to 421 BC"] = {
  startDate=-448,
  endDate=-421
}
army_dates["5fb1b9dde1af06001770960e"]["420 BC to 419 BC"] = {
  startDate=-420,
  endDate=-419
}
army_dates["5fb1b9dde1af06001770960e"]["418 BC"] = {
  startDate=-418,
  endDate=-418
}
army_dates["5fb1b9dde1af06001770960e"]["417 BC to 410 BC"] = {
  startDate=-417,
  endDate=-410
}
army_dates["5fb1b9dde1af06001770960e"]["409 BC"] = {
  startDate=-409,
  endDate=-409
}
army_dates["5fb1b9dde1af06001770960e"]["408 BC to 329 BC"] = {
  startDate=-408,
  endDate=-329
}
army_dates["5fb1b9dde1af06001770960e"]["328 BC to 225 BC"] = {
  startDate=-328,
  endDate=-225
}
