-- 5fb1b9dae1af0600177093c8 Middle Assyrian and Early Neo-Assyrian  1365 to 745 BC

army['5fb1b9dae1af0600177093c8']={
  data={
    invasionRatings={
      4,
    },
    maneuverRatings={
      3,
      4,
      2,
    },
    homeTopographies={
      'Arable',
      'Hilly',
    },
    name='Middle Assyrian and Early Neo-Assyrian  1365 to 745 BC',
    id='5fb1b9dae1af0600177093c8',
    dateRange={
      startDate=-1365,
      endDate=-745,
    },
  },
  g_base_definitions[g_str_68c995d35791630015888703_general],
  g_base_definitions[g_str_68c995d35791630015888703],
  g_base_definitions[g_str_68c995d35791630015888706],
  g_base_definitions[g_str_68c995d35791630015888709],
  g_base_definitions[g_str_68c995d3579163001588870b],
  g_base_definitions[g_str_68c995d3579163001588870e],
  g_base_definitions[g_str_68c995d35791630015888711],
  g_base_definitions[g_str_68c995d35791630015888711_shower_shooting],
  g_base_definitions[g_str_68c995d35791630015888715],
  g_base_definitions[g_str_5fb1b9dae1af0600177093c8_camp],
  g_base_definitions[g_str_5fb1b9dae1af0600177093c8_camp_fortified],
  g_base_definitions[g_str_5fb1b9dae1af0600177093c8_camp_pack_train],
  g_base_definitions[g_str_68c995c45791630015886b9c],
  g_base_definitions[g_str_68c995c45791630015886b9e],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dae1af0600177093c8"] = army["5fb1b9dae1af0600177093c8"]
if nil == armies["Chariot Supremacy"] then
  armies["Chariot Supremacy"] ={}
end
armies["Chariot Supremacy"]["Middle Assyrian and Early Neo-Assyrian  1365 to 745 BC"] = army["5fb1b9dae1af0600177093c8"]
if nil == armies["Assyrian Empire"] then
  armies["Assyrian Empire"] ={}
end
armies["Assyrian Empire"]["Middle Assyrian and Early Neo-Assyrian  1365 to 745 BC"] = army["5fb1b9dae1af0600177093c8"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Middle Assyrian and Early Neo-Assyrian  1365 to 745 BC"] = army["5fb1b9dae1af0600177093c8"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dae1af0600177093c8"] = {}
army_dates["5fb1b9dae1af0600177093c8"]["1365 BC to 745 BC"] = {
  startDate=-1365,
  endDate=-745
}
army_dates["5fb1b9dae1af0600177093c8"]["1365 BC to 901 BC"] = {
  startDate=-1365,
  endDate=-901
}
army_dates["5fb1b9dae1af0600177093c8"]["900 BC to 890 BC"] = {
  startDate=-900,
  endDate=-890
}
army_dates["5fb1b9dae1af0600177093c8"]["889 BC to 745 BC"] = {
  startDate=-889,
  endDate=-745
}
