-- 5fb1b9f1e1af06001770a168 Later Spring and Autumn: Northern States  549 to 480 BC

army['5fb1b9f1e1af06001770a168']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Hilly',
      'Arable',
    },
    name='Later Spring and Autumn: Northern States  549 to 480 BC',
    id='5fb1b9f1e1af06001770a168',
    dateRange={
      startDate=-549,
      endDate=-480,
    },
  },
  g_base_definitions[g_str_68c995e7579163001588bc91_general],
  g_base_definitions[g_str_68c995e7579163001588bc91],
  g_base_definitions[g_str_68c995e7579163001588bc93],
  g_base_definitions[g_str_68c995e7579163001588bc94],
  g_base_definitions[g_str_68c995e7579163001588bc97],
  g_base_definitions[g_str_68c995e7579163001588bc98],
  g_base_definitions[g_str_68c995e7579163001588bc9b],
  g_base_definitions[g_str_68c995e7579163001588bc9b_shower_shooting],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a168_camp],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a168_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f1e1af06001770a168"] = army["5fb1b9f1e1af06001770a168"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Later Spring and Autumn: Northern States  549 to 480 BC"] = army["5fb1b9f1e1af06001770a168"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Spring and Autumn: Northern States  549 to 480 BC"] = army["5fb1b9f1e1af06001770a168"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f1e1af06001770a168"] = {}
army_dates["5fb1b9f1e1af06001770a168"]["549 BC to 480 BC"] = {
  startDate=-549,
  endDate=-480
}
