-- 5fb1b9e0e1af0600177097f6 Early Armenian and Gordyene  300 BC to 244 AD

army['5fb1b9e0e1af0600177097f6']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Hilly',
    },
    name='Early Armenian and Gordyene  300 BC to 244 AD',
    id='5fb1b9e0e1af0600177097f6',
    dateRange={
      startDate=-300,
      endDate=244,
    },
  },
  g_base_definitions[g_str_68c995da5791630015889783_general],
  g_base_definitions[g_str_68c995da5791630015889783],
  g_base_definitions[g_str_68c995da5791630015889785],
  g_base_definitions[g_str_68c995da5791630015889787],
  g_base_definitions[g_str_68c995da5791630015889787_shower_shooting],
  g_base_definitions[g_str_68c995da579163001588978a],
  g_base_definitions[g_str_68c995da579163001588978c],
  g_base_definitions[g_str_68c995da579163001588978f],
  g_base_definitions[g_str_5fb1b9e0e1af0600177097f6_camp],
  g_base_definitions[g_str_5fb1b9e0e1af0600177097f6_camp_pack_train],
  g_base_definitions[g_str_68c995c857916300158871a7_general],
  g_base_definitions[g_str_68c995c857916300158871a7],
  g_base_definitions[g_str_68c995c857916300158871a9],
  g_base_definitions[g_str_68c995c857916300158871ab],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e0e1af0600177097f6"] = army["5fb1b9e0e1af0600177097f6"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Early Armenian and Gordyene  300 BC to 244 AD"] = army["5fb1b9e0e1af0600177097f6"]
if nil == armies["Pax Romana"] then
  armies["Pax Romana"] ={}
end
armies["Pax Romana"]["Early Armenian and Gordyene  300 BC to 244 AD"] = army["5fb1b9e0e1af0600177097f6"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Early Armenian and Gordyene  300 BC to 244 AD"] = army["5fb1b9e0e1af0600177097f6"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Early Armenian and Gordyene  300 BC to 244 AD"] = army["5fb1b9e0e1af0600177097f6"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Armenian and Gordyene  300 BC to 244 AD"] = army["5fb1b9e0e1af0600177097f6"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e0e1af0600177097f6"] = {}
army_dates["5fb1b9e0e1af0600177097f6"]["300 BC to 244 AD"] = {
  startDate=-300,
  endDate=244
}
army_dates["5fb1b9e0e1af0600177097f6"]["300 BC to 34 AD"] = {
  startDate=-300,
  endDate=34
}
army_dates["5fb1b9e0e1af0600177097f6"]["35 AD"] = {
  startDate=35,
  endDate=35
}
army_dates["5fb1b9e0e1af0600177097f6"]["36 AD to 49 AD"] = {
  startDate=36,
  endDate=49
}
army_dates["5fb1b9e0e1af0600177097f6"]["50 AD to 229 AD"] = {
  startDate=50,
  endDate=229
}
army_dates["5fb1b9e0e1af0600177097f6"]["230 AD"] = {
  startDate=230,
  endDate=230
}
army_dates["5fb1b9e0e1af0600177097f6"]["231 AD to 244 AD"] = {
  startDate=231,
  endDate=244
}
