-- 5fb1b9eae1af060017709ddd Kievan Rus  860 to 1054 AD

army['5fb1b9eae1af060017709ddd']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Forest',
    },
    name='Kievan Rus  860 to 1054 AD',
    id='5fb1b9eae1af060017709ddd',
    dateRange={
      startDate=860,
      endDate=1054,
    },
  },
  g_base_definitions[g_str_68c995e2579163001588ad84_general],
  g_base_definitions[g_str_68c995e2579163001588ad84_general_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e2579163001588ad84_general_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e2579163001588ad84],
  g_base_definitions[g_str_68c995e2579163001588ad84_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e2579163001588ad84_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e2579163001588ad85_general],
  g_base_definitions[g_str_68c995e2579163001588ad85],
  g_base_definitions[g_str_68c995e2579163001588ad88_general],
  g_base_definitions[g_str_68c995e2579163001588ad88_general_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e2579163001588ad88_general_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e2579163001588ad88],
  g_base_definitions[g_str_68c995e2579163001588ad88_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e2579163001588ad88_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e2579163001588ad8c],
  g_base_definitions[g_str_68c995e2579163001588ad8f],
  g_base_definitions[g_str_68c995e2579163001588ad92],
  g_base_definitions[g_str_5fb1b9eae1af060017709ddd_camp],
  g_base_definitions[g_str_5fb1b9eae1af060017709ddd_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eae1af060017709ddd"] = army["5fb1b9eae1af060017709ddd"]
if nil == armies["Russian Princes"] then
  armies["Russian Princes"] ={}
end
armies["Russian Princes"]["Kievan Rus  860 to 1054 AD"] = army["5fb1b9eae1af060017709ddd"]
if nil == armies["Baltic Powers"] then
  armies["Baltic Powers"] ={}
end
armies["Baltic Powers"]["Kievan Rus  860 to 1054 AD"] = army["5fb1b9eae1af060017709ddd"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Kievan Rus  860 to 1054 AD"] = army["5fb1b9eae1af060017709ddd"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Kievan Rus  860 to 1054 AD"] = army["5fb1b9eae1af060017709ddd"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eae1af060017709ddd"] = {}
army_dates["5fb1b9eae1af060017709ddd"]["860 AD to 1054 AD"] = {
  startDate=860,
  endDate=1054
}
army_dates["5fb1b9eae1af060017709ddd"]["860 AD to 959 AD"] = {
  startDate=860,
  endDate=959
}
army_dates["5fb1b9eae1af060017709ddd"]["960 AD to 967 AD"] = {
  startDate=960,
  endDate=967
}
army_dates["5fb1b9eae1af060017709ddd"]["968 AD to 970 AD"] = {
  startDate=968,
  endDate=970
}
army_dates["5fb1b9eae1af060017709ddd"]["971 AD"] = {
  startDate=971,
  endDate=971
}
army_dates["5fb1b9eae1af060017709ddd"]["972 AD to 1017 AD"] = {
  startDate=972,
  endDate=1017
}
army_dates["5fb1b9eae1af060017709ddd"]["1018 AD"] = {
  startDate=1018,
  endDate=1018
}
army_dates["5fb1b9eae1af060017709ddd"]["1019 AD to 1035 AD"] = {
  startDate=1019,
  endDate=1035
}
army_dates["5fb1b9eae1af060017709ddd"]["1036 AD to 1054 AD"] = {
  startDate=1036,
  endDate=1054
}
