-- 5fb1b9e0e1af0600177097ef Later Commagene  79 BC to 72 AD

army['5fb1b9e0e1af0600177097ef']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Hilly',
    },
    name='Later Commagene  79 BC to 72 AD',
    id='5fb1b9e0e1af0600177097ef',
    dateRange={
      startDate=-79,
      endDate=72,
    },
  },
  g_base_definitions[g_str_68c995da579163001588976b_general],
  g_base_definitions[g_str_68c995da579163001588976b],
  g_base_definitions[g_str_68c995da579163001588976e_general],
  g_base_definitions[g_str_68c995da579163001588976e],
  g_base_definitions[g_str_68c995da5791630015889770],
  g_base_definitions[g_str_68c995da5791630015889772],
  g_base_definitions[g_str_68c995da5791630015889774],
  g_base_definitions[g_str_68c995da5791630015889776],
  g_base_definitions[g_str_68c995da5791630015889776_shower_shooting],
  g_base_definitions[g_str_68c995da5791630015889779],
  g_base_definitions[g_str_68c995da579163001588977b],
  g_base_definitions[g_str_68c995da579163001588977e],
  g_base_definitions[g_str_5fb1b9e0e1af0600177097ef_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e0e1af0600177097ef"] = army["5fb1b9e0e1af0600177097ef"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Later Commagene  79 BC to 72 AD"] = army["5fb1b9e0e1af0600177097ef"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Later Commagene  79 BC to 72 AD"] = army["5fb1b9e0e1af0600177097ef"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Commagene  79 BC to 72 AD"] = army["5fb1b9e0e1af0600177097ef"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e0e1af0600177097ef"] = {}
army_dates["5fb1b9e0e1af0600177097ef"]["79 BC to 72 AD"] = {
  startDate=-79,
  endDate=72
}
