-- 5fb1b9e8e1af060017709cca Medieval German Citystates  1321 to 1439 AD

army['5fb1b9e8e1af060017709cca']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Hilly',
      'Arable',
    },
    name='Medieval German Citystates  1321 to 1439 AD',
    id='5fb1b9e8e1af060017709cca',
    dateRange={
      startDate=1321,
      endDate=1439,
    },
  },
  g_base_definitions[g_str_68c995e0579163001588a8cd_general],
  g_base_definitions[g_str_68c995e0579163001588a8cd_general_mounted],
  g_base_definitions[g_str_68c995e0579163001588a8cd_general_dismounted],
  g_base_definitions[g_str_68c995e0579163001588a8cd],
  g_base_definitions[g_str_68c995e0579163001588a8cd_mounted],
  g_base_definitions[g_str_68c995e0579163001588a8cd_dismounted],
  g_base_definitions[g_str_68c995e0579163001588a8d0_general],
  g_base_definitions[g_str_68c995e0579163001588a8d0],
  g_base_definitions[g_str_68c995e0579163001588a8d2],
  g_base_definitions[g_str_68c995e0579163001588a8d4],
  g_base_definitions[g_str_68c995e0579163001588a8d4_shower_shooting],
  g_base_definitions[g_str_68c995e0579163001588a8d5_general],
  g_base_definitions[g_str_68c995e0579163001588a8d5_general_shower_shooting],
  g_base_definitions[g_str_68c995e0579163001588a8d5],
  g_base_definitions[g_str_68c995e0579163001588a8d5_shower_shooting],
  g_base_definitions[g_str_68c995e0579163001588a8d8_general],
  g_base_definitions[g_str_68c995e0579163001588a8d8],
  g_base_definitions[g_str_68c995e0579163001588a8db],
  g_base_definitions[g_str_68c995e0579163001588a8de],
  g_base_definitions[g_str_68c995e0579163001588a8e0],
  g_base_definitions[g_str_68c995e0579163001588a8e0_shower_shooting],
  g_base_definitions[g_str_68c995e0579163001588a8e3_general],
  g_base_definitions[g_str_68c995e0579163001588a8e3],
  g_base_definitions[g_str_68c995e0579163001588a8e6_general],
  g_base_definitions[g_str_68c995e0579163001588a8e6],
  g_base_definitions[g_str_68c995e0579163001588a8e7],
  g_base_definitions[g_str_68c995e0579163001588a8eb],
  g_base_definitions[g_str_68c995e0579163001588a8ee],
  g_base_definitions[g_str_5fb1b9e8e1af060017709cca_camp],
  g_base_definitions[g_str_5fb1b9e8e1af060017709cca_camp_fortified],
  g_base_definitions[g_str_5fb1b9e8e1af060017709cca_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e8e1af060017709cca"] = army["5fb1b9e8e1af060017709cca"]
if nil == armies["Holy Roman Empire"] then
  armies["Holy Roman Empire"] ={}
end
armies["Holy Roman Empire"]["Medieval German Citystates  1321 to 1439 AD"] = army["5fb1b9e8e1af060017709cca"]
if nil == armies["Baltic Powers"] then
  armies["Baltic Powers"] ={}
end
armies["Baltic Powers"]["Medieval German Citystates  1321 to 1439 AD"] = army["5fb1b9e8e1af060017709cca"]
if nil == armies["Flower of Chivalry"] then
  armies["Flower of Chivalry"] ={}
end
armies["Flower of Chivalry"]["Medieval German Citystates  1321 to 1439 AD"] = army["5fb1b9e8e1af060017709cca"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Medieval German Citystates  1321 to 1439 AD"] = army["5fb1b9e8e1af060017709cca"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e8e1af060017709cca"] = {}
army_dates["5fb1b9e8e1af060017709cca"]["1321 AD to 1439 AD"] = {
  startDate=1321,
  endDate=1439
}
army_dates["5fb1b9e8e1af060017709cca"]["1321 AD to 1384 AD"] = {
  startDate=1321,
  endDate=1384
}
army_dates["5fb1b9e8e1af060017709cca"]["1385 AD to 1388 AD"] = {
  startDate=1385,
  endDate=1388
}
army_dates["5fb1b9e8e1af060017709cca"]["1389 AD to 1424 AD"] = {
  startDate=1389,
  endDate=1424
}
army_dates["5fb1b9e8e1af060017709cca"]["1425 AD to 1439 AD"] = {
  startDate=1425,
  endDate=1439
}
