-- 5fb1b9e3e1af0600177099bf Merovingian Frankish: Neustria or Aquitaine  511 to 639 AD

army['5fb1b9e3e1af0600177099bf']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Merovingian Frankish: Neustria or Aquitaine  511 to 639 AD',
    id='5fb1b9e3e1af0600177099bf',
    dateRange={
      startDate=511,
      endDate=639,
    },
  },
  g_base_definitions[g_str_68c995dc5791630015889de0_general],
  g_base_definitions[g_str_68c995dc5791630015889de0_general_mounted],
  g_base_definitions[g_str_68c995dc5791630015889de0_general_dismounted],
  g_base_definitions[g_str_68c995dc5791630015889de0],
  g_base_definitions[g_str_68c995dc5791630015889de0_mounted],
  g_base_definitions[g_str_68c995dc5791630015889de0_dismounted],
  g_base_definitions[g_str_68c995dc5791630015889de3_general],
  g_base_definitions[g_str_68c995dc5791630015889de3_general_mounted],
  g_base_definitions[g_str_68c995dc5791630015889de3_general_dismounted],
  g_base_definitions[g_str_68c995dc5791630015889de3],
  g_base_definitions[g_str_68c995dc5791630015889de3_mounted],
  g_base_definitions[g_str_68c995dc5791630015889de3_dismounted],
  g_base_definitions[g_str_68c995dc5791630015889de4],
  g_base_definitions[g_str_68c995dc5791630015889de4_mounted],
  g_base_definitions[g_str_68c995dc5791630015889de4_dismounted],
  g_base_definitions[g_str_68c995dc5791630015889de7],
  g_base_definitions[g_str_68c995dc5791630015889de9],
  g_base_definitions[g_str_68c995dc5791630015889deb],
  g_base_definitions[g_str_68c995dc5791630015889ded],
  g_base_definitions[g_str_68c995dc5791630015889def],
  g_base_definitions[g_str_68c995dc5791630015889df1],
  g_base_definitions[g_str_68c995dc5791630015889df2],
  g_base_definitions[g_str_5fb1b9e3e1af0600177099bf_camp],
  g_base_definitions[g_str_5fb1b9e3e1af0600177099bf_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e3e1af0600177099bf"] = army["5fb1b9e3e1af0600177099bf"]
if nil == armies["Fall of Rome"] then
  armies["Fall of Rome"] ={}
end
armies["Fall of Rome"]["Merovingian Frankish: Neustria or Aquitaine  511 to 639 AD"] = army["5fb1b9e3e1af0600177099bf"]
if nil == armies["Dark Ages"] then
  armies["Dark Ages"] ={}
end
armies["Dark Ages"]["Merovingian Frankish: Neustria or Aquitaine  511 to 639 AD"] = army["5fb1b9e3e1af0600177099bf"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Merovingian Frankish: Neustria or Aquitaine  511 to 639 AD"] = army["5fb1b9e3e1af0600177099bf"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e3e1af0600177099bf"] = {}
army_dates["5fb1b9e3e1af0600177099bf"]["511 AD to 639 AD"] = {
  startDate=511,
  endDate=639
}
army_dates["5fb1b9e3e1af0600177099bf"]["511 AD to 588 AD"] = {
  startDate=511,
  endDate=588
}
army_dates["5fb1b9e3e1af0600177099bf"]["589 AD to 639 AD"] = {
  startDate=589,
  endDate=639
}
