-- 5fb1b9e7e1af060017709c43 Early Medieval French  1330 to 1346 AD

army['5fb1b9e7e1af060017709c43']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
      0,
    },
    homeTopographies={
      'Arable',
    },
    name='Early Medieval French  1330 to 1346 AD',
    id='5fb1b9e7e1af060017709c43',
    dateRange={
      startDate=1330,
      endDate=1346,
    },
  },
  g_base_definitions[g_str_68c995e0579163001588a69d_general],
  g_base_definitions[g_str_68c995e0579163001588a69d],
  g_base_definitions[g_str_68c995e0579163001588a69f],
  g_base_definitions[g_str_68c995e0579163001588a69f_shower_shooting],
  g_base_definitions[g_str_68c995e0579163001588a6a2],
  g_base_definitions[g_str_68c995e0579163001588a6a2_shower_shooting],
  g_base_definitions[g_str_68c995e0579163001588a6a2_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e0579163001588a6a2_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e0579163001588a6a6],
  g_base_definitions[g_str_68c995e0579163001588a6a8],
  g_base_definitions[g_str_68c995e0579163001588a6aa],
  g_base_definitions[g_str_68c995e0579163001588a6ac],
  g_base_definitions[g_str_68c995e0579163001588a6ae],
  g_base_definitions[g_str_68c995e0579163001588a6b0],
  g_base_definitions[g_str_5fb1b9e7e1af060017709c43_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e7e1af060017709c43"] = army["5fb1b9e7e1af060017709c43"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Early Medieval French  1330 to 1346 AD"] = army["5fb1b9e7e1af060017709c43"]
if nil == armies["Flower of Chivalry"] then
  armies["Flower of Chivalry"] ={}
end
armies["Flower of Chivalry"]["Early Medieval French  1330 to 1346 AD"] = army["5fb1b9e7e1af060017709c43"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Medieval French  1330 to 1346 AD"] = army["5fb1b9e7e1af060017709c43"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e7e1af060017709c43"] = {}
army_dates["5fb1b9e7e1af060017709c43"]["1330 AD to 1346 AD"] = {
  startDate=1330,
  endDate=1346
}
