-- 5fb1b9f5e1af06001770a38c Early Nomadic Meso-American  899 to 400 BC

army['5fb1b9f5e1af06001770a38c']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Forest',
      'Hilly',
    },
    name='Early Nomadic Meso-American  899 to 400 BC',
    id='5fb1b9f5e1af06001770a38c',
    dateRange={
      startDate=-899,
      endDate=-400,
    },
    ambush=true,  },
  g_base_definitions[g_str_68c995ea579163001588c45a_general],
  g_base_definitions[g_str_68c995ea579163001588c45a],
  g_base_definitions[g_str_68c995ea579163001588c45c],
  g_base_definitions[g_str_68c995ea579163001588c45e_general],
  g_base_definitions[g_str_68c995ea579163001588c45e],
  g_base_definitions[g_str_5fb1b9f5e1af06001770a38c_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f5e1af06001770a38c"] = army["5fb1b9f5e1af06001770a38c"]
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["Early Nomadic Meso-American  899 to 400 BC"] = army["5fb1b9f5e1af06001770a38c"]
if nil == armies["Mexico"] then
  armies["Mexico"] ={}
end
armies["Mexico"]["Early Nomadic Meso-American  899 to 400 BC"] = army["5fb1b9f5e1af06001770a38c"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Nomadic Meso-American  899 to 400 BC"] = army["5fb1b9f5e1af06001770a38c"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f5e1af06001770a38c"] = {}
army_dates["5fb1b9f5e1af06001770a38c"]["899 BC to 400 BC"] = {
  startDate=-899,
  endDate=-400
}
