-- 5fb1b9ece1af060017709ef4 Arab Conquest Expansion  639 to 660 AD

army['5fb1b9ece1af060017709ef4']={
  data={
    invasionRatings={
      4,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Dry',
    },
    name='Arab Conquest Expansion  639 to 660 AD',
    id='5fb1b9ece1af060017709ef4',
    dateRange={
      startDate=639,
      endDate=660,
    },
  },
  g_base_definitions[g_str_68c995e4579163001588b272],
  g_base_definitions[g_str_68c995e4579163001588b272_light_camelry],
  g_base_definitions[g_str_68c995e4579163001588b275_general],
  g_base_definitions[g_str_68c995e4579163001588b275_general_mounted],
  g_base_definitions[g_str_68c995e4579163001588b275_general_dismounted],
  g_base_definitions[g_str_68c995e4579163001588b275],
  g_base_definitions[g_str_68c995e4579163001588b275_mounted],
  g_base_definitions[g_str_68c995e4579163001588b275_dismounted],
  g_base_definitions[g_str_68c995e4579163001588b278],
  g_base_definitions[g_str_68c995e4579163001588b278_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b278_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b27b],
  g_base_definitions[g_str_68c995e4579163001588b27b_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b27b_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b27e],
  g_base_definitions[g_str_68c995e4579163001588b27e_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b27e_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b281],
  g_base_definitions[g_str_68c995e4579163001588b281_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b281_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b284],
  g_base_definitions[g_str_68c995e4579163001588b284_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b284_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b287],
  g_base_definitions[g_str_68c995e4579163001588b287_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b287_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b28a],
  g_base_definitions[g_str_68c995e4579163001588b28a_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b28a_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1b9ece1af060017709ef4_camp],
  g_base_definitions[g_str_5fb1b9ece1af060017709ef4_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ece1af060017709ef4"] = army["5fb1b9ece1af060017709ef4"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Arab Conquest Expansion  639 to 660 AD"] = army["5fb1b9ece1af060017709ef4"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Arab Conquest Expansion  639 to 660 AD"] = army["5fb1b9ece1af060017709ef4"]
if nil == armies["Spread of Islam"] then
  armies["Spread of Islam"] ={}
end
armies["Spread of Islam"]["Arab Conquest Expansion  639 to 660 AD"] = army["5fb1b9ece1af060017709ef4"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Arab Conquest Expansion  639 to 660 AD"] = army["5fb1b9ece1af060017709ef4"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ece1af060017709ef4"] = {}
army_dates["5fb1b9ece1af060017709ef4"]["639 AD to 660 AD"] = {
  startDate=639,
  endDate=660
}
