-- 5fb1b9e2e1af0600177098b5 Adrianople Campaign Visigoth  378 to 378 AD

army['5fb1b9e2e1af0600177098b5']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Adrianople Campaign Visigoth  378 to 378 AD',
    id='5fb1b9e2e1af0600177098b5',
    dateRange={
      startDate=378,
      endDate=378,
    },
  },
  g_base_definitions[g_str_68c995db5791630015889a34_general],
  g_base_definitions[g_str_68c995db5791630015889a34],
  g_base_definitions[g_str_68c995db5791630015889a36_general],
  g_base_definitions[g_str_68c995db5791630015889a36],
  g_base_definitions[g_str_68c995db5791630015889a38],
  g_base_definitions[g_str_68c995db5791630015889a38_shower_shooting],
  g_base_definitions[g_str_68c995db5791630015889a3b],
  g_base_definitions[g_str_5fb1b9e2e1af0600177098b5_camp],
  g_base_definitions[g_str_5fb1b9e2e1af0600177098b5_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e2e1af0600177098b5"] = army["5fb1b9e2e1af0600177098b5"]
if nil == armies["Fall of Rome"] then
  armies["Fall of Rome"] ={}
end
armies["Fall of Rome"]["Adrianople Campaign Visigoth  378 to 378 AD"] = army["5fb1b9e2e1af0600177098b5"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Adrianople Campaign Visigoth  378 to 378 AD"] = army["5fb1b9e2e1af0600177098b5"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e2e1af0600177098b5"] = {}
army_dates["5fb1b9e2e1af0600177098b5"]["378 AD"] = {
  startDate=378,
  endDate=378
}
