-- 5fb1b9dde1af0600177095d5 Early Macedonian  650 to 355 BC

army['5fb1b9dde1af0600177095d5']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      1,
      2,
    },
    homeTopographies={
      'Arable',
    },
    name='Early Macedonian  650 to 355 BC',
    id='5fb1b9dde1af0600177095d5',
    dateRange={
      startDate=-650,
      endDate=-355,
    },
  },
  g_base_definitions[g_str_68c995d75791630015888f1c_general],
  g_base_definitions[g_str_68c995d75791630015888f1c],
  g_base_definitions[g_str_68c995d75791630015888f1f],
  g_base_definitions[g_str_68c995d75791630015888f20],
  g_base_definitions[g_str_68c995d75791630015888f22],
  g_base_definitions[g_str_68c995d75791630015888f24],
  g_base_definitions[g_str_68c995d75791630015888f26],
  g_base_definitions[g_str_68c995d75791630015888f28],
  g_base_definitions[g_str_68c995d75791630015888f2b],
  g_base_definitions[g_str_5fb1b9dde1af0600177095d5_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dde1af0600177095d5"] = army["5fb1b9dde1af0600177095d5"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Early Macedonian  650 to 355 BC"] = army["5fb1b9dde1af0600177095d5"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Macedonian  650 to 355 BC"] = army["5fb1b9dde1af0600177095d5"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dde1af0600177095d5"] = {}
army_dates["5fb1b9dde1af0600177095d5"]["650 BC to 355 BC"] = {
  startDate=-650,
  endDate=-355
}
army_dates["5fb1b9dde1af0600177095d5"]["650 BC to 449 BC"] = {
  startDate=-650,
  endDate=-449
}
army_dates["5fb1b9dde1af0600177095d5"]["448 BC to 425 BC"] = {
  startDate=-448,
  endDate=-425
}
army_dates["5fb1b9dde1af0600177095d5"]["424 BC to 423 BC"] = {
  startDate=-424,
  endDate=-423
}
army_dates["5fb1b9dde1af0600177095d5"]["422 BC to 393 BC"] = {
  startDate=-422,
  endDate=-393
}
army_dates["5fb1b9dde1af0600177095d5"]["392 BC"] = {
  startDate=-392,
  endDate=-392
}
army_dates["5fb1b9dde1af0600177095d5"]["391 BC to 355 BC"] = {
  startDate=-391,
  endDate=-355
}
