-- 5fb1b9f0e1af06001770a123 Xia Chinese  2000 to 1750 BC

army['5fb1b9f0e1af06001770a123']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Xia Chinese  2000 to 1750 BC',
    id='5fb1b9f0e1af06001770a123',
    dateRange={
      startDate=-2000,
      endDate=-1750,
    },
  },
  g_base_definitions[g_str_68c995e7579163001588bbdc_general],
  g_base_definitions[g_str_68c995e7579163001588bbdc],
  g_base_definitions[g_str_68c995e7579163001588bbde_general],
  g_base_definitions[g_str_68c995e7579163001588bbde],
  g_base_definitions[g_str_68c995e7579163001588bbe0],
  g_base_definitions[g_str_68c995e7579163001588bbe1],
  g_base_definitions[g_str_68c995e7579163001588bbe3],
  g_base_definitions[g_str_68c995e7579163001588bbe3_shower_shooting],
  g_base_definitions[g_str_68c995e7579163001588bbe6],
  g_base_definitions[g_str_5fb1b9f0e1af06001770a123_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f0e1af06001770a123"] = army["5fb1b9f0e1af06001770a123"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Xia Chinese  2000 to 1750 BC"] = army["5fb1b9f0e1af06001770a123"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Xia Chinese  2000 to 1750 BC"] = army["5fb1b9f0e1af06001770a123"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f0e1af06001770a123"] = {}
army_dates["5fb1b9f0e1af06001770a123"]["2000 BC to 1750 BC"] = {
  startDate=-2000,
  endDate=-1750
}
