-- 5fb1b9e6e1af060017709b83 Mali  900 to 1600 AD

army['5fb1b9e6e1af060017709b83']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Forest',
    },
    name='Mali  900 to 1600 AD',
    id='5fb1b9e6e1af060017709b83',
    dateRange={
      startDate=900,
      endDate=1600,
    },
  },
  g_base_definitions[g_str_68c995df579163001588a3e7_general],
  g_base_definitions[g_str_68c995df579163001588a3e7],
  g_base_definitions[g_str_68c995df579163001588a3e9_general],
  g_base_definitions[g_str_68c995df579163001588a3e9],
  g_base_definitions[g_str_68c995df579163001588a3eb],
  g_base_definitions[g_str_68c995df579163001588a3eb_shower_shooting],
  g_base_definitions[g_str_68c995df579163001588a3ee],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b83_camp],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b83_camp_fortified],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b83_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e6e1af060017709b83"] = army["5fb1b9e6e1af060017709b83"]
if nil == armies["Sahel Africa"] then
  armies["Sahel Africa"] ={}
end
armies["Sahel Africa"]["Mali  900 to 1600 AD"] = army["5fb1b9e6e1af060017709b83"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Mali  900 to 1600 AD"] = army["5fb1b9e6e1af060017709b83"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e6e1af060017709b83"] = {}
army_dates["5fb1b9e6e1af060017709b83"]["900 AD to 1600 AD"] = {
  startDate=900,
  endDate=1600
}
