-- 5fb1b9e6e1af060017709bbd Early Muslim North Africa and Sicily  696 to 800 AD

army['5fb1b9e6e1af060017709bbd']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
      'Dry',
      'Hilly',
    },
    name='Early Muslim North Africa and Sicily  696 to 800 AD',
    id='5fb1b9e6e1af060017709bbd',
    dateRange={
      startDate=696,
      endDate=800,
    },
  },
  g_base_definitions[g_str_68c995df579163001588a495_general],
  g_base_definitions[g_str_68c995df579163001588a495],
  g_base_definitions[g_str_68c995df579163001588a497],
  g_base_definitions[g_str_68c995df579163001588a499],
  g_base_definitions[g_str_68c995df579163001588a49b],
  g_base_definitions[g_str_68c995df579163001588a49b_shower_shooting],
  g_base_definitions[g_str_68c995df579163001588a49c],
  g_base_definitions[g_str_68c995df579163001588a49c_shower_shooting],
  g_base_definitions[g_str_68c995df579163001588a49d],
  g_base_definitions[g_str_68c995df579163001588a49d_shower_shooting],
  g_base_definitions[g_str_68c995df579163001588a4a0],
  g_base_definitions[g_str_68c995df579163001588a4a2],
  g_base_definitions[g_str_68c995df579163001588a4a2_shower_shooting],
  g_base_definitions[g_str_68c995df579163001588a4a7],
  g_base_definitions[g_str_5fb1b9e6e1af060017709bbd_camp],
  g_base_definitions[g_str_5fb1b9e6e1af060017709bbd_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e6e1af060017709bbd"] = army["5fb1b9e6e1af060017709bbd"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Early Muslim North Africa and Sicily  696 to 800 AD"] = army["5fb1b9e6e1af060017709bbd"]
if nil == armies["Spread of Islam"] then
  armies["Spread of Islam"] ={}
end
armies["Spread of Islam"]["Early Muslim North Africa and Sicily  696 to 800 AD"] = army["5fb1b9e6e1af060017709bbd"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Muslim North Africa and Sicily  696 to 800 AD"] = army["5fb1b9e6e1af060017709bbd"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e6e1af060017709bbd"] = {}
army_dates["5fb1b9e6e1af060017709bbd"]["696 AD to 800 AD"] = {
  startDate=696,
  endDate=800
}
