-- 5fb1b9ede1af060017709f67 Early Crusader  1096 to 1128 AD

army['5fb1b9ede1af060017709f67']={
  data={
    invasionRatings={
      4,
      1,
    },
    maneuverRatings={
      1,
      3,
      0,
    },
    homeTopographies={
      'Arable',
      'Hilly',
    },
    name='Early Crusader  1096 to 1128 AD',
    id='5fb1b9ede1af060017709f67',
    dateRange={
      startDate=1096,
      endDate=1128,
    },
  },
  g_base_definitions[g_str_68c995e4579163001588b49f_general],
  g_base_definitions[g_str_68c995e4579163001588b49f],
  g_base_definitions[g_str_68c995e4579163001588b4a2_general],
  g_base_definitions[g_str_68c995e4579163001588b4a2],
  g_base_definitions[g_str_68c995e4579163001588b4a5],
  g_base_definitions[g_str_68c995e4579163001588b4a7],
  g_base_definitions[g_str_68c995e4579163001588b4a9],
  g_base_definitions[g_str_68c995e4579163001588b4a9_shower_shooting],
  g_base_definitions[g_str_68c995e4579163001588b4aa],
  g_base_definitions[g_str_68c995e4579163001588b4aa_shower_shooting],
  g_base_definitions[g_str_68c995e4579163001588b4ad],
  g_base_definitions[g_str_68c995e4579163001588b4ad_shower_shooting],
  g_base_definitions[g_str_68c995e4579163001588b4b0],
  g_base_definitions[g_str_68c995e4579163001588b4b1],
  g_base_definitions[g_str_68c995e4579163001588b4b4],
  g_base_definitions[g_str_68c995e4579163001588b4b7],
  g_base_definitions[g_str_68c995e4579163001588b4ba],
  g_base_definitions[g_str_68c995e4579163001588b4ba_shower_shooting],
  g_base_definitions[g_str_68c995e4579163001588b4be],
  g_base_definitions[g_str_5fb1b9ede1af060017709f67_camp],
  g_base_definitions[g_str_5fb1b9ede1af060017709f67_camp_fortified],
  g_base_definitions[g_str_5fb1b9ede1af060017709f67_camp_standard_wagon],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ede1af060017709f67"] = army["5fb1b9ede1af060017709f67"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Early Crusader  1096 to 1128 AD"] = army["5fb1b9ede1af060017709f67"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Early Crusader  1096 to 1128 AD"] = army["5fb1b9ede1af060017709f67"]
if nil == armies["Crusader Kingdoms"] then
  armies["Crusader Kingdoms"] ={}
end
armies["Crusader Kingdoms"]["Early Crusader  1096 to 1128 AD"] = army["5fb1b9ede1af060017709f67"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Crusader  1096 to 1128 AD"] = army["5fb1b9ede1af060017709f67"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ede1af060017709f67"] = {}
army_dates["5fb1b9ede1af060017709f67"]["1096 AD to 1128 AD"] = {
  startDate=1096,
  endDate=1128
}
army_dates["5fb1b9ede1af060017709f67"]["1096 AD to 1099 AD"] = {
  startDate=1096,
  endDate=1099
}
army_dates["5fb1b9ede1af060017709f67"]["1100 AD to 1128 AD"] = {
  startDate=1100,
  endDate=1128
}
