-- 5fb1b9dae1af0600177093c2 Vedic Indian  1500 to 512 BC

army['5fb1b9dae1af0600177093c2']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Arable',
      'Forest',
    },
    name='Vedic Indian  1500 to 512 BC',
    id='5fb1b9dae1af0600177093c2',
    dateRange={
      startDate=-1500,
      endDate=-512,
    },
  },
  g_base_definitions[g_str_68c995d357916300158886ed_general],
  g_base_definitions[g_str_68c995d357916300158886ed],
  g_base_definitions[g_str_68c995d357916300158886f0],
  g_base_definitions[g_str_68c995d357916300158886f2],
  g_base_definitions[g_str_68c995d357916300158886f2_shower_shooting],
  g_base_definitions[g_str_68c995d357916300158886f5],
  g_base_definitions[g_str_68c995d357916300158886f8],
  g_base_definitions[g_str_68c995d357916300158886fb],
  g_base_definitions[g_str_68c995d357916300158886fe],
  g_base_definitions[g_str_5fb1b9dae1af0600177093c2_camp],
  g_base_definitions[g_str_5fb1b9dae1af0600177093c2_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dae1af0600177093c2"] = army["5fb1b9dae1af0600177093c2"]
if nil == armies["Chariot Supremacy"] then
  armies["Chariot Supremacy"] ={}
end
armies["Chariot Supremacy"]["Vedic Indian  1500 to 512 BC"] = army["5fb1b9dae1af0600177093c2"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Vedic Indian  1500 to 512 BC"] = army["5fb1b9dae1af0600177093c2"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dae1af0600177093c2"] = {}
army_dates["5fb1b9dae1af0600177093c2"]["1500 BC to 512 BC"] = {
  startDate=-1500,
  endDate=-512
}
