-- 5fb1b9dce1af060017709534 Romanized Campanian  340 to 203 BC

army['5fb1b9dce1af060017709534']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
    },
    name='Romanized Campanian  340 to 203 BC',
    id='5fb1b9dce1af060017709534',
    dateRange={
      startDate=-340,
      endDate=-203,
    },
  },
  g_base_definitions[g_str_68c995d65791630015888cc5_general],
  g_base_definitions[g_str_68c995d65791630015888cc5],
  g_base_definitions[g_str_68c995d65791630015888cc7],
  g_base_definitions[g_str_68c995d65791630015888cc9],
  g_base_definitions[g_str_5fb1b9dce1af060017709534_camp],
  g_base_definitions[g_str_5fb1b9dce1af060017709534_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dce1af060017709534"] = army["5fb1b9dce1af060017709534"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Romanized Campanian  340 to 203 BC"] = army["5fb1b9dce1af060017709534"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Romanized Campanian  340 to 203 BC"] = army["5fb1b9dce1af060017709534"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Romanized Campanian  340 to 203 BC"] = army["5fb1b9dce1af060017709534"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dce1af060017709534"] = {}
army_dates["5fb1b9dce1af060017709534"]["340 BC to 203 BC"] = {
  startDate=-340,
  endDate=-203
}
army_dates["5fb1b9dce1af060017709534"]["340 BC to 272 BC"] = {
  startDate=-340,
  endDate=-272
}
army_dates["5fb1b9dce1af060017709534"]["271 BC to 203 BC"] = {
  startDate=-271,
  endDate=-203
}
