-- 5fb1b9e7e1af060017709c33 Early Feudal French  1072 to 1085 AD

army['5fb1b9e7e1af060017709c33']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Arable',
    },
    name='Early Feudal French  1072 to 1085 AD',
    id='5fb1b9e7e1af060017709c33',
    dateRange={
      startDate=1072,
      endDate=1085,
    },
  },
  g_base_definitions[g_str_68c995df579163001588a65b_general],
  g_base_definitions[g_str_68c995df579163001588a65b],
  g_base_definitions[g_str_68c995df579163001588a65d],
  g_base_definitions[g_str_68c995df579163001588a65f],
  g_base_definitions[g_str_68c995df579163001588a65f_shower_shooting],
  g_base_definitions[g_str_68c995df579163001588a65f_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995df579163001588a65f_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995df579163001588a663],
  g_base_definitions[g_str_68c995df579163001588a665_general],
  g_base_definitions[g_str_68c995df579163001588a665],
  g_base_definitions[g_str_68c995df579163001588a667],
  g_base_definitions[g_str_68c995df579163001588a669],
  g_base_definitions[g_str_68c995df579163001588a66b],
  g_base_definitions[g_str_5fb1b9e7e1af060017709c33_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e7e1af060017709c33"] = army["5fb1b9e7e1af060017709c33"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Early Feudal French  1072 to 1085 AD"] = army["5fb1b9e7e1af060017709c33"]
if nil == armies["Flower of Chivalry"] then
  armies["Flower of Chivalry"] ={}
end
armies["Flower of Chivalry"]["Early Feudal French  1072 to 1085 AD"] = army["5fb1b9e7e1af060017709c33"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Feudal French  1072 to 1085 AD"] = army["5fb1b9e7e1af060017709c33"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e7e1af060017709c33"] = {}
army_dates["5fb1b9e7e1af060017709c33"]["1072 AD to 1085 AD"] = {
  startDate=1072,
  endDate=1085
}
