-- 5fb1b9ede1af060017709f47  Dynastic Bedouin  890 to 1163 AD

army['5fb1b9ede1af060017709f47']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Dry',
    },
    name='Dynastic Bedouin  890 to 1163 AD',
    id='5fb1b9ede1af060017709f47',
    dateRange={
      startDate=890,
      endDate=1163,
    },
  },
  g_base_definitions[g_str_68c995e4579163001588b403_general],
  g_base_definitions[g_str_68c995e4579163001588b403],
  g_base_definitions[g_str_68c995e4579163001588b405],
  g_base_definitions[g_str_68c995e4579163001588b407],
  g_base_definitions[g_str_68c995e4579163001588b407_light_camelry],
  g_base_definitions[g_str_68c995e4579163001588b40a],
  g_base_definitions[g_str_68c995e4579163001588b40d],
  g_base_definitions[g_str_5fb1b9ede1af060017709f47_camp],
  g_base_definitions[g_str_5fb1b9ede1af060017709f47_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ede1af060017709f47"] = army["5fb1b9ede1af060017709f47"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Dynastic Bedouin  890 to 1163 AD"] = army["5fb1b9ede1af060017709f47"]
if nil == armies["Crusader Kingdoms"] then
  armies["Crusader Kingdoms"] ={}
end
armies["Crusader Kingdoms"]["Dynastic Bedouin  890 to 1163 AD"] = army["5fb1b9ede1af060017709f47"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Dynastic Bedouin  890 to 1163 AD"] = army["5fb1b9ede1af060017709f47"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ede1af060017709f47"] = {}
army_dates["5fb1b9ede1af060017709f47"]["890 AD to 1163 AD"] = {
  startDate=890,
  endDate=1163
}
army_dates["5fb1b9ede1af060017709f47"]["890 AD to 949 AD"] = {
  startDate=890,
  endDate=949
}
army_dates["5fb1b9ede1af060017709f47"]["950 AD to 995 AD"] = {
  startDate=950,
  endDate=995
}
army_dates["5fb1b9ede1af060017709f47"]["996 AD to 1085 AD"] = {
  startDate=996,
  endDate=1085
}
army_dates["5fb1b9ede1af060017709f47"]["1086 AD to 1163 AD"] = {
  startDate=1086,
  endDate=1163
}
