-- 5fb1b9f5e1af06001770a42a Aztec  1325 to 1521 AD

army['5fb1b9f5e1af06001770a42a']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Arable',
      'Hilly',
    },
    name='Aztec  1325 to 1521 AD',
    id='5fb1b9f5e1af06001770a42a',
    dateRange={
      startDate=1325,
      endDate=1521,
    },
    ambush=true,  },
  g_base_definitions[g_str_68c995eb579163001588c573_general],
  g_base_definitions[g_str_68c995eb579163001588c573],
  g_base_definitions[g_str_68c995eb579163001588c575_general],
  g_base_definitions[g_str_68c995eb579163001588c575],
  g_base_definitions[g_str_68c995eb579163001588c577],
  g_base_definitions[g_str_68c995eb579163001588c579],
  g_base_definitions[g_str_68c995eb579163001588c57b],
  g_base_definitions[g_str_68c995eb579163001588c57b_shower_shooting],
  g_base_definitions[g_str_5fb1b9f5e1af06001770a42a_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f5e1af06001770a42a"] = army["5fb1b9f5e1af06001770a42a"]
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["Aztec  1325 to 1521 AD"] = army["5fb1b9f5e1af06001770a42a"]
if nil == armies["Mexico"] then
  armies["Mexico"] ={}
end
armies["Mexico"]["Aztec  1325 to 1521 AD"] = army["5fb1b9f5e1af06001770a42a"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Aztec  1325 to 1521 AD"] = army["5fb1b9f5e1af06001770a42a"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f5e1af06001770a42a"] = {}
army_dates["5fb1b9f5e1af06001770a42a"]["1325 AD to 1521 AD"] = {
  startDate=1325,
  endDate=1521
}
army_dates["5fb1b9f5e1af06001770a42a"]["1325 AD to 1427 AD"] = {
  startDate=1325,
  endDate=1427
}
army_dates["5fb1b9f5e1af06001770a42a"]["1428 AD to 1518 AD"] = {
  startDate=1428,
  endDate=1518
}
army_dates["5fb1b9f5e1af06001770a42a"]["1519 AD to 1521 AD"] = {
  startDate=1519,
  endDate=1521
}
