-- 5fb1b9e7e1af060017709bd2 Berber Invasions of Iberia  710 to 764 AD

army['5fb1b9e7e1af060017709bd2']={
  data={
    invasionRatings={
      4,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
      'Hilly',
    },
    name='Berber Invasions of Iberia  710 to 764 AD',
    id='5fb1b9e7e1af060017709bd2',
    dateRange={
      startDate=710,
      endDate=764,
    },
  },
  g_base_definitions[g_str_68c995df579163001588a4ec_general],
  g_base_definitions[g_str_68c995df579163001588a4ec],
  g_base_definitions[g_str_68c995df579163001588a4ee_general],
  g_base_definitions[g_str_68c995df579163001588a4ee],
  g_base_definitions[g_str_68c995df579163001588a4ef_general],
  g_base_definitions[g_str_68c995df579163001588a4ef],
  g_base_definitions[g_str_68c995df579163001588a4f1],
  g_base_definitions[g_str_68c995df579163001588a4f3_general],
  g_base_definitions[g_str_68c995df579163001588a4f3],
  g_base_definitions[g_str_68c995df579163001588a4f6_general],
  g_base_definitions[g_str_68c995df579163001588a4f6],
  g_base_definitions[g_str_5fb1b9e7e1af060017709bd2_camp],
  g_base_definitions[g_str_5fb1b9e7e1af060017709bd2_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e7e1af060017709bd2"] = army["5fb1b9e7e1af060017709bd2"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Berber Invasions of Iberia  710 to 764 AD"] = army["5fb1b9e7e1af060017709bd2"]
if nil == armies["Spread of Islam"] then
  armies["Spread of Islam"] ={}
end
armies["Spread of Islam"]["Berber Invasions of Iberia  710 to 764 AD"] = army["5fb1b9e7e1af060017709bd2"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Berber Invasions of Iberia  710 to 764 AD"] = army["5fb1b9e7e1af060017709bd2"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e7e1af060017709bd2"] = {}
army_dates["5fb1b9e7e1af060017709bd2"]["710 AD to 764 AD"] = {
  startDate=710,
  endDate=764
}
