-- 5fb1b9ede1af060017709f72 Great Seljuk or Seljuks of Rum  1037 to 1276 AD

army['5fb1b9ede1af060017709f72']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Hilly',
      'Steppe',
    },
    name='Great Seljuk or Seljuks of Rum  1037 to 1276 AD',
    id='5fb1b9ede1af060017709f72',
    dateRange={
      startDate=1037,
      endDate=1276,
    },
  },
  g_base_definitions[g_str_68c995e4579163001588b4cd_general],
  g_base_definitions[g_str_68c995e4579163001588b4cd_general_shower_shooting],
  g_base_definitions[g_str_68c995e4579163001588b4cd],
  g_base_definitions[g_str_68c995e4579163001588b4cd_shower_shooting],
  g_base_definitions[g_str_68c995e4579163001588b4d0_general],
  g_base_definitions[g_str_68c995e4579163001588b4d0],
  g_base_definitions[g_str_68c995e4579163001588b4d2_general],
  g_base_definitions[g_str_68c995e4579163001588b4d2],
  g_base_definitions[g_str_68c995e4579163001588b4d4],
  g_base_definitions[g_str_68c995e4579163001588b4d6],
  g_base_definitions[g_str_68c995e4579163001588b4d6_shower_shooting],
  g_base_definitions[g_str_68c995e4579163001588b4d9],
  g_base_definitions[g_str_68c995e4579163001588b4d9_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b4d9_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b4dd],
  g_base_definitions[g_str_68c995e4579163001588b4e0],
  g_base_definitions[g_str_68c995e4579163001588b4e3],
  g_base_definitions[g_str_5fb1b9ede1af060017709f72_camp],
  g_base_definitions[g_str_5fb1b9ede1af060017709f72_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ede1af060017709f72"] = army["5fb1b9ede1af060017709f72"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Great Seljuk or Seljuks of Rum  1037 to 1276 AD"] = army["5fb1b9ede1af060017709f72"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Great Seljuk or Seljuks of Rum  1037 to 1276 AD"] = army["5fb1b9ede1af060017709f72"]
if nil == armies["Byzantium in Decay"] then
  armies["Byzantium in Decay"] ={}
end
armies["Byzantium in Decay"]["Great Seljuk or Seljuks of Rum  1037 to 1276 AD"] = army["5fb1b9ede1af060017709f72"]
if nil == armies["Crusader Kingdoms"] then
  armies["Crusader Kingdoms"] ={}
end
armies["Crusader Kingdoms"]["Great Seljuk or Seljuks of Rum  1037 to 1276 AD"] = army["5fb1b9ede1af060017709f72"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Great Seljuk or Seljuks of Rum  1037 to 1276 AD"] = army["5fb1b9ede1af060017709f72"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ede1af060017709f72"] = {}
army_dates["5fb1b9ede1af060017709f72"]["1037 AD to 1276 AD"] = {
  startDate=1037,
  endDate=1276
}
army_dates["5fb1b9ede1af060017709f72"]["1037 AD to 1091 AD"] = {
  startDate=1037,
  endDate=1091
}
army_dates["5fb1b9ede1af060017709f72"]["1092 AD to 1163 AD"] = {
  startDate=1092,
  endDate=1163
}
army_dates["5fb1b9ede1af060017709f72"]["1164 AD to 1185 AD"] = {
  startDate=1164,
  endDate=1185
}
army_dates["5fb1b9ede1af060017709f72"]["1186 AD to 1236 AD"] = {
  startDate=1186,
  endDate=1236
}
army_dates["5fb1b9ede1af060017709f72"]["1237 AD"] = {
  startDate=1237,
  endDate=1237
}
army_dates["5fb1b9ede1af060017709f72"]["1238 AD to 1246 AD"] = {
  startDate=1238,
  endDate=1246
}
army_dates["5fb1b9ede1af060017709f72"]["1247 AD to 1250 AD"] = {
  startDate=1247,
  endDate=1250
}
army_dates["5fb1b9ede1af060017709f72"]["1251 AD to 1255 AD"] = {
  startDate=1251,
  endDate=1255
}
army_dates["5fb1b9ede1af060017709f72"]["1256 AD to 1276 AD"] = {
  startDate=1256,
  endDate=1276
}
