-- 5fb1b9dfe1af0600177096fc Early Seleucid  320 to 281 BC

army['5fb1b9dfe1af0600177096fc']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Arable',
      'Hilly',
    },
    name='Early Seleucid  320 to 281 BC',
    id='5fb1b9dfe1af0600177096fc',
    dateRange={
      startDate=-320,
      endDate=-281,
    },
  },
  g_base_definitions[g_str_68c995d857916300158893b7_general],
  g_base_definitions[g_str_68c995d857916300158893b7],
  g_base_definitions[g_str_68c995d857916300158893b9_general],
  g_base_definitions[g_str_68c995d857916300158893b9],
  g_base_definitions[g_str_68c995d857916300158893bb],
  g_base_definitions[g_str_68c995d857916300158893bd],
  g_base_definitions[g_str_68c995d857916300158893bd_elephant_screen],
  g_base_definitions[g_str_68c995d857916300158893c0],
  g_base_definitions[g_str_68c995d857916300158893c2],
  g_base_definitions[g_str_68c995d857916300158893c4],
  g_base_definitions[g_str_68c995d857916300158893c6],
  g_base_definitions[g_str_68c995d857916300158893c8],
  g_base_definitions[g_str_68c995d857916300158893ca],
  g_base_definitions[g_str_68c995d857916300158893cc],
  g_base_definitions[g_str_5fb1b9dfe1af0600177096fc_camp],
  g_base_definitions[g_str_5fb1b9dfe1af0600177096fc_camp_fortified],
  g_base_definitions[g_str_5fb1b9dfe1af0600177096fc_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dfe1af0600177096fc"] = army["5fb1b9dfe1af0600177096fc"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Early Seleucid  320 to 281 BC"] = army["5fb1b9dfe1af0600177096fc"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Seleucid  320 to 281 BC"] = army["5fb1b9dfe1af0600177096fc"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dfe1af0600177096fc"] = {}
army_dates["5fb1b9dfe1af0600177096fc"]["320 BC to 281 BC"] = {
  startDate=-320,
  endDate=-281
}
