-- 5fb1b9e6e1af060017709baf Almohades  1121 to 1145 AD

army['5fb1b9e6e1af060017709baf']={
  data={
    invasionRatings={
      4,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
      'Dry',
    },
    name='Almohades  1121 to 1145 AD',
    id='5fb1b9e6e1af060017709baf',
    dateRange={
      startDate=1121,
      endDate=1145,
    },
  },
  g_base_definitions[g_str_68c995df579163001588a461_general],
  g_base_definitions[g_str_68c995df579163001588a461],
  g_base_definitions[g_str_68c995df579163001588a463],
  g_base_definitions[g_str_68c995df579163001588a465],
  g_base_definitions[g_str_68c995df579163001588a468],
  g_base_definitions[g_str_68c995df579163001588a468_shower_shooting],
  g_base_definitions[g_str_68c995df579163001588a46c],
  g_base_definitions[g_str_68c995df579163001588a46d],
  g_base_definitions[g_str_5fb1b9e6e1af060017709baf_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e6e1af060017709baf"] = army["5fb1b9e6e1af060017709baf"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Almohades  1121 to 1145 AD"] = army["5fb1b9e6e1af060017709baf"]
if nil == armies["Sahel Africa"] then
  armies["Sahel Africa"] ={}
end
armies["Sahel Africa"]["Almohades  1121 to 1145 AD"] = army["5fb1b9e6e1af060017709baf"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Almohades  1121 to 1145 AD"] = army["5fb1b9e6e1af060017709baf"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e6e1af060017709baf"] = {}
army_dates["5fb1b9e6e1af060017709baf"]["1121 AD to 1145 AD"] = {
  startDate=1121,
  endDate=1145
}
