-- 5fb1b9e4e1af060017709a6e Frisian  793 to 1105 AD

army['5fb1b9e4e1af060017709a6e']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Marsh',
    },
    name='Frisian  793 to 1105 AD',
    id='5fb1b9e4e1af060017709a6e',
    dateRange={
      startDate=793,
      endDate=1105,
    },
  },
  g_base_definitions[g_str_68c995dd579163001588a033_general],
  g_base_definitions[g_str_68c995dd579163001588a033],
  g_base_definitions[g_str_68c995dd579163001588a035_general],
  g_base_definitions[g_str_68c995dd579163001588a035],
  g_base_definitions[g_str_68c995dd579163001588a037],
  g_base_definitions[g_str_68c995dd579163001588a038],
  g_base_definitions[g_str_68c995dd579163001588a03a],
  g_base_definitions[g_str_68c995dd579163001588a03c],
  g_base_definitions[g_str_68c995dd579163001588a03c_shower_shooting],
  g_base_definitions[g_str_5fb1b9e4e1af060017709a6e_camp],
  g_base_definitions[g_str_5fb1b9e4e1af060017709a6e_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e4e1af060017709a6e"] = army["5fb1b9e4e1af060017709a6e"]
if nil == armies["Viking Seas"] then
  armies["Viking Seas"] ={}
end
armies["Viking Seas"]["Frisian  793 to 1105 AD"] = army["5fb1b9e4e1af060017709a6e"]
if nil == armies["Holy Roman Empire"] then
  armies["Holy Roman Empire"] ={}
end
armies["Holy Roman Empire"]["Frisian  793 to 1105 AD"] = army["5fb1b9e4e1af060017709a6e"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Frisian  793 to 1105 AD"] = army["5fb1b9e4e1af060017709a6e"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e4e1af060017709a6e"] = {}
army_dates["5fb1b9e4e1af060017709a6e"]["793 AD to 1105 AD"] = {
  startDate=793,
  endDate=1105
}
