-- 5fb1b9e3e1af0600177099a3 Italian Ostrogothic  493 to 561 AD

army['5fb1b9e3e1af0600177099a3']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
      'Hilly',
    },
    name='Italian Ostrogothic  493 to 561 AD',
    id='5fb1b9e3e1af0600177099a3',
    dateRange={
      startDate=493,
      endDate=561,
    },
  },
  g_base_definitions[g_str_68c995dc5791630015889d97_general],
  g_base_definitions[g_str_68c995dc5791630015889d97_general_mounted],
  g_base_definitions[g_str_68c995dc5791630015889d97_general_dismounted],
  g_base_definitions[g_str_68c995dc5791630015889d97],
  g_base_definitions[g_str_68c995dc5791630015889d97_mounted],
  g_base_definitions[g_str_68c995dc5791630015889d97_dismounted],
  g_base_definitions[g_str_68c995dc5791630015889d9a],
  g_base_definitions[g_str_68c995dc5791630015889d9d],
  g_base_definitions[g_str_68c995dc5791630015889d9d_shower_shooting],
  g_base_definitions[g_str_68c995dc5791630015889da1],
  g_base_definitions[g_str_68c995dc5791630015889da3],
  g_base_definitions[g_str_5fb1b9e3e1af0600177099a3_camp],
  g_base_definitions[g_str_5fb1b9e3e1af0600177099a3_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e3e1af0600177099a3"] = army["5fb1b9e3e1af0600177099a3"]
if nil == armies["Fall of Rome"] then
  armies["Fall of Rome"] ={}
end
armies["Fall of Rome"]["Italian Ostrogothic  493 to 561 AD"] = army["5fb1b9e3e1af0600177099a3"]
if nil == armies["Dark Ages"] then
  armies["Dark Ages"] ={}
end
armies["Dark Ages"]["Italian Ostrogothic  493 to 561 AD"] = army["5fb1b9e3e1af0600177099a3"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Italian Ostrogothic  493 to 561 AD"] = army["5fb1b9e3e1af0600177099a3"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e3e1af0600177099a3"] = {}
army_dates["5fb1b9e3e1af0600177099a3"]["493 AD to 561 AD"] = {
  startDate=493,
  endDate=561
}
army_dates["5fb1b9e3e1af0600177099a3"]["493 AD to 495 AD"] = {
  startDate=493,
  endDate=495
}
army_dates["5fb1b9e3e1af0600177099a3"]["496 AD to 534 AD"] = {
  startDate=496,
  endDate=534
}
army_dates["5fb1b9e3e1af0600177099a3"]["535 AD to 561 AD"] = {
  startDate=535,
  endDate=561
}
