-- 5fb1b9d9e1af060017709357 Later Nine Bows Libyan  1213 to 665 BC

army['5fb1b9d9e1af060017709357']={
  data={
    invasionRatings={
      4,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Dry',
    },
    name='Later Nine Bows Libyan  1213 to 665 BC',
    id='5fb1b9d9e1af060017709357',
    dateRange={
      startDate=-1213,
      endDate=-665,
    },
    ambush=true,  },
  g_base_definitions[g_str_68c995d35791630015888583_general],
  g_base_definitions[g_str_68c995d35791630015888583],
  g_base_definitions[g_str_68c995d35791630015888585],
  g_base_definitions[g_str_68c995d35791630015888587],
  g_base_definitions[g_str_68c995d3579163001588858a],
  g_base_definitions[g_str_68c995d3579163001588858c],
  g_base_definitions[g_str_68c995d3579163001588858c_shower_shooting],
  g_base_definitions[g_str_68c995d3579163001588858d],
  g_base_definitions[g_str_68c995d3579163001588858d_shower_shooting],
  g_base_definitions[g_str_68c995d35791630015888590],
  g_base_definitions[g_str_5fb1b9d9e1af060017709357_camp],
  g_base_definitions[g_str_5fb1b9d9e1af060017709357_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9d9e1af060017709357"] = army["5fb1b9d9e1af060017709357"]
if nil == armies["Chariot Supremacy"] then
  armies["Chariot Supremacy"] ={}
end
armies["Chariot Supremacy"]["Later Nine Bows Libyan  1213 to 665 BC"] = army["5fb1b9d9e1af060017709357"]
if nil == armies["Assyrian Empire"] then
  armies["Assyrian Empire"] ={}
end
armies["Assyrian Empire"]["Later Nine Bows Libyan  1213 to 665 BC"] = army["5fb1b9d9e1af060017709357"]
if nil == armies["Sea Peoples Invasions"] then
  armies["Sea Peoples Invasions"] ={}
end
armies["Sea Peoples Invasions"]["Later Nine Bows Libyan  1213 to 665 BC"] = army["5fb1b9d9e1af060017709357"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Nine Bows Libyan  1213 to 665 BC"] = army["5fb1b9d9e1af060017709357"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9d9e1af060017709357"] = {}
army_dates["5fb1b9d9e1af060017709357"]["1213 BC to 665 BC"] = {
  startDate=-1213,
  endDate=-665
}
army_dates["5fb1b9d9e1af060017709357"]["1213 BC to 1176 BC"] = {
  startDate=-1213,
  endDate=-1176
}
army_dates["5fb1b9d9e1af060017709357"]["1175 BC to 665 BC"] = {
  startDate=-1175,
  endDate=-665
}
