-- 5fb1b9dde1af060017709652 Bithynian  435 to 74 BC

army['5fb1b9dde1af060017709652']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
    },
    name='Bithynian  435 to 74 BC',
    id='5fb1b9dde1af060017709652',
    dateRange={
      startDate=-435,
      endDate=-74,
    },
    ambush=true,  },
  g_base_definitions[g_str_68c995d85791630015889124_general],
  g_base_definitions[g_str_68c995d85791630015889124],
  g_base_definitions[g_str_68c995d85791630015889126],
  g_base_definitions[g_str_68c995d85791630015889128],
  g_base_definitions[g_str_68c995d8579163001588912a],
  g_base_definitions[g_str_68c995d8579163001588912d],
  g_base_definitions[g_str_5fb1b9dde1af060017709652_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dde1af060017709652"] = army["5fb1b9dde1af060017709652"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Bithynian  435 to 74 BC"] = army["5fb1b9dde1af060017709652"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Bithynian  435 to 74 BC"] = army["5fb1b9dde1af060017709652"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Bithynian  435 to 74 BC"] = army["5fb1b9dde1af060017709652"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dde1af060017709652"] = {}
army_dates["5fb1b9dde1af060017709652"]["435 BC to 74 BC"] = {
  startDate=-435,
  endDate=-74
}
army_dates["5fb1b9dde1af060017709652"]["435 BC to 281 BC"] = {
  startDate=-435,
  endDate=-281
}
army_dates["5fb1b9dde1af060017709652"]["280 BC to 279 BC"] = {
  startDate=-280,
  endDate=-279
}
army_dates["5fb1b9dde1af060017709652"]["278 BC to 253 BC"] = {
  startDate=-278,
  endDate=-253
}
army_dates["5fb1b9dde1af060017709652"]["252 BC to 228 BC"] = {
  startDate=-252,
  endDate=-228
}
army_dates["5fb1b9dde1af060017709652"]["227 BC to 225 BC"] = {
  startDate=-227,
  endDate=-225
}
army_dates["5fb1b9dde1af060017709652"]["224 BC to 74 BC"] = {
  startDate=-224,
  endDate=-74
}
