-- 5fb1b9eae1af060017709db9 Teutonic Orders  1201 to 1525 AD

army['5fb1b9eae1af060017709db9']={
  data={
    invasionRatings={
      4,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
    },
    name='Teutonic Orders  1201 to 1525 AD',
    id='5fb1b9eae1af060017709db9',
    dateRange={
      startDate=1201,
      endDate=1525,
    },
  },
  g_base_definitions[g_str_68c995e2579163001588acf8_general],
  g_base_definitions[g_str_68c995e2579163001588acf8_general_mounted],
  g_base_definitions[g_str_68c995e2579163001588acf8_general_dismounted],
  g_base_definitions[g_str_68c995e2579163001588acf8],
  g_base_definitions[g_str_68c995e2579163001588acf8_mounted],
  g_base_definitions[g_str_68c995e2579163001588acf8_dismounted],
  g_base_definitions[g_str_68c995e2579163001588acfc_general],
  g_base_definitions[g_str_68c995e2579163001588acfc],
  g_base_definitions[g_str_68c995e2579163001588acff],
  g_base_definitions[g_str_68c995e2579163001588ad01],
  g_base_definitions[g_str_68c995e2579163001588ad03],
  g_base_definitions[g_str_68c995e2579163001588ad05],
  g_base_definitions[g_str_68c995e2579163001588ad08],
  g_base_definitions[g_str_68c995e2579163001588ad0a],
  g_base_definitions[g_str_68c995e2579163001588ad0d],
  g_base_definitions[g_str_68c995e2579163001588ad0f],
  g_base_definitions[g_str_68c995e2579163001588ad11],
  g_base_definitions[g_str_68c995e2579163001588ad13],
  g_base_definitions[g_str_68c995e2579163001588ad16],
  g_base_definitions[g_str_68c995e2579163001588ad19],
  g_base_definitions[g_str_5fb1b9eae1af060017709db9_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eae1af060017709db9"] = army["5fb1b9eae1af060017709db9"]
if nil == armies["Russian Princes"] then
  armies["Russian Princes"] ={}
end
armies["Russian Princes"]["Teutonic Orders  1201 to 1525 AD"] = army["5fb1b9eae1af060017709db9"]
if nil == armies["Baltic Powers"] then
  armies["Baltic Powers"] ={}
end
armies["Baltic Powers"]["Teutonic Orders  1201 to 1525 AD"] = army["5fb1b9eae1af060017709db9"]
if nil == armies["Holy Roman Empire"] then
  armies["Holy Roman Empire"] ={}
end
armies["Holy Roman Empire"]["Teutonic Orders  1201 to 1525 AD"] = army["5fb1b9eae1af060017709db9"]
if nil == armies["Plate and Handgonne"] then
  armies["Plate and Handgonne"] ={}
end
armies["Plate and Handgonne"]["Teutonic Orders  1201 to 1525 AD"] = army["5fb1b9eae1af060017709db9"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Teutonic Orders  1201 to 1525 AD"] = army["5fb1b9eae1af060017709db9"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eae1af060017709db9"] = {}
army_dates["5fb1b9eae1af060017709db9"]["1201 AD to 1525 AD"] = {
  startDate=1201,
  endDate=1525
}
army_dates["5fb1b9eae1af060017709db9"]["1201 AD to 1241 AD"] = {
  startDate=1201,
  endDate=1241
}
army_dates["5fb1b9eae1af060017709db9"]["1242 AD to 1320 AD"] = {
  startDate=1242,
  endDate=1320
}
army_dates["5fb1b9eae1af060017709db9"]["1321 AD to 1335 AD"] = {
  startDate=1321,
  endDate=1335
}
army_dates["5fb1b9eae1af060017709db9"]["1336 AD to 1439 AD"] = {
  startDate=1336,
  endDate=1439
}
army_dates["5fb1b9eae1af060017709db9"]["1440 AD to 1493 AD"] = {
  startDate=1440,
  endDate=1493
}
army_dates["5fb1b9eae1af060017709db9"]["1494 AD to 1525 AD"] = {
  startDate=1494,
  endDate=1525
}
