-- 5fb1b9f5e1af06001770a3bf Late Maya  1462 to 1546 AD

army['5fb1b9f5e1af06001770a3bf']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Forest',
    },
    name='Late Maya  1462 to 1546 AD',
    id='5fb1b9f5e1af06001770a3bf',
    dateRange={
      startDate=1462,
      endDate=1546,
    },
    ambush=true,  },
  g_base_definitions[g_str_68c995eb579163001588c4a8],
  g_base_definitions[g_str_68c995eb579163001588c4a8_shower_shooting],
  g_base_definitions[g_str_68c995eb579163001588c4ab],
  g_base_definitions[g_str_68c995eb579163001588c4ab_shower_shooting],
  g_base_definitions[g_str_68c995eb579163001588c4ae_general],
  g_base_definitions[g_str_68c995eb579163001588c4ae],
  g_base_definitions[g_str_68c995eb579163001588c4b0],
  g_base_definitions[g_str_68c995eb579163001588c4b2],
  g_base_definitions[g_str_5fb1b9f5e1af06001770a3bf_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f5e1af06001770a3bf"] = army["5fb1b9f5e1af06001770a3bf"]
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["Late Maya  1462 to 1546 AD"] = army["5fb1b9f5e1af06001770a3bf"]
if nil == armies["Mexico"] then
  armies["Mexico"] ={}
end
armies["Mexico"]["Late Maya  1462 to 1546 AD"] = army["5fb1b9f5e1af06001770a3bf"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Late Maya  1462 to 1546 AD"] = army["5fb1b9f5e1af06001770a3bf"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f5e1af06001770a3bf"] = {}
army_dates["5fb1b9f5e1af06001770a3bf"]["1462 AD to 1546 AD"] = {
  startDate=1462,
  endDate=1546
}
