-- 5fb1b9ede1af060017709f41 Hamdanid Dynasties  890 to 1003 AD

army['5fb1b9ede1af060017709f41']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Dry',
    },
    name='Hamdanid Dynasties  890 to 1003 AD',
    id='5fb1b9ede1af060017709f41',
    dateRange={
      startDate=890,
      endDate=1003,
    },
  },
  g_base_definitions[g_str_68c995e4579163001588b3e9_general],
  g_base_definitions[g_str_68c995e4579163001588b3e9],
  g_base_definitions[g_str_68c995e4579163001588b3eb_general],
  g_base_definitions[g_str_68c995e4579163001588b3eb_general_shower_shooting],
  g_base_definitions[g_str_68c995e4579163001588b3eb],
  g_base_definitions[g_str_68c995e4579163001588b3eb_shower_shooting],
  g_base_definitions[g_str_68c995e4579163001588b3ec_general],
  g_base_definitions[g_str_68c995e4579163001588b3ec_general_shower_shooting],
  g_base_definitions[g_str_68c995e4579163001588b3ec],
  g_base_definitions[g_str_68c995e4579163001588b3ec_shower_shooting],
  g_base_definitions[g_str_68c995e4579163001588b3ef_general],
  g_base_definitions[g_str_68c995e4579163001588b3ef],
  g_base_definitions[g_str_68c995e4579163001588b3f2],
  g_base_definitions[g_str_68c995e4579163001588b3f2_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b3f2_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b3f6],
  g_base_definitions[g_str_68c995e4579163001588b3f9],
  g_base_definitions[g_str_68c995e4579163001588b3f9_light_camelry],
  g_base_definitions[g_str_68c995e4579163001588b3fc],
  g_base_definitions[g_str_5fb1b9ede1af060017709f41_camp],
  g_base_definitions[g_str_5fb1b9ede1af060017709f41_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ede1af060017709f41"] = army["5fb1b9ede1af060017709f41"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Hamdanid Dynasties  890 to 1003 AD"] = army["5fb1b9ede1af060017709f41"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Hamdanid Dynasties  890 to 1003 AD"] = army["5fb1b9ede1af060017709f41"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ede1af060017709f41"] = {}
army_dates["5fb1b9ede1af060017709f41"]["890 AD to 1003 AD"] = {
  startDate=890,
  endDate=1003
}
