-- 5fb1b9e3e1af0600177099b8 Merovingian Frankish: Provence  535 to 639 AD

army['5fb1b9e3e1af0600177099b8']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Merovingian Frankish: Provence  535 to 639 AD',
    id='5fb1b9e3e1af0600177099b8',
    dateRange={
      startDate=535,
      endDate=639,
    },
  },
  g_base_definitions[g_str_68c995dc5791630015889dcb_general],
  g_base_definitions[g_str_68c995dc5791630015889dcb_general_mounted],
  g_base_definitions[g_str_68c995dc5791630015889dcb_general_dismounted],
  g_base_definitions[g_str_68c995dc5791630015889dcb],
  g_base_definitions[g_str_68c995dc5791630015889dcb_mounted],
  g_base_definitions[g_str_68c995dc5791630015889dcb_dismounted],
  g_base_definitions[g_str_68c995dc5791630015889dce_general],
  g_base_definitions[g_str_68c995dc5791630015889dce_general_mounted],
  g_base_definitions[g_str_68c995dc5791630015889dce_general_dismounted],
  g_base_definitions[g_str_68c995dc5791630015889dce],
  g_base_definitions[g_str_68c995dc5791630015889dce_mounted],
  g_base_definitions[g_str_68c995dc5791630015889dce_dismounted],
  g_base_definitions[g_str_68c995dc5791630015889dcf_general],
  g_base_definitions[g_str_68c995dc5791630015889dcf_general_mounted],
  g_base_definitions[g_str_68c995dc5791630015889dcf_general_dismounted],
  g_base_definitions[g_str_68c995dc5791630015889dcf],
  g_base_definitions[g_str_68c995dc5791630015889dcf_mounted],
  g_base_definitions[g_str_68c995dc5791630015889dcf_dismounted],
  g_base_definitions[g_str_68c995dc5791630015889dd2],
  g_base_definitions[g_str_68c995dc5791630015889dd4],
  g_base_definitions[g_str_68c995dc5791630015889dd6],
  g_base_definitions[g_str_68c995dc5791630015889dd7],
  g_base_definitions[g_str_5fb1b9e3e1af0600177099b8_camp],
  g_base_definitions[g_str_5fb1b9e3e1af0600177099b8_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e3e1af0600177099b8"] = army["5fb1b9e3e1af0600177099b8"]
if nil == armies["Fall of Rome"] then
  armies["Fall of Rome"] ={}
end
armies["Fall of Rome"]["Merovingian Frankish: Provence  535 to 639 AD"] = army["5fb1b9e3e1af0600177099b8"]
if nil == armies["Dark Ages"] then
  armies["Dark Ages"] ={}
end
armies["Dark Ages"]["Merovingian Frankish: Provence  535 to 639 AD"] = army["5fb1b9e3e1af0600177099b8"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Merovingian Frankish: Provence  535 to 639 AD"] = army["5fb1b9e3e1af0600177099b8"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e3e1af0600177099b8"] = {}
army_dates["5fb1b9e3e1af0600177099b8"]["535 AD to 639 AD"] = {
  startDate=535,
  endDate=639
}
army_dates["5fb1b9e3e1af0600177099b8"]["535 AD to 588 AD"] = {
  startDate=535,
  endDate=588
}
army_dates["5fb1b9e3e1af0600177099b8"]["589 AD to 639 AD"] = {
  startDate=589,
  endDate=639
}
