-- 5fb1b9eee1af06001770a01c Golden Horde and Successors  1251 to 1556 AD

army['5fb1b9eee1af06001770a01c']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      3,
      4,
    },
    homeTopographies={
      'Steppe',
    },
    name='Golden Horde and Successors  1251 to 1556 AD',
    id='5fb1b9eee1af06001770a01c',
    dateRange={
      startDate=1251,
      endDate=1556,
    },
  },
  g_base_definitions[g_str_68c995e6579163001588b76d_general],
  g_base_definitions[g_str_68c995e6579163001588b76d],
  g_base_definitions[g_str_68c995e6579163001588b76f_general],
  g_base_definitions[g_str_68c995e6579163001588b76f],
  g_base_definitions[g_str_68c995e6579163001588b771],
  g_base_definitions[g_str_68c995e6579163001588b771_shower_shooting],
  g_base_definitions[g_str_68c995e6579163001588b774_general],
  g_base_definitions[g_str_68c995e6579163001588b774],
  g_base_definitions[g_str_68c995e6579163001588b776_general],
  g_base_definitions[g_str_68c995e6579163001588b776],
  g_base_definitions[g_str_68c995e6579163001588b778],
  g_base_definitions[g_str_68c995e6579163001588b77a],
  g_base_definitions[g_str_5fb1b9eee1af06001770a01c_camp],
  g_base_definitions[g_str_5fb1b9eee1af06001770a01c_camp_fortified],
  g_base_definitions[g_str_5fb1b9eee1af06001770a01c_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eee1af06001770a01c"] = army["5fb1b9eee1af06001770a01c"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Golden Horde and Successors  1251 to 1556 AD"] = army["5fb1b9eee1af06001770a01c"]
if nil == armies["Byzantium in Decay"] then
  armies["Byzantium in Decay"] ={}
end
armies["Byzantium in Decay"]["Golden Horde and Successors  1251 to 1556 AD"] = army["5fb1b9eee1af06001770a01c"]
if nil == armies["Russian Princes"] then
  armies["Russian Princes"] ={}
end
armies["Russian Princes"]["Golden Horde and Successors  1251 to 1556 AD"] = army["5fb1b9eee1af06001770a01c"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Golden Horde and Successors  1251 to 1556 AD"] = army["5fb1b9eee1af06001770a01c"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eee1af06001770a01c"] = {}
army_dates["5fb1b9eee1af06001770a01c"]["1251 AD to 1556 AD"] = {
  startDate=1251,
  endDate=1556
}
army_dates["5fb1b9eee1af06001770a01c"]["1251 AD to 1258 AD"] = {
  startDate=1251,
  endDate=1258
}
army_dates["5fb1b9eee1af06001770a01c"]["1259 AD to 1361 AD"] = {
  startDate=1259,
  endDate=1361
}
army_dates["5fb1b9eee1af06001770a01c"]["1362 AD to 1455 AD"] = {
  startDate=1362,
  endDate=1455
}
army_dates["5fb1b9eee1af06001770a01c"]["1456 AD to 1475 AD"] = {
  startDate=1456,
  endDate=1475
}
army_dates["5fb1b9eee1af06001770a01c"]["1476 AD to 1520 AD"] = {
  startDate=1476,
  endDate=1520
}
army_dates["5fb1b9eee1af06001770a01c"]["1521 AD to 1556 AD"] = {
  startDate=1521,
  endDate=1556
}
