-- 5fb1b9f6e1af06001770a490 Araucanian  1461 to 1552 AD

army['5fb1b9f6e1af06001770a490']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Araucanian  1461 to 1552 AD',
    id='5fb1b9f6e1af06001770a490',
    dateRange={
      startDate=1461,
      endDate=1552,
    },
    ambush=true,  },
  g_base_definitions[g_str_68c995eb579163001588c61d_general],
  g_base_definitions[g_str_68c995eb579163001588c61d],
  g_base_definitions[g_str_68c995eb579163001588c61f],
  g_base_definitions[g_str_68c995eb579163001588c621],
  g_base_definitions[g_str_5fb1b9f6e1af06001770a490_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f6e1af06001770a490"] = army["5fb1b9f6e1af06001770a490"]
if nil == armies["Andes and Amazon"] then
  armies["Andes and Amazon"] ={}
end
armies["Andes and Amazon"]["Araucanian  1461 to 1552 AD"] = army["5fb1b9f6e1af06001770a490"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Araucanian  1461 to 1552 AD"] = army["5fb1b9f6e1af06001770a490"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f6e1af06001770a490"] = {}
army_dates["5fb1b9f6e1af06001770a490"]["1461 AD to 1552 AD"] = {
  startDate=1461,
  endDate=1552
}
