-- 5fb1b9d9e1af0600177093a4 Midianites and Early Arabs  1500 to 312 BC

army['5fb1b9d9e1af0600177093a4']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Dry',
    },
    name='Midianites and Early Arabs  1500 to 312 BC',
    id='5fb1b9d9e1af0600177093a4',
    dateRange={
      startDate=-1500,
      endDate=-312,
    },
  },
  g_base_definitions[g_str_68c995d35791630015888695_general],
  g_base_definitions[g_str_68c995d35791630015888695_general_light_camelry],
  g_base_definitions[g_str_68c995d35791630015888695],
  g_base_definitions[g_str_68c995d35791630015888695_light_camelry],
  g_base_definitions[g_str_68c995d35791630015888698],
  g_base_definitions[g_str_68c995d3579163001588869a],
  g_base_definitions[g_str_68c995d3579163001588869c],
  g_base_definitions[g_str_68c995d3579163001588869f],
  g_base_definitions[g_str_68c995d3579163001588869f_shower_shooting],
  g_base_definitions[g_str_5fb1b9d9e1af0600177093a4_camp],
  g_base_definitions[g_str_5fb1b9d9e1af0600177093a4_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9d9e1af0600177093a4"] = army["5fb1b9d9e1af0600177093a4"]
if nil == armies["Chariot Supremacy"] then
  armies["Chariot Supremacy"] ={}
end
armies["Chariot Supremacy"]["Midianites and Early Arabs  1500 to 312 BC"] = army["5fb1b9d9e1af0600177093a4"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Midianites and Early Arabs  1500 to 312 BC"] = army["5fb1b9d9e1af0600177093a4"]
if nil == armies["Assyrian Empire"] then
  armies["Assyrian Empire"] ={}
end
armies["Assyrian Empire"]["Midianites and Early Arabs  1500 to 312 BC"] = army["5fb1b9d9e1af0600177093a4"]
if nil == armies["Sea Peoples Invasions"] then
  armies["Sea Peoples Invasions"] ={}
end
armies["Sea Peoples Invasions"]["Midianites and Early Arabs  1500 to 312 BC"] = army["5fb1b9d9e1af0600177093a4"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Midianites and Early Arabs  1500 to 312 BC"] = army["5fb1b9d9e1af0600177093a4"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9d9e1af0600177093a4"] = {}
army_dates["5fb1b9d9e1af0600177093a4"]["1500 BC to 312 BC"] = {
  startDate=-1500,
  endDate=-312
}
