-- 5fb1b9e8e1af060017709c6a Free Company  1357 to 1410 AD

army['5fb1b9e8e1af060017709c6a']={
  data={
    invasionRatings={
      4,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
    },
    name='Free Company  1357 to 1410 AD',
    id='5fb1b9e8e1af060017709c6a',
    dateRange={
      startDate=1357,
      endDate=1410,
    },
  },
  g_base_definitions[g_str_68c995e0579163001588a72f_general],
  g_base_definitions[g_str_68c995e0579163001588a72f_general_mounted],
  g_base_definitions[g_str_68c995e0579163001588a72f_general_dismounted],
  g_base_definitions[g_str_68c995e0579163001588a72f],
  g_base_definitions[g_str_68c995e0579163001588a72f_mounted],
  g_base_definitions[g_str_68c995e0579163001588a72f_dismounted],
  g_base_definitions[g_str_68c995e0579163001588a732],
  g_base_definitions[g_str_68c995e0579163001588a734],
  g_base_definitions[g_str_68c995e0579163001588a734_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e0579163001588a734_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e0579163001588a737],
  g_base_definitions[g_str_68c995e0579163001588a73a],
  g_base_definitions[g_str_5fb1b9e8e1af060017709c6a_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e8e1af060017709c6a"] = army["5fb1b9e8e1af060017709c6a"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Free Company  1357 to 1410 AD"] = army["5fb1b9e8e1af060017709c6a"]
if nil == armies["Flower of Chivalry"] then
  armies["Flower of Chivalry"] ={}
end
armies["Flower of Chivalry"]["Free Company  1357 to 1410 AD"] = army["5fb1b9e8e1af060017709c6a"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Free Company  1357 to 1410 AD"] = army["5fb1b9e8e1af060017709c6a"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e8e1af060017709c6a"] = {}
army_dates["5fb1b9e8e1af060017709c6a"]["1357 AD to 1410 AD"] = {
  startDate=1357,
  endDate=1410
}
army_dates["5fb1b9e8e1af060017709c6a"]["1357 AD to 1362 AD"] = {
  startDate=1357,
  endDate=1362
}
army_dates["5fb1b9e8e1af060017709c6a"]["1363 AD to 1399 AD"] = {
  startDate=1363,
  endDate=1399
}
army_dates["5fb1b9e8e1af060017709c6a"]["1400 AD to 1410 AD"] = {
  startDate=1400,
  endDate=1410
}
