-- 5fb1b9dee1af0600177096d6 Later Skythian  300 BC to 50 AD

army['5fb1b9dee1af0600177096d6']={
  data={
    invasionRatings={
      4,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Steppe',
    },
    name='Later Skythian  300 BC to 50 AD',
    id='5fb1b9dee1af0600177096d6',
    dateRange={
      startDate=-300,
      endDate=50,
    },
  },
  g_base_definitions[g_str_68c995d8579163001588933f_general],
  g_base_definitions[g_str_68c995d8579163001588933f],
  g_base_definitions[g_str_68c995d85791630015889341_general],
  g_base_definitions[g_str_68c995d85791630015889341],
  g_base_definitions[g_str_5fb1b9dee1af0600177096d6_camp],
  g_base_definitions[g_str_5fb1b9dee1af0600177096d6_camp_fortified],
  g_base_definitions[g_str_5fb1b9dee1af0600177096d6_camp_pack_train],
  g_base_definitions[g_str_68c995c75791630015887037],
  g_base_definitions[g_str_68c995c75791630015887039],
  g_base_definitions[g_str_68c995c7579163001588703b],
  g_base_definitions[g_str_68c995c7579163001588703c],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dee1af0600177096d6"] = army["5fb1b9dee1af0600177096d6"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Later Skythian  300 BC to 50 AD"] = army["5fb1b9dee1af0600177096d6"]
if nil == armies["India and the Khyber Pass"] then
  armies["India and the Khyber Pass"] ={}
end
armies["India and the Khyber Pass"]["Later Skythian  300 BC to 50 AD"] = army["5fb1b9dee1af0600177096d6"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Later Skythian  300 BC to 50 AD"] = army["5fb1b9dee1af0600177096d6"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Skythian  300 BC to 50 AD"] = army["5fb1b9dee1af0600177096d6"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dee1af0600177096d6"] = {}
army_dates["5fb1b9dee1af0600177096d6"]["300 BC to 50 AD"] = {
  startDate=-300,
  endDate=50
}
army_dates["5fb1b9dee1af0600177096d6"]["300 BC to 167 BC"] = {
  startDate=-300,
  endDate=-167
}
army_dates["5fb1b9dee1af0600177096d6"]["166 BC to 130 BC"] = {
  startDate=-166,
  endDate=-130
}
army_dates["5fb1b9dee1af0600177096d6"]["129 BC"] = {
  startDate=-129,
  endDate=-129
}
army_dates["5fb1b9dee1af0600177096d6"]["128 BC to 63 BC"] = {
  startDate=-128,
  endDate=-63
}
army_dates["5fb1b9dee1af0600177096d6"]["62 BC to 50 AD"] = {
  startDate=-62,
  endDate=50
}
