-- 5fb1b9efe1af06001770a0ab Rajput Indian  747 to 1303 AD

army['5fb1b9efe1af06001770a0ab']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Dry',
      'Arable',
    },
    name='Rajput Indian  747 to 1303 AD',
    id='5fb1b9efe1af06001770a0ab',
    dateRange={
      startDate=747,
      endDate=1303,
    },
  },
  g_base_definitions[g_str_68c995e6579163001588b9f9_general],
  g_base_definitions[g_str_68c995e6579163001588b9f9],
  g_base_definitions[g_str_68c995e6579163001588b9fc_general],
  g_base_definitions[g_str_68c995e6579163001588b9fc],
  g_base_definitions[g_str_68c995e6579163001588b9fe],
  g_base_definitions[g_str_68c995e6579163001588b9fe_light_camelry],
  g_base_definitions[g_str_68c995e6579163001588ba01],
  g_base_definitions[g_str_68c995e6579163001588ba03],
  g_base_definitions[g_str_68c995e6579163001588ba05],
  g_base_definitions[g_str_68c995e6579163001588ba05_elephant_screen],
  g_base_definitions[g_str_68c995e6579163001588ba08],
  g_base_definitions[g_str_68c995e6579163001588ba08_elephant_screen],
  g_base_definitions[g_str_68c995e6579163001588ba0b],
  g_base_definitions[g_str_68c995e6579163001588ba0b_elephant_screen],
  g_base_definitions[g_str_68c995e6579163001588ba0e],
  g_base_definitions[g_str_68c995e6579163001588ba0e_elephant_screen],
  g_base_definitions[g_str_68c995e6579163001588ba0e_shower_shooting],
  g_base_definitions[g_str_68c995e6579163001588ba12],
  g_base_definitions[g_str_5fb1b9efe1af06001770a0ab_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9efe1af06001770a0ab"] = army["5fb1b9efe1af06001770a0ab"]
if nil == armies["Monsoon Region"] then
  armies["Monsoon Region"] ={}
end
armies["Monsoon Region"]["Rajput Indian  747 to 1303 AD"] = army["5fb1b9efe1af06001770a0ab"]
if nil == armies["Southeast Asia"] then
  armies["Southeast Asia"] ={}
end
armies["Southeast Asia"]["Rajput Indian  747 to 1303 AD"] = army["5fb1b9efe1af06001770a0ab"]
if nil == armies["India and the Khyber Pass"] then
  armies["India and the Khyber Pass"] ={}
end
armies["India and the Khyber Pass"]["Rajput Indian  747 to 1303 AD"] = army["5fb1b9efe1af06001770a0ab"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Rajput Indian  747 to 1303 AD"] = army["5fb1b9efe1af06001770a0ab"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9efe1af06001770a0ab"] = {}
army_dates["5fb1b9efe1af06001770a0ab"]["747 AD to 1303 AD"] = {
  startDate=747,
  endDate=1303
}
