-- 5fb1b9efe1af06001770a0a3 Kannauj Empire  606 to 647 AD

army['5fb1b9efe1af06001770a0a3']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Kannauj Empire  606 to 647 AD',
    id='5fb1b9efe1af06001770a0a3',
    dateRange={
      startDate=606,
      endDate=647,
    },
  },
  g_base_definitions[g_str_68c995e6579163001588b9e0_general],
  g_base_definitions[g_str_68c995e6579163001588b9e0],
  g_base_definitions[g_str_68c995e6579163001588b9e3_general],
  g_base_definitions[g_str_68c995e6579163001588b9e3],
  g_base_definitions[g_str_68c995e6579163001588b9e5],
  g_base_definitions[g_str_68c995e6579163001588b9e7],
  g_base_definitions[g_str_68c995e6579163001588b9e7_elephant_screen],
  g_base_definitions[g_str_68c995e6579163001588b9ea],
  g_base_definitions[g_str_68c995e6579163001588b9ea_elephant_screen],
  g_base_definitions[g_str_68c995e6579163001588b9ed],
  g_base_definitions[g_str_68c995e6579163001588b9ed_elephant_screen],
  g_base_definitions[g_str_68c995e6579163001588b9ed_shower_shooting],
  g_base_definitions[g_str_68c995e6579163001588b9f1],
  g_base_definitions[g_str_68c995e6579163001588b9f3],
  g_base_definitions[g_str_5fb1b9efe1af06001770a0a3_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9efe1af06001770a0a3"] = army["5fb1b9efe1af06001770a0a3"]
if nil == armies["Monsoon Region"] then
  armies["Monsoon Region"] ={}
end
armies["Monsoon Region"]["Kannauj Empire  606 to 647 AD"] = army["5fb1b9efe1af06001770a0a3"]
if nil == armies["Southeast Asia"] then
  armies["Southeast Asia"] ={}
end
armies["Southeast Asia"]["Kannauj Empire  606 to 647 AD"] = army["5fb1b9efe1af06001770a0a3"]
if nil == armies["India and the Khyber Pass"] then
  armies["India and the Khyber Pass"] ={}
end
armies["India and the Khyber Pass"]["Kannauj Empire  606 to 647 AD"] = army["5fb1b9efe1af06001770a0a3"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Kannauj Empire  606 to 647 AD"] = army["5fb1b9efe1af06001770a0a3"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9efe1af06001770a0a3"] = {}
army_dates["5fb1b9efe1af06001770a0a3"]["606 AD to 647 AD"] = {
  startDate=606,
  endDate=647
}
