-- 5fb1b9e1e1af06001770988c Scots-Irish  400 BC to 841 AD

army['5fb1b9e1e1af06001770988c']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Forest',
    },
    name='Scots-Irish  400 BC to 841 AD',
    id='5fb1b9e1e1af06001770988c',
    dateRange={
      startDate=-400,
      endDate=841,
    },
  },
  g_base_definitions[g_str_68c995db5791630015889993_general],
  g_base_definitions[g_str_68c995db5791630015889993_general_mounted],
  g_base_definitions[g_str_68c995db5791630015889993_general_dismounted],
  g_base_definitions[g_str_68c995db5791630015889993],
  g_base_definitions[g_str_68c995db5791630015889993_mounted],
  g_base_definitions[g_str_68c995db5791630015889993_dismounted],
  g_base_definitions[g_str_68c995db5791630015889997_general],
  g_base_definitions[g_str_68c995db5791630015889997],
  g_base_definitions[g_str_68c995db5791630015889999_general],
  g_base_definitions[g_str_68c995db5791630015889999],
  g_base_definitions[g_str_68c995db579163001588999b],
  g_base_definitions[g_str_68c995db579163001588999d],
  g_base_definitions[g_str_68c995db579163001588999f_general],
  g_base_definitions[g_str_68c995db579163001588999f],
  g_base_definitions[g_str_68c995db57916300158899a3],
  g_base_definitions[g_str_68c995db57916300158899a6],
  g_base_definitions[g_str_68c995db57916300158899a9],
  g_base_definitions[g_str_68c995db57916300158899ad],
  g_base_definitions[g_str_68c995db57916300158899ae],
  g_base_definitions[g_str_5fb1b9e1e1af06001770988c_camp],
  g_base_definitions[g_str_5fb1b9e1e1af06001770988c_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e1e1af06001770988c"] = army["5fb1b9e1e1af06001770988c"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Scots-Irish  400 BC to 841 AD"] = army["5fb1b9e1e1af06001770988c"]
if nil == armies["Pax Romana"] then
  armies["Pax Romana"] ={}
end
armies["Pax Romana"]["Scots-Irish  400 BC to 841 AD"] = army["5fb1b9e1e1af06001770988c"]
if nil == armies["Fall of Rome"] then
  armies["Fall of Rome"] ={}
end
armies["Fall of Rome"]["Scots-Irish  400 BC to 841 AD"] = army["5fb1b9e1e1af06001770988c"]
if nil == armies["Dark Ages"] then
  armies["Dark Ages"] ={}
end
armies["Dark Ages"]["Scots-Irish  400 BC to 841 AD"] = army["5fb1b9e1e1af06001770988c"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Scots-Irish  400 BC to 841 AD"] = army["5fb1b9e1e1af06001770988c"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e1e1af06001770988c"] = {}
army_dates["5fb1b9e1e1af06001770988c"]["400 BC to 841 AD"] = {
  startDate=-400,
  endDate=841
}
