-- 5fb1b9eae1af060017709dca Medieval Danish and Kalmar Union  1350 to 1523 AD

army['5fb1b9eae1af060017709dca']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
      'Marsh',
      'Arable',
      'Forest',
      'Marsh',
    },
    name='Medieval Danish and Kalmar Union  1350 to 1523 AD',
    id='5fb1b9eae1af060017709dca',
    dateRange={
      startDate=1350,
      endDate=1523,
    },
  },
  g_base_definitions[g_str_68c995e2579163001588ad44_general],
  g_base_definitions[g_str_68c995e2579163001588ad44],
  g_base_definitions[g_str_68c995e2579163001588ad46_general],
  g_base_definitions[g_str_68c995e2579163001588ad46],
  g_base_definitions[g_str_68c995e2579163001588ad48],
  g_base_definitions[g_str_68c995e2579163001588ad4a],
  g_base_definitions[g_str_68c995e2579163001588ad4c_general],
  g_base_definitions[g_str_68c995e2579163001588ad4c],
  g_base_definitions[g_str_68c995e2579163001588ad4e],
  g_base_definitions[g_str_68c995e2579163001588ad50],
  g_base_definitions[g_str_68c995e2579163001588ad53],
  g_base_definitions[g_str_68c995e2579163001588ad56],
  g_base_definitions[g_str_5fb1b9eae1af060017709dca_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eae1af060017709dca"] = army["5fb1b9eae1af060017709dca"]
if nil == armies["Russian Princes"] then
  armies["Russian Princes"] ={}
end
armies["Russian Princes"]["Medieval Danish and Kalmar Union  1350 to 1523 AD"] = army["5fb1b9eae1af060017709dca"]
if nil == armies["Baltic Powers"] then
  armies["Baltic Powers"] ={}
end
armies["Baltic Powers"]["Medieval Danish and Kalmar Union  1350 to 1523 AD"] = army["5fb1b9eae1af060017709dca"]
if nil == armies["Holy Roman Empire"] then
  armies["Holy Roman Empire"] ={}
end
armies["Holy Roman Empire"]["Medieval Danish and Kalmar Union  1350 to 1523 AD"] = army["5fb1b9eae1af060017709dca"]
if nil == armies["Plate and Handgonne"] then
  armies["Plate and Handgonne"] ={}
end
armies["Plate and Handgonne"]["Medieval Danish and Kalmar Union  1350 to 1523 AD"] = army["5fb1b9eae1af060017709dca"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Medieval Danish and Kalmar Union  1350 to 1523 AD"] = army["5fb1b9eae1af060017709dca"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eae1af060017709dca"] = {}
army_dates["5fb1b9eae1af060017709dca"]["1350 AD to 1523 AD"] = {
  startDate=1350,
  endDate=1523
}
army_dates["5fb1b9eae1af060017709dca"]["1350 AD to 1390 AD"] = {
  startDate=1350,
  endDate=1390
}
army_dates["5fb1b9eae1af060017709dca"]["1391 AD to 1439 AD"] = {
  startDate=1391,
  endDate=1439
}
army_dates["5fb1b9eae1af060017709dca"]["1440 AD to 1493 AD"] = {
  startDate=1440,
  endDate=1493
}
army_dates["5fb1b9eae1af060017709dca"]["1494 AD to 1518 AD"] = {
  startDate=1494,
  endDate=1518
}
army_dates["5fb1b9eae1af060017709dca"]["1519 AD to 1523 AD"] = {
  startDate=1519,
  endDate=1523
}
