-- 5fb1b9e6e1af060017709b32 Middle Hundred-Years War English  1350 to 1414 AD

army['5fb1b9e6e1af060017709b32']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Arable',
    },
    name='Middle Hundred-Years War English  1350 to 1414 AD',
    id='5fb1b9e6e1af060017709b32',
    dateRange={
      startDate=1350,
      endDate=1414,
    },
  },
  g_base_definitions[g_str_68c995df579163001588a309_general],
  g_base_definitions[g_str_68c995df579163001588a309_general_mounted],
  g_base_definitions[g_str_68c995df579163001588a309_general_dismounted],
  g_base_definitions[g_str_68c995df579163001588a309],
  g_base_definitions[g_str_68c995df579163001588a309_mounted],
  g_base_definitions[g_str_68c995df579163001588a309_dismounted],
  g_base_definitions[g_str_68c995df579163001588a30c],
  g_base_definitions[g_str_68c995df579163001588a30e],
  g_base_definitions[g_str_68c995df579163001588a30e_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995df579163001588a30e_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995df579163001588a311],
  g_base_definitions[g_str_68c995df579163001588a313],
  g_base_definitions[g_str_68c995df579163001588a315],
  g_base_definitions[g_str_68c995df579163001588a315_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995df579163001588a315_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b32_camp],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b32_camp_fortified],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b32_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e6e1af060017709b32"] = army["5fb1b9e6e1af060017709b32"]
if nil == armies["Embattled Isle"] then
  armies["Embattled Isle"] ={}
end
armies["Embattled Isle"]["Middle Hundred-Years War English  1350 to 1414 AD"] = army["5fb1b9e6e1af060017709b32"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Middle Hundred-Years War English  1350 to 1414 AD"] = army["5fb1b9e6e1af060017709b32"]
if nil == armies["Flower of Chivalry"] then
  armies["Flower of Chivalry"] ={}
end
armies["Flower of Chivalry"]["Middle Hundred-Years War English  1350 to 1414 AD"] = army["5fb1b9e6e1af060017709b32"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Middle Hundred-Years War English  1350 to 1414 AD"] = army["5fb1b9e6e1af060017709b32"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e6e1af060017709b32"] = {}
army_dates["5fb1b9e6e1af060017709b32"]["1350 AD to 1414 AD"] = {
  startDate=1350,
  endDate=1414
}
