-- 5fb1b9dfe1af0600177096e6 Hellenistic Bosporan  348 to 11 BC

army['5fb1b9dfe1af0600177096e6']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
    },
    name='Hellenistic Bosporan  348 to 11 BC',
    id='5fb1b9dfe1af0600177096e6',
    dateRange={
      startDate=-348,
      endDate=-11,
    },
  },
  g_base_definitions[g_str_68c995d8579163001588935c_general],
  g_base_definitions[g_str_68c995d8579163001588935c],
  g_base_definitions[g_str_68c995d8579163001588935e],
  g_base_definitions[g_str_68c995d85791630015889361],
  g_base_definitions[g_str_68c995d85791630015889364],
  g_base_definitions[g_str_68c995d85791630015889365],
  g_base_definitions[g_str_68c995d85791630015889367],
  g_base_definitions[g_str_68c995d85791630015889369],
  g_base_definitions[g_str_68c995d85791630015889369_shower_shooting],
  g_base_definitions[g_str_68c995d8579163001588936c],
  g_base_definitions[g_str_68c995d8579163001588936e],
  g_base_definitions[g_str_5fb1b9dfe1af0600177096e6_camp],
  g_base_definitions[g_str_5fb1b9dfe1af0600177096e6_camp_fortified],
  g_base_definitions[g_str_68c995c7579163001588706a],
  g_base_definitions[g_str_68c995c7579163001588706c],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dfe1af0600177096e6"] = army["5fb1b9dfe1af0600177096e6"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Hellenistic Bosporan  348 to 11 BC"] = army["5fb1b9dfe1af0600177096e6"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Hellenistic Bosporan  348 to 11 BC"] = army["5fb1b9dfe1af0600177096e6"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Hellenistic Bosporan  348 to 11 BC"] = army["5fb1b9dfe1af0600177096e6"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Hellenistic Bosporan  348 to 11 BC"] = army["5fb1b9dfe1af0600177096e6"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dfe1af0600177096e6"] = {}
army_dates["5fb1b9dfe1af0600177096e6"]["348 BC to 11 BC"] = {
  startDate=-348,
  endDate=-11
}
army_dates["5fb1b9dfe1af0600177096e6"]["348 BC to 311 BC"] = {
  startDate=-348,
  endDate=-311
}
army_dates["5fb1b9dfe1af0600177096e6"]["310 BC"] = {
  startDate=-310,
  endDate=-310
}
army_dates["5fb1b9dfe1af0600177096e6"]["309 BC to 300 BC"] = {
  startDate=-309,
  endDate=-300
}
army_dates["5fb1b9dfe1af0600177096e6"]["299 BC to 146 BC"] = {
  startDate=-299,
  endDate=-146
}
army_dates["5fb1b9dfe1af0600177096e6"]["145 BC to 11 BC"] = {
  startDate=-145,
  endDate=-11
}
