-- 5fb1b9dbe1af060017709471 Napata Kushite  1068 to 746 BC

army['5fb1b9dbe1af060017709471']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Dry',
    },
    name='Napata Kushite  1068 to 746 BC',
    id='5fb1b9dbe1af060017709471',
    dateRange={
      startDate=-1068,
      endDate=-746,
    },
  },
  g_base_definitions[g_str_68c995d55791630015888a1f_general],
  g_base_definitions[g_str_68c995d55791630015888a1f],
  g_base_definitions[g_str_68c995d55791630015888a22],
  g_base_definitions[g_str_68c995d55791630015888a24],
  g_base_definitions[g_str_68c995d55791630015888a25],
  g_base_definitions[g_str_68c995d55791630015888a27],
  g_base_definitions[g_str_68c995d55791630015888a29],
  g_base_definitions[g_str_5fb1b9dbe1af060017709471_camp],
  g_base_definitions[g_str_5fb1b9dbe1af060017709471_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dbe1af060017709471"] = army["5fb1b9dbe1af060017709471"]
if nil == armies["Chariot Supremacy"] then
  armies["Chariot Supremacy"] ={}
end
armies["Chariot Supremacy"]["Napata Kushite  1068 to 746 BC"] = army["5fb1b9dbe1af060017709471"]
if nil == armies["Assyrian Empire"] then
  armies["Assyrian Empire"] ={}
end
armies["Assyrian Empire"]["Napata Kushite  1068 to 746 BC"] = army["5fb1b9dbe1af060017709471"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Napata Kushite  1068 to 746 BC"] = army["5fb1b9dbe1af060017709471"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dbe1af060017709471"] = {}
army_dates["5fb1b9dbe1af060017709471"]["1068 BC to 746 BC"] = {
  startDate=-1068,
  endDate=-746
}
