-- 5fb1b9e2e1af0600177098fa Burgundi or Limigantes  250 to 534 AD

army['5fb1b9e2e1af0600177098fa']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Forest',
      'Arable',
    },
    name='Burgundi or Limigantes  250 to 534 AD',
    id='5fb1b9e2e1af0600177098fa',
    dateRange={
      startDate=250,
      endDate=534,
    },
  },
  g_base_definitions[g_str_68c995db5791630015889b51_general],
  g_base_definitions[g_str_68c995db5791630015889b51],
  g_base_definitions[g_str_68c995db5791630015889b53_general],
  g_base_definitions[g_str_68c995db5791630015889b53],
  g_base_definitions[g_str_68c995db5791630015889b55],
  g_base_definitions[g_str_68c995db5791630015889b57],
  g_base_definitions[g_str_5fb1b9e2e1af0600177098fa_camp],
  g_base_definitions[g_str_5fb1b9e2e1af0600177098fa_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e2e1af0600177098fa"] = army["5fb1b9e2e1af0600177098fa"]
if nil == armies["Pax Romana"] then
  armies["Pax Romana"] ={}
end
armies["Pax Romana"]["Burgundi or Limigantes  250 to 534 AD"] = army["5fb1b9e2e1af0600177098fa"]
if nil == armies["Fall of Rome"] then
  armies["Fall of Rome"] ={}
end
armies["Fall of Rome"]["Burgundi or Limigantes  250 to 534 AD"] = army["5fb1b9e2e1af0600177098fa"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Burgundi or Limigantes  250 to 534 AD"] = army["5fb1b9e2e1af0600177098fa"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e2e1af0600177098fa"] = {}
army_dates["5fb1b9e2e1af0600177098fa"]["250 AD to 534 AD"] = {
  startDate=250,
  endDate=534
}
army_dates["5fb1b9e2e1af0600177098fa"]["250 AD to 443 AD"] = {
  startDate=250,
  endDate=443
}
army_dates["5fb1b9e2e1af0600177098fa"]["444 AD to 534 AD"] = {
  startDate=444,
  endDate=534
}
