-- 5fb1b9dae1af060017709418 Phrygian  850 to 676 BC

army['5fb1b9dae1af060017709418']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Phrygian  850 to 676 BC',
    id='5fb1b9dae1af060017709418',
    dateRange={
      startDate=-850,
      endDate=-676,
    },
  },
  g_base_definitions[g_str_68c995d45791630015888887_general],
  g_base_definitions[g_str_68c995d45791630015888887],
  g_base_definitions[g_str_68c995d45791630015888889],
  g_base_definitions[g_str_68c995d4579163001588888b],
  g_base_definitions[g_str_68c995d4579163001588888d],
  g_base_definitions[g_str_68c995d4579163001588888f],
  g_base_definitions[g_str_68c995d45791630015888890],
  g_base_definitions[g_str_5fb1b9dae1af060017709418_camp],
  g_base_definitions[g_str_5fb1b9dae1af060017709418_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dae1af060017709418"] = army["5fb1b9dae1af060017709418"]
if nil == armies["Assyrian Empire"] then
  armies["Assyrian Empire"] ={}
end
armies["Assyrian Empire"]["Phrygian  850 to 676 BC"] = army["5fb1b9dae1af060017709418"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Phrygian  850 to 676 BC"] = army["5fb1b9dae1af060017709418"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dae1af060017709418"] = {}
army_dates["5fb1b9dae1af060017709418"]["850 BC to 676 BC"] = {
  startDate=-850,
  endDate=-676
}
army_dates["5fb1b9dae1af060017709418"]["850 BC to 723 BC"] = {
  startDate=-850,
  endDate=-723
}
army_dates["5fb1b9dae1af060017709418"]["722 BC to 676 BC"] = {
  startDate=-722,
  endDate=-676
}
