-- 5fb1b9e7e1af060017709be7 Emirate of Granada  1228 to 1492 AD

army['5fb1b9e7e1af060017709be7']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      4,
    },
    homeTopographies={
      'Hilly',
    },
    name='Emirate of Granada  1228 to 1492 AD',
    id='5fb1b9e7e1af060017709be7',
    dateRange={
      startDate=1228,
      endDate=1492,
    },
  },
  g_base_definitions[g_str_68c995df579163001588a523_general],
  g_base_definitions[g_str_68c995df579163001588a523],
  g_base_definitions[g_str_68c995df579163001588a526_general],
  g_base_definitions[g_str_68c995df579163001588a526],
  g_base_definitions[g_str_68c995df579163001588a528_general],
  g_base_definitions[g_str_68c995df579163001588a528],
  g_base_definitions[g_str_68c995df579163001588a52a],
  g_base_definitions[g_str_68c995df579163001588a52c],
  g_base_definitions[g_str_68c995df579163001588a52e],
  g_base_definitions[g_str_68c995df579163001588a530],
  g_base_definitions[g_str_68c995df579163001588a532],
  g_base_definitions[g_str_68c995df579163001588a532_shower_shooting],
  g_base_definitions[g_str_68c995df579163001588a535],
  g_base_definitions[g_str_68c995df579163001588a538],
  g_base_definitions[g_str_5fb1b9e7e1af060017709be7_camp],
  g_base_definitions[g_str_5fb1b9e7e1af060017709be7_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e7e1af060017709be7"] = army["5fb1b9e7e1af060017709be7"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Emirate of Granada  1228 to 1492 AD"] = army["5fb1b9e7e1af060017709be7"]
if nil == armies["Plate and Handgonne"] then
  armies["Plate and Handgonne"] ={}
end
armies["Plate and Handgonne"]["Emirate of Granada  1228 to 1492 AD"] = army["5fb1b9e7e1af060017709be7"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Emirate of Granada  1228 to 1492 AD"] = army["5fb1b9e7e1af060017709be7"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e7e1af060017709be7"] = {}
army_dates["5fb1b9e7e1af060017709be7"]["1228 AD to 1492 AD"] = {
  startDate=1228,
  endDate=1492
}
army_dates["5fb1b9e7e1af060017709be7"]["1228 AD to 1243 AD"] = {
  startDate=1228,
  endDate=1243
}
army_dates["5fb1b9e7e1af060017709be7"]["1244 AD to 1340 AD"] = {
  startDate=1244,
  endDate=1340
}
army_dates["5fb1b9e7e1af060017709be7"]["1341 AD to 1492 AD"] = {
  startDate=1341,
  endDate=1492
}
