-- 5fb1b9dbe1af0600177094fb Early Hoplite Greek  669 to 449 BC

army['5fb1b9dbe1af0600177094fb']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
      'Hilly',
    },
    name='Early Hoplite Greek  669 to 449 BC',
    id='5fb1b9dbe1af0600177094fb',
    dateRange={
      startDate=-669,
      endDate=-449,
    },
  },
  g_base_definitions[g_str_68c995d55791630015888bb1_general],
  g_base_definitions[g_str_68c995d55791630015888bb1],
  g_base_definitions[g_str_68c995d55791630015888bb3],
  g_base_definitions[g_str_68c995d55791630015888bb5],
  g_base_definitions[g_str_5fb1b9dbe1af0600177094fb_camp],
  g_base_definitions[g_str_68c995c55791630015886d67],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dbe1af0600177094fb"] = army["5fb1b9dbe1af0600177094fb"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Early Hoplite Greek  669 to 449 BC"] = army["5fb1b9dbe1af0600177094fb"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Hoplite Greek  669 to 449 BC"] = army["5fb1b9dbe1af0600177094fb"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dbe1af0600177094fb"] = {}
army_dates["5fb1b9dbe1af0600177094fb"]["669 BC to 449 BC"] = {
  startDate=-669,
  endDate=-449
}
army_dates["5fb1b9dbe1af0600177094fb"]["669 BC to 511 BC"] = {
  startDate=-669,
  endDate=-511
}
army_dates["5fb1b9dbe1af0600177094fb"]["510 BC to 449 BC"] = {
  startDate=-510,
  endDate=-449
}
