-- 5fb1b9dbe1af060017709491 Urnfield Culture  1400 to 700 BC

army['5fb1b9dbe1af060017709491']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Forest',
    },
    name='Urnfield Culture  1400 to 700 BC',
    id='5fb1b9dbe1af060017709491',
    dateRange={
      startDate=-1400,
      endDate=-700,
    },
  },
  g_base_definitions[g_str_68c995d55791630015888a84_general],
  g_base_definitions[g_str_68c995d55791630015888a84],
  g_base_definitions[g_str_68c995d55791630015888a86],
  g_base_definitions[g_str_68c995d55791630015888a88],
  g_base_definitions[g_str_68c995d55791630015888a8a],
  g_base_definitions[g_str_68c995d55791630015888a8c],
  g_base_definitions[g_str_5fb1b9dbe1af060017709491_camp],
  g_base_definitions[g_str_5fb1b9dbe1af060017709491_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dbe1af060017709491"] = army["5fb1b9dbe1af060017709491"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Urnfield Culture  1400 to 700 BC"] = army["5fb1b9dbe1af060017709491"]
if nil == armies["Sea Peoples Invasions"] then
  armies["Sea Peoples Invasions"] ={}
end
armies["Sea Peoples Invasions"]["Urnfield Culture  1400 to 700 BC"] = army["5fb1b9dbe1af060017709491"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Urnfield Culture  1400 to 700 BC"] = army["5fb1b9dbe1af060017709491"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dbe1af060017709491"] = {}
army_dates["5fb1b9dbe1af060017709491"]["1400 BC to 700 BC"] = {
  startDate=-1400,
  endDate=-700
}
