-- 5fb1b9eae1af060017709d8c Wallachian or Moldavian  1330 to 1517 AD

army['5fb1b9eae1af060017709d8c']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      4,
    },
    homeTopographies={
      'Forest',
    },
    name='Wallachian or Moldavian  1330 to 1517 AD',
    id='5fb1b9eae1af060017709d8c',
    dateRange={
      startDate=1330,
      endDate=1517,
    },
    ambush=true,  },
  g_base_definitions[g_str_68c995e1579163001588ac3f_general],
  g_base_definitions[g_str_68c995e1579163001588ac3f],
  g_base_definitions[g_str_68c995e1579163001588ac42],
  g_base_definitions[g_str_68c995e1579163001588ac45],
  g_base_definitions[g_str_68c995e1579163001588ac47],
  g_base_definitions[g_str_68c995e1579163001588ac49],
  g_base_definitions[g_str_68c995e1579163001588ac4b],
  g_base_definitions[g_str_68c995e1579163001588ac4b_shower_shooting],
  g_base_definitions[g_str_68c995e1579163001588ac4e],
  g_base_definitions[g_str_68c995e1579163001588ac4e_shower_shooting],
  g_base_definitions[g_str_68c995e1579163001588ac4f],
  g_base_definitions[g_str_68c995e1579163001588ac4f_shower_shooting],
  g_base_definitions[g_str_68c995e1579163001588ac52],
  g_base_definitions[g_str_68c995e1579163001588ac53],
  g_base_definitions[g_str_68c995e1579163001588ac55],
  g_base_definitions[g_str_68c995e1579163001588ac58],
  g_base_definitions[g_str_5fb1b9eae1af060017709d8c_camp],
  g_base_definitions[g_str_5fb1b9eae1af060017709d8c_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eae1af060017709d8c"] = army["5fb1b9eae1af060017709d8c"]
if nil == armies["Italy and Balkans"] then
  armies["Italy and Balkans"] ={}
end
armies["Italy and Balkans"]["Wallachian or Moldavian  1330 to 1517 AD"] = army["5fb1b9eae1af060017709d8c"]
if nil == armies["Russian Princes"] then
  armies["Russian Princes"] ={}
end
armies["Russian Princes"]["Wallachian or Moldavian  1330 to 1517 AD"] = army["5fb1b9eae1af060017709d8c"]
if nil == armies["Byzantium in Decay"] then
  armies["Byzantium in Decay"] ={}
end
armies["Byzantium in Decay"]["Wallachian or Moldavian  1330 to 1517 AD"] = army["5fb1b9eae1af060017709d8c"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Wallachian or Moldavian  1330 to 1517 AD"] = army["5fb1b9eae1af060017709d8c"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eae1af060017709d8c"] = {}
army_dates["5fb1b9eae1af060017709d8c"]["1330 AD to 1517 AD"] = {
  startDate=1330,
  endDate=1517
}
army_dates["5fb1b9eae1af060017709d8c"]["1330 AD to 1334 AD"] = {
  startDate=1330,
  endDate=1334
}
army_dates["5fb1b9eae1af060017709d8c"]["1335 AD to 1361 AD"] = {
  startDate=1335,
  endDate=1361
}
army_dates["5fb1b9eae1af060017709d8c"]["1362 AD to 1441 AD"] = {
  startDate=1362,
  endDate=1441
}
army_dates["5fb1b9eae1af060017709d8c"]["1442 AD to 1494 AD"] = {
  startDate=1442,
  endDate=1494
}
army_dates["5fb1b9eae1af060017709d8c"]["1495 AD to 1515 AD"] = {
  startDate=1495,
  endDate=1515
}
army_dates["5fb1b9eae1af060017709d8c"]["1516 AD to 1517 AD"] = {
  startDate=1516,
  endDate=1517
}
