-- 5fb1b9e6e1af060017709b2a Early Hundred-Years War English  1322 to 1349 AD

army['5fb1b9e6e1af060017709b2a']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Arable',
    },
    name='Early Hundred-Years War English  1322 to 1349 AD',
    id='5fb1b9e6e1af060017709b2a',
    dateRange={
      startDate=1322,
      endDate=1349,
    },
  },
  g_base_definitions[g_str_68c995df579163001588a2ed_general],
  g_base_definitions[g_str_68c995df579163001588a2ed_general_mounted],
  g_base_definitions[g_str_68c995df579163001588a2ed_general_dismounted],
  g_base_definitions[g_str_68c995df579163001588a2ed],
  g_base_definitions[g_str_68c995df579163001588a2ed_mounted],
  g_base_definitions[g_str_68c995df579163001588a2ed_dismounted],
  g_base_definitions[g_str_68c995df579163001588a2f0],
  g_base_definitions[g_str_68c995df579163001588a2f0_mounted],
  g_base_definitions[g_str_68c995df579163001588a2f0_dismounted],
  g_base_definitions[g_str_68c995df579163001588a2f3],
  g_base_definitions[g_str_68c995df579163001588a2f5],
  g_base_definitions[g_str_68c995df579163001588a2f5_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995df579163001588a2f5_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995df579163001588a2f8],
  g_base_definitions[g_str_68c995df579163001588a2fa],
  g_base_definitions[g_str_68c995df579163001588a2fc],
  g_base_definitions[g_str_68c995df579163001588a2fc_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995df579163001588a2fc_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b2a_camp],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b2a_camp_fortified],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b2a_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e6e1af060017709b2a"] = army["5fb1b9e6e1af060017709b2a"]
if nil == armies["Embattled Isle"] then
  armies["Embattled Isle"] ={}
end
armies["Embattled Isle"]["Early Hundred-Years War English  1322 to 1349 AD"] = army["5fb1b9e6e1af060017709b2a"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Early Hundred-Years War English  1322 to 1349 AD"] = army["5fb1b9e6e1af060017709b2a"]
if nil == armies["Flower of Chivalry"] then
  armies["Flower of Chivalry"] ={}
end
armies["Flower of Chivalry"]["Early Hundred-Years War English  1322 to 1349 AD"] = army["5fb1b9e6e1af060017709b2a"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Hundred-Years War English  1322 to 1349 AD"] = army["5fb1b9e6e1af060017709b2a"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e6e1af060017709b2a"] = {}
army_dates["5fb1b9e6e1af060017709b2a"]["1322 AD to 1349 AD"] = {
  startDate=1322,
  endDate=1349
}
army_dates["5fb1b9e6e1af060017709b2a"]["1322 AD to 1338 AD"] = {
  startDate=1322,
  endDate=1338
}
army_dates["5fb1b9e6e1af060017709b2a"]["1339 AD"] = {
  startDate=1339,
  endDate=1339
}
army_dates["5fb1b9e6e1af060017709b2a"]["1340 AD"] = {
  startDate=1340,
  endDate=1340
}
army_dates["5fb1b9e6e1af060017709b2a"]["1341 AD to 1349 AD"] = {
  startDate=1341,
  endDate=1349
}
