-- 5fb1b9ece1af060017709edd Christian Nubian  550 to 1500 AD

army['5fb1b9ece1af060017709edd']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Dry',
    },
    name='Christian Nubian  550 to 1500 AD',
    id='5fb1b9ece1af060017709edd',
    dateRange={
      startDate=550,
      endDate=1500,
    },
  },
  g_base_definitions[g_str_68c995e4579163001588b212_general],
  g_base_definitions[g_str_68c995e4579163001588b212],
  g_base_definitions[g_str_68c995e4579163001588b214_general],
  g_base_definitions[g_str_68c995e4579163001588b214],
  g_base_definitions[g_str_68c995e4579163001588b216],
  g_base_definitions[g_str_68c995e4579163001588b216_light_camelry],
  g_base_definitions[g_str_68c995e4579163001588b219],
  g_base_definitions[g_str_68c995e4579163001588b219_light_camelry],
  g_base_definitions[g_str_68c995e4579163001588b21c],
  g_base_definitions[g_str_68c995e4579163001588b21c_shower_shooting],
  g_base_definitions[g_str_68c995e4579163001588b21d],
  g_base_definitions[g_str_68c995e4579163001588b21d_shower_shooting],
  g_base_definitions[g_str_68c995e4579163001588b220],
  g_base_definitions[g_str_68c995e4579163001588b222],
  g_base_definitions[g_str_68c995e4579163001588b223],
  g_base_definitions[g_str_68c995e4579163001588b225],
  g_base_definitions[g_str_5fb1b9ece1af060017709edd_camp],
  g_base_definitions[g_str_5fb1b9ece1af060017709edd_camp_fortified],
  g_base_definitions[g_str_5fb1b9ece1af060017709edd_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ece1af060017709edd"] = army["5fb1b9ece1af060017709edd"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Christian Nubian  550 to 1500 AD"] = army["5fb1b9ece1af060017709edd"]
if nil == armies["Spread of Islam"] then
  armies["Spread of Islam"] ={}
end
armies["Spread of Islam"]["Christian Nubian  550 to 1500 AD"] = army["5fb1b9ece1af060017709edd"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Christian Nubian  550 to 1500 AD"] = army["5fb1b9ece1af060017709edd"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ece1af060017709edd"] = {}
army_dates["5fb1b9ece1af060017709edd"]["550 AD to 1500 AD"] = {
  startDate=550,
  endDate=1500
}
army_dates["5fb1b9ece1af060017709edd"]["550 AD to 1174 AD"] = {
  startDate=550,
  endDate=1174
}
army_dates["5fb1b9ece1af060017709edd"]["1175 AD to 1249 AD"] = {
  startDate=1175,
  endDate=1249
}
army_dates["5fb1b9ece1af060017709edd"]["1250 AD to 1275 AD"] = {
  startDate=1250,
  endDate=1275
}
army_dates["5fb1b9ece1af060017709edd"]["1276 AD to 1365 AD"] = {
  startDate=1276,
  endDate=1365
}
army_dates["5fb1b9ece1af060017709edd"]["1366 AD to 1500 AD"] = {
  startDate=1366,
  endDate=1500
}
