-- 5fb1b9f6e1af06001770a4a3 Tupi  1200 to 1580 AD

army['5fb1b9f6e1af06001770a4a3']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Forest',
    },
    name='Tupi  1200 to 1580 AD',
    id='5fb1b9f6e1af06001770a4a3',
    dateRange={
      startDate=1200,
      endDate=1580,
    },
    ambush=true,  },
  g_base_definitions[g_str_68c995eb579163001588c637],
  g_base_definitions[g_str_68c995eb579163001588c639_general],
  g_base_definitions[g_str_68c995eb579163001588c639],
  g_base_definitions[g_str_68c995eb579163001588c63b],
  g_base_definitions[g_str_5fb1b9f6e1af06001770a4a3_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f6e1af06001770a4a3"] = army["5fb1b9f6e1af06001770a4a3"]
if nil == armies["Andes and Amazon"] then
  armies["Andes and Amazon"] ={}
end
armies["Andes and Amazon"]["Tupi  1200 to 1580 AD"] = army["5fb1b9f6e1af06001770a4a3"]
if nil == armies["Caribbean"] then
  armies["Caribbean"] ={}
end
armies["Caribbean"]["Tupi  1200 to 1580 AD"] = army["5fb1b9f6e1af06001770a4a3"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Tupi  1200 to 1580 AD"] = army["5fb1b9f6e1af06001770a4a3"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f6e1af06001770a4a3"] = {}
army_dates["5fb1b9f6e1af06001770a4a3"]["1200 AD to 1580 AD"] = {
  startDate=1200,
  endDate=1580
}
