-- 5fb1b9e6e1af060017709b7d Fante and Gold Coast Peoples  800 to 1600 AD

army['5fb1b9e6e1af060017709b7d']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Forest',
    },
    name='Fante and Gold Coast Peoples  800 to 1600 AD',
    id='5fb1b9e6e1af060017709b7d',
    dateRange={
      startDate=800,
      endDate=1600,
    },
  },
  g_base_definitions[g_str_68c995df579163001588a3db_general],
  g_base_definitions[g_str_68c995df579163001588a3db],
  g_base_definitions[g_str_68c995df579163001588a3dd],
  g_base_definitions[g_str_68c995df579163001588a3df],
  g_base_definitions[g_str_68c995df579163001588a3e1],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b7d_camp],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b7d_camp_fortified],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b7d_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e6e1af060017709b7d"] = army["5fb1b9e6e1af060017709b7d"]
if nil == armies["Sahel Africa"] then
  armies["Sahel Africa"] ={}
end
armies["Sahel Africa"]["Fante and Gold Coast Peoples  800 to 1600 AD"] = army["5fb1b9e6e1af060017709b7d"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Fante and Gold Coast Peoples  800 to 1600 AD"] = army["5fb1b9e6e1af060017709b7d"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e6e1af060017709b7d"] = {}
army_dates["5fb1b9e6e1af060017709b7d"]["800 AD to 1600 AD"] = {
  startDate=800,
  endDate=1600
}
