-- 5fb1b9ede1af060017709f35 Iqshidid Egyptian  935 to 970 AD

army['5fb1b9ede1af060017709f35']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Delta',
      'Dry',
    },
    name='Iqshidid Egyptian  935 to 970 AD',
    id='5fb1b9ede1af060017709f35',
    dateRange={
      startDate=935,
      endDate=970,
    },
  },
  g_base_definitions[g_str_68c995e4579163001588b3a6_general],
  g_base_definitions[g_str_68c995e4579163001588b3a6_general_mounted],
  g_base_definitions[g_str_68c995e4579163001588b3a6_general_dismounted],
  g_base_definitions[g_str_68c995e4579163001588b3a6_general_shower_shooting],
  g_base_definitions[g_str_68c995e4579163001588b3a6],
  g_base_definitions[g_str_68c995e4579163001588b3a6_mounted],
  g_base_definitions[g_str_68c995e4579163001588b3a6_dismounted],
  g_base_definitions[g_str_68c995e4579163001588b3a6_shower_shooting],
  g_base_definitions[g_str_68c995e4579163001588b3aa],
  g_base_definitions[g_str_68c995e4579163001588b3ac],
  g_base_definitions[g_str_68c995e4579163001588b3ac_shower_shooting],
  g_base_definitions[g_str_68c995e4579163001588b3af],
  g_base_definitions[g_str_68c995e4579163001588b3b0],
  g_base_definitions[g_str_68c995e4579163001588b3b2],
  g_base_definitions[g_str_68c995e4579163001588b3b4],
  g_base_definitions[g_str_68c995e4579163001588b3b6],
  g_base_definitions[g_str_5fb1b9ede1af060017709f35_camp],
  g_base_definitions[g_str_5fb1b9ede1af060017709f35_camp_fortified],
  g_base_definitions[g_str_5fb1b9ede1af060017709f35_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ede1af060017709f35"] = army["5fb1b9ede1af060017709f35"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Iqshidid Egyptian  935 to 970 AD"] = army["5fb1b9ede1af060017709f35"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Iqshidid Egyptian  935 to 970 AD"] = army["5fb1b9ede1af060017709f35"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ede1af060017709f35"] = {}
army_dates["5fb1b9ede1af060017709f35"]["935 AD to 970 AD"] = {
  startDate=935,
  endDate=970
}
army_dates["5fb1b9ede1af060017709f35"]["935 AD to 969 AD"] = {
  startDate=935,
  endDate=969
}
army_dates["5fb1b9ede1af060017709f35"]["970 AD"] = {
  startDate=970,
  endDate=970
}
