-- 5fb1b9dee1af060017709698 Later Hellenistic Achaean  207 to 146 BC

army['5fb1b9dee1af060017709698']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Later Hellenistic Achaean  207 to 146 BC',
    id='5fb1b9dee1af060017709698',
    dateRange={
      startDate=-207,
      endDate=-146,
    },
  },
  g_base_definitions[g_str_68c995d8579163001588924c_general],
  g_base_definitions[g_str_68c995d8579163001588924c],
  g_base_definitions[g_str_68c995d8579163001588924e],
  g_base_definitions[g_str_68c995d85791630015889250],
  g_base_definitions[g_str_68c995d85791630015889252],
  g_base_definitions[g_str_68c995d85791630015889254],
  g_base_definitions[g_str_68c995d85791630015889256],
  g_base_definitions[g_str_68c995d85791630015889258],
  g_base_definitions[g_str_68c995d8579163001588925a],
  g_base_definitions[g_str_68c995d8579163001588925b],
  g_base_definitions[g_str_5fb1b9dee1af060017709698_camp],
  g_base_definitions[g_str_5fb1b9dee1af060017709698_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dee1af060017709698"] = army["5fb1b9dee1af060017709698"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Later Hellenistic Achaean  207 to 146 BC"] = army["5fb1b9dee1af060017709698"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Hellenistic Achaean  207 to 146 BC"] = army["5fb1b9dee1af060017709698"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dee1af060017709698"] = {}
army_dates["5fb1b9dee1af060017709698"]["207 BC to 146 BC"] = {
  startDate=-207,
  endDate=-146
}
