-- 5fb1b9ece1af060017709eec Early Arab Conquest  631 to 638 AD

army['5fb1b9ece1af060017709eec']={
  data={
    invasionRatings={
      4,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Dry',
    },
    name='Early Arab Conquest  631 to 638 AD',
    id='5fb1b9ece1af060017709eec',
    dateRange={
      startDate=631,
      endDate=638,
    },
  },
  g_base_definitions[g_str_68c995e4579163001588b24b_general],
  g_base_definitions[g_str_68c995e4579163001588b24b_general_mounted],
  g_base_definitions[g_str_68c995e4579163001588b24b_general_dismounted],
  g_base_definitions[g_str_68c995e4579163001588b24b],
  g_base_definitions[g_str_68c995e4579163001588b24b_mounted],
  g_base_definitions[g_str_68c995e4579163001588b24b_dismounted],
  g_base_definitions[g_str_68c995e4579163001588b24e],
  g_base_definitions[g_str_68c995e4579163001588b24e_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b24e_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b252_general],
  g_base_definitions[g_str_68c995e4579163001588b252_general_mounted],
  g_base_definitions[g_str_68c995e4579163001588b252_general_dismounted],
  g_base_definitions[g_str_68c995e4579163001588b252],
  g_base_definitions[g_str_68c995e4579163001588b252_mounted],
  g_base_definitions[g_str_68c995e4579163001588b252_dismounted],
  g_base_definitions[g_str_68c995e4579163001588b255],
  g_base_definitions[g_str_68c995e4579163001588b255_light_camelry],
  g_base_definitions[g_str_68c995e4579163001588b258],
  g_base_definitions[g_str_68c995e4579163001588b258_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b258_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b25b],
  g_base_definitions[g_str_68c995e4579163001588b25b_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b25b_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b25f],
  g_base_definitions[g_str_68c995e4579163001588b25f_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b25f_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b263],
  g_base_definitions[g_str_68c995e4579163001588b263_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b263_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b266],
  g_base_definitions[g_str_68c995e4579163001588b266_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b266_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b269],
  g_base_definitions[g_str_68c995e4579163001588b269_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e4579163001588b269_dismounted_mobile_infantry],
  g_base_definitions[g_str_5fb1b9ece1af060017709eec_camp],
  g_base_definitions[g_str_5fb1b9ece1af060017709eec_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ece1af060017709eec"] = army["5fb1b9ece1af060017709eec"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Early Arab Conquest  631 to 638 AD"] = army["5fb1b9ece1af060017709eec"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Early Arab Conquest  631 to 638 AD"] = army["5fb1b9ece1af060017709eec"]
if nil == armies["Spread of Islam"] then
  armies["Spread of Islam"] ={}
end
armies["Spread of Islam"]["Early Arab Conquest  631 to 638 AD"] = army["5fb1b9ece1af060017709eec"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Arab Conquest  631 to 638 AD"] = army["5fb1b9ece1af060017709eec"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ece1af060017709eec"] = {}
army_dates["5fb1b9ece1af060017709eec"]["631 AD to 638 AD"] = {
  startDate=631,
  endDate=638
}
army_dates["5fb1b9ece1af060017709eec"]["631 AD to 632 AD"] = {
  startDate=631,
  endDate=632
}
army_dates["5fb1b9ece1af060017709eec"]["633 AD to 638 AD"] = {
  startDate=633,
  endDate=638
}
