-- 5fb1b9f2e1af06001770a238 Western Jin Invasion of Wu in 279 AD  279 to 279 AD

army['5fb1b9f2e1af06001770a238']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
    },
    name='Western Jin Invasion of Wu in 279 AD  279 to 279 AD',
    id='5fb1b9f2e1af06001770a238',
    dateRange={
      startDate=279,
      endDate=279,
    },
  },
  g_base_definitions[g_str_68c995e8579163001588bf25_general],
  g_base_definitions[g_str_68c995e8579163001588bf25],
  g_base_definitions[g_str_68c995e8579163001588bf26_general],
  g_base_definitions[g_str_68c995e8579163001588bf26],
  g_base_definitions[g_str_68c995e8579163001588bf28_general],
  g_base_definitions[g_str_68c995e8579163001588bf28],
  g_base_definitions[g_str_68c995e8579163001588bf2a_general],
  g_base_definitions[g_str_68c995e8579163001588bf2a],
  g_base_definitions[g_str_68c995e8579163001588bf2c_general],
  g_base_definitions[g_str_68c995e8579163001588bf2c],
  g_base_definitions[g_str_68c995e8579163001588bf2e],
  g_base_definitions[g_str_68c995e8579163001588bf30],
  g_base_definitions[g_str_68c995e8579163001588bf32],
  g_base_definitions[g_str_68c995e8579163001588bf34],
  g_base_definitions[g_str_68c995e8579163001588bf36],
  g_base_definitions[g_str_68c995e8579163001588bf38],
  g_base_definitions[g_str_68c995e8579163001588bf3a],
  g_base_definitions[g_str_68c995e8579163001588bf3b],
  g_base_definitions[g_str_5fb1b9f2e1af06001770a238_camp],
  g_base_definitions[g_str_5fb1b9f2e1af06001770a238_camp_fortified],
  g_base_definitions[g_str_5fb1b9f2e1af06001770a238_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f2e1af06001770a238"] = army["5fb1b9f2e1af06001770a238"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Western Jin Invasion of Wu in 279 AD  279 to 279 AD"] = army["5fb1b9f2e1af06001770a238"]
if nil == armies["Dark Ages China"] then
  armies["Dark Ages China"] ={}
end
armies["Dark Ages China"]["Western Jin Invasion of Wu in 279 AD  279 to 279 AD"] = army["5fb1b9f2e1af06001770a238"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Western Jin Invasion of Wu in 279 AD  279 to 279 AD"] = army["5fb1b9f2e1af06001770a238"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f2e1af06001770a238"] = {}
army_dates["5fb1b9f2e1af06001770a238"]["279 AD"] = {
  startDate=279,
  endDate=279
}
