-- 5fb1b9e3e1af06001770997a Army of Attila  433 to 453 AD

army['5fb1b9e3e1af06001770997a']={
  data={
    invasionRatings={
      4,
    },
    maneuverRatings={
      4,
    },
    homeTopographies={
      'Steppe',
    },
    name='Army of Attila  433 to 453 AD',
    id='5fb1b9e3e1af06001770997a',
    dateRange={
      startDate=433,
      endDate=453,
    },
  },
  g_base_definitions[g_str_68c995dc5791630015889ceb_general],
  g_base_definitions[g_str_68c995dc5791630015889ceb],
  g_base_definitions[g_str_68c995dc5791630015889ced_general],
  g_base_definitions[g_str_68c995dc5791630015889ced],
  g_base_definitions[g_str_68c995dc5791630015889cef],
  g_base_definitions[g_str_68c995dc5791630015889cf1],
  g_base_definitions[g_str_68c995dc5791630015889cf3],
  g_base_definitions[g_str_68c995dc5791630015889cf5],
  g_base_definitions[g_str_68c995dc5791630015889cf5_shower_shooting],
  g_base_definitions[g_str_5fb1b9e3e1af06001770997a_camp],
  g_base_definitions[g_str_5fb1b9e3e1af06001770997a_camp_fortified],
  g_base_definitions[g_str_5fb1b9e3e1af06001770997a_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e3e1af06001770997a"] = army["5fb1b9e3e1af06001770997a"]
if nil == armies["Fall of Rome"] then
  armies["Fall of Rome"] ={}
end
armies["Fall of Rome"]["Army of Attila  433 to 453 AD"] = army["5fb1b9e3e1af06001770997a"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Army of Attila  433 to 453 AD"] = army["5fb1b9e3e1af06001770997a"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e3e1af06001770997a"] = {}
army_dates["5fb1b9e3e1af06001770997a"]["433 AD to 453 AD"] = {
  startDate=433,
  endDate=453
}
