-- 5fb1b9f1e1af06001770a18e Qin Collapse  209 to 206 BC

army['5fb1b9f1e1af06001770a18e']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Hilly',
      'Arable',
    },
    name='Qin Collapse  209 to 206 BC',
    id='5fb1b9f1e1af06001770a18e',
    dateRange={
      startDate=-209,
      endDate=-206,
    },
  },
  g_base_definitions[g_str_68c995e8579163001588bd00_general],
  g_base_definitions[g_str_68c995e8579163001588bd00],
  g_base_definitions[g_str_68c995e8579163001588bd02_general],
  g_base_definitions[g_str_68c995e8579163001588bd02_general_mounted],
  g_base_definitions[g_str_68c995e8579163001588bd02_general_dismounted],
  g_base_definitions[g_str_68c995e8579163001588bd02],
  g_base_definitions[g_str_68c995e8579163001588bd02_mounted],
  g_base_definitions[g_str_68c995e8579163001588bd02_dismounted],
  g_base_definitions[g_str_68c995e8579163001588bd05],
  g_base_definitions[g_str_68c995e8579163001588bd07],
  g_base_definitions[g_str_68c995e8579163001588bd09],
  g_base_definitions[g_str_68c995e8579163001588bd0b],
  g_base_definitions[g_str_68c995e8579163001588bd0e],
  g_base_definitions[g_str_68c995e8579163001588bd0e_shower_shooting],
  g_base_definitions[g_str_68c995e8579163001588bd11],
  g_base_definitions[g_str_68c995e8579163001588bd12],
  g_base_definitions[g_str_68c995e8579163001588bd14],
  g_base_definitions[g_str_68c995e8579163001588bd17],
  g_base_definitions[g_str_68c995e8579163001588bd19],
  g_base_definitions[g_str_68c995e8579163001588bd1b],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a18e_camp],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a18e_camp_fortified],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a18e_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f1e1af06001770a18e"] = army["5fb1b9f1e1af06001770a18e"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Qin Collapse  209 to 206 BC"] = army["5fb1b9f1e1af06001770a18e"]
if nil == armies["Warring States"] then
  armies["Warring States"] ={}
end
armies["Warring States"]["Qin Collapse  209 to 206 BC"] = army["5fb1b9f1e1af06001770a18e"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Qin Collapse  209 to 206 BC"] = army["5fb1b9f1e1af06001770a18e"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f1e1af06001770a18e"] = {}
army_dates["5fb1b9f1e1af06001770a18e"]["209 BC to 206 BC"] = {
  startDate=-209,
  endDate=-206
}
