-- 5fb1b9d8e1af0600177092f2 Amurru and Early Aramaean  2000 to 747 BC

army['5fb1b9d8e1af0600177092f2']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Dry',
    },
    name='Amurru and Early Aramaean  2000 to 747 BC',
    id='5fb1b9d8e1af0600177092f2',
    dateRange={
      startDate=-2000,
      endDate=-747,
    },
  },
  g_base_definitions[g_str_68c995d25791630015888431_general],
  g_base_definitions[g_str_68c995d25791630015888431],
  g_base_definitions[g_str_68c995d25791630015888432_general],
  g_base_definitions[g_str_68c995d25791630015888432],
  g_base_definitions[g_str_68c995d25791630015888434_general],
  g_base_definitions[g_str_68c995d25791630015888434],
  g_base_definitions[g_str_68c995d25791630015888438],
  g_base_definitions[g_str_68c995d2579163001588843b],
  g_base_definitions[g_str_68c995d2579163001588843d],
  g_base_definitions[g_str_68c995d2579163001588843f],
  g_base_definitions[g_str_68c995d2579163001588843f_shower_shooting],
  g_base_definitions[g_str_68c995d25791630015888440],
  g_base_definitions[g_str_68c995d25791630015888440_shower_shooting],
  g_base_definitions[g_str_5fb1b9d8e1af0600177092f2_camp],
  g_base_definitions[g_str_5fb1b9d8e1af0600177092f2_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9d8e1af0600177092f2"] = army["5fb1b9d8e1af0600177092f2"]
if nil == armies["Cradle of Civilization"] then
  armies["Cradle of Civilization"] ={}
end
armies["Cradle of Civilization"]["Amurru and Early Aramaean  2000 to 747 BC"] = army["5fb1b9d8e1af0600177092f2"]
if nil == armies["Chariot Supremacy"] then
  armies["Chariot Supremacy"] ={}
end
armies["Chariot Supremacy"]["Amurru and Early Aramaean  2000 to 747 BC"] = army["5fb1b9d8e1af0600177092f2"]
if nil == armies["Sea Peoples Invasions"] then
  armies["Sea Peoples Invasions"] ={}
end
armies["Sea Peoples Invasions"]["Amurru and Early Aramaean  2000 to 747 BC"] = army["5fb1b9d8e1af0600177092f2"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Amurru and Early Aramaean  2000 to 747 BC"] = army["5fb1b9d8e1af0600177092f2"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9d8e1af0600177092f2"] = {}
army_dates["5fb1b9d8e1af0600177092f2"]["2000 BC to 747 BC"] = {
  startDate=-2000,
  endDate=-747
}
army_dates["5fb1b9d8e1af0600177092f2"]["2000 BC to 1800 BC"] = {
  startDate=-2000,
  endDate=-1800
}
army_dates["5fb1b9d8e1af0600177092f2"]["1799 BC to 1460 BC"] = {
  startDate=-1799,
  endDate=-1460
}
army_dates["5fb1b9d8e1af0600177092f2"]["1459 BC to 747 BC"] = {
  startDate=-1459,
  endDate=-747
}
