-- 5fb1b9e0e1af0600177097e8 Early Commagene  163 to 80 BC

army['5fb1b9e0e1af0600177097e8']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Hilly',
    },
    name='Early Commagene  163 to 80 BC',
    id='5fb1b9e0e1af0600177097e8',
    dateRange={
      startDate=-163,
      endDate=-80,
    },
  },
  g_base_definitions[g_str_68c995da5791630015889757_general],
  g_base_definitions[g_str_68c995da5791630015889757],
  g_base_definitions[g_str_68c995da5791630015889759],
  g_base_definitions[g_str_68c995da579163001588975b],
  g_base_definitions[g_str_68c995da579163001588975d],
  g_base_definitions[g_str_68c995da579163001588975f],
  g_base_definitions[g_str_68c995da579163001588975f_shower_shooting],
  g_base_definitions[g_str_68c995da5791630015889762],
  g_base_definitions[g_str_68c995da5791630015889764],
  g_base_definitions[g_str_68c995da5791630015889766],
  g_base_definitions[g_str_5fb1b9e0e1af0600177097e8_camp],
  g_base_definitions[g_str_5fb1b9e0e1af0600177097e8_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e0e1af0600177097e8"] = army["5fb1b9e0e1af0600177097e8"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Early Commagene  163 to 80 BC"] = army["5fb1b9e0e1af0600177097e8"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Early Commagene  163 to 80 BC"] = army["5fb1b9e0e1af0600177097e8"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Commagene  163 to 80 BC"] = army["5fb1b9e0e1af0600177097e8"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e0e1af0600177097e8"] = {}
army_dates["5fb1b9e0e1af0600177097e8"]["163 BC to 80 BC"] = {
  startDate=-163,
  endDate=-80
}
