-- 5fb1b9ebe1af060017709e78 Serbian Kingdom  1180 to 1300 AD

army['5fb1b9ebe1af060017709e78']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Hilly',
    },
    name='Serbian Kingdom  1180 to 1300 AD',
    id='5fb1b9ebe1af060017709e78',
    dateRange={
      startDate=1180,
      endDate=1300,
    },
  },
  g_base_definitions[g_str_68c995e3579163001588b032_general],
  g_base_definitions[g_str_68c995e3579163001588b032],
  g_base_definitions[g_str_68c995e3579163001588b034],
  g_base_definitions[g_str_68c995e3579163001588b036],
  g_base_definitions[g_str_68c995e3579163001588b036_shower_shooting],
  g_base_definitions[g_str_68c995e3579163001588b039],
  g_base_definitions[g_str_68c995e3579163001588b03b],
  g_base_definitions[g_str_5fb1b9ebe1af060017709e78_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ebe1af060017709e78"] = army["5fb1b9ebe1af060017709e78"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Serbian Kingdom  1180 to 1300 AD"] = army["5fb1b9ebe1af060017709e78"]
if nil == armies["Byzantium in Decay"] then
  armies["Byzantium in Decay"] ={}
end
armies["Byzantium in Decay"]["Serbian Kingdom  1180 to 1300 AD"] = army["5fb1b9ebe1af060017709e78"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Serbian Kingdom  1180 to 1300 AD"] = army["5fb1b9ebe1af060017709e78"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ebe1af060017709e78"] = {}
army_dates["5fb1b9ebe1af060017709e78"]["1180 AD to 1300 AD"] = {
  startDate=1180,
  endDate=1300
}
