-- 5fb1b9e1e1af060017709806 Tigranes  83 to 66 BC

army['5fb1b9e1e1af060017709806']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Hilly',
    },
    name='Tigranes  83 to 66 BC',
    id='5fb1b9e1e1af060017709806',
    dateRange={
      startDate=-83,
      endDate=-66,
    },
  },
  g_base_definitions[g_str_68c995da57916300158897b4_general],
  g_base_definitions[g_str_68c995da57916300158897b4],
  g_base_definitions[g_str_68c995da57916300158897b6],
  g_base_definitions[g_str_68c995da57916300158897b8],
  g_base_definitions[g_str_68c995da57916300158897b8_shower_shooting],
  g_base_definitions[g_str_68c995da57916300158897bb],
  g_base_definitions[g_str_68c995da57916300158897bd],
  g_base_definitions[g_str_68c995da57916300158897bf],
  g_base_definitions[g_str_68c995da57916300158897c1],
  g_base_definitions[g_str_68c995da57916300158897c3],
  g_base_definitions[g_str_5fb1b9e1e1af060017709806_camp],
  g_base_definitions[g_str_5fb1b9e1e1af060017709806_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e1e1af060017709806"] = army["5fb1b9e1e1af060017709806"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Tigranes  83 to 66 BC"] = army["5fb1b9e1e1af060017709806"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Tigranes  83 to 66 BC"] = army["5fb1b9e1e1af060017709806"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Tigranes  83 to 66 BC"] = army["5fb1b9e1e1af060017709806"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e1e1af060017709806"] = {}
army_dates["5fb1b9e1e1af060017709806"]["83 BC to 66 BC"] = {
  startDate=-83,
  endDate=-66
}
