-- 5fb1b9f3e1af06001770a2ce Jurchen Jin Rebellion  1114 to 1125 AD

army['5fb1b9f3e1af06001770a2ce']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Steppe',
      'Arable',
    },
    name='Jurchen Jin Rebellion  1114 to 1125 AD',
    id='5fb1b9f3e1af06001770a2ce',
    dateRange={
      startDate=1114,
      endDate=1125,
    },
  },
  g_base_definitions[g_str_68c995e9579163001588c1ad_general],
  g_base_definitions[g_str_68c995e9579163001588c1ad],
  g_base_definitions[g_str_68c995e9579163001588c1af],
  g_base_definitions[g_str_68c995e9579163001588c1b1_general],
  g_base_definitions[g_str_68c995e9579163001588c1b1],
  g_base_definitions[g_str_68c995e9579163001588c1b3],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2ce_camp],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2ce_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f3e1af06001770a2ce"] = army["5fb1b9f3e1af06001770a2ce"]
if nil == armies["Middle Kingdom"] then
  armies["Middle Kingdom"] ={}
end
armies["Middle Kingdom"]["Jurchen Jin Rebellion  1114 to 1125 AD"] = army["5fb1b9f3e1af06001770a2ce"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Jurchen Jin Rebellion  1114 to 1125 AD"] = army["5fb1b9f3e1af06001770a2ce"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f3e1af06001770a2ce"] = {}
army_dates["5fb1b9f3e1af06001770a2ce"]["1114 AD to 1125 AD"] = {
  startDate=1114,
  endDate=1125
}
