-- 5fb1b9dae1af0600177093e4 Later Syro-Hittite  900 to 710 BC

army['5fb1b9dae1af0600177093e4']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
    },
    name='Later Syro-Hittite  900 to 710 BC',
    id='5fb1b9dae1af0600177093e4',
    dateRange={
      startDate=-900,
      endDate=-710,
    },
  },
  g_base_definitions[g_str_68c995d4579163001588876d_general],
  g_base_definitions[g_str_68c995d4579163001588876d],
  g_base_definitions[g_str_68c995d4579163001588876f],
  g_base_definitions[g_str_68c995d45791630015888771],
  g_base_definitions[g_str_68c995d45791630015888773],
  g_base_definitions[g_str_68c995d45791630015888775],
  g_base_definitions[g_str_68c995d45791630015888775_shower_shooting],
  g_base_definitions[g_str_68c995d45791630015888778],
  g_base_definitions[g_str_68c995d4579163001588877a],
  g_base_definitions[g_str_68c995d4579163001588877a_light_camelry],
  g_base_definitions[g_str_5fb1b9dae1af0600177093e4_camp],
  g_base_definitions[g_str_5fb1b9dae1af0600177093e4_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dae1af0600177093e4"] = army["5fb1b9dae1af0600177093e4"]
if nil == armies["Chariot Supremacy"] then
  armies["Chariot Supremacy"] ={}
end
armies["Chariot Supremacy"]["Later Syro-Hittite  900 to 710 BC"] = army["5fb1b9dae1af0600177093e4"]
if nil == armies["Assyrian Empire"] then
  armies["Assyrian Empire"] ={}
end
armies["Assyrian Empire"]["Later Syro-Hittite  900 to 710 BC"] = army["5fb1b9dae1af0600177093e4"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Syro-Hittite  900 to 710 BC"] = army["5fb1b9dae1af0600177093e4"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dae1af0600177093e4"] = {}
army_dates["5fb1b9dae1af0600177093e4"]["900 BC to 710 BC"] = {
  startDate=-900,
  endDate=-710
}
army_dates["5fb1b9dae1af0600177093e4"]["900 BC to 722 BC"] = {
  startDate=-900,
  endDate=-722
}
army_dates["5fb1b9dae1af0600177093e4"]["721 BC to 710 BC"] = {
  startDate=-721,
  endDate=-710
}
