-- 5fb1b9eee1af060017709feb Early Ottoman  1281 to 1361 AD

army['5fb1b9eee1af060017709feb']={
  data={
    invasionRatings={
      4,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Arable',
    },
    name='Early Ottoman  1281 to 1361 AD',
    id='5fb1b9eee1af060017709feb',
    dateRange={
      startDate=1281,
      endDate=1361,
    },
  },
  g_base_definitions[g_str_68c995e5579163001588b69f_general],
  g_base_definitions[g_str_68c995e5579163001588b69f],
  g_base_definitions[g_str_68c995e5579163001588b6a1_general],
  g_base_definitions[g_str_68c995e5579163001588b6a1],
  g_base_definitions[g_str_68c995e5579163001588b6a3],
  g_base_definitions[g_str_68c995e5579163001588b6a4],
  g_base_definitions[g_str_68c995e5579163001588b6a6],
  g_base_definitions[g_str_68c995e5579163001588b6a6_shower_shooting],
  g_base_definitions[g_str_68c995e5579163001588b6a7],
  g_base_definitions[g_str_68c995e5579163001588b6a7_shower_shooting],
  g_base_definitions[g_str_68c995e5579163001588b6aa],
  g_base_definitions[g_str_68c995e5579163001588b6ac],
  g_base_definitions[g_str_5fb1b9eee1af060017709feb_camp],
  g_base_definitions[g_str_5fb1b9eee1af060017709feb_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eee1af060017709feb"] = army["5fb1b9eee1af060017709feb"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Early Ottoman  1281 to 1361 AD"] = army["5fb1b9eee1af060017709feb"]
if nil == armies["Byzantium in Decay"] then
  armies["Byzantium in Decay"] ={}
end
armies["Byzantium in Decay"]["Early Ottoman  1281 to 1361 AD"] = army["5fb1b9eee1af060017709feb"]
if nil == armies["Crusader Kingdoms"] then
  armies["Crusader Kingdoms"] ={}
end
armies["Crusader Kingdoms"]["Early Ottoman  1281 to 1361 AD"] = army["5fb1b9eee1af060017709feb"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Ottoman  1281 to 1361 AD"] = army["5fb1b9eee1af060017709feb"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eee1af060017709feb"] = {}
army_dates["5fb1b9eee1af060017709feb"]["1281 AD to 1361 AD"] = {
  startDate=1281,
  endDate=1361
}
