-- 5fb1b9f1e1af06001770a1df Nanyue  206 to 111 BC

army['5fb1b9f1e1af06001770a1df']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Forest',
    },
    name='Nanyue  206 to 111 BC',
    id='5fb1b9f1e1af06001770a1df',
    dateRange={
      startDate=-206,
      endDate=-111,
    },
  },
  g_base_definitions[g_str_68c995e8579163001588bdee_general],
  g_base_definitions[g_str_68c995e8579163001588bdee],
  g_base_definitions[g_str_68c995e8579163001588bdf0],
  g_base_definitions[g_str_68c995e8579163001588bdf0_shower_shooting],
  g_base_definitions[g_str_68c995e8579163001588bdf3_general],
  g_base_definitions[g_str_68c995e8579163001588bdf3],
  g_base_definitions[g_str_68c995e8579163001588bdf5],
  g_base_definitions[g_str_68c995e8579163001588bdf7],
  g_base_definitions[g_str_68c995e8579163001588bdf9],
  g_base_definitions[g_str_68c995e8579163001588bdfb],
  g_base_definitions[g_str_68c995e8579163001588bdfb_shower_shooting],
  g_base_definitions[g_str_68c995e8579163001588bdfe],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a1df_camp],
  g_base_definitions[g_str_68c995cf5791630015887f72],
  g_base_definitions[g_str_68c995cf5791630015887f74],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f1e1af06001770a1df"] = army["5fb1b9f1e1af06001770a1df"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Nanyue  206 to 111 BC"] = army["5fb1b9f1e1af06001770a1df"]
if nil == armies["Southeast Asia"] then
  armies["Southeast Asia"] ={}
end
armies["Southeast Asia"]["Nanyue  206 to 111 BC"] = army["5fb1b9f1e1af06001770a1df"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Nanyue  206 to 111 BC"] = army["5fb1b9f1e1af06001770a1df"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f1e1af06001770a1df"] = {}
army_dates["5fb1b9f1e1af06001770a1df"]["206 BC to 111 BC"] = {
  startDate=-206,
  endDate=-111
}
