-- 5fb1b9e8e1af060017709c53 French Ordonnance  1445 to 1480 AD

army['5fb1b9e8e1af060017709c53']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
    },
    name='French Ordonnance  1445 to 1480 AD',
    id='5fb1b9e8e1af060017709c53',
    dateRange={
      startDate=1445,
      endDate=1480,
    },
  },
  g_base_definitions[g_str_68c995e0579163001588a6d7_general],
  g_base_definitions[g_str_68c995e0579163001588a6d7_general_mounted],
  g_base_definitions[g_str_68c995e0579163001588a6d7_general_dismounted],
  g_base_definitions[g_str_68c995e0579163001588a6d7],
  g_base_definitions[g_str_68c995e0579163001588a6d7_mounted],
  g_base_definitions[g_str_68c995e0579163001588a6d7_dismounted],
  g_base_definitions[g_str_68c995e0579163001588a6da],
  g_base_definitions[g_str_68c995e0579163001588a6da_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e0579163001588a6da_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e0579163001588a6dd_general],
  g_base_definitions[g_str_68c995e0579163001588a6dd],
  g_base_definitions[g_str_68c995e0579163001588a6df],
  g_base_definitions[g_str_68c995e0579163001588a6df_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e0579163001588a6df_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e0579163001588a6e2],
  g_base_definitions[g_str_68c995e0579163001588a6e2_shower_shooting],
  g_base_definitions[g_str_68c995e0579163001588a6e5],
  g_base_definitions[g_str_68c995e0579163001588a6e5_shower_shooting],
  g_base_definitions[g_str_68c995e0579163001588a6e5_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e0579163001588a6e5_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e0579163001588a6e9],
  g_base_definitions[g_str_68c995e0579163001588a6e9_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e0579163001588a6e9_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e0579163001588a6ec],
  g_base_definitions[g_str_68c995e0579163001588a6ee],
  g_base_definitions[g_str_68c995e0579163001588a6f0],
  g_base_definitions[g_str_5fb1b9e8e1af060017709c53_camp],
  g_base_definitions[g_str_5fb1b9e8e1af060017709c53_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e8e1af060017709c53"] = army["5fb1b9e8e1af060017709c53"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["French Ordonnance  1445 to 1480 AD"] = army["5fb1b9e8e1af060017709c53"]
if nil == armies["Flower of Chivalry"] then
  armies["Flower of Chivalry"] ={}
end
armies["Flower of Chivalry"]["French Ordonnance  1445 to 1480 AD"] = army["5fb1b9e8e1af060017709c53"]
if nil == armies["Plate and Handgonne"] then
  armies["Plate and Handgonne"] ={}
end
armies["Plate and Handgonne"]["French Ordonnance  1445 to 1480 AD"] = army["5fb1b9e8e1af060017709c53"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["French Ordonnance  1445 to 1480 AD"] = army["5fb1b9e8e1af060017709c53"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e8e1af060017709c53"] = {}
army_dates["5fb1b9e8e1af060017709c53"]["1445 AD to 1480 AD"] = {
  startDate=1445,
  endDate=1480
}
army_dates["5fb1b9e8e1af060017709c53"]["1445 AD to 1477 AD"] = {
  startDate=1445,
  endDate=1477
}
army_dates["5fb1b9e8e1af060017709c53"]["1478 AD to 1480 AD"] = {
  startDate=1478,
  endDate=1480
}
