-- 5fb1b9f1e1af06001770a1e6 Chinese-Dominated Vietnamese  136 to 938 AD

army['5fb1b9f1e1af06001770a1e6']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Forest',
    },
    name='Chinese-Dominated Vietnamese  136 to 938 AD',
    id='5fb1b9f1e1af06001770a1e6',
    dateRange={
      startDate=136,
      endDate=938,
    },
  },
  g_base_definitions[g_str_68c995e8579163001588be06_general],
  g_base_definitions[g_str_68c995e8579163001588be06],
  g_base_definitions[g_str_68c995e8579163001588be08_general],
  g_base_definitions[g_str_68c995e8579163001588be08],
  g_base_definitions[g_str_68c995e8579163001588be0a_general],
  g_base_definitions[g_str_68c995e8579163001588be0a],
  g_base_definitions[g_str_68c995e8579163001588be0d],
  g_base_definitions[g_str_68c995e8579163001588be0d_shower_shooting],
  g_base_definitions[g_str_68c995e8579163001588be11],
  g_base_definitions[g_str_68c995e8579163001588be13],
  g_base_definitions[g_str_68c995e8579163001588be13_shower_shooting],
  g_base_definitions[g_str_68c995e8579163001588be16],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a1e6_camp],
  g_base_definitions[g_str_68c995cf5791630015887f72],
  g_base_definitions[g_str_68c995cf5791630015887f74],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f1e1af06001770a1e6"] = army["5fb1b9f1e1af06001770a1e6"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Chinese-Dominated Vietnamese  136 to 938 AD"] = army["5fb1b9f1e1af06001770a1e6"]
if nil == armies["Southeast Asia"] then
  armies["Southeast Asia"] ={}
end
armies["Southeast Asia"]["Chinese-Dominated Vietnamese  136 to 938 AD"] = army["5fb1b9f1e1af06001770a1e6"]
if nil == armies["Dark Ages China"] then
  armies["Dark Ages China"] ={}
end
armies["Dark Ages China"]["Chinese-Dominated Vietnamese  136 to 938 AD"] = army["5fb1b9f1e1af06001770a1e6"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Chinese-Dominated Vietnamese  136 to 938 AD"] = army["5fb1b9f1e1af06001770a1e6"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f1e1af06001770a1e6"] = {}
army_dates["5fb1b9f1e1af06001770a1e6"]["136 AD to 938 AD"] = {
  startDate=136,
  endDate=938
}
