-- 5fb1b9f2e1af06001770a255 Sui Chinese  581 to 623 AD

army['5fb1b9f2e1af06001770a255']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      2,
      0,
    },
    homeTopographies={
      'Hilly',
      'Arable',
      'Forest',
    },
    name='Sui Chinese  581 to 623 AD',
    id='5fb1b9f2e1af06001770a255',
    dateRange={
      startDate=581,
      endDate=623,
    },
  },
  g_base_definitions[g_str_68c995e8579163001588bf97_general],
  g_base_definitions[g_str_68c995e8579163001588bf97],
  g_base_definitions[g_str_68c995e8579163001588bf99],
  g_base_definitions[g_str_68c995e8579163001588bf9b],
  g_base_definitions[g_str_68c995e8579163001588bf9d],
  g_base_definitions[g_str_68c995e8579163001588bf9f],
  g_base_definitions[g_str_68c995e8579163001588bfa0],
  g_base_definitions[g_str_68c995e8579163001588bfa1],
  g_base_definitions[g_str_68c995e8579163001588bfa3],
  g_base_definitions[g_str_68c995e8579163001588bfa3_shower_shooting],
  g_base_definitions[g_str_68c995e8579163001588bfa4],
  g_base_definitions[g_str_68c995e8579163001588bfa4_shower_shooting],
  g_base_definitions[g_str_68c995e8579163001588bfa7],
  g_base_definitions[g_str_68c995e8579163001588bfa9],
  g_base_definitions[g_str_68c995e8579163001588bfab],
  g_base_definitions[g_str_68c995e8579163001588bfad],
  g_base_definitions[g_str_5fb1b9f2e1af06001770a255_camp],
  g_base_definitions[g_str_5fb1b9f2e1af06001770a255_camp_fortified],
  g_base_definitions[g_str_68c995d05791630015887fef],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f2e1af06001770a255"] = army["5fb1b9f2e1af06001770a255"]
if nil == armies["Middle Kingdom"] then
  armies["Middle Kingdom"] ={}
end
armies["Middle Kingdom"]["Sui Chinese  581 to 623 AD"] = army["5fb1b9f2e1af06001770a255"]
if nil == armies["Southeast Asia"] then
  armies["Southeast Asia"] ={}
end
armies["Southeast Asia"]["Sui Chinese  581 to 623 AD"] = army["5fb1b9f2e1af06001770a255"]
if nil == armies["Korea and Japan"] then
  armies["Korea and Japan"] ={}
end
armies["Korea and Japan"]["Sui Chinese  581 to 623 AD"] = army["5fb1b9f2e1af06001770a255"]
if nil == armies["Dark Ages China"] then
  armies["Dark Ages China"] ={}
end
armies["Dark Ages China"]["Sui Chinese  581 to 623 AD"] = army["5fb1b9f2e1af06001770a255"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Sui Chinese  581 to 623 AD"] = army["5fb1b9f2e1af06001770a255"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f2e1af06001770a255"] = {}
army_dates["5fb1b9f2e1af06001770a255"]["581 AD to 623 AD"] = {
  startDate=581,
  endDate=623
}
army_dates["5fb1b9f2e1af06001770a255"]["581 AD to 597 AD"] = {
  startDate=581,
  endDate=597
}
army_dates["5fb1b9f2e1af06001770a255"]["598 AD to 618 AD"] = {
  startDate=598,
  endDate=618
}
army_dates["5fb1b9f2e1af06001770a255"]["619 AD to 623 AD"] = {
  startDate=619,
  endDate=623
}
