-- 5fb1b9dbe1af060017709508 Early Hoplite Athens  669 to 449 BC

army['5fb1b9dbe1af060017709508']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Early Hoplite Athens  669 to 449 BC',
    id='5fb1b9dbe1af060017709508',
    dateRange={
      startDate=-669,
      endDate=-449,
    },
  },
  g_base_definitions[g_str_68c995d65791630015888bd9_general],
  g_base_definitions[g_str_68c995d65791630015888bd9],
  g_base_definitions[g_str_68c995d65791630015888bdb],
  g_base_definitions[g_str_68c995d65791630015888bdd],
  g_base_definitions[g_str_68c995d65791630015888be0],
  g_base_definitions[g_str_68c995d65791630015888be3],
  g_base_definitions[g_str_68c995d65791630015888be3_shower_shooting],
  g_base_definitions[g_str_68c995d65791630015888be4],
  g_base_definitions[g_str_68c995d65791630015888be4_shower_shooting],
  g_base_definitions[g_str_5fb1b9dbe1af060017709508_camp],
  g_base_definitions[g_str_68c995c55791630015886d67],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dbe1af060017709508"] = army["5fb1b9dbe1af060017709508"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Early Hoplite Athens  669 to 449 BC"] = army["5fb1b9dbe1af060017709508"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Hoplite Athens  669 to 449 BC"] = army["5fb1b9dbe1af060017709508"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dbe1af060017709508"] = {}
army_dates["5fb1b9dbe1af060017709508"]["669 BC to 449 BC"] = {
  startDate=-669,
  endDate=-449
}
army_dates["5fb1b9dbe1af060017709508"]["669 BC to 511 BC"] = {
  startDate=-669,
  endDate=-511
}
army_dates["5fb1b9dbe1af060017709508"]["510 BC to 449 BC"] = {
  startDate=-510,
  endDate=-449
}
