-- 5fb1b9f3e1af06001770a2a9 Western Xia (all mounted)  982 to 1227 AD

army['5fb1b9f3e1af06001770a2a9']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Hilly',
    },
    name='Western Xia (all mounted)  982 to 1227 AD',
    id='5fb1b9f3e1af06001770a2a9',
    dateRange={
      startDate=982,
      endDate=1227,
    },
  },
  g_base_definitions[g_str_68c995e9579163001588c110],
  g_base_definitions[g_str_68c995e9579163001588c110_mounted],
  g_base_definitions[g_str_68c995e9579163001588c110_dismounted],
  g_base_definitions[g_str_68c995e9579163001588c113_general],
  g_base_definitions[g_str_68c995e9579163001588c113_general_mounted],
  g_base_definitions[g_str_68c995e9579163001588c113_general_dismounted],
  g_base_definitions[g_str_68c995e9579163001588c113],
  g_base_definitions[g_str_68c995e9579163001588c113_mounted],
  g_base_definitions[g_str_68c995e9579163001588c113_dismounted],
  g_base_definitions[g_str_68c995e9579163001588c116],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2a9_camp],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a2a9_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f3e1af06001770a2a9"] = army["5fb1b9f3e1af06001770a2a9"]
if nil == armies["Middle Kingdom"] then
  armies["Middle Kingdom"] ={}
end
armies["Middle Kingdom"]["Western Xia (all mounted)  982 to 1227 AD"] = army["5fb1b9f3e1af06001770a2a9"]
if nil == armies["Silk Road"] then
  armies["Silk Road"] ={}
end
armies["Silk Road"]["Western Xia (all mounted)  982 to 1227 AD"] = army["5fb1b9f3e1af06001770a2a9"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Western Xia (all mounted)  982 to 1227 AD"] = army["5fb1b9f3e1af06001770a2a9"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f3e1af06001770a2a9"] = {}
army_dates["5fb1b9f3e1af06001770a2a9"]["982 AD to 1227 AD"] = {
  startDate=982,
  endDate=1227
}
army_dates["5fb1b9f3e1af06001770a2a9"]["982 AD to 1064 AD"] = {
  startDate=982,
  endDate=1064
}
army_dates["5fb1b9f3e1af06001770a2a9"]["1065 AD"] = {
  startDate=1065,
  endDate=1065
}
army_dates["5fb1b9f3e1af06001770a2a9"]["1066 AD to 1199 AD"] = {
  startDate=1066,
  endDate=1199
}
army_dates["5fb1b9f3e1af06001770a2a9"]["1200 AD to 1226 AD"] = {
  startDate=1200,
  endDate=1226
}
army_dates["5fb1b9f3e1af06001770a2a9"]["1227 AD"] = {
  startDate=1227,
  endDate=1227
}
