-- 5fb1b9e2e1af0600177098d5 Army of Radagaisus  401 to 406 AD

army['5fb1b9e2e1af0600177098d5']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Army of Radagaisus  401 to 406 AD',
    id='5fb1b9e2e1af0600177098d5',
    dateRange={
      startDate=401,
      endDate=406,
    },
  },
  g_base_definitions[g_str_68c995db5791630015889a88_general],
  g_base_definitions[g_str_68c995db5791630015889a88],
  g_base_definitions[g_str_68c995db5791630015889a8a],
  g_base_definitions[g_str_68c995db5791630015889a8a_shower_shooting],
  g_base_definitions[g_str_68c995db5791630015889a8d],
  g_base_definitions[g_str_68c995db5791630015889a8f],
  g_base_definitions[g_str_68c995db5791630015889a91],
  g_base_definitions[g_str_68c995db5791630015889a93],
  g_base_definitions[g_str_5fb1b9e2e1af0600177098d5_camp],
  g_base_definitions[g_str_5fb1b9e2e1af0600177098d5_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e2e1af0600177098d5"] = army["5fb1b9e2e1af0600177098d5"]
if nil == armies["Fall of Rome"] then
  armies["Fall of Rome"] ={}
end
armies["Fall of Rome"]["Army of Radagaisus  401 to 406 AD"] = army["5fb1b9e2e1af0600177098d5"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Army of Radagaisus  401 to 406 AD"] = army["5fb1b9e2e1af0600177098d5"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e2e1af0600177098d5"] = {}
army_dates["5fb1b9e2e1af0600177098d5"]["401 AD to 406 AD"] = {
  startDate=401,
  endDate=406
}
