-- 5fb1b9f6e1af06001770a4aa Caribbean Indians: Arawaks  1200 to 1520 AD

army['5fb1b9f6e1af06001770a4aa']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Forest',
    },
    name='Caribbean Indians: Arawaks  1200 to 1520 AD',
    id='5fb1b9f6e1af06001770a4aa',
    dateRange={
      startDate=1200,
      endDate=1520,
    },
    ambush=true,  },
  g_base_definitions[g_str_68c995eb579163001588c640_general],
  g_base_definitions[g_str_68c995eb579163001588c640_general_shower_shooting],
  g_base_definitions[g_str_68c995eb579163001588c640],
  g_base_definitions[g_str_68c995eb579163001588c640_shower_shooting],
  g_base_definitions[g_str_68c995eb579163001588c641_general],
  g_base_definitions[g_str_68c995eb579163001588c641_general_shower_shooting],
  g_base_definitions[g_str_68c995eb579163001588c641],
  g_base_definitions[g_str_68c995eb579163001588c641_shower_shooting],
  g_base_definitions[g_str_68c995eb579163001588c644_general],
  g_base_definitions[g_str_68c995eb579163001588c644_general_shower_shooting],
  g_base_definitions[g_str_68c995eb579163001588c644],
  g_base_definitions[g_str_68c995eb579163001588c644_shower_shooting],
  g_base_definitions[g_str_68c995eb579163001588c647],
  g_base_definitions[g_str_68c995eb579163001588c649],
  g_base_definitions[g_str_5fb1b9f6e1af06001770a4aa_camp],
  g_base_definitions[g_str_5fb1b9f6e1af06001770a4aa_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f6e1af06001770a4aa"] = army["5fb1b9f6e1af06001770a4aa"]
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["Caribbean Indians: Arawaks  1200 to 1520 AD"] = army["5fb1b9f6e1af06001770a4aa"]
if nil == armies["Caribbean"] then
  armies["Caribbean"] ={}
end
armies["Caribbean"]["Caribbean Indians: Arawaks  1200 to 1520 AD"] = army["5fb1b9f6e1af06001770a4aa"]
if nil == armies["Andes and Amazon"] then
  armies["Andes and Amazon"] ={}
end
armies["Andes and Amazon"]["Caribbean Indians: Arawaks  1200 to 1520 AD"] = army["5fb1b9f6e1af06001770a4aa"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Caribbean Indians: Arawaks  1200 to 1520 AD"] = army["5fb1b9f6e1af06001770a4aa"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f6e1af06001770a4aa"] = {}
army_dates["5fb1b9f6e1af06001770a4aa"]["1200 AD to 1520 AD"] = {
  startDate=1200,
  endDate=1520
}
