-- 5fb1b9f4e1af06001770a377 Yi Dynasty Korean  1392 to 1598 AD

army['5fb1b9f4e1af06001770a377']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Hilly',
    },
    name='Yi Dynasty Korean  1392 to 1598 AD',
    id='5fb1b9f4e1af06001770a377',
    dateRange={
      startDate=1392,
      endDate=1598,
    },
  },
  g_base_definitions[g_str_68c995ea579163001588c431_general],
  g_base_definitions[g_str_68c995ea579163001588c431],
  g_base_definitions[g_str_68c995ea579163001588c433_general],
  g_base_definitions[g_str_68c995ea579163001588c433],
  g_base_definitions[g_str_68c995ea579163001588c435_general],
  g_base_definitions[g_str_68c995ea579163001588c435],
  g_base_definitions[g_str_68c995ea579163001588c437],
  g_base_definitions[g_str_68c995ea579163001588c439],
  g_base_definitions[g_str_68c995ea579163001588c43b],
  g_base_definitions[g_str_68c995ea579163001588c43d],
  g_base_definitions[g_str_68c995ea579163001588c43f],
  g_base_definitions[g_str_68c995ea579163001588c441],
  g_base_definitions[g_str_68c995ea579163001588c444],
  g_base_definitions[g_str_5fb1b9f4e1af06001770a377_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f4e1af06001770a377"] = army["5fb1b9f4e1af06001770a377"]
if nil == armies["Korea and Japan"] then
  armies["Korea and Japan"] ={}
end
armies["Korea and Japan"]["Yi Dynasty Korean  1392 to 1598 AD"] = army["5fb1b9f4e1af06001770a377"]
if nil == armies["Middle Kingdom"] then
  armies["Middle Kingdom"] ={}
end
armies["Middle Kingdom"]["Yi Dynasty Korean  1392 to 1598 AD"] = army["5fb1b9f4e1af06001770a377"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Yi Dynasty Korean  1392 to 1598 AD"] = army["5fb1b9f4e1af06001770a377"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f4e1af06001770a377"] = {}
army_dates["5fb1b9f4e1af06001770a377"]["1392 AD to 1598 AD"] = {
  startDate=1392,
  endDate=1598
}
