-- 5fb1b9e7e1af060017709bfd Medieval Portuguese  1340 to 1515 AD

army['5fb1b9e7e1af060017709bfd']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
      'Hilly',
    },
    name='Medieval Portuguese  1340 to 1515 AD',
    id='5fb1b9e7e1af060017709bfd',
    dateRange={
      startDate=1340,
      endDate=1515,
    },
  },
  g_base_definitions[g_str_68c995df579163001588a590_general],
  g_base_definitions[g_str_68c995df579163001588a590_general_mounted],
  g_base_definitions[g_str_68c995df579163001588a590_general_dismounted],
  g_base_definitions[g_str_68c995df579163001588a590],
  g_base_definitions[g_str_68c995df579163001588a590_mounted],
  g_base_definitions[g_str_68c995df579163001588a590_dismounted],
  g_base_definitions[g_str_68c995df579163001588a593],
  g_base_definitions[g_str_68c995df579163001588a595],
  g_base_definitions[g_str_68c995df579163001588a597],
  g_base_definitions[g_str_68c995df579163001588a597_shower_shooting],
  g_base_definitions[g_str_68c995df579163001588a598],
  g_base_definitions[g_str_68c995df579163001588a598_shower_shooting],
  g_base_definitions[g_str_68c995df579163001588a59b],
  g_base_definitions[g_str_68c995df579163001588a59d],
  g_base_definitions[g_str_68c995df579163001588a59f],
  g_base_definitions[g_str_68c995df579163001588a5a1],
  g_base_definitions[g_str_5fb1b9e7e1af060017709bfd_camp],
  g_base_definitions[g_str_5fb1b9e7e1af060017709bfd_camp_pack_train],
  g_base_definitions[g_str_5fb1b9e7e1af060017709bfd_prepared_defenses],
  g_base_definitions[g_str_68c995cb57916300158876c6_general],
  g_base_definitions[g_str_68c995cb57916300158876c6],
  g_base_definitions[g_str_68c995cb57916300158876c8],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e7e1af060017709bfd"] = army["5fb1b9e7e1af060017709bfd"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Medieval Portuguese  1340 to 1515 AD"] = army["5fb1b9e7e1af060017709bfd"]
if nil == armies["Plate and Handgonne"] then
  armies["Plate and Handgonne"] ={}
end
armies["Plate and Handgonne"]["Medieval Portuguese  1340 to 1515 AD"] = army["5fb1b9e7e1af060017709bfd"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Medieval Portuguese  1340 to 1515 AD"] = army["5fb1b9e7e1af060017709bfd"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e7e1af060017709bfd"] = {}
army_dates["5fb1b9e7e1af060017709bfd"]["1340 AD to 1515 AD"] = {
  startDate=1340,
  endDate=1515
}
army_dates["5fb1b9e7e1af060017709bfd"]["1340 AD to 1390 AD"] = {
  startDate=1340,
  endDate=1390
}
army_dates["5fb1b9e7e1af060017709bfd"]["1391 AD to 1515 AD"] = {
  startDate=1391,
  endDate=1515
}
