-- 5fb1b9ede1af060017709f54 Dynastic Kurdish  950 to 1085 AD

army['5fb1b9ede1af060017709f54']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Hilly',
    },
    name='Dynastic Kurdish  950 to 1085 AD',
    id='5fb1b9ede1af060017709f54',
    dateRange={
      startDate=950,
      endDate=1085,
    },
  },
  g_base_definitions[g_str_68c995e4579163001588b429_general],
  g_base_definitions[g_str_68c995e4579163001588b429],
  g_base_definitions[g_str_68c995e4579163001588b42c_general],
  g_base_definitions[g_str_68c995e4579163001588b42c],
  g_base_definitions[g_str_68c995e4579163001588b42e],
  g_base_definitions[g_str_68c995e4579163001588b42e_shower_shooting],
  g_base_definitions[g_str_68c995e4579163001588b431],
  g_base_definitions[g_str_5fb1b9ede1af060017709f54_camp],
  g_base_definitions[g_str_5fb1b9ede1af060017709f54_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ede1af060017709f54"] = army["5fb1b9ede1af060017709f54"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Dynastic Kurdish  950 to 1085 AD"] = army["5fb1b9ede1af060017709f54"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Dynastic Kurdish  950 to 1085 AD"] = army["5fb1b9ede1af060017709f54"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ede1af060017709f54"] = {}
army_dates["5fb1b9ede1af060017709f54"]["950 AD to 1085 AD"] = {
  startDate=950,
  endDate=1085
}
