-- 5fb1b9dde1af0600177095ff Sacred War Phokian  357 to 347 BC

army['5fb1b9dde1af0600177095ff']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
    },
    name='Sacred War Phokian  357 to 347 BC',
    id='5fb1b9dde1af0600177095ff',
    dateRange={
      startDate=-357,
      endDate=-347,
    },
  },
  g_base_definitions[g_str_68c995d75791630015888fe8_general],
  g_base_definitions[g_str_68c995d75791630015888fe8],
  g_base_definitions[g_str_68c995d75791630015888feb],
  g_base_definitions[g_str_68c995d75791630015888fed_general],
  g_base_definitions[g_str_68c995d75791630015888fed],
  g_base_definitions[g_str_68c995d75791630015888fef],
  g_base_definitions[g_str_68c995d75791630015888ff1],
  g_base_definitions[g_str_68c995d75791630015888ff3],
  g_base_definitions[g_str_68c995d75791630015888ff5_general],
  g_base_definitions[g_str_68c995d75791630015888ff5],
  g_base_definitions[g_str_68c995d75791630015888ff8],
  g_base_definitions[g_str_68c995d75791630015888ffa],
  g_base_definitions[g_str_5fb1b9dde1af0600177095ff_camp],
  g_base_definitions[g_str_5fb1b9dde1af0600177095ff_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dde1af0600177095ff"] = army["5fb1b9dde1af0600177095ff"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Sacred War Phokian  357 to 347 BC"] = army["5fb1b9dde1af0600177095ff"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Sacred War Phokian  357 to 347 BC"] = army["5fb1b9dde1af0600177095ff"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Sacred War Phokian  357 to 347 BC"] = army["5fb1b9dde1af0600177095ff"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dde1af0600177095ff"] = {}
army_dates["5fb1b9dde1af0600177095ff"]["357 BC to 347 BC"] = {
  startDate=-357,
  endDate=-347
}
