-- 5fb1b9dde1af060017709606 Later Hoplite Italiot, Siciliot, or Tarentine  448 to 225 BC

army['5fb1b9dde1af060017709606']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Later Hoplite Italiot, Siciliot, or Tarentine  448 to 225 BC',
    id='5fb1b9dde1af060017709606',
    dateRange={
      startDate=-448,
      endDate=-225,
    },
  },
  g_base_definitions[g_str_68c995d75791630015889007_general],
  g_base_definitions[g_str_68c995d75791630015889007],
  g_base_definitions[g_str_68c995d7579163001588900a],
  g_base_definitions[g_str_68c995d7579163001588900c_general],
  g_base_definitions[g_str_68c995d7579163001588900c],
  g_base_definitions[g_str_68c995d7579163001588900e],
  g_base_definitions[g_str_68c995d75791630015889010],
  g_base_definitions[g_str_68c995d75791630015889012_general],
  g_base_definitions[g_str_68c995d75791630015889012],
  g_base_definitions[g_str_68c995d75791630015889015],
  g_base_definitions[g_str_68c995d75791630015889017],
  g_base_definitions[g_str_5fb1b9dde1af060017709606_camp],
  g_base_definitions[g_str_5fb1b9dde1af060017709606_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dde1af060017709606"] = army["5fb1b9dde1af060017709606"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Later Hoplite Italiot, Siciliot, or Tarentine  448 to 225 BC"] = army["5fb1b9dde1af060017709606"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Later Hoplite Italiot, Siciliot, or Tarentine  448 to 225 BC"] = army["5fb1b9dde1af060017709606"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Later Hoplite Italiot, Siciliot, or Tarentine  448 to 225 BC"] = army["5fb1b9dde1af060017709606"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Hoplite Italiot, Siciliot, or Tarentine  448 to 225 BC"] = army["5fb1b9dde1af060017709606"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dde1af060017709606"] = {}
army_dates["5fb1b9dde1af060017709606"]["448 BC to 225 BC"] = {
  startDate=-448,
  endDate=-225
}
army_dates["5fb1b9dde1af060017709606"]["448 BC to 421 BC"] = {
  startDate=-448,
  endDate=-421
}
army_dates["5fb1b9dde1af060017709606"]["420 BC to 344 BC"] = {
  startDate=-420,
  endDate=-344
}
army_dates["5fb1b9dde1af060017709606"]["343 BC"] = {
  startDate=-343,
  endDate=-343
}
army_dates["5fb1b9dde1af060017709606"]["342 BC to 225 BC"] = {
  startDate=-342,
  endDate=-225
}
