-- 5fb1b9efe1af06001770a093 Early Sultanate of Delhi  1206 to 1295 AD

army['5fb1b9efe1af06001770a093']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
    },
    name='Early Sultanate of Delhi  1206 to 1295 AD',
    id='5fb1b9efe1af06001770a093',
    dateRange={
      startDate=1206,
      endDate=1295,
    },
  },
  g_base_definitions[g_str_68c995e6579163001588b99b_general],
  g_base_definitions[g_str_68c995e6579163001588b99b_general_shower_shooting],
  g_base_definitions[g_str_68c995e6579163001588b99b],
  g_base_definitions[g_str_68c995e6579163001588b99b_shower_shooting],
  g_base_definitions[g_str_68c995e6579163001588b99f],
  g_base_definitions[g_str_68c995e6579163001588b9a2_general],
  g_base_definitions[g_str_68c995e6579163001588b9a2],
  g_base_definitions[g_str_68c995e6579163001588b9a4],
  g_base_definitions[g_str_68c995e6579163001588b9a6],
  g_base_definitions[g_str_68c995e6579163001588b9a6_plaustrella],
  g_base_definitions[g_str_68c995e6579163001588b9a9],
  g_base_definitions[g_str_68c995e6579163001588b9a9_shower_shooting],
  g_base_definitions[g_str_68c995e6579163001588b9a9_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e6579163001588b9a9_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e6579163001588b9ad],
  g_base_definitions[g_str_68c995e6579163001588b9af],
  g_base_definitions[g_str_68c995e6579163001588b9b1],
  g_base_definitions[g_str_68c995e6579163001588b9b3],
  g_base_definitions[g_str_5fb1b9efe1af06001770a093_camp],
  g_base_definitions[g_str_5fb1b9efe1af06001770a093_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9efe1af06001770a093"] = army["5fb1b9efe1af06001770a093"]
if nil == armies["Monsoon Region"] then
  armies["Monsoon Region"] ={}
end
armies["Monsoon Region"]["Early Sultanate of Delhi  1206 to 1295 AD"] = army["5fb1b9efe1af06001770a093"]
if nil == armies["Silk Road"] then
  armies["Silk Road"] ={}
end
armies["Silk Road"]["Early Sultanate of Delhi  1206 to 1295 AD"] = army["5fb1b9efe1af06001770a093"]
if nil == armies["India and the Khyber Pass"] then
  armies["India and the Khyber Pass"] ={}
end
armies["India and the Khyber Pass"]["Early Sultanate of Delhi  1206 to 1295 AD"] = army["5fb1b9efe1af06001770a093"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Sultanate of Delhi  1206 to 1295 AD"] = army["5fb1b9efe1af06001770a093"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9efe1af06001770a093"] = {}
army_dates["5fb1b9efe1af06001770a093"]["1206 AD to 1295 AD"] = {
  startDate=1206,
  endDate=1295
}
