-- 5fb1b9eae1af060017709e17 Pecheneg  850 to 1122 AD

army['5fb1b9eae1af060017709e17']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Steppe',
    },
    name='Pecheneg  850 to 1122 AD',
    id='5fb1b9eae1af060017709e17',
    dateRange={
      startDate=850,
      endDate=1122,
    },
  },
  g_base_definitions[g_str_68c995e2579163001588ae88_general],
  g_base_definitions[g_str_68c995e2579163001588ae88],
  g_base_definitions[g_str_68c995e2579163001588ae8a],
  g_base_definitions[g_str_68c995e2579163001588ae8a_shower_shooting],
  g_base_definitions[g_str_68c995e2579163001588ae8b],
  g_base_definitions[g_str_68c995e2579163001588ae8b_shower_shooting],
  g_base_definitions[g_str_68c995e2579163001588ae8c],
  g_base_definitions[g_str_68c995e2579163001588ae8c_shower_shooting],
  g_base_definitions[g_str_5fb1b9eae1af060017709e17_camp],
  g_base_definitions[g_str_5fb1b9eae1af060017709e17_camp_fortified],
  g_base_definitions[g_str_5fb1b9eae1af060017709e17_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eae1af060017709e17"] = army["5fb1b9eae1af060017709e17"]
if nil == armies["Russian Princes"] then
  armies["Russian Princes"] ={}
end
armies["Russian Princes"]["Pecheneg  850 to 1122 AD"] = army["5fb1b9eae1af060017709e17"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Pecheneg  850 to 1122 AD"] = army["5fb1b9eae1af060017709e17"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Pecheneg  850 to 1122 AD"] = army["5fb1b9eae1af060017709e17"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eae1af060017709e17"] = {}
army_dates["5fb1b9eae1af060017709e17"]["850 AD to 1122 AD"] = {
  startDate=850,
  endDate=1122
}
