-- 5fb1b9e9e1af060017709cf0 Later Medieval German Princes  1440 to 1493 AD

army['5fb1b9e9e1af060017709cf0']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Hilly',
      'Arable',
    },
    name='Later Medieval German Princes  1440 to 1493 AD',
    id='5fb1b9e9e1af060017709cf0',
    dateRange={
      startDate=1440,
      endDate=1493,
    },
  },
  g_base_definitions[g_str_68c995e0579163001588a985_general],
  g_base_definitions[g_str_68c995e0579163001588a985],
  g_base_definitions[g_str_68c995e0579163001588a987],
  g_base_definitions[g_str_68c995e0579163001588a989],
  g_base_definitions[g_str_68c995e0579163001588a98b],
  g_base_definitions[g_str_68c995e0579163001588a98d],
  g_base_definitions[g_str_68c995e0579163001588a98d_shower_shooting],
  g_base_definitions[g_str_68c995e0579163001588a990],
  g_base_definitions[g_str_68c995e0579163001588a993],
  g_base_definitions[g_str_68c995e0579163001588a994],
  g_base_definitions[g_str_68c995e0579163001588a997],
  g_base_definitions[g_str_68c995e0579163001588a997_shower_shooting],
  g_base_definitions[g_str_68c995e0579163001588a998],
  g_base_definitions[g_str_68c995e0579163001588a998_shower_shooting],
  g_base_definitions[g_str_68c995e0579163001588a99b],
  g_base_definitions[g_str_68c995e0579163001588a99e],
  g_base_definitions[g_str_68c995e0579163001588a9a1],
  g_base_definitions[g_str_68c995e0579163001588a9a3],
  g_base_definitions[g_str_5fb1b9e9e1af060017709cf0_camp],
  g_base_definitions[g_str_5fb1b9e9e1af060017709cf0_camp_fortified],
  g_base_definitions[g_str_5fb1b9e9e1af060017709cf0_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e9e1af060017709cf0"] = army["5fb1b9e9e1af060017709cf0"]
if nil == armies["Holy Roman Empire"] then
  armies["Holy Roman Empire"] ={}
end
armies["Holy Roman Empire"]["Later Medieval German Princes  1440 to 1493 AD"] = army["5fb1b9e9e1af060017709cf0"]
if nil == armies["Baltic Powers"] then
  armies["Baltic Powers"] ={}
end
armies["Baltic Powers"]["Later Medieval German Princes  1440 to 1493 AD"] = army["5fb1b9e9e1af060017709cf0"]
if nil == armies["Flower of Chivalry"] then
  armies["Flower of Chivalry"] ={}
end
armies["Flower of Chivalry"]["Later Medieval German Princes  1440 to 1493 AD"] = army["5fb1b9e9e1af060017709cf0"]
if nil == armies["Plate and Handgonne"] then
  armies["Plate and Handgonne"] ={}
end
armies["Plate and Handgonne"]["Later Medieval German Princes  1440 to 1493 AD"] = army["5fb1b9e9e1af060017709cf0"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Medieval German Princes  1440 to 1493 AD"] = army["5fb1b9e9e1af060017709cf0"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e9e1af060017709cf0"] = {}
army_dates["5fb1b9e9e1af060017709cf0"]["1440 AD to 1493 AD"] = {
  startDate=1440,
  endDate=1493
}
army_dates["5fb1b9e9e1af060017709cf0"]["1440 AD to 1441 AD"] = {
  startDate=1440,
  endDate=1441
}
army_dates["5fb1b9e9e1af060017709cf0"]["1442 AD to 1446 AD"] = {
  startDate=1442,
  endDate=1446
}
army_dates["5fb1b9e9e1af060017709cf0"]["1447 AD to 1477 AD"] = {
  startDate=1447,
  endDate=1477
}
army_dates["5fb1b9e9e1af060017709cf0"]["1478 AD to 1485 AD"] = {
  startDate=1478,
  endDate=1485
}
army_dates["5fb1b9e9e1af060017709cf0"]["1486 AD to 1493 AD"] = {
  startDate=1486,
  endDate=1493
}
