-- 5fb1b9f3e1af06001770a302 Early Ming Chinese  1350 to 1419 AD

army['5fb1b9f3e1af06001770a302']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
      'Hilly',
      'Forest',
    },
    name='Early Ming Chinese  1350 to 1419 AD',
    id='5fb1b9f3e1af06001770a302',
    dateRange={
      startDate=1350,
      endDate=1419,
    },
  },
  g_base_definitions[g_str_68c995ea579163001588c29d_general],
  g_base_definitions[g_str_68c995ea579163001588c29d],
  g_base_definitions[g_str_68c995ea579163001588c2a0_general],
  g_base_definitions[g_str_68c995ea579163001588c2a0],
  g_base_definitions[g_str_68c995ea579163001588c2a2_general],
  g_base_definitions[g_str_68c995ea579163001588c2a2],
  g_base_definitions[g_str_68c995ea579163001588c2a5_general],
  g_base_definitions[g_str_68c995ea579163001588c2a5],
  g_base_definitions[g_str_68c995ea579163001588c2a7],
  g_base_definitions[g_str_68c995ea579163001588c2aa],
  g_base_definitions[g_str_68c995ea579163001588c2ab],
  g_base_definitions[g_str_68c995ea579163001588c2ad],
  g_base_definitions[g_str_68c995ea579163001588c2ae],
  g_base_definitions[g_str_68c995ea579163001588c2b0],
  g_base_definitions[g_str_68c995ea579163001588c2b1],
  g_base_definitions[g_str_68c995ea579163001588c2b3],
  g_base_definitions[g_str_5fb1b9f3e1af06001770a302_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f3e1af06001770a302"] = army["5fb1b9f3e1af06001770a302"]
if nil == armies["Middle Kingdom"] then
  armies["Middle Kingdom"] ={}
end
armies["Middle Kingdom"]["Early Ming Chinese  1350 to 1419 AD"] = army["5fb1b9f3e1af06001770a302"]
if nil == armies["Southeast Asia"] then
  armies["Southeast Asia"] ={}
end
armies["Southeast Asia"]["Early Ming Chinese  1350 to 1419 AD"] = army["5fb1b9f3e1af06001770a302"]
if nil == armies["Korea and Japan"] then
  armies["Korea and Japan"] ={}
end
armies["Korea and Japan"]["Early Ming Chinese  1350 to 1419 AD"] = army["5fb1b9f3e1af06001770a302"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Ming Chinese  1350 to 1419 AD"] = army["5fb1b9f3e1af06001770a302"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f3e1af06001770a302"] = {}
army_dates["5fb1b9f3e1af06001770a302"]["1350 AD to 1419 AD"] = {
  startDate=1350,
  endDate=1419
}
army_dates["5fb1b9f3e1af06001770a302"]["1350 AD to 1359 AD"] = {
  startDate=1350,
  endDate=1359
}
army_dates["5fb1b9f3e1af06001770a302"]["1360 AD to 1419 AD"] = {
  startDate=1360,
  endDate=1419
}
