-- 5fb1b9e5e1af060017709ab6 Dublin or Manx Vikings  842 to 1229 AD

army['5fb1b9e5e1af060017709ab6']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Arable',
    },
    name='Dublin or Manx Vikings  842 to 1229 AD',
    id='5fb1b9e5e1af060017709ab6',
    dateRange={
      startDate=842,
      endDate=1229,
    },
  },
  g_base_definitions[g_str_68c995de579163001588a0f6_general],
  g_base_definitions[g_str_68c995de579163001588a0f6],
  g_base_definitions[g_str_68c995de579163001588a0f9],
  g_base_definitions[g_str_68c995de579163001588a0f9_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995de579163001588a0f9_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995de579163001588a0fc],
  g_base_definitions[g_str_68c995de579163001588a0fc_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995de579163001588a0fc_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995de579163001588a0ff],
  g_base_definitions[g_str_68c995de579163001588a100],
  g_base_definitions[g_str_68c995de579163001588a103],
  g_base_definitions[g_str_68c995de579163001588a103_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995de579163001588a103_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995de579163001588a106],
  g_base_definitions[g_str_5fb1b9e5e1af060017709ab6_camp],
  g_base_definitions[g_str_5fb1b9e5e1af060017709ab6_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e5e1af060017709ab6"] = army["5fb1b9e5e1af060017709ab6"]
if nil == armies["Viking Seas"] then
  armies["Viking Seas"] ={}
end
armies["Viking Seas"]["Dublin or Manx Vikings  842 to 1229 AD"] = army["5fb1b9e5e1af060017709ab6"]
if nil == armies["Embattled Isle"] then
  armies["Embattled Isle"] ={}
end
armies["Embattled Isle"]["Dublin or Manx Vikings  842 to 1229 AD"] = army["5fb1b9e5e1af060017709ab6"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Dublin or Manx Vikings  842 to 1229 AD"] = army["5fb1b9e5e1af060017709ab6"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e5e1af060017709ab6"] = {}
army_dates["5fb1b9e5e1af060017709ab6"]["842 AD to 1229 AD"] = {
  startDate=842,
  endDate=1229
}
army_dates["5fb1b9e5e1af060017709ab6"]["842 AD to 1053 AD"] = {
  startDate=842,
  endDate=1053
}
army_dates["5fb1b9e5e1af060017709ab6"]["1054 AD to 1229 AD"] = {
  startDate=1054,
  endDate=1229
}
