-- 5fb1b9dbe1af0600177094e3 Early Hoplite Theban  669 to 449 BC

army['5fb1b9dbe1af0600177094e3']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Early Hoplite Theban  669 to 449 BC',
    id='5fb1b9dbe1af0600177094e3',
    dateRange={
      startDate=-669,
      endDate=-449,
    },
  },
  g_base_definitions[g_str_68c995d55791630015888b71_general],
  g_base_definitions[g_str_68c995d55791630015888b71],
  g_base_definitions[g_str_68c995d55791630015888b73],
  g_base_definitions[g_str_68c995d55791630015888b75],
  g_base_definitions[g_str_68c995d55791630015888b77],
  g_base_definitions[g_str_5fb1b9dbe1af0600177094e3_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dbe1af0600177094e3"] = army["5fb1b9dbe1af0600177094e3"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Early Hoplite Theban  669 to 449 BC"] = army["5fb1b9dbe1af0600177094e3"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Hoplite Theban  669 to 449 BC"] = army["5fb1b9dbe1af0600177094e3"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dbe1af0600177094e3"] = {}
army_dates["5fb1b9dbe1af0600177094e3"]["669 BC to 449 BC"] = {
  startDate=-669,
  endDate=-449
}
