-- 5fb1b9e4e1af060017709a18 Maurikian Byzantine  575 to 650 AD

army['5fb1b9e4e1af060017709a18']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      3,
      4,
    },
    homeTopographies={
      'Arable',
      'Dry',
      'Hilly',
    },
    name='Maurikian Byzantine  575 to 650 AD',
    id='5fb1b9e4e1af060017709a18',
    dateRange={
      startDate=575,
      endDate=650,
    },
  },
  g_base_definitions[g_str_68c995dd5791630015889ee9_general],
  g_base_definitions[g_str_68c995dd5791630015889ee9_general_shower_shooting],
  g_base_definitions[g_str_68c995dd5791630015889ee9],
  g_base_definitions[g_str_68c995dd5791630015889ee9_shower_shooting],
  g_base_definitions[g_str_68c995dd5791630015889eec],
  g_base_definitions[g_str_68c995dd5791630015889eee],
  g_base_definitions[g_str_68c995dd5791630015889ef0],
  g_base_definitions[g_str_68c995dd5791630015889ef3],
  g_base_definitions[g_str_68c995dd5791630015889ef6],
  g_base_definitions[g_str_68c995dd5791630015889ef8],
  g_base_definitions[g_str_5fb1b9e4e1af060017709a18_camp],
  g_base_definitions[g_str_5fb1b9e4e1af060017709a18_camp_fortified],
  g_base_definitions[g_str_5fb1b9e4e1af060017709a18_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e4e1af060017709a18"] = army["5fb1b9e4e1af060017709a18"]
if nil == armies["Dark Ages"] then
  armies["Dark Ages"] ={}
end
armies["Dark Ages"]["Maurikian Byzantine  575 to 650 AD"] = army["5fb1b9e4e1af060017709a18"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Maurikian Byzantine  575 to 650 AD"] = army["5fb1b9e4e1af060017709a18"]
if nil == armies["Spread of Islam"] then
  armies["Spread of Islam"] ={}
end
armies["Spread of Islam"]["Maurikian Byzantine  575 to 650 AD"] = army["5fb1b9e4e1af060017709a18"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Maurikian Byzantine  575 to 650 AD"] = army["5fb1b9e4e1af060017709a18"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e4e1af060017709a18"] = {}
army_dates["5fb1b9e4e1af060017709a18"]["575 AD to 650 AD"] = {
  startDate=575,
  endDate=650
}
army_dates["5fb1b9e4e1af060017709a18"]["575 AD to 576 AD"] = {
  startDate=575,
  endDate=576
}
army_dates["5fb1b9e4e1af060017709a18"]["577 AD to 590 AD"] = {
  startDate=577,
  endDate=590
}
army_dates["5fb1b9e4e1af060017709a18"]["591 AD to 608 AD"] = {
  startDate=591,
  endDate=608
}
army_dates["5fb1b9e4e1af060017709a18"]["609 AD to 628 AD"] = {
  startDate=609,
  endDate=628
}
army_dates["5fb1b9e4e1af060017709a18"]["629 AD to 633 AD"] = {
  startDate=629,
  endDate=633
}
army_dates["5fb1b9e4e1af060017709a18"]["634 AD to 650 AD"] = {
  startDate=634,
  endDate=650
}
