-- 5fb1b9eae1af060017709e02 Khazar Empire  738 to 965 AD

army['5fb1b9eae1af060017709e02']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Steppe',
    },
    name='Khazar Empire  738 to 965 AD',
    id='5fb1b9eae1af060017709e02',
    dateRange={
      startDate=738,
      endDate=965,
    },
  },
  g_base_definitions[g_str_68c995e2579163001588ae40_general],
  g_base_definitions[g_str_68c995e2579163001588ae40],
  g_base_definitions[g_str_68c995e2579163001588ae43_general],
  g_base_definitions[g_str_68c995e2579163001588ae43],
  g_base_definitions[g_str_68c995e2579163001588ae45],
  g_base_definitions[g_str_68c995e2579163001588ae45_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e2579163001588ae45_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e2579163001588ae48_general],
  g_base_definitions[g_str_68c995e2579163001588ae48],
  g_base_definitions[g_str_68c995e2579163001588ae4a],
  g_base_definitions[g_str_68c995e2579163001588ae4c],
  g_base_definitions[g_str_68c995e2579163001588ae4c_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e2579163001588ae4c_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e2579163001588ae4f],
  g_base_definitions[g_str_68c995e2579163001588ae51],
  g_base_definitions[g_str_68c995e2579163001588ae53],
  g_base_definitions[g_str_5fb1b9eae1af060017709e02_camp],
  g_base_definitions[g_str_5fb1b9eae1af060017709e02_camp_fortified],
  g_base_definitions[g_str_5fb1b9eae1af060017709e02_camp_standard_wagon],
  g_base_definitions[g_str_68c995cc57916300158879fb_general],
  g_base_definitions[g_str_68c995cc57916300158879fb],
  g_base_definitions[g_str_68c995cc57916300158879fd],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eae1af060017709e02"] = army["5fb1b9eae1af060017709e02"]
if nil == armies["Russian Princes"] then
  armies["Russian Princes"] ={}
end
armies["Russian Princes"]["Khazar Empire  738 to 965 AD"] = army["5fb1b9eae1af060017709e02"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Khazar Empire  738 to 965 AD"] = army["5fb1b9eae1af060017709e02"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Khazar Empire  738 to 965 AD"] = army["5fb1b9eae1af060017709e02"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eae1af060017709e02"] = {}
army_dates["5fb1b9eae1af060017709e02"]["738 AD to 965 AD"] = {
  startDate=738,
  endDate=965
}
army_dates["5fb1b9eae1af060017709e02"]["738 AD to 779 AD"] = {
  startDate=738,
  endDate=779
}
army_dates["5fb1b9eae1af060017709e02"]["780 AD to 965 AD"] = {
  startDate=780,
  endDate=965
}
