-- 5fb1b9e1e1af060017709813 First Servile War  135 to 132 BC

army['5fb1b9e1e1af060017709813']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Arable',
      'Hilly',
    },
    name='First Servile War  135 to 132 BC',
    id='5fb1b9e1e1af060017709813',
    dateRange={
      startDate=-135,
      endDate=-132,
    },
  },
  g_base_definitions[g_str_68c995da5791630015889808_general],
  g_base_definitions[g_str_68c995da5791630015889808],
  g_base_definitions[g_str_68c995da579163001588980a],
  g_base_definitions[g_str_68c995da579163001588980c],
  g_base_definitions[g_str_5fb1b9e1e1af060017709813_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e1e1af060017709813"] = army["5fb1b9e1e1af060017709813"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["First Servile War  135 to 132 BC"] = army["5fb1b9e1e1af060017709813"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["First Servile War  135 to 132 BC"] = army["5fb1b9e1e1af060017709813"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e1e1af060017709813"] = {}
army_dates["5fb1b9e1e1af060017709813"]["135 BC to 132 BC"] = {
  startDate=-135,
  endDate=-132
}
