-- 5fb1b9f0e1af06001770a0bc Vijayanagar Empire  1336 to 1510 AD

army['5fb1b9f0e1af06001770a0bc']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
      'Forest',
    },
    name='Vijayanagar Empire  1336 to 1510 AD',
    id='5fb1b9f0e1af06001770a0bc',
    dateRange={
      startDate=1336,
      endDate=1510,
    },
  },
  g_base_definitions[g_str_68c995e6579163001588ba46_general],
  g_base_definitions[g_str_68c995e6579163001588ba46],
  g_base_definitions[g_str_68c995e6579163001588ba4a],
  g_base_definitions[g_str_68c995e6579163001588ba4c_general],
  g_base_definitions[g_str_68c995e6579163001588ba4c],
  g_base_definitions[g_str_68c995e6579163001588ba4d_general],
  g_base_definitions[g_str_68c995e6579163001588ba4d],
  g_base_definitions[g_str_68c995e6579163001588ba4f_general],
  g_base_definitions[g_str_68c995e6579163001588ba4f_general_shower_shooting],
  g_base_definitions[g_str_68c995e6579163001588ba4f],
  g_base_definitions[g_str_68c995e6579163001588ba4f_shower_shooting],
  g_base_definitions[g_str_68c995e6579163001588ba50],
  g_base_definitions[g_str_68c995e6579163001588ba50_shower_shooting],
  g_base_definitions[g_str_68c995e6579163001588ba53_general],
  g_base_definitions[g_str_68c995e6579163001588ba53_general_elephant_screen],
  g_base_definitions[g_str_68c995e6579163001588ba53],
  g_base_definitions[g_str_68c995e6579163001588ba53_elephant_screen],
  g_base_definitions[g_str_68c995e6579163001588ba56],
  g_base_definitions[g_str_68c995e6579163001588ba56_elephant_screen],
  g_base_definitions[g_str_68c995e6579163001588ba59],
  g_base_definitions[g_str_68c995e6579163001588ba59_elephant_screen],
  g_base_definitions[g_str_68c995e6579163001588ba5c],
  g_base_definitions[g_str_68c995e6579163001588ba5c_elephant_screen],
  g_base_definitions[g_str_68c995e6579163001588ba5c_shower_shooting],
  g_base_definitions[g_str_68c995e6579163001588ba60],
  g_base_definitions[g_str_68c995e6579163001588ba62],
  g_base_definitions[g_str_68c995e6579163001588ba65],
  g_base_definitions[g_str_5fb1b9f0e1af06001770a0bc_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f0e1af06001770a0bc"] = army["5fb1b9f0e1af06001770a0bc"]
if nil == armies["Monsoon Region"] then
  armies["Monsoon Region"] ={}
end
armies["Monsoon Region"]["Vijayanagar Empire  1336 to 1510 AD"] = army["5fb1b9f0e1af06001770a0bc"]
if nil == armies["Southeast Asia"] then
  armies["Southeast Asia"] ={}
end
armies["Southeast Asia"]["Vijayanagar Empire  1336 to 1510 AD"] = army["5fb1b9f0e1af06001770a0bc"]
if nil == armies["India and the Khyber Pass"] then
  armies["India and the Khyber Pass"] ={}
end
armies["India and the Khyber Pass"]["Vijayanagar Empire  1336 to 1510 AD"] = army["5fb1b9f0e1af06001770a0bc"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Vijayanagar Empire  1336 to 1510 AD"] = army["5fb1b9f0e1af06001770a0bc"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f0e1af06001770a0bc"] = {}
army_dates["5fb1b9f0e1af06001770a0bc"]["1336 AD to 1510 AD"] = {
  startDate=1336,
  endDate=1510
}
