-- 5fb1b9f1e1af06001770a195 Later Warring States Chinese  355 to 202 BC

army['5fb1b9f1e1af06001770a195']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      3,
      1,
    },
    homeTopographies={
      'Forest',
      'Arable',
    },
    name='Later Warring States Chinese  355 to 202 BC',
    id='5fb1b9f1e1af06001770a195',
    dateRange={
      startDate=-355,
      endDate=-202,
    },
  },
  g_base_definitions[g_str_68c995e8579163001588bd22_general],
  g_base_definitions[g_str_68c995e8579163001588bd22],
  g_base_definitions[g_str_68c995e8579163001588bd26_general],
  g_base_definitions[g_str_68c995e8579163001588bd26_general_mounted],
  g_base_definitions[g_str_68c995e8579163001588bd26_general_dismounted],
  g_base_definitions[g_str_68c995e8579163001588bd26],
  g_base_definitions[g_str_68c995e8579163001588bd26_mounted],
  g_base_definitions[g_str_68c995e8579163001588bd26_dismounted],
  g_base_definitions[g_str_68c995e8579163001588bd2a],
  g_base_definitions[g_str_68c995e8579163001588bd2d],
  g_base_definitions[g_str_68c995e8579163001588bd31],
  g_base_definitions[g_str_68c995e8579163001588bd33],
  g_base_definitions[g_str_68c995e8579163001588bd35],
  g_base_definitions[g_str_68c995e8579163001588bd38],
  g_base_definitions[g_str_68c995e8579163001588bd38_shower_shooting],
  g_base_definitions[g_str_68c995e8579163001588bd3b],
  g_base_definitions[g_str_68c995e8579163001588bd3d],
  g_base_definitions[g_str_68c995e8579163001588bd41],
  g_base_definitions[g_str_68c995e8579163001588bd43],
  g_base_definitions[g_str_68c995e8579163001588bd45],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a195_camp],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a195_camp_fortified],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a195_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f1e1af06001770a195"] = army["5fb1b9f1e1af06001770a195"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Later Warring States Chinese  355 to 202 BC"] = army["5fb1b9f1e1af06001770a195"]
if nil == armies["Southeast Asia"] then
  armies["Southeast Asia"] ={}
end
armies["Southeast Asia"]["Later Warring States Chinese  355 to 202 BC"] = army["5fb1b9f1e1af06001770a195"]
if nil == armies["Warring States"] then
  armies["Warring States"] ={}
end
armies["Warring States"]["Later Warring States Chinese  355 to 202 BC"] = army["5fb1b9f1e1af06001770a195"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Warring States Chinese  355 to 202 BC"] = army["5fb1b9f1e1af06001770a195"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f1e1af06001770a195"] = {}
army_dates["5fb1b9f1e1af06001770a195"]["355 BC to 202 BC"] = {
  startDate=-355,
  endDate=-202
}
