-- 5fb1b9dbe1af0600177094cb Umbrian Italian  650 to 290 BC

army['5fb1b9dbe1af0600177094cb']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Umbrian Italian  650 to 290 BC',
    id='5fb1b9dbe1af0600177094cb',
    dateRange={
      startDate=-650,
      endDate=-290,
    },
  },
  g_base_definitions[g_str_68c995d55791630015888b11_general],
  g_base_definitions[g_str_68c995d55791630015888b11],
  g_base_definitions[g_str_68c995d55791630015888b13],
  g_base_definitions[g_str_68c995d55791630015888b15],
  g_base_definitions[g_str_68c995d55791630015888b17],
  g_base_definitions[g_str_68c995d55791630015888b19],
  g_base_definitions[g_str_5fb1b9dbe1af0600177094cb_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dbe1af0600177094cb"] = army["5fb1b9dbe1af0600177094cb"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Umbrian Italian  650 to 290 BC"] = army["5fb1b9dbe1af0600177094cb"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Umbrian Italian  650 to 290 BC"] = army["5fb1b9dbe1af0600177094cb"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dbe1af0600177094cb"] = {}
army_dates["5fb1b9dbe1af0600177094cb"]["650 BC to 290 BC"] = {
  startDate=-650,
  endDate=-290
}
