-- 5fb1b9f5e1af06001770a3d4 Teotihuacan Decline  651 to 750 AD

army['5fb1b9f5e1af06001770a3d4']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Hilly',
    },
    name='Teotihuacan Decline  651 to 750 AD',
    id='5fb1b9f5e1af06001770a3d4',
    dateRange={
      startDate=651,
      endDate=750,
    },
    ambush=true,  },
  g_base_definitions[g_str_68c995eb579163001588c4df_general],
  g_base_definitions[g_str_68c995eb579163001588c4df],
  g_base_definitions[g_str_68c995eb579163001588c4e0_general],
  g_base_definitions[g_str_68c995eb579163001588c4e0],
  g_base_definitions[g_str_68c995eb579163001588c4e2_general],
  g_base_definitions[g_str_68c995eb579163001588c4e2],
  g_base_definitions[g_str_68c995eb579163001588c4e4],
  g_base_definitions[g_str_68c995eb579163001588c4e6],
  g_base_definitions[g_str_68c995eb579163001588c4e8],
  g_base_definitions[g_str_5fb1b9f5e1af06001770a3d4_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f5e1af06001770a3d4"] = army["5fb1b9f5e1af06001770a3d4"]
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["Teotihuacan Decline  651 to 750 AD"] = army["5fb1b9f5e1af06001770a3d4"]
if nil == armies["Mexico"] then
  armies["Mexico"] ={}
end
armies["Mexico"]["Teotihuacan Decline  651 to 750 AD"] = army["5fb1b9f5e1af06001770a3d4"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Teotihuacan Decline  651 to 750 AD"] = army["5fb1b9f5e1af06001770a3d4"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f5e1af06001770a3d4"] = {}
army_dates["5fb1b9f5e1af06001770a3d4"]["651 AD to 750 AD"] = {
  startDate=651,
  endDate=750
}
