-- 5fb1b9d9e1af0600177093b4 Sea Peoples  1213 to 1176 BC

army['5fb1b9d9e1af0600177093b4']={
  data={
    invasionRatings={
      4,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Delta',
    },
    name='Sea Peoples  1213 to 1176 BC',
    id='5fb1b9d9e1af0600177093b4',
    dateRange={
      startDate=-1213,
      endDate=-1176,
    },
  },
  g_base_definitions[g_str_68c995d357916300158886c1_general],
  g_base_definitions[g_str_68c995d357916300158886c1],
  g_base_definitions[g_str_68c995d357916300158886c3_general],
  g_base_definitions[g_str_68c995d357916300158886c3],
  g_base_definitions[g_str_68c995d357916300158886c5_general],
  g_base_definitions[g_str_68c995d357916300158886c5],
  g_base_definitions[g_str_68c995d357916300158886c7],
  g_base_definitions[g_str_68c995d357916300158886c9],
  g_base_definitions[g_str_68c995d357916300158886cb],
  g_base_definitions[g_str_5fb1b9d9e1af0600177093b4_camp],
  g_base_definitions[g_str_5fb1b9d9e1af0600177093b4_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9d9e1af0600177093b4"] = army["5fb1b9d9e1af0600177093b4"]
if nil == armies["Chariot Supremacy"] then
  armies["Chariot Supremacy"] ={}
end
armies["Chariot Supremacy"]["Sea Peoples  1213 to 1176 BC"] = army["5fb1b9d9e1af0600177093b4"]
if nil == armies["Sea Peoples Invasions"] then
  armies["Sea Peoples Invasions"] ={}
end
armies["Sea Peoples Invasions"]["Sea Peoples  1213 to 1176 BC"] = army["5fb1b9d9e1af0600177093b4"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Sea Peoples  1213 to 1176 BC"] = army["5fb1b9d9e1af0600177093b4"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9d9e1af0600177093b4"] = {}
army_dates["5fb1b9d9e1af0600177093b4"]["1213 BC to 1176 BC"] = {
  startDate=-1213,
  endDate=-1176
}
