-- 5fb1b9dce1af060017709597 Thapsus Campaign  47 to 46 BC

army['5fb1b9dce1af060017709597']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
    },
    name='Thapsus Campaign  47 to 46 BC',
    id='5fb1b9dce1af060017709597',
    dateRange={
      startDate=-47,
      endDate=-46,
    },
  },
  g_base_definitions[g_str_68c995d75791630015888e3a_general],
  g_base_definitions[g_str_68c995d75791630015888e3a],
  g_base_definitions[g_str_68c995d75791630015888e3c_general],
  g_base_definitions[g_str_68c995d75791630015888e3c],
  g_base_definitions[g_str_68c995d75791630015888e3e],
  g_base_definitions[g_str_68c995d75791630015888e3f],
  g_base_definitions[g_str_68c995d75791630015888e41],
  g_base_definitions[g_str_68c995d75791630015888e43],
  g_base_definitions[g_str_68c995d75791630015888e45],
  g_base_definitions[g_str_68c995d75791630015888e47],
  g_base_definitions[g_str_5fb1b9dce1af060017709597_camp],
  g_base_definitions[g_str_5fb1b9dce1af060017709597_camp_fortified],
  g_base_definitions[g_str_5fb1b9dce1af060017709597_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dce1af060017709597"] = army["5fb1b9dce1af060017709597"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Thapsus Campaign  47 to 46 BC"] = army["5fb1b9dce1af060017709597"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Thapsus Campaign  47 to 46 BC"] = army["5fb1b9dce1af060017709597"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dce1af060017709597"] = {}
army_dates["5fb1b9dce1af060017709597"]["47 BC to 46 BC"] = {
  startDate=-47,
  endDate=-46
}
