-- 5fb1b9ece1af060017709ed1 Horn of Africa smaller states  1285 to 1529 AD

army['5fb1b9ece1af060017709ed1']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Hilly',
    },
    name='Horn of Africa smaller states  1285 to 1529 AD',
    id='5fb1b9ece1af060017709ed1',
    dateRange={
      startDate=1285,
      endDate=1529,
    },
  },
  g_base_definitions[g_str_68c995e4579163001588b1e4_general],
  g_base_definitions[g_str_68c995e4579163001588b1e4],
  g_base_definitions[g_str_68c995e4579163001588b1e6],
  g_base_definitions[g_str_68c995e4579163001588b1e8],
  g_base_definitions[g_str_68c995e4579163001588b1e8_shower_shooting],
  g_base_definitions[g_str_68c995e4579163001588b1e9],
  g_base_definitions[g_str_68c995e4579163001588b1e9_shower_shooting],
  g_base_definitions[g_str_68c995e4579163001588b1ec],
  g_base_definitions[g_str_68c995e4579163001588b1ee],
  g_base_definitions[g_str_68c995e4579163001588b1f0],
  g_base_definitions[g_str_68c995e4579163001588b1f0_light_camelry],
  g_base_definitions[g_str_68c995e4579163001588b1f3],
  g_base_definitions[g_str_5fb1b9ece1af060017709ed1_camp],
  g_base_definitions[g_str_5fb1b9ece1af060017709ed1_camp_fortified],
  g_base_definitions[g_str_5fb1b9ece1af060017709ed1_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ece1af060017709ed1"] = army["5fb1b9ece1af060017709ed1"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Horn of Africa smaller states  1285 to 1529 AD"] = army["5fb1b9ece1af060017709ed1"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Horn of Africa smaller states  1285 to 1529 AD"] = army["5fb1b9ece1af060017709ed1"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ece1af060017709ed1"] = {}
army_dates["5fb1b9ece1af060017709ed1"]["1285 AD to 1529 AD"] = {
  startDate=1285,
  endDate=1529
}
