-- 5fb1b9dfe1af060017709766 Later Pre-Islamic Arab City  312 BC to 633 AD

army['5fb1b9dfe1af060017709766']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Dry',
    },
    name='Later Pre-Islamic Arab City  312 BC to 633 AD',
    id='5fb1b9dfe1af060017709766',
    dateRange={
      startDate=-312,
      endDate=633,
    },
  },
  g_base_definitions[g_str_68c995d957916300158895c2_general],
  g_base_definitions[g_str_68c995d957916300158895c2],
  g_base_definitions[g_str_68c995d957916300158895c4],
  g_base_definitions[g_str_68c995d957916300158895c4_light_camelry],
  g_base_definitions[g_str_68c995d957916300158895c7],
  g_base_definitions[g_str_68c995d957916300158895c9],
  g_base_definitions[g_str_68c995d957916300158895cb],
  g_base_definitions[g_str_68c995d957916300158895cb_shower_shooting],
  g_base_definitions[g_str_68c995d957916300158895cc],
  g_base_definitions[g_str_68c995d957916300158895cc_shower_shooting],
  g_base_definitions[g_str_68c995d957916300158895cf],
  g_base_definitions[g_str_68c995d957916300158895d1],
  g_base_definitions[g_str_5fb1b9dfe1af060017709766_camp],
  g_base_definitions[g_str_5fb1b9dfe1af060017709766_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dfe1af060017709766"] = army["5fb1b9dfe1af060017709766"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Later Pre-Islamic Arab City  312 BC to 633 AD"] = army["5fb1b9dfe1af060017709766"]
if nil == armies["Spread of Islam"] then
  armies["Spread of Islam"] ={}
end
armies["Spread of Islam"]["Later Pre-Islamic Arab City  312 BC to 633 AD"] = army["5fb1b9dfe1af060017709766"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Later Pre-Islamic Arab City  312 BC to 633 AD"] = army["5fb1b9dfe1af060017709766"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Pre-Islamic Arab City  312 BC to 633 AD"] = army["5fb1b9dfe1af060017709766"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dfe1af060017709766"] = {}
army_dates["5fb1b9dfe1af060017709766"]["312 BC to 633 AD"] = {
  startDate=-312,
  endDate=633
}
army_dates["5fb1b9dfe1af060017709766"]["312 BC to 349 AD"] = {
  startDate=-312,
  endDate=349
}
army_dates["5fb1b9dfe1af060017709766"]["350 AD to 530 AD"] = {
  startDate=350,
  endDate=530
}
army_dates["5fb1b9dfe1af060017709766"]["531 AD to 576 AD"] = {
  startDate=531,
  endDate=576
}
army_dates["5fb1b9dfe1af060017709766"]["577 AD to 633 AD"] = {
  startDate=577,
  endDate=633
}
