g_str_68c995dd5791630015889eac_general='68c995dd5791630015889eac_general'
g_base_definitions[g_str_68c995dd5791630015889eac_general]={
  id=g_str_68c995dd5791630015889eac_general,
  name='Horse Bow General',
  min=10,
  max=1,
  description='Boyars and Bulgar horse archers',
  general=true,
  troop_type="Horse Bow",
  troop_option_id="68c995dd5791630015889eab",
}
g_str_68c995dd5791630015889eac='68c995dd5791630015889eac'
g_base_definitions[g_str_68c995dd5791630015889eac]={
  id=g_str_68c995dd5791630015889eac,
  name='Horse Bow',
  min=10,
  max=12,
  description='Boyars and Bulgar horse archers',
  troop_type="Horse Bow",
  troop_option_id="68c995dd5791630015889eab",
}
g_str_68c995dd5791630015889eae='68c995dd5791630015889eae'
g_base_definitions[g_str_68c995dd5791630015889eae]={
  id=g_str_68c995dd5791630015889eae,
  name='Horde',
  min=0,
  max=2,
  description='Camp defenders',
  troop_type="Horde",
  troop_option_id="68c995dd5791630015889ead",
}
g_str_5fb1b9e4e1af0600177099fc_camp='5fb1b9e4e1af0600177099fc_camp'
g_base_definitions[g_str_5fb1b9e4e1af0600177099fc_camp]={
  id=g_str_5fb1b9e4e1af0600177099fc_camp,
  name='Camp',
  min=0,
  max=1,
  description='Camp',
  troop_type="Camp",
}
g_str_5fb1b9e4e1af0600177099fc_camp_fortified='5fb1b9e4e1af0600177099fc_camp_fortified'
g_base_definitions[g_str_5fb1b9e4e1af0600177099fc_camp_fortified]={
  id=g_str_5fb1b9e4e1af0600177099fc_camp_fortified,
  name='Camp',
  min=0,
  max=1,
  description='Fortified camp',
  fortified_camp=true,
  troop_type="Camp",
}
g_str_5fb1b9e4e1af0600177099fc_camp_pack_train='5fb1b9e4e1af0600177099fc_camp_pack_train'
g_base_definitions[g_str_5fb1b9e4e1af0600177099fc_camp_pack_train]={
  id=g_str_5fb1b9e4e1af0600177099fc_camp_pack_train,
  name='Camp',
  min=0,
  max=1,
  description='Pack Train',
  pack_train=true,
  troop_type="Camp",
}
g_str_5fb1b9e4e1af0600177099fc_prepared_defenses='5fb1b9e4e1af0600177099fc_prepared_defenses'
g_base_definitions[g_str_5fb1b9e4e1af0600177099fc_prepared_defenses]={
  id=g_str_5fb1b9e4e1af0600177099fc_prepared_defenses,
  name='Prepared Defenses',
  min=0,
  max=4,
  description='Ditch and Palisade, or Abatis',
  prepared_defenses=true,
  troop_type="Prepared Defenses",
}
