-- 5fb1b9efe1af06001770a09b Later Muslim Indian  1296 to 1526 AD

army['5fb1b9efe1af06001770a09b']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
    },
    name='Later Muslim Indian  1296 to 1526 AD',
    id='5fb1b9efe1af06001770a09b',
    dateRange={
      startDate=1296,
      endDate=1526,
    },
  },
  g_base_definitions[g_str_68c995e6579163001588b9b8_general],
  g_base_definitions[g_str_68c995e6579163001588b9b8_general_shower_shooting],
  g_base_definitions[g_str_68c995e6579163001588b9b8],
  g_base_definitions[g_str_68c995e6579163001588b9b8_shower_shooting],
  g_base_definitions[g_str_68c995e6579163001588b9bb_general],
  g_base_definitions[g_str_68c995e6579163001588b9bb],
  g_base_definitions[g_str_68c995e6579163001588b9bd],
  g_base_definitions[g_str_68c995e6579163001588b9c0],
  g_base_definitions[g_str_68c995e6579163001588b9c2],
  g_base_definitions[g_str_68c995e6579163001588b9c5],
  g_base_definitions[g_str_68c995e6579163001588b9c5_plaustrella],
  g_base_definitions[g_str_68c995e6579163001588b9c8],
  g_base_definitions[g_str_68c995e6579163001588b9c8_shower_shooting],
  g_base_definitions[g_str_68c995e6579163001588b9c8_elephant_screen],
  g_base_definitions[g_str_68c995e6579163001588b9c8_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e6579163001588b9c8_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e6579163001588b9cd],
  g_base_definitions[g_str_68c995e6579163001588b9cd_elephant_screen],
  g_base_definitions[g_str_68c995e6579163001588b9d0],
  g_base_definitions[g_str_68c995e6579163001588b9d0_elephant_screen],
  g_base_definitions[g_str_68c995e6579163001588b9d3],
  g_base_definitions[g_str_68c995e6579163001588b9d3_elephant_screen],
  g_base_definitions[g_str_68c995e6579163001588b9d6],
  g_base_definitions[g_str_68c995e6579163001588b9d9],
  g_base_definitions[g_str_5fb1b9efe1af06001770a09b_camp],
  g_base_definitions[g_str_5fb1b9efe1af06001770a09b_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9efe1af06001770a09b"] = army["5fb1b9efe1af06001770a09b"]
if nil == armies["Monsoon Region"] then
  armies["Monsoon Region"] ={}
end
armies["Monsoon Region"]["Later Muslim Indian  1296 to 1526 AD"] = army["5fb1b9efe1af06001770a09b"]
if nil == armies["Silk Road"] then
  armies["Silk Road"] ={}
end
armies["Silk Road"]["Later Muslim Indian  1296 to 1526 AD"] = army["5fb1b9efe1af06001770a09b"]
if nil == armies["India and the Khyber Pass"] then
  armies["India and the Khyber Pass"] ={}
end
armies["India and the Khyber Pass"]["Later Muslim Indian  1296 to 1526 AD"] = army["5fb1b9efe1af06001770a09b"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Muslim Indian  1296 to 1526 AD"] = army["5fb1b9efe1af06001770a09b"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9efe1af06001770a09b"] = {}
army_dates["5fb1b9efe1af06001770a09b"]["1296 AD to 1526 AD"] = {
  startDate=1296,
  endDate=1526
}
army_dates["5fb1b9efe1af06001770a09b"]["1296 AD to 1510 AD"] = {
  startDate=1296,
  endDate=1510
}
army_dates["5fb1b9efe1af06001770a09b"]["1511 AD to 1526 AD"] = {
  startDate=1511,
  endDate=1526
}
