-- 5fb1b9ede1af060017709fad Zengid Dynasties in Syria  1092 to 1286 AD

army['5fb1b9ede1af060017709fad']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
      'Dry',
    },
    name='Zengid Dynasties in Syria  1092 to 1286 AD',
    id='5fb1b9ede1af060017709fad',
    dateRange={
      startDate=1092,
      endDate=1286,
    },
  },
  g_base_definitions[g_str_68c995e5579163001588b591_general],
  g_base_definitions[g_str_68c995e5579163001588b591_general_shower_shooting],
  g_base_definitions[g_str_68c995e5579163001588b591],
  g_base_definitions[g_str_68c995e5579163001588b591_shower_shooting],
  g_base_definitions[g_str_68c995e5579163001588b594_general],
  g_base_definitions[g_str_68c995e5579163001588b594],
  g_base_definitions[g_str_68c995e5579163001588b596_general],
  g_base_definitions[g_str_68c995e5579163001588b596],
  g_base_definitions[g_str_68c995e5579163001588b598_general],
  g_base_definitions[g_str_68c995e5579163001588b598],
  g_base_definitions[g_str_68c995e5579163001588b59a],
  g_base_definitions[g_str_68c995e5579163001588b59c],
  g_base_definitions[g_str_68c995e5579163001588b59e],
  g_base_definitions[g_str_68c995e5579163001588b5a0],
  g_base_definitions[g_str_68c995e5579163001588b5a2],
  g_base_definitions[g_str_5fb1b9ede1af060017709fad_camp],
  g_base_definitions[g_str_5fb1b9ede1af060017709fad_camp_pack_train],
  g_base_definitions[g_str_5fb1b9ede1af060017709fad_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ede1af060017709fad"] = army["5fb1b9ede1af060017709fad"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Zengid Dynasties in Syria  1092 to 1286 AD"] = army["5fb1b9ede1af060017709fad"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Zengid Dynasties in Syria  1092 to 1286 AD"] = army["5fb1b9ede1af060017709fad"]
if nil == armies["Byzantium in Decay"] then
  armies["Byzantium in Decay"] ={}
end
armies["Byzantium in Decay"]["Zengid Dynasties in Syria  1092 to 1286 AD"] = army["5fb1b9ede1af060017709fad"]
if nil == armies["Crusader Kingdoms"] then
  armies["Crusader Kingdoms"] ={}
end
armies["Crusader Kingdoms"]["Zengid Dynasties in Syria  1092 to 1286 AD"] = army["5fb1b9ede1af060017709fad"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Zengid Dynasties in Syria  1092 to 1286 AD"] = army["5fb1b9ede1af060017709fad"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ede1af060017709fad"] = {}
army_dates["5fb1b9ede1af060017709fad"]["1092 AD to 1286 AD"] = {
  startDate=1092,
  endDate=1286
}
army_dates["5fb1b9ede1af060017709fad"]["1092 AD to 1095 AD"] = {
  startDate=1092,
  endDate=1095
}
army_dates["5fb1b9ede1af060017709fad"]["1096 AD to 1099 AD"] = {
  startDate=1096,
  endDate=1099
}
army_dates["5fb1b9ede1af060017709fad"]["1100 AD to 1127 AD"] = {
  startDate=1100,
  endDate=1127
}
army_dates["5fb1b9ede1af060017709fad"]["1128 AD"] = {
  startDate=1128,
  endDate=1128
}
army_dates["5fb1b9ede1af060017709fad"]["1129 AD to 1172 AD"] = {
  startDate=1129,
  endDate=1172
}
army_dates["5fb1b9ede1af060017709fad"]["1173 AD to 1185 AD"] = {
  startDate=1173,
  endDate=1185
}
army_dates["5fb1b9ede1af060017709fad"]["1186 AD to 1245 AD"] = {
  startDate=1186,
  endDate=1245
}
army_dates["5fb1b9ede1af060017709fad"]["1246 AD"] = {
  startDate=1246,
  endDate=1246
}
army_dates["5fb1b9ede1af060017709fad"]["1247 AD to 1286 AD"] = {
  startDate=1247,
  endDate=1286
}
