-- 5fb1b9e7e1af060017709c12 Combined Spain  1480 to 1494 AD

army['5fb1b9e7e1af060017709c12']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
      'Hilly',
    },
    name='Combined Spain  1480 to 1494 AD',
    id='5fb1b9e7e1af060017709c12',
    dateRange={
      startDate=1480,
      endDate=1494,
    },
  },
  g_base_definitions[g_str_68c995df579163001588a5ed_general],
  g_base_definitions[g_str_68c995df579163001588a5ed],
  g_base_definitions[g_str_68c995df579163001588a5ef_general],
  g_base_definitions[g_str_68c995df579163001588a5ef],
  g_base_definitions[g_str_68c995df579163001588a5f1],
  g_base_definitions[g_str_68c995df579163001588a5f3],
  g_base_definitions[g_str_68c995df579163001588a5f5],
  g_base_definitions[g_str_68c995df579163001588a5f5_shower_shooting],
  g_base_definitions[g_str_68c995df579163001588a5f6],
  g_base_definitions[g_str_68c995df579163001588a5f6_shower_shooting],
  g_base_definitions[g_str_68c995df579163001588a5f9],
  g_base_definitions[g_str_68c995df579163001588a5fb],
  g_base_definitions[g_str_5fb1b9e7e1af060017709c12_camp],
  g_base_definitions[g_str_5fb1b9e7e1af060017709c12_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e7e1af060017709c12"] = army["5fb1b9e7e1af060017709c12"]
if nil == armies["Medieval Western Europe"] then
  armies["Medieval Western Europe"] ={}
end
armies["Medieval Western Europe"]["Combined Spain  1480 to 1494 AD"] = army["5fb1b9e7e1af060017709c12"]
if nil == armies["Plate and Handgonne"] then
  armies["Plate and Handgonne"] ={}
end
armies["Plate and Handgonne"]["Combined Spain  1480 to 1494 AD"] = army["5fb1b9e7e1af060017709c12"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Combined Spain  1480 to 1494 AD"] = army["5fb1b9e7e1af060017709c12"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e7e1af060017709c12"] = {}
army_dates["5fb1b9e7e1af060017709c12"]["1480 AD to 1494 AD"] = {
  startDate=1480,
  endDate=1494
}
