-- 5fb1b9f2e1af06001770a24e Eastern Jin Dynasty and Liu Yu  376 to 425 AD

army['5fb1b9f2e1af06001770a24e']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Forest',
      'Arable',
      'Hilly',
    },
    name='Eastern Jin Dynasty and Liu Yu  376 to 425 AD',
    id='5fb1b9f2e1af06001770a24e',
    dateRange={
      startDate=376,
      endDate=425,
    },
  },
  g_base_definitions[g_str_68c995e8579163001588bf75_general],
  g_base_definitions[g_str_68c995e8579163001588bf75],
  g_base_definitions[g_str_68c995e8579163001588bf76_general],
  g_base_definitions[g_str_68c995e8579163001588bf76],
  g_base_definitions[g_str_68c995e8579163001588bf78],
  g_base_definitions[g_str_68c995e8579163001588bf7a],
  g_base_definitions[g_str_68c995e8579163001588bf7b],
  g_base_definitions[g_str_68c995e8579163001588bf7d],
  g_base_definitions[g_str_68c995e8579163001588bf7e],
  g_base_definitions[g_str_68c995e8579163001588bf81],
  g_base_definitions[g_str_68c995e8579163001588bf84],
  g_base_definitions[g_str_68c995e8579163001588bf87],
  g_base_definitions[g_str_68c995e8579163001588bf87_shower_shooting],
  g_base_definitions[g_str_68c995e8579163001588bf8b],
  g_base_definitions[g_str_68c995e8579163001588bf8d],
  g_base_definitions[g_str_68c995e8579163001588bf8d_shower_shooting],
  g_base_definitions[g_str_68c995e8579163001588bf90],
  g_base_definitions[g_str_68c995e8579163001588bf92],
  g_base_definitions[g_str_5fb1b9f2e1af06001770a24e_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f2e1af06001770a24e"] = army["5fb1b9f2e1af06001770a24e"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Eastern Jin Dynasty and Liu Yu  376 to 425 AD"] = army["5fb1b9f2e1af06001770a24e"]
if nil == armies["Dark Ages China"] then
  armies["Dark Ages China"] ={}
end
armies["Dark Ages China"]["Eastern Jin Dynasty and Liu Yu  376 to 425 AD"] = army["5fb1b9f2e1af06001770a24e"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Eastern Jin Dynasty and Liu Yu  376 to 425 AD"] = army["5fb1b9f2e1af06001770a24e"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f2e1af06001770a24e"] = {}
army_dates["5fb1b9f2e1af06001770a24e"]["376 AD to 425 AD"] = {
  startDate=376,
  endDate=425
}
