-- 5fb1b9e6e1af060017709b5d Hausa States  900 to 1600 AD

army['5fb1b9e6e1af060017709b5d']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Steppe',
    },
    name='Hausa States  900 to 1600 AD',
    id='5fb1b9e6e1af060017709b5d',
    dateRange={
      startDate=900,
      endDate=1600,
    },
  },
  g_base_definitions[g_str_68c995df579163001588a39b_general],
  g_base_definitions[g_str_68c995df579163001588a39b],
  g_base_definitions[g_str_68c995df579163001588a39e_general],
  g_base_definitions[g_str_68c995df579163001588a39e],
  g_base_definitions[g_str_68c995df579163001588a3a1_general],
  g_base_definitions[g_str_68c995df579163001588a3a1],
  g_base_definitions[g_str_68c995df579163001588a3a2_general],
  g_base_definitions[g_str_68c995df579163001588a3a2],
  g_base_definitions[g_str_68c995df579163001588a3a4],
  g_base_definitions[g_str_68c995df579163001588a3a6],
  g_base_definitions[g_str_68c995df579163001588a3a6_shower_shooting],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b5d_camp],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b5d_camp_fortified],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b5d_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e6e1af060017709b5d"] = army["5fb1b9e6e1af060017709b5d"]
if nil == armies["Sahel Africa"] then
  armies["Sahel Africa"] ={}
end
armies["Sahel Africa"]["Hausa States  900 to 1600 AD"] = army["5fb1b9e6e1af060017709b5d"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Hausa States  900 to 1600 AD"] = army["5fb1b9e6e1af060017709b5d"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e6e1af060017709b5d"] = {}
army_dates["5fb1b9e6e1af060017709b5d"]["900 AD to 1600 AD"] = {
  startDate=900,
  endDate=1600
}
