-- 5fb1b9e1e1af060017709871 Cassivellaunus all mounted  55 to 54 BC

army['5fb1b9e1e1af060017709871']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Cassivellaunus all mounted  55 to 54 BC',
    id='5fb1b9e1e1af060017709871',
    dateRange={
      startDate=-55,
      endDate=-54,
    },
  },
  g_base_definitions[g_str_68c995da5791630015889930_general],
  g_base_definitions[g_str_68c995da5791630015889930],
  g_base_definitions[g_str_68c995da5791630015889932],
  g_base_definitions[g_str_68c995da5791630015889934],
  g_base_definitions[g_str_68c995da5791630015889935],
  g_base_definitions[g_str_68c995da5791630015889937],
  g_base_definitions[g_str_5fb1b9e1e1af060017709871_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e1e1af060017709871"] = army["5fb1b9e1e1af060017709871"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Cassivellaunus all mounted  55 to 54 BC"] = army["5fb1b9e1e1af060017709871"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Cassivellaunus all mounted  55 to 54 BC"] = army["5fb1b9e1e1af060017709871"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e1e1af060017709871"] = {}
army_dates["5fb1b9e1e1af060017709871"]["55 BC to 54 BC"] = {
  startDate=-55,
  endDate=-54
}
