-- 5fb1b9dae1af06001770944a Neo-Babylonian Revolts  522 to 422 BC

army['5fb1b9dae1af06001770944a']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Delta',
    },
    name='Neo-Babylonian Revolts  522 to 422 BC',
    id='5fb1b9dae1af06001770944a',
    dateRange={
      startDate=-522,
      endDate=-422,
    },
  },
  g_base_definitions[g_str_68c995d45791630015888944_general],
  g_base_definitions[g_str_68c995d45791630015888944],
  g_base_definitions[g_str_68c995d45791630015888946],
  g_base_definitions[g_str_68c995d45791630015888948],
  g_base_definitions[g_str_68c995d4579163001588894a],
  g_base_definitions[g_str_68c995d4579163001588894a_shower_shooting],
  g_base_definitions[g_str_68c995d4579163001588894d],
  g_base_definitions[g_str_68c995d4579163001588894f],
  g_base_definitions[g_str_5fb1b9dae1af06001770944a_camp],
  g_base_definitions[g_str_5fb1b9dae1af06001770944a_camp_pack_train],
  g_base_definitions[g_str_5fb1b9dae1af06001770944a_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dae1af06001770944a"] = army["5fb1b9dae1af06001770944a"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Neo-Babylonian Revolts  522 to 422 BC"] = army["5fb1b9dae1af06001770944a"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Neo-Babylonian Revolts  522 to 422 BC"] = army["5fb1b9dae1af06001770944a"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dae1af06001770944a"] = {}
army_dates["5fb1b9dae1af06001770944a"]["522 BC to 422 BC"] = {
  startDate=-522,
  endDate=-422
}
