-- 5fb1b9eae1af060017709db2 Prussian  1200 to 1295 AD

army['5fb1b9eae1af060017709db2']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Forest',
    },
    name='Prussian  1200 to 1295 AD',
    id='5fb1b9eae1af060017709db2',
    dateRange={
      startDate=1200,
      endDate=1295,
    },
    ambush=true,  },
  g_base_definitions[g_str_68c995e2579163001588ace6_general],
  g_base_definitions[g_str_68c995e2579163001588ace6_general_mounted],
  g_base_definitions[g_str_68c995e2579163001588ace6_general_dismounted],
  g_base_definitions[g_str_68c995e2579163001588ace6],
  g_base_definitions[g_str_68c995e2579163001588ace6_mounted],
  g_base_definitions[g_str_68c995e2579163001588ace6_dismounted],
  g_base_definitions[g_str_68c995e2579163001588ace9_general],
  g_base_definitions[g_str_68c995e2579163001588ace9],
  g_base_definitions[g_str_68c995e2579163001588aceb],
  g_base_definitions[g_str_68c995e2579163001588aced],
  g_base_definitions[g_str_68c995e2579163001588aced_shower_shooting],
  g_base_definitions[g_str_5fb1b9eae1af060017709db2_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eae1af060017709db2"] = army["5fb1b9eae1af060017709db2"]
if nil == armies["Russian Princes"] then
  armies["Russian Princes"] ={}
end
armies["Russian Princes"]["Prussian  1200 to 1295 AD"] = army["5fb1b9eae1af060017709db2"]
if nil == armies["Baltic Powers"] then
  armies["Baltic Powers"] ={}
end
armies["Baltic Powers"]["Prussian  1200 to 1295 AD"] = army["5fb1b9eae1af060017709db2"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Prussian  1200 to 1295 AD"] = army["5fb1b9eae1af060017709db2"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eae1af060017709db2"] = {}
army_dates["5fb1b9eae1af060017709db2"]["1200 AD to 1295 AD"] = {
  startDate=1200,
  endDate=1295
}
