-- 5fb1b9e2e1af0600177098ee Early Patrician Roman West: Africa  408 to 441 AD

army['5fb1b9e2e1af0600177098ee']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Arable',
      'Hilly',
    },
    name='Early Patrician Roman West: Africa  408 to 441 AD',
    id='5fb1b9e2e1af0600177098ee',
    dateRange={
      startDate=408,
      endDate=441,
    },
  },
  g_base_definitions[g_str_68c995db5791630015889b05_general],
  g_base_definitions[g_str_68c995db5791630015889b05],
  g_base_definitions[g_str_68c995db5791630015889b07_general],
  g_base_definitions[g_str_68c995db5791630015889b07],
  g_base_definitions[g_str_68c995db5791630015889b09],
  g_base_definitions[g_str_68c995db5791630015889b0d],
  g_base_definitions[g_str_68c995db5791630015889b10],
  g_base_definitions[g_str_68c995db5791630015889b12],
  g_base_definitions[g_str_68c995db5791630015889b15],
  g_base_definitions[g_str_68c995db5791630015889b18],
  g_base_definitions[g_str_68c995db5791630015889b1a_general],
  g_base_definitions[g_str_68c995db5791630015889b1a],
  g_base_definitions[g_str_68c995db5791630015889b1c],
  g_base_definitions[g_str_5fb1b9e2e1af0600177098ee_camp],
  g_base_definitions[g_str_5fb1b9e2e1af0600177098ee_camp_fortified],
  g_base_definitions[g_str_5fb1b9e2e1af0600177098ee_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e2e1af0600177098ee"] = army["5fb1b9e2e1af0600177098ee"]
if nil == armies["Fall of Rome"] then
  armies["Fall of Rome"] ={}
end
armies["Fall of Rome"]["Early Patrician Roman West: Africa  408 to 441 AD"] = army["5fb1b9e2e1af0600177098ee"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Patrician Roman West: Africa  408 to 441 AD"] = army["5fb1b9e2e1af0600177098ee"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e2e1af0600177098ee"] = {}
army_dates["5fb1b9e2e1af0600177098ee"]["408 AD to 441 AD"] = {
  startDate=408,
  endDate=441
}
