-- 5fb1b9eae1af060017709dfa Early Khazar  568 to 737 AD

army['5fb1b9eae1af060017709dfa']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
      3,
    },
    homeTopographies={
      'Steppe',
    },
    name='Early Khazar  568 to 737 AD',
    id='5fb1b9eae1af060017709dfa',
    dateRange={
      startDate=568,
      endDate=737,
    },
  },
  g_base_definitions[g_str_68c995e2579163001588ae29_general],
  g_base_definitions[g_str_68c995e2579163001588ae29],
  g_base_definitions[g_str_68c995e2579163001588ae2b],
  g_base_definitions[g_str_68c995e2579163001588ae2b_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e2579163001588ae2b_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e2579163001588ae2e],
  g_base_definitions[g_str_68c995e2579163001588ae30],
  g_base_definitions[g_str_68c995e2579163001588ae30_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e2579163001588ae30_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e2579163001588ae33],
  g_base_definitions[g_str_68c995e2579163001588ae35],
  g_base_definitions[g_str_68c995e2579163001588ae37],
  g_base_definitions[g_str_5fb1b9eae1af060017709dfa_camp],
  g_base_definitions[g_str_5fb1b9eae1af060017709dfa_camp_fortified],
  g_base_definitions[g_str_5fb1b9eae1af060017709dfa_camp_standard_wagon],
  g_base_definitions[g_str_68c995cc57916300158879fb],
  g_base_definitions[g_str_68c995cc57916300158879fd],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eae1af060017709dfa"] = army["5fb1b9eae1af060017709dfa"]
if nil == armies["Russian Princes"] then
  armies["Russian Princes"] ={}
end
armies["Russian Princes"]["Early Khazar  568 to 737 AD"] = army["5fb1b9eae1af060017709dfa"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Early Khazar  568 to 737 AD"] = army["5fb1b9eae1af060017709dfa"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Khazar  568 to 737 AD"] = army["5fb1b9eae1af060017709dfa"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eae1af060017709dfa"] = {}
army_dates["5fb1b9eae1af060017709dfa"]["568 AD to 737 AD"] = {
  startDate=568,
  endDate=737
}
