-- 5fb1b9dbe1af06001770946a Libyan Egyptian  946 to 712 BC

army['5fb1b9dbe1af06001770946a']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Delta',
      'Dry',
    },
    name='Libyan Egyptian  946 to 712 BC',
    id='5fb1b9dbe1af06001770946a',
    dateRange={
      startDate=-946,
      endDate=-712,
    },
  },
  g_base_definitions[g_str_68c995d55791630015888a09_general],
  g_base_definitions[g_str_68c995d55791630015888a09],
  g_base_definitions[g_str_68c995d55791630015888a0b],
  g_base_definitions[g_str_68c995d55791630015888a0d],
  g_base_definitions[g_str_68c995d55791630015888a0f],
  g_base_definitions[g_str_68c995d55791630015888a11],
  g_base_definitions[g_str_68c995d55791630015888a13],
  g_base_definitions[g_str_68c995d55791630015888a15],
  g_base_definitions[g_str_68c995d55791630015888a17],
  g_base_definitions[g_str_68c995d55791630015888a19],
  g_base_definitions[g_str_68c995d55791630015888a19_shower_shooting],
  g_base_definitions[g_str_5fb1b9dbe1af06001770946a_camp],
  g_base_definitions[g_str_5fb1b9dbe1af06001770946a_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dbe1af06001770946a"] = army["5fb1b9dbe1af06001770946a"]
if nil == armies["Chariot Supremacy"] then
  armies["Chariot Supremacy"] ={}
end
armies["Chariot Supremacy"]["Libyan Egyptian  946 to 712 BC"] = army["5fb1b9dbe1af06001770946a"]
if nil == armies["Assyrian Empire"] then
  armies["Assyrian Empire"] ={}
end
armies["Assyrian Empire"]["Libyan Egyptian  946 to 712 BC"] = army["5fb1b9dbe1af06001770946a"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Libyan Egyptian  946 to 712 BC"] = army["5fb1b9dbe1af06001770946a"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dbe1af06001770946a"] = {}
army_dates["5fb1b9dbe1af06001770946a"]["946 BC to 712 BC"] = {
  startDate=-946,
  endDate=-712
}
