-- 5fb1b9eae1af060017709de5 Early Russian  1054 to 1246 AD

army['5fb1b9eae1af060017709de5']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Forest',
    },
    name='Early Russian  1054 to 1246 AD',
    id='5fb1b9eae1af060017709de5',
    dateRange={
      startDate=1054,
      endDate=1246,
    },
  },
  g_base_definitions[g_str_68c995e2579163001588ada9_general],
  g_base_definitions[g_str_68c995e2579163001588ada9],
  g_base_definitions[g_str_68c995e2579163001588adab],
  g_base_definitions[g_str_68c995e2579163001588adad],
  g_base_definitions[g_str_68c995e2579163001588adaf],
  g_base_definitions[g_str_68c995e2579163001588adb2],
  g_base_definitions[g_str_68c995e2579163001588adb5],
  g_base_definitions[g_str_68c995e2579163001588adb8],
  g_base_definitions[g_str_68c995e2579163001588adba],
  g_base_definitions[g_str_68c995e2579163001588adbc],
  g_base_definitions[g_str_68c995e2579163001588adbe_general],
  g_base_definitions[g_str_68c995e2579163001588adbe_general_mounted],
  g_base_definitions[g_str_68c995e2579163001588adbe_general_dismounted],
  g_base_definitions[g_str_68c995e2579163001588adbe],
  g_base_definitions[g_str_68c995e2579163001588adbe_mounted],
  g_base_definitions[g_str_68c995e2579163001588adbe_dismounted],
  g_base_definitions[g_str_68c995e2579163001588adbf],
  g_base_definitions[g_str_68c995e2579163001588adbf_mounted],
  g_base_definitions[g_str_68c995e2579163001588adbf_dismounted],
  g_base_definitions[g_str_68c995e2579163001588adc2],
  g_base_definitions[g_str_5fb1b9eae1af060017709de5_camp],
  g_base_definitions[g_str_5fb1b9eae1af060017709de5_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eae1af060017709de5"] = army["5fb1b9eae1af060017709de5"]
if nil == armies["Russian Princes"] then
  armies["Russian Princes"] ={}
end
armies["Russian Princes"]["Early Russian  1054 to 1246 AD"] = army["5fb1b9eae1af060017709de5"]
if nil == armies["Baltic Powers"] then
  armies["Baltic Powers"] ={}
end
armies["Baltic Powers"]["Early Russian  1054 to 1246 AD"] = army["5fb1b9eae1af060017709de5"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Russian  1054 to 1246 AD"] = army["5fb1b9eae1af060017709de5"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eae1af060017709de5"] = {}
army_dates["5fb1b9eae1af060017709de5"]["1054 AD to 1246 AD"] = {
  startDate=1054,
  endDate=1246
}
army_dates["5fb1b9eae1af060017709de5"]["1054 AD to 1072 AD"] = {
  startDate=1054,
  endDate=1072
}
army_dates["5fb1b9eae1af060017709de5"]["1073 AD to 1150 AD"] = {
  startDate=1073,
  endDate=1150
}
army_dates["5fb1b9eae1af060017709de5"]["1151 AD to 1245 AD"] = {
  startDate=1151,
  endDate=1245
}
army_dates["5fb1b9eae1af060017709de5"]["1246 AD"] = {
  startDate=1246,
  endDate=1246
}
