-- 5fb1b9eae1af060017709dc2 Early Medieval Scandinavian  1280 to 1390 AD

army['5fb1b9eae1af060017709dc2']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Hilly',
    },
    name='Early Medieval Scandinavian  1280 to 1390 AD',
    id='5fb1b9eae1af060017709dc2',
    dateRange={
      startDate=1280,
      endDate=1390,
    },
  },
  g_base_definitions[g_str_68c995e2579163001588ad2c_general],
  g_base_definitions[g_str_68c995e2579163001588ad2c_general_mounted],
  g_base_definitions[g_str_68c995e2579163001588ad2c_general_dismounted],
  g_base_definitions[g_str_68c995e2579163001588ad2c],
  g_base_definitions[g_str_68c995e2579163001588ad2c_mounted],
  g_base_definitions[g_str_68c995e2579163001588ad2c_dismounted],
  g_base_definitions[g_str_68c995e2579163001588ad2f_general],
  g_base_definitions[g_str_68c995e2579163001588ad2f],
  g_base_definitions[g_str_68c995e2579163001588ad31_general],
  g_base_definitions[g_str_68c995e2579163001588ad31],
  g_base_definitions[g_str_68c995e2579163001588ad34],
  g_base_definitions[g_str_68c995e2579163001588ad35],
  g_base_definitions[g_str_5fb1b9eae1af060017709dc2_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eae1af060017709dc2"] = army["5fb1b9eae1af060017709dc2"]
if nil == armies["Russian Princes"] then
  armies["Russian Princes"] ={}
end
armies["Russian Princes"]["Early Medieval Scandinavian  1280 to 1390 AD"] = army["5fb1b9eae1af060017709dc2"]
if nil == armies["Baltic Powers"] then
  armies["Baltic Powers"] ={}
end
armies["Baltic Powers"]["Early Medieval Scandinavian  1280 to 1390 AD"] = army["5fb1b9eae1af060017709dc2"]
if nil == armies["Holy Roman Empire"] then
  armies["Holy Roman Empire"] ={}
end
armies["Holy Roman Empire"]["Early Medieval Scandinavian  1280 to 1390 AD"] = army["5fb1b9eae1af060017709dc2"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Medieval Scandinavian  1280 to 1390 AD"] = army["5fb1b9eae1af060017709dc2"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eae1af060017709dc2"] = {}
army_dates["5fb1b9eae1af060017709dc2"]["1280 AD to 1390 AD"] = {
  startDate=1280,
  endDate=1390
}
army_dates["5fb1b9eae1af060017709dc2"]["1280 AD to 1320 AD"] = {
  startDate=1280,
  endDate=1320
}
army_dates["5fb1b9eae1af060017709dc2"]["1321 AD to 1349 AD"] = {
  startDate=1321,
  endDate=1349
}
army_dates["5fb1b9eae1af060017709dc2"]["1350 AD to 1390 AD"] = {
  startDate=1350,
  endDate=1390
}
