-- 5fb1b9e6e1af060017709ba2 Tuareg  960 to 1880 AD

army['5fb1b9e6e1af060017709ba2']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Dry',
    },
    name='Tuareg  960 to 1880 AD',
    id='5fb1b9e6e1af060017709ba2',
    dateRange={
      startDate=960,
      endDate=1880,
    },
  },
  g_base_definitions[g_str_68c995df579163001588a42e_general],
  g_base_definitions[g_str_68c995df579163001588a42e_general_charging_camelry],
  g_base_definitions[g_str_68c995df579163001588a42e],
  g_base_definitions[g_str_68c995df579163001588a42e_charging_camelry],
  g_base_definitions[g_str_68c995df579163001588a431],
  g_base_definitions[g_str_68c995df579163001588a431_light_camelry],
  g_base_definitions[g_str_68c995df579163001588a434],
  g_base_definitions[g_str_68c995df579163001588a436],
  g_base_definitions[g_str_68c995df579163001588a438],
  g_base_definitions[g_str_5fb1b9e6e1af060017709ba2_camp],
  g_base_definitions[g_str_5fb1b9e6e1af060017709ba2_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e6e1af060017709ba2"] = army["5fb1b9e6e1af060017709ba2"]
if nil == armies["Sahel Africa"] then
  armies["Sahel Africa"] ={}
end
armies["Sahel Africa"]["Tuareg  960 to 1880 AD"] = army["5fb1b9e6e1af060017709ba2"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Tuareg  960 to 1880 AD"] = army["5fb1b9e6e1af060017709ba2"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e6e1af060017709ba2"] = {}
army_dates["5fb1b9e6e1af060017709ba2"]["960 AD to 1880 AD"] = {
  startDate=960,
  endDate=1880
}
