-- 5fb1b9ede1af060017709fa5 Syrian Arab-ruled Citystates  1092 to 1172 AD

army['5fb1b9ede1af060017709fa5']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
      'Dry',
    },
    name='Syrian Arab-ruled Citystates  1092 to 1172 AD',
    id='5fb1b9ede1af060017709fa5',
    dateRange={
      startDate=1092,
      endDate=1172,
    },
  },
  g_base_definitions[g_str_68c995e5579163001588b577_general],
  g_base_definitions[g_str_68c995e5579163001588b577],
  g_base_definitions[g_str_68c995e5579163001588b579_general],
  g_base_definitions[g_str_68c995e5579163001588b579],
  g_base_definitions[g_str_68c995e5579163001588b57b],
  g_base_definitions[g_str_68c995e5579163001588b57d],
  g_base_definitions[g_str_68c995e5579163001588b57f],
  g_base_definitions[g_str_68c995e5579163001588b581],
  g_base_definitions[g_str_68c995e5579163001588b583],
  g_base_definitions[g_str_5fb1b9ede1af060017709fa5_camp],
  g_base_definitions[g_str_5fb1b9ede1af060017709fa5_camp_pack_train],
  g_base_definitions[g_str_5fb1b9ede1af060017709fa5_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ede1af060017709fa5"] = army["5fb1b9ede1af060017709fa5"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Syrian Arab-ruled Citystates  1092 to 1172 AD"] = army["5fb1b9ede1af060017709fa5"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Syrian Arab-ruled Citystates  1092 to 1172 AD"] = army["5fb1b9ede1af060017709fa5"]
if nil == armies["Crusader Kingdoms"] then
  armies["Crusader Kingdoms"] ={}
end
armies["Crusader Kingdoms"]["Syrian Arab-ruled Citystates  1092 to 1172 AD"] = army["5fb1b9ede1af060017709fa5"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Syrian Arab-ruled Citystates  1092 to 1172 AD"] = army["5fb1b9ede1af060017709fa5"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ede1af060017709fa5"] = {}
army_dates["5fb1b9ede1af060017709fa5"]["1092 AD to 1172 AD"] = {
  startDate=1092,
  endDate=1172
}
army_dates["5fb1b9ede1af060017709fa5"]["1092 AD to 1095 AD"] = {
  startDate=1092,
  endDate=1095
}
army_dates["5fb1b9ede1af060017709fa5"]["1096 AD to 1099 AD"] = {
  startDate=1096,
  endDate=1099
}
army_dates["5fb1b9ede1af060017709fa5"]["1100 AD to 1127 AD"] = {
  startDate=1100,
  endDate=1127
}
army_dates["5fb1b9ede1af060017709fa5"]["1128 AD"] = {
  startDate=1128,
  endDate=1128
}
army_dates["5fb1b9ede1af060017709fa5"]["1129 AD to 1172 AD"] = {
  startDate=1129,
  endDate=1172
}
