-- 5fb1b9e6e1af060017709b9c Fulani  1400 to 1600 AD

army['5fb1b9e6e1af060017709b9c']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Steppe',
    },
    name='Fulani  1400 to 1600 AD',
    id='5fb1b9e6e1af060017709b9c',
    dateRange={
      startDate=1400,
      endDate=1600,
    },
  },
  g_base_definitions[g_str_68c995df579163001588a41f_general],
  g_base_definitions[g_str_68c995df579163001588a41f],
  g_base_definitions[g_str_68c995df579163001588a421_general],
  g_base_definitions[g_str_68c995df579163001588a421],
  g_base_definitions[g_str_68c995df579163001588a423],
  g_base_definitions[g_str_68c995df579163001588a425],
  g_base_definitions[g_str_68c995df579163001588a427],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b9c_camp],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b9c_camp_fortified],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b9c_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e6e1af060017709b9c"] = army["5fb1b9e6e1af060017709b9c"]
if nil == armies["Sahel Africa"] then
  armies["Sahel Africa"] ={}
end
armies["Sahel Africa"]["Fulani  1400 to 1600 AD"] = army["5fb1b9e6e1af060017709b9c"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Fulani  1400 to 1600 AD"] = army["5fb1b9e6e1af060017709b9c"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e6e1af060017709b9c"] = {}
army_dates["5fb1b9e6e1af060017709b9c"]["1400 AD to 1600 AD"] = {
  startDate=1400,
  endDate=1600
}
