-- 5fb1b9eae1af060017709da4 Estonian  1200 to 1227 AD

army['5fb1b9eae1af060017709da4']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      4,
    },
    homeTopographies={
      'Forest',
    },
    name='Estonian  1200 to 1227 AD',
    id='5fb1b9eae1af060017709da4',
    dateRange={
      startDate=1200,
      endDate=1227,
    },
    ambush=true,  },
  g_base_definitions[g_str_68c995e2579163001588acbb_general],
  g_base_definitions[g_str_68c995e2579163001588acbb_general_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e2579163001588acbb_general_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e2579163001588acbb],
  g_base_definitions[g_str_68c995e2579163001588acbb_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e2579163001588acbb_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e2579163001588acbe_general],
  g_base_definitions[g_str_68c995e2579163001588acbe],
  g_base_definitions[g_str_68c995e2579163001588acc0],
  g_base_definitions[g_str_68c995e2579163001588acc0_shower_shooting],
  g_base_definitions[g_str_68c995e2579163001588acc1],
  g_base_definitions[g_str_68c995e2579163001588acc1_shower_shooting],
  g_base_definitions[g_str_68c995e2579163001588acc5],
  g_base_definitions[g_str_5fb1b9eae1af060017709da4_camp],
  g_base_definitions[g_str_5fb1b9eae1af060017709da4_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eae1af060017709da4"] = army["5fb1b9eae1af060017709da4"]
if nil == armies["Russian Princes"] then
  armies["Russian Princes"] ={}
end
armies["Russian Princes"]["Estonian  1200 to 1227 AD"] = army["5fb1b9eae1af060017709da4"]
if nil == armies["Baltic Powers"] then
  armies["Baltic Powers"] ={}
end
armies["Baltic Powers"]["Estonian  1200 to 1227 AD"] = army["5fb1b9eae1af060017709da4"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Estonian  1200 to 1227 AD"] = army["5fb1b9eae1af060017709da4"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eae1af060017709da4"] = {}
army_dates["5fb1b9eae1af060017709da4"]["1200 AD to 1227 AD"] = {
  startDate=1200,
  endDate=1227
}
army_dates["5fb1b9eae1af060017709da4"]["1200 AD to 1222 AD"] = {
  startDate=1200,
  endDate=1222
}
army_dates["5fb1b9eae1af060017709da4"]["1223 AD to 1227 AD"] = {
  startDate=1223,
  endDate=1227
}
