-- 5fb1b9e2e1af0600177098cf Battle of Marcianople  376 to 376 AD

army['5fb1b9e2e1af0600177098cf']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Battle of Marcianople  376 to 376 AD',
    id='5fb1b9e2e1af0600177098cf',
    dateRange={
      startDate=376,
      endDate=376,
    },
  },
  g_base_definitions[g_str_68c995db5791630015889a7d_general],
  g_base_definitions[g_str_68c995db5791630015889a7d],
  g_base_definitions[g_str_68c995db5791630015889a7f],
  g_base_definitions[g_str_68c995db5791630015889a7f_shower_shooting],
  g_base_definitions[g_str_68c995db5791630015889a82],
  g_base_definitions[g_str_5fb1b9e2e1af0600177098cf_camp],
  g_base_definitions[g_str_5fb1b9e2e1af0600177098cf_camp_fortified],
  g_base_definitions[g_str_5fb1b9e2e1af0600177098cf_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e2e1af0600177098cf"] = army["5fb1b9e2e1af0600177098cf"]
if nil == armies["Fall of Rome"] then
  armies["Fall of Rome"] ={}
end
armies["Fall of Rome"]["Battle of Marcianople  376 to 376 AD"] = army["5fb1b9e2e1af0600177098cf"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Battle of Marcianople  376 to 376 AD"] = army["5fb1b9e2e1af0600177098cf"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e2e1af0600177098cf"] = {}
army_dates["5fb1b9e2e1af0600177098cf"]["376 AD"] = {
  startDate=376,
  endDate=376
}
