-- 5fb1b9f4e1af06001770a325 Baekje and Gaya Korean  300 to 663 AD

army['5fb1b9f4e1af06001770a325']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      3,
      2,
    },
    homeTopographies={
      'Hilly',
    },
    name='Baekje and Gaya Korean  300 to 663 AD',
    id='5fb1b9f4e1af06001770a325',
    dateRange={
      startDate=300,
      endDate=663,
    },
  },
  g_base_definitions[g_str_68c995ea579163001588c30f_general],
  g_base_definitions[g_str_68c995ea579163001588c30f],
  g_base_definitions[g_str_68c995ea579163001588c312],
  g_base_definitions[g_str_68c995ea579163001588c315_general],
  g_base_definitions[g_str_68c995ea579163001588c315],
  g_base_definitions[g_str_68c995ea579163001588c317],
  g_base_definitions[g_str_68c995ea579163001588c319],
  g_base_definitions[g_str_68c995ea579163001588c31b],
  g_base_definitions[g_str_68c995ea579163001588c31d],
  g_base_definitions[g_str_68c995ea579163001588c31d_shower_shooting],
  g_base_definitions[g_str_68c995ea579163001588c320],
  g_base_definitions[g_str_5fb1b9f4e1af06001770a325_camp],
  g_base_definitions[g_str_5fb1b9f4e1af06001770a325_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f4e1af06001770a325"] = army["5fb1b9f4e1af06001770a325"]
if nil == armies["Korea and Japan"] then
  armies["Korea and Japan"] ={}
end
armies["Korea and Japan"]["Baekje and Gaya Korean  300 to 663 AD"] = army["5fb1b9f4e1af06001770a325"]
if nil == armies["Dark Ages China"] then
  armies["Dark Ages China"] ={}
end
armies["Dark Ages China"]["Baekje and Gaya Korean  300 to 663 AD"] = army["5fb1b9f4e1af06001770a325"]
if nil == armies["Middle Kingdom"] then
  armies["Middle Kingdom"] ={}
end
armies["Middle Kingdom"]["Baekje and Gaya Korean  300 to 663 AD"] = army["5fb1b9f4e1af06001770a325"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Baekje and Gaya Korean  300 to 663 AD"] = army["5fb1b9f4e1af06001770a325"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f4e1af06001770a325"] = {}
army_dates["5fb1b9f4e1af06001770a325"]["300 AD to 663 AD"] = {
  startDate=300,
  endDate=663
}
army_dates["5fb1b9f4e1af06001770a325"]["300 AD to 374 AD"] = {
  startDate=300,
  endDate=374
}
army_dates["5fb1b9f4e1af06001770a325"]["375 AD to 499 AD"] = {
  startDate=375,
  endDate=499
}
army_dates["5fb1b9f4e1af06001770a325"]["500 AD"] = {
  startDate=500,
  endDate=500
}
army_dates["5fb1b9f4e1af06001770a325"]["501 AD to 645 AD"] = {
  startDate=501,
  endDate=645
}
army_dates["5fb1b9f4e1af06001770a325"]["646 AD to 663 AD"] = {
  startDate=646,
  endDate=663
}
