-- 5fb1b9ebe1af060017709e53 Konstantinian Byzantine  1042 to 1073 AD

army['5fb1b9ebe1af060017709e53']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      3,
      2,
    },
    homeTopographies={
      'Arable',
      'Hilly',
    },
    name='Konstantinian Byzantine  1042 to 1073 AD',
    id='5fb1b9ebe1af060017709e53',
    dateRange={
      startDate=1042,
      endDate=1073,
    },
  },
  g_base_definitions[g_str_68c995e3579163001588af5d_general],
  g_base_definitions[g_str_68c995e3579163001588af5d],
  g_base_definitions[g_str_68c995e3579163001588af5f],
  g_base_definitions[g_str_68c995e3579163001588af61],
  g_base_definitions[g_str_68c995e3579163001588af63],
  g_base_definitions[g_str_68c995e3579163001588af65],
  g_base_definitions[g_str_68c995e3579163001588af67],
  g_base_definitions[g_str_68c995e3579163001588af6a],
  g_base_definitions[g_str_68c995e3579163001588af6d],
  g_base_definitions[g_str_68c995e3579163001588af71],
  g_base_definitions[g_str_68c995e3579163001588af74],
  g_base_definitions[g_str_5fb1b9ebe1af060017709e53_camp],
  g_base_definitions[g_str_5fb1b9ebe1af060017709e53_camp_fortified],
  g_base_definitions[g_str_5fb1b9ebe1af060017709e53_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ebe1af060017709e53"] = army["5fb1b9ebe1af060017709e53"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Konstantinian Byzantine  1042 to 1073 AD"] = army["5fb1b9ebe1af060017709e53"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Konstantinian Byzantine  1042 to 1073 AD"] = army["5fb1b9ebe1af060017709e53"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ebe1af060017709e53"] = {}
army_dates["5fb1b9ebe1af060017709e53"]["1042 AD to 1073 AD"] = {
  startDate=1042,
  endDate=1073
}
