-- 5fb1b9e4e1af060017709a21 Early Serbian or Croatian  627 to 798 AD

army['5fb1b9e4e1af060017709a21']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Hilly',
    },
    name='Early Serbian or Croatian  627 to 798 AD',
    id='5fb1b9e4e1af060017709a21',
    dateRange={
      startDate=627,
      endDate=798,
    },
  },
  g_base_definitions[g_str_68c995dd5791630015889f09_general],
  g_base_definitions[g_str_68c995dd5791630015889f09],
  g_base_definitions[g_str_68c995dd5791630015889f0a_general],
  g_base_definitions[g_str_68c995dd5791630015889f0a],
  g_base_definitions[g_str_68c995dd5791630015889f0c],
  g_base_definitions[g_str_68c995dd5791630015889f0e],
  g_base_definitions[g_str_68c995dd5791630015889f10],
  g_base_definitions[g_str_68c995dd5791630015889f12],
  g_base_definitions[g_str_68c995dd5791630015889f12_shower_shooting],
  g_base_definitions[g_str_5fb1b9e4e1af060017709a21_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e4e1af060017709a21"] = army["5fb1b9e4e1af060017709a21"]
if nil == armies["Dark Ages"] then
  armies["Dark Ages"] ={}
end
armies["Dark Ages"]["Early Serbian or Croatian  627 to 798 AD"] = army["5fb1b9e4e1af060017709a21"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Early Serbian or Croatian  627 to 798 AD"] = army["5fb1b9e4e1af060017709a21"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Serbian or Croatian  627 to 798 AD"] = army["5fb1b9e4e1af060017709a21"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e4e1af060017709a21"] = {}
army_dates["5fb1b9e4e1af060017709a21"]["627 AD to 798 AD"] = {
  startDate=627,
  endDate=798
}
