-- 5fb1b9f6e1af06001770a458 Hawaii  1200 to 1785 AD

army['5fb1b9f6e1af06001770a458']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Forest',
    },
    name='Hawaii  1200 to 1785 AD',
    id='5fb1b9f6e1af06001770a458',
    dateRange={
      startDate=1200,
      endDate=1785,
    },
  },
  g_base_definitions[g_str_68c995eb579163001588c5b3_general],
  g_base_definitions[g_str_68c995eb579163001588c5b3],
  g_base_definitions[g_str_68c995eb579163001588c5b5],
  g_base_definitions[g_str_68c995eb579163001588c5b7],
  g_base_definitions[g_str_68c995eb579163001588c5b9],
  g_base_definitions[g_str_68c995eb579163001588c5bb],
  g_base_definitions[g_str_5fb1b9f6e1af06001770a458_camp],
  g_base_definitions[g_str_5fb1b9f6e1af06001770a458_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f6e1af06001770a458"] = army["5fb1b9f6e1af06001770a458"]
if nil == armies["New World"] then
  armies["New World"] ={}
end
armies["New World"]["Hawaii  1200 to 1785 AD"] = army["5fb1b9f6e1af06001770a458"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Hawaii  1200 to 1785 AD"] = army["5fb1b9f6e1af06001770a458"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f6e1af06001770a458"] = {}
army_dates["5fb1b9f6e1af06001770a458"]["1200 AD to 1785 AD"] = {
  startDate=1200,
  endDate=1785
}
