-- 5fb1b9ece1af060017709ee4 Arab Conquest under Muhammad  622 to 630 AD

army['5fb1b9ece1af060017709ee4']={
  data={
    invasionRatings={
      4,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Dry',
    },
    name='Arab Conquest under Muhammad  622 to 630 AD',
    id='5fb1b9ece1af060017709ee4',
    dateRange={
      startDate=622,
      endDate=630,
    },
  },
  g_base_definitions[g_str_68c995e4579163001588b234_general],
  g_base_definitions[g_str_68c995e4579163001588b234_general_mounted],
  g_base_definitions[g_str_68c995e4579163001588b234_general_dismounted],
  g_base_definitions[g_str_68c995e4579163001588b234],
  g_base_definitions[g_str_68c995e4579163001588b234_mounted],
  g_base_definitions[g_str_68c995e4579163001588b234_dismounted],
  g_base_definitions[g_str_68c995e4579163001588b237],
  g_base_definitions[g_str_68c995e4579163001588b237_light_camelry],
  g_base_definitions[g_str_68c995e4579163001588b23a_general],
  g_base_definitions[g_str_68c995e4579163001588b23a],
  g_base_definitions[g_str_68c995e4579163001588b23c],
  g_base_definitions[g_str_68c995e4579163001588b23e],
  g_base_definitions[g_str_68c995e4579163001588b240],
  g_base_definitions[g_str_5fb1b9ece1af060017709ee4_camp],
  g_base_definitions[g_str_5fb1b9ece1af060017709ee4_camp_pack_train],
  g_base_definitions[g_str_5fb1b9ece1af060017709ee4_camp_standard_wagon],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9ece1af060017709ee4"] = army["5fb1b9ece1af060017709ee4"]
if nil == armies["Scimitar and Crescent"] then
  armies["Scimitar and Crescent"] ={}
end
armies["Scimitar and Crescent"]["Arab Conquest under Muhammad  622 to 630 AD"] = army["5fb1b9ece1af060017709ee4"]
if nil == armies["Glorious Byzantium"] then
  armies["Glorious Byzantium"] ={}
end
armies["Glorious Byzantium"]["Arab Conquest under Muhammad  622 to 630 AD"] = army["5fb1b9ece1af060017709ee4"]
if nil == armies["Spread of Islam"] then
  armies["Spread of Islam"] ={}
end
armies["Spread of Islam"]["Arab Conquest under Muhammad  622 to 630 AD"] = army["5fb1b9ece1af060017709ee4"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Arab Conquest under Muhammad  622 to 630 AD"] = army["5fb1b9ece1af060017709ee4"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9ece1af060017709ee4"] = {}
army_dates["5fb1b9ece1af060017709ee4"]["622 AD to 630 AD"] = {
  startDate=622,
  endDate=630
}
army_dates["5fb1b9ece1af060017709ee4"]["622 AD to 625 AD"] = {
  startDate=622,
  endDate=625
}
army_dates["5fb1b9ece1af060017709ee4"]["626 AD to 630 AD"] = {
  startDate=626,
  endDate=630
}
