-- 5fb1b9efe1af06001770a089 Arab Indian  751 to 1206 AD

army['5fb1b9efe1af06001770a089']={
  data={
    invasionRatings={
      3,
      1,
    },
    maneuverRatings={
      3,
      1,
    },
    homeTopographies={
      'Delta',
      'Dry',
    },
    name='Arab Indian  751 to 1206 AD',
    id='5fb1b9efe1af06001770a089',
    dateRange={
      startDate=751,
      endDate=1206,
    },
  },
  g_base_definitions[g_str_68c995e6579163001588b97c_general],
  g_base_definitions[g_str_68c995e6579163001588b97c],
  g_base_definitions[g_str_68c995e6579163001588b97f_general],
  g_base_definitions[g_str_68c995e6579163001588b97f_general_shower_shooting],
  g_base_definitions[g_str_68c995e6579163001588b97f],
  g_base_definitions[g_str_68c995e6579163001588b97f_shower_shooting],
  g_base_definitions[g_str_68c995e6579163001588b982],
  g_base_definitions[g_str_68c995e6579163001588b984],
  g_base_definitions[g_str_68c995e6579163001588b987],
  g_base_definitions[g_str_68c995e6579163001588b988],
  g_base_definitions[g_str_68c995e6579163001588b98b],
  g_base_definitions[g_str_68c995e6579163001588b98d],
  g_base_definitions[g_str_68c995e6579163001588b98f],
  g_base_definitions[g_str_68c995e6579163001588b98f_shower_shooting],
  g_base_definitions[g_str_68c995e6579163001588b992],
  g_base_definitions[g_str_68c995e6579163001588b995],
  g_base_definitions[g_str_5fb1b9efe1af06001770a089_camp],
  g_base_definitions[g_str_5fb1b9efe1af06001770a089_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9efe1af06001770a089"] = army["5fb1b9efe1af06001770a089"]
if nil == armies["Monsoon Region"] then
  armies["Monsoon Region"] ={}
end
armies["Monsoon Region"]["Arab Indian  751 to 1206 AD"] = army["5fb1b9efe1af06001770a089"]
if nil == armies["Silk Road"] then
  armies["Silk Road"] ={}
end
armies["Silk Road"]["Arab Indian  751 to 1206 AD"] = army["5fb1b9efe1af06001770a089"]
if nil == armies["India and the Khyber Pass"] then
  armies["India and the Khyber Pass"] ={}
end
armies["India and the Khyber Pass"]["Arab Indian  751 to 1206 AD"] = army["5fb1b9efe1af06001770a089"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Arab Indian  751 to 1206 AD"] = army["5fb1b9efe1af06001770a089"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9efe1af06001770a089"] = {}
army_dates["5fb1b9efe1af06001770a089"]["751 AD to 1206 AD"] = {
  startDate=751,
  endDate=1206
}
