-- 5fb1b9e9e1af060017709d15 Early Renaissance Swiss  1478 to 1522 AD

army['5fb1b9e9e1af060017709d15']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Hilly',
    },
    name='Early Renaissance Swiss  1478 to 1522 AD',
    id='5fb1b9e9e1af060017709d15',
    dateRange={
      startDate=1478,
      endDate=1522,
    },
  },
  g_base_definitions[g_str_68c995e1579163001588aa03],
  g_base_definitions[g_str_68c995e1579163001588aa03_mounted],
  g_base_definitions[g_str_68c995e1579163001588aa03_dismounted],
  g_base_definitions[g_str_68c995e1579163001588aa06_general],
  g_base_definitions[g_str_68c995e1579163001588aa06],
  g_base_definitions[g_str_68c995e1579163001588aa08],
  g_base_definitions[g_str_68c995e1579163001588aa09],
  g_base_definitions[g_str_68c995e1579163001588aa0b],
  g_base_definitions[g_str_68c995e1579163001588aa0d],
  g_base_definitions[g_str_5fb1b9e9e1af060017709d15_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e9e1af060017709d15"] = army["5fb1b9e9e1af060017709d15"]
if nil == armies["Holy Roman Empire"] then
  armies["Holy Roman Empire"] ={}
end
armies["Holy Roman Empire"]["Early Renaissance Swiss  1478 to 1522 AD"] = army["5fb1b9e9e1af060017709d15"]
if nil == armies["Italy and Balkans"] then
  armies["Italy and Balkans"] ={}
end
armies["Italy and Balkans"]["Early Renaissance Swiss  1478 to 1522 AD"] = army["5fb1b9e9e1af060017709d15"]
if nil == armies["Flower of Chivalry"] then
  armies["Flower of Chivalry"] ={}
end
armies["Flower of Chivalry"]["Early Renaissance Swiss  1478 to 1522 AD"] = army["5fb1b9e9e1af060017709d15"]
if nil == armies["Plate and Handgonne"] then
  armies["Plate and Handgonne"] ={}
end
armies["Plate and Handgonne"]["Early Renaissance Swiss  1478 to 1522 AD"] = army["5fb1b9e9e1af060017709d15"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Renaissance Swiss  1478 to 1522 AD"] = army["5fb1b9e9e1af060017709d15"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e9e1af060017709d15"] = {}
army_dates["5fb1b9e9e1af060017709d15"]["1478 AD to 1522 AD"] = {
  startDate=1478,
  endDate=1522
}
