-- 5fb1b9e3e1af060017709956 Late Sassanid Persian  577 to 651 AD

army['5fb1b9e3e1af060017709956']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Arable',
      'Dry',
      'Hilly',
    },
    name='Late Sassanid Persian  577 to 651 AD',
    id='5fb1b9e3e1af060017709956',
    dateRange={
      startDate=577,
      endDate=651,
    },
  },
  g_base_definitions[g_str_68c995dc5791630015889c9d_general],
  g_base_definitions[g_str_68c995dc5791630015889c9d_general_shower_shooting],
  g_base_definitions[g_str_68c995dc5791630015889c9d],
  g_base_definitions[g_str_68c995dc5791630015889c9d_shower_shooting],
  g_base_definitions[g_str_68c995dc5791630015889ca0],
  g_base_definitions[g_str_68c995dc5791630015889ca2],
  g_base_definitions[g_str_68c995dc5791630015889ca2_elephant_screen],
  g_base_definitions[g_str_68c995dc5791630015889ca5],
  g_base_definitions[g_str_68c995dc5791630015889ca5_elephant_screen],
  g_base_definitions[g_str_68c995dc5791630015889ca5_shower_shooting],
  g_base_definitions[g_str_68c995dc5791630015889ca9],
  g_base_definitions[g_str_68c995dc5791630015889cab],
  g_base_definitions[g_str_68c995dc5791630015889cab_elephant_screen],
  g_base_definitions[g_str_68c995dc5791630015889cac],
  g_base_definitions[g_str_68c995dc5791630015889cac_elephant_screen],
  g_base_definitions[g_str_68c995dc5791630015889caf],
  g_base_definitions[g_str_68c995dc5791630015889cb2],
  g_base_definitions[g_str_68c995dc5791630015889cb4],
  g_base_definitions[g_str_68c995dc5791630015889cb7],
  g_base_definitions[g_str_5fb1b9e3e1af060017709956_camp],
  g_base_definitions[g_str_5fb1b9e3e1af060017709956_camp_fortified],
  g_base_definitions[g_str_5fb1b9e3e1af060017709956_camp_pack_train],
  g_base_definitions[g_str_5fb1b9e3e1af060017709956_camp_standard_wagon],
  g_base_definitions[g_str_5fb1b9e3e1af060017709956_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e3e1af060017709956"] = army["5fb1b9e3e1af060017709956"]
if nil == armies["Fall of Rome"] then
  armies["Fall of Rome"] ={}
end
armies["Fall of Rome"]["Late Sassanid Persian  577 to 651 AD"] = army["5fb1b9e3e1af060017709956"]
if nil == armies["Spread of Islam"] then
  armies["Spread of Islam"] ={}
end
armies["Spread of Islam"]["Late Sassanid Persian  577 to 651 AD"] = army["5fb1b9e3e1af060017709956"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Late Sassanid Persian  577 to 651 AD"] = army["5fb1b9e3e1af060017709956"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e3e1af060017709956"] = {}
army_dates["5fb1b9e3e1af060017709956"]["577 AD to 651 AD"] = {
  startDate=577,
  endDate=651
}
army_dates["5fb1b9e3e1af060017709956"]["577 AD to 600 AD"] = {
  startDate=577,
  endDate=600
}
army_dates["5fb1b9e3e1af060017709956"]["601 AD to 602 AD"] = {
  startDate=601,
  endDate=602
}
army_dates["5fb1b9e3e1af060017709956"]["603 AD to 633 AD"] = {
  startDate=603,
  endDate=633
}
army_dates["5fb1b9e3e1af060017709956"]["634 AD to 651 AD"] = {
  startDate=634,
  endDate=651
}
