-- 5fb1b9e2e1af0600177098bb Visigoths under Alaric as Magister Militum  395 to 407 AD

army['5fb1b9e2e1af0600177098bb']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
      'Hilly',
    },
    name='Visigoths under Alaric as Magister Militum  395 to 407 AD',
    id='5fb1b9e2e1af0600177098bb',
    dateRange={
      startDate=395,
      endDate=407,
    },
  },
  g_base_definitions[g_str_68c995db5791630015889a41_general],
  g_base_definitions[g_str_68c995db5791630015889a41],
  g_base_definitions[g_str_68c995db5791630015889a43],
  g_base_definitions[g_str_68c995db5791630015889a45],
  g_base_definitions[g_str_68c995db5791630015889a45_shower_shooting],
  g_base_definitions[g_str_68c995db5791630015889a48],
  g_base_definitions[g_str_68c995db5791630015889a4a],
  g_base_definitions[g_str_68c995db5791630015889a4c],
  g_base_definitions[g_str_5fb1b9e2e1af0600177098bb_camp],
  g_base_definitions[g_str_5fb1b9e2e1af0600177098bb_camp_fortified],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e2e1af0600177098bb"] = army["5fb1b9e2e1af0600177098bb"]
if nil == armies["Fall of Rome"] then
  armies["Fall of Rome"] ={}
end
armies["Fall of Rome"]["Visigoths under Alaric as Magister Militum  395 to 407 AD"] = army["5fb1b9e2e1af0600177098bb"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Visigoths under Alaric as Magister Militum  395 to 407 AD"] = army["5fb1b9e2e1af0600177098bb"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e2e1af0600177098bb"] = {}
army_dates["5fb1b9e2e1af0600177098bb"]["395 AD to 407 AD"] = {
  startDate=395,
  endDate=407
}
