-- 5fb1b9dde1af0600177095f8 Later Hoplite Aitolian or Akarnanian  448 to 225 BC

army['5fb1b9dde1af0600177095f8']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Hilly',
    },
    name='Later Hoplite Aitolian or Akarnanian  448 to 225 BC',
    id='5fb1b9dde1af0600177095f8',
    dateRange={
      startDate=-448,
      endDate=-225,
    },
  },
  g_base_definitions[g_str_68c995d75791630015888fcf_general],
  g_base_definitions[g_str_68c995d75791630015888fcf],
  g_base_definitions[g_str_68c995d75791630015888fd2_general],
  g_base_definitions[g_str_68c995d75791630015888fd2],
  g_base_definitions[g_str_68c995d75791630015888fd5],
  g_base_definitions[g_str_68c995d75791630015888fd7_general],
  g_base_definitions[g_str_68c995d75791630015888fd7],
  g_base_definitions[g_str_68c995d75791630015888fd9],
  g_base_definitions[g_str_68c995d75791630015888fdb],
  g_base_definitions[g_str_68c995d75791630015888fdd],
  g_base_definitions[g_str_68c995d75791630015888fdf],
  g_base_definitions[g_str_5fb1b9dde1af0600177095f8_camp],
  g_base_definitions[g_str_5fb1b9dde1af0600177095f8_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dde1af0600177095f8"] = army["5fb1b9dde1af0600177095f8"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Later Hoplite Aitolian or Akarnanian  448 to 225 BC"] = army["5fb1b9dde1af0600177095f8"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Later Hoplite Aitolian or Akarnanian  448 to 225 BC"] = army["5fb1b9dde1af0600177095f8"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Hoplite Aitolian or Akarnanian  448 to 225 BC"] = army["5fb1b9dde1af0600177095f8"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dde1af0600177095f8"] = {}
army_dates["5fb1b9dde1af0600177095f8"]["448 BC to 225 BC"] = {
  startDate=-448,
  endDate=-225
}
army_dates["5fb1b9dde1af0600177095f8"]["448 BC to 322 BC"] = {
  startDate=-448,
  endDate=-322
}
army_dates["5fb1b9dde1af0600177095f8"]["321 BC"] = {
  startDate=-321,
  endDate=-321
}
army_dates["5fb1b9dde1af0600177095f8"]["320 BC to 225 BC"] = {
  startDate=-320,
  endDate=-225
}
