-- 5fb1b9dee1af060017709692 Early Hellenistic Achaean  251 to 208 BC

army['5fb1b9dee1af060017709692']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Early Hellenistic Achaean  251 to 208 BC',
    id='5fb1b9dee1af060017709692',
    dateRange={
      startDate=-251,
      endDate=-208,
    },
  },
  g_base_definitions[g_str_68c995d8579163001588923c_general],
  g_base_definitions[g_str_68c995d8579163001588923c],
  g_base_definitions[g_str_68c995d8579163001588923e_general],
  g_base_definitions[g_str_68c995d8579163001588923e],
  g_base_definitions[g_str_68c995d85791630015889240],
  g_base_definitions[g_str_68c995d85791630015889242],
  g_base_definitions[g_str_68c995d85791630015889244],
  g_base_definitions[g_str_68c995d85791630015889246],
  g_base_definitions[g_str_68c995d85791630015889247],
  g_base_definitions[g_str_5fb1b9dee1af060017709692_camp],
  g_base_definitions[g_str_5fb1b9dee1af060017709692_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dee1af060017709692"] = army["5fb1b9dee1af060017709692"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Early Hellenistic Achaean  251 to 208 BC"] = army["5fb1b9dee1af060017709692"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Hellenistic Achaean  251 to 208 BC"] = army["5fb1b9dee1af060017709692"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dee1af060017709692"] = {}
army_dates["5fb1b9dee1af060017709692"]["251 BC to 208 BC"] = {
  startDate=-251,
  endDate=-208
}
