-- 5fb1b9dee1af06001770969e Hellenistic Minor States  278 to 146 BC

army['5fb1b9dee1af06001770969e']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
      'Hilly',
    },
    name='Hellenistic Minor States  278 to 146 BC',
    id='5fb1b9dee1af06001770969e',
    dateRange={
      startDate=-278,
      endDate=-146,
    },
  },
  g_base_definitions[g_str_68c995d85791630015889260_general],
  g_base_definitions[g_str_68c995d85791630015889260],
  g_base_definitions[g_str_68c995d85791630015889262_general],
  g_base_definitions[g_str_68c995d85791630015889262],
  g_base_definitions[g_str_68c995d85791630015889264_general],
  g_base_definitions[g_str_68c995d85791630015889264],
  g_base_definitions[g_str_68c995d85791630015889266],
  g_base_definitions[g_str_68c995d85791630015889268],
  g_base_definitions[g_str_68c995d85791630015889269],
  g_base_definitions[g_str_68c995d8579163001588926c],
  g_base_definitions[g_str_68c995d8579163001588926e],
  g_base_definitions[g_str_68c995d8579163001588926f],
  g_base_definitions[g_str_5fb1b9dee1af06001770969e_camp],
  g_base_definitions[g_str_5fb1b9dee1af06001770969e_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dee1af06001770969e"] = army["5fb1b9dee1af06001770969e"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Hellenistic Minor States  278 to 146 BC"] = army["5fb1b9dee1af06001770969e"]
if nil == armies["Alexander and Successors"] then
  armies["Alexander and Successors"] ={}
end
armies["Alexander and Successors"]["Hellenistic Minor States  278 to 146 BC"] = army["5fb1b9dee1af06001770969e"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Hellenistic Minor States  278 to 146 BC"] = army["5fb1b9dee1af06001770969e"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dee1af06001770969e"] = {}
army_dates["5fb1b9dee1af06001770969e"]["278 BC to 146 BC"] = {
  startDate=-278,
  endDate=-146
}
army_dates["5fb1b9dee1af06001770969e"]["278 BC to 276 BC"] = {
  startDate=-278,
  endDate=-276
}
army_dates["5fb1b9dee1af06001770969e"]["275 BC to 208 BC"] = {
  startDate=-275,
  endDate=-208
}
army_dates["5fb1b9dee1af06001770969e"]["207 BC"] = {
  startDate=-207,
  endDate=-207
}
army_dates["5fb1b9dee1af06001770969e"]["206 BC to 146 BC"] = {
  startDate=-206,
  endDate=-146
}
