-- 5fb1b9f1e1af06001770a16f Later Spring and Autumn: Chu  549 to 480 BC

army['5fb1b9f1e1af06001770a16f']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
      'Forest',
    },
    name='Later Spring and Autumn: Chu  549 to 480 BC',
    id='5fb1b9f1e1af06001770a16f',
    dateRange={
      startDate=-549,
      endDate=-480,
    },
  },
  g_base_definitions[g_str_68c995e7579163001588bca4_general],
  g_base_definitions[g_str_68c995e7579163001588bca4],
  g_base_definitions[g_str_68c995e7579163001588bca6],
  g_base_definitions[g_str_68c995e7579163001588bca9],
  g_base_definitions[g_str_68c995e7579163001588bcaa],
  g_base_definitions[g_str_68c995e7579163001588bcad],
  g_base_definitions[g_str_68c995e7579163001588bcad_shower_shooting],
  g_base_definitions[g_str_68c995e7579163001588bcb1],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a16f_camp],
  g_base_definitions[g_str_5fb1b9f1e1af06001770a16f_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f1e1af06001770a16f"] = army["5fb1b9f1e1af06001770a16f"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Later Spring and Autumn: Chu  549 to 480 BC"] = army["5fb1b9f1e1af06001770a16f"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Spring and Autumn: Chu  549 to 480 BC"] = army["5fb1b9f1e1af06001770a16f"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f1e1af06001770a16f"] = {}
army_dates["5fb1b9f1e1af06001770a16f"]["549 BC to 480 BC"] = {
  startDate=-549,
  endDate=-480
}
