-- 5fb1b9e1e1af060017709851 Early German Suebi  19 to 49 AD

army['5fb1b9e1e1af060017709851']={
  data={
    invasionRatings={
      2,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Forest',
    },
    name='Early German Suebi  19 to 49 AD',
    id='5fb1b9e1e1af060017709851',
    dateRange={
      startDate=19,
      endDate=49,
    },
  },
  g_base_definitions[g_str_68c995da57916300158898d6_general],
  g_base_definitions[g_str_68c995da57916300158898d6],
  g_base_definitions[g_str_68c995da57916300158898d8],
  g_base_definitions[g_str_68c995da57916300158898d8_mounted],
  g_base_definitions[g_str_68c995da57916300158898d8_dismounted],
  g_base_definitions[g_str_68c995da57916300158898db],
  g_base_definitions[g_str_68c995da57916300158898dd],
  g_base_definitions[g_str_68c995da57916300158898df],
  g_base_definitions[g_str_68c995da57916300158898e1],
  g_base_definitions[g_str_5fb1b9e1e1af060017709851_camp],
  g_base_definitions[g_str_5fb1b9e1e1af060017709851_camp_fortified],
  g_base_definitions[g_str_5fb1b9e1e1af060017709851_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e1e1af060017709851"] = army["5fb1b9e1e1af060017709851"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Early German Suebi  19 to 49 AD"] = army["5fb1b9e1e1af060017709851"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early German Suebi  19 to 49 AD"] = army["5fb1b9e1e1af060017709851"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e1e1af060017709851"] = {}
army_dates["5fb1b9e1e1af060017709851"]["19 AD to 49 AD"] = {
  startDate=19,
  endDate=49
}
