-- 5fb1b9e6e1af060017709b16 South Welsh  1100 to 1197 AD

army['5fb1b9e6e1af060017709b16']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Hilly',
    },
    name='South Welsh  1100 to 1197 AD',
    id='5fb1b9e6e1af060017709b16',
    dateRange={
      startDate=1100,
      endDate=1197,
    },
    ambush=true,  },
  g_base_definitions[g_str_68c995de579163001588a296_general],
  g_base_definitions[g_str_68c995de579163001588a296_general_mounted],
  g_base_definitions[g_str_68c995de579163001588a296_general_dismounted],
  g_base_definitions[g_str_68c995de579163001588a296],
  g_base_definitions[g_str_68c995de579163001588a296_mounted],
  g_base_definitions[g_str_68c995de579163001588a296_dismounted],
  g_base_definitions[g_str_68c995de579163001588a299],
  g_base_definitions[g_str_68c995de579163001588a299_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995de579163001588a299_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995de579163001588a29c],
  g_base_definitions[g_str_68c995de579163001588a29f],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b16_camp],
  g_base_definitions[g_str_5fb1b9e6e1af060017709b16_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e6e1af060017709b16"] = army["5fb1b9e6e1af060017709b16"]
if nil == armies["Embattled Isle"] then
  armies["Embattled Isle"] ={}
end
armies["Embattled Isle"]["South Welsh  1100 to 1197 AD"] = army["5fb1b9e6e1af060017709b16"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["South Welsh  1100 to 1197 AD"] = army["5fb1b9e6e1af060017709b16"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e6e1af060017709b16"] = {}
army_dates["5fb1b9e6e1af060017709b16"]["1100 AD to 1197 AD"] = {
  startDate=1100,
  endDate=1197
}
