-- 5fb1b9e8e1af060017709c9d Hapsburg Burgundian  1478 to 1506 AD

army['5fb1b9e8e1af060017709c9d']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
      'Marsh',
    },
    name='Hapsburg Burgundian  1478 to 1506 AD',
    id='5fb1b9e8e1af060017709c9d',
    dateRange={
      startDate=1478,
      endDate=1506,
    },
  },
  g_base_definitions[g_str_68c995e0579163001588a802_general],
  g_base_definitions[g_str_68c995e0579163001588a802_general_mounted],
  g_base_definitions[g_str_68c995e0579163001588a802_general_dismounted],
  g_base_definitions[g_str_68c995e0579163001588a802],
  g_base_definitions[g_str_68c995e0579163001588a805],
  g_base_definitions[g_str_68c995e0579163001588a807],
  g_base_definitions[g_str_68c995e0579163001588a807_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995e0579163001588a807_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995e0579163001588a80a_general],
  g_base_definitions[g_str_68c995e0579163001588a80a],
  g_base_definitions[g_str_68c995e0579163001588a80c],
  g_base_definitions[g_str_68c995e0579163001588a80e],
  g_base_definitions[g_str_68c995e0579163001588a811],
  g_base_definitions[g_str_5fb1b9e8e1af060017709c9d_camp],
  g_base_definitions[g_str_5fb1b9e8e1af060017709c9d_camp_fortified],
  g_base_definitions[g_str_5fb1b9e8e1af060017709c9d_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9e8e1af060017709c9d"] = army["5fb1b9e8e1af060017709c9d"]
if nil == armies["Holy Roman Empire"] then
  armies["Holy Roman Empire"] ={}
end
armies["Holy Roman Empire"]["Hapsburg Burgundian  1478 to 1506 AD"] = army["5fb1b9e8e1af060017709c9d"]
if nil == armies["Flower of Chivalry"] then
  armies["Flower of Chivalry"] ={}
end
armies["Flower of Chivalry"]["Hapsburg Burgundian  1478 to 1506 AD"] = army["5fb1b9e8e1af060017709c9d"]
if nil == armies["Plate and Handgonne"] then
  armies["Plate and Handgonne"] ={}
end
armies["Plate and Handgonne"]["Hapsburg Burgundian  1478 to 1506 AD"] = army["5fb1b9e8e1af060017709c9d"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Hapsburg Burgundian  1478 to 1506 AD"] = army["5fb1b9e8e1af060017709c9d"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9e8e1af060017709c9d"] = {}
army_dates["5fb1b9e8e1af060017709c9d"]["1478 AD to 1506 AD"] = {
  startDate=1478,
  endDate=1506
}
