-- 5fb1b9dbe1af060017709515 Ptolemaic Kyrene  322 to 74 BC

army['5fb1b9dbe1af060017709515']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      2,
    },
    homeTopographies={
      'Arable',
    },
    name='Ptolemaic Kyrene  322 to 74 BC',
    id='5fb1b9dbe1af060017709515',
    dateRange={
      startDate=-322,
      endDate=-74,
    },
  },
  g_base_definitions[g_str_68c995d65791630015888c16_general],
  g_base_definitions[g_str_68c995d65791630015888c16],
  g_base_definitions[g_str_68c995d65791630015888c18],
  g_base_definitions[g_str_68c995d65791630015888c19_general],
  g_base_definitions[g_str_68c995d65791630015888c19],
  g_base_definitions[g_str_68c995d65791630015888c1b_general],
  g_base_definitions[g_str_68c995d65791630015888c1b_general_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995d65791630015888c1b_general_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995d65791630015888c1b],
  g_base_definitions[g_str_68c995d65791630015888c1b_mounted_mobile_infantry],
  g_base_definitions[g_str_68c995d65791630015888c1b_dismounted_mobile_infantry],
  g_base_definitions[g_str_68c995d65791630015888c1f],
  g_base_definitions[g_str_68c995d65791630015888c21],
  g_base_definitions[g_str_68c995d65791630015888c23],
  g_base_definitions[g_str_68c995d65791630015888c24],
  g_base_definitions[g_str_68c995d65791630015888c26],
  g_base_definitions[g_str_5fb1b9dbe1af060017709515_camp],
  g_base_definitions[g_str_5fb1b9dbe1af060017709515_camp_fortified],
  g_base_definitions[g_str_5fb1b9dbe1af060017709515_camp_pack_train],
  g_base_definitions[g_str_5fb1b9dbe1af060017709515_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dbe1af060017709515"] = army["5fb1b9dbe1af060017709515"]
if nil == armies["Birth of the West"] then
  armies["Birth of the West"] ={}
end
armies["Birth of the West"]["Ptolemaic Kyrene  322 to 74 BC"] = army["5fb1b9dbe1af060017709515"]
if nil == armies["Rise of Rome"] then
  armies["Rise of Rome"] ={}
end
armies["Rise of Rome"]["Ptolemaic Kyrene  322 to 74 BC"] = army["5fb1b9dbe1af060017709515"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Ptolemaic Kyrene  322 to 74 BC"] = army["5fb1b9dbe1af060017709515"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dbe1af060017709515"] = {}
army_dates["5fb1b9dbe1af060017709515"]["322 BC to 74 BC"] = {
  startDate=-322,
  endDate=-74
}
