-- 5fb1b9dfe1af060017709724 Maccabean Jewish Trained Army  152 to 104 BC

army['5fb1b9dfe1af060017709724']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      3,
    },
    homeTopographies={
      'Hilly',
    },
    name='Maccabean Jewish Trained Army  152 to 104 BC',
    id='5fb1b9dfe1af060017709724',
    dateRange={
      startDate=-152,
      endDate=-104,
    },
    ambush=true,  },
  g_base_definitions[g_str_68c995d957916300158894ab_general],
  g_base_definitions[g_str_68c995d957916300158894ab],
  g_base_definitions[g_str_68c995d957916300158894ad],
  g_base_definitions[g_str_68c995d957916300158894af_general],
  g_base_definitions[g_str_68c995d957916300158894af],
  g_base_definitions[g_str_68c995d957916300158894b1],
  g_base_definitions[g_str_68c995d957916300158894b3],
  g_base_definitions[g_str_5fb1b9dfe1af060017709724_camp],
  g_base_definitions[g_str_5fb1b9dfe1af060017709724_camp_pack_train],
  g_base_definitions[g_str_68c995c757916300158870bd_general],
  g_base_definitions[g_str_68c995c757916300158870bd],
  g_base_definitions[g_str_68c995c757916300158870be],
  g_base_definitions[g_str_68c995c757916300158870c0],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dfe1af060017709724"] = army["5fb1b9dfe1af060017709724"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Maccabean Jewish Trained Army  152 to 104 BC"] = army["5fb1b9dfe1af060017709724"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Maccabean Jewish Trained Army  152 to 104 BC"] = army["5fb1b9dfe1af060017709724"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dfe1af060017709724"] = {}
army_dates["5fb1b9dfe1af060017709724"]["152 BC to 104 BC"] = {
  startDate=-152,
  endDate=-104
}
