-- 5fb1b9d9e1af060017709327 Early Bronze Age Highlanders  3000 to 950 BC

army['5fb1b9d9e1af060017709327']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Hilly',
    },
    name='Early Bronze Age Highlanders  3000 to 950 BC',
    id='5fb1b9d9e1af060017709327',
    dateRange={
      startDate=-3000,
      endDate=-950,
    },
  },
  g_base_definitions[g_str_68c995d357916300158884ef_general],
  g_base_definitions[g_str_68c995d357916300158884ef],
  g_base_definitions[g_str_68c995d357916300158884f0_general],
  g_base_definitions[g_str_68c995d357916300158884f0],
  g_base_definitions[g_str_68c995d357916300158884f2],
  g_base_definitions[g_str_68c995d357916300158884f5],
  g_base_definitions[g_str_68c995d357916300158884f7],
  g_base_definitions[g_str_68c995d357916300158884f7_shower_shooting],
  g_base_definitions[g_str_68c995d357916300158884fa],
  g_base_definitions[g_str_5fb1b9d9e1af060017709327_camp],
  g_base_definitions[g_str_5fb1b9d9e1af060017709327_camp_pack_train],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9d9e1af060017709327"] = army["5fb1b9d9e1af060017709327"]
if nil == armies["Cradle of Civilization"] then
  armies["Cradle of Civilization"] ={}
end
armies["Cradle of Civilization"]["Early Bronze Age Highlanders  3000 to 950 BC"] = army["5fb1b9d9e1af060017709327"]
if nil == armies["Chariot Supremacy"] then
  armies["Chariot Supremacy"] ={}
end
armies["Chariot Supremacy"]["Early Bronze Age Highlanders  3000 to 950 BC"] = army["5fb1b9d9e1af060017709327"]
if nil == armies["Sea Peoples Invasions"] then
  armies["Sea Peoples Invasions"] ={}
end
armies["Sea Peoples Invasions"]["Early Bronze Age Highlanders  3000 to 950 BC"] = army["5fb1b9d9e1af060017709327"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Early Bronze Age Highlanders  3000 to 950 BC"] = army["5fb1b9d9e1af060017709327"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9d9e1af060017709327"] = {}
army_dates["5fb1b9d9e1af060017709327"]["3000 BC to 950 BC"] = {
  startDate=-3000,
  endDate=-950
}
