-- 5fb1b9f0e1af06001770a0cd Later Sinhalese  301 to 1515 AD

army['5fb1b9f0e1af06001770a0cd']={
  data={
    invasionRatings={
      0,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Forest',
    },
    name='Later Sinhalese  301 to 1515 AD',
    id='5fb1b9f0e1af06001770a0cd',
    dateRange={
      startDate=301,
      endDate=1515,
    },
  },
  g_base_definitions[g_str_68c995e7579163001588ba85_general],
  g_base_definitions[g_str_68c995e7579163001588ba85],
  g_base_definitions[g_str_68c995e7579163001588ba88],
  g_base_definitions[g_str_68c995e7579163001588ba8a_general],
  g_base_definitions[g_str_68c995e7579163001588ba8a_general_elephant_screen],
  g_base_definitions[g_str_68c995e7579163001588ba8a],
  g_base_definitions[g_str_68c995e7579163001588ba8a_elephant_screen],
  g_base_definitions[g_str_68c995e7579163001588ba8d],
  g_base_definitions[g_str_68c995e7579163001588ba8e],
  g_base_definitions[g_str_68c995e7579163001588ba90],
  g_base_definitions[g_str_68c995e7579163001588ba90_shower_shooting],
  g_base_definitions[g_str_68c995e7579163001588ba93],
  g_base_definitions[g_str_68c995e7579163001588ba93_shower_shooting],
  g_base_definitions[g_str_5fb1b9f0e1af06001770a0cd_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f0e1af06001770a0cd"] = army["5fb1b9f0e1af06001770a0cd"]
if nil == armies["Monsoon Region"] then
  armies["Monsoon Region"] ={}
end
armies["Monsoon Region"]["Later Sinhalese  301 to 1515 AD"] = army["5fb1b9f0e1af06001770a0cd"]
if nil == armies["Southeast Asia"] then
  armies["Southeast Asia"] ={}
end
armies["Southeast Asia"]["Later Sinhalese  301 to 1515 AD"] = army["5fb1b9f0e1af06001770a0cd"]
if nil == armies["India and the Khyber Pass"] then
  armies["India and the Khyber Pass"] ={}
end
armies["India and the Khyber Pass"]["Later Sinhalese  301 to 1515 AD"] = army["5fb1b9f0e1af06001770a0cd"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Sinhalese  301 to 1515 AD"] = army["5fb1b9f0e1af06001770a0cd"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f0e1af06001770a0cd"] = {}
army_dates["5fb1b9f0e1af06001770a0cd"]["301 AD to 1515 AD"] = {
  startDate=301,
  endDate=1515
}
