-- 5fb1b9f0e1af06001770a135 Beidi  788 to 588 BC

army['5fb1b9f0e1af06001770a135']={
  data={
    invasionRatings={
      3,
    },
    maneuverRatings={
      0,
    },
    homeTopographies={
      'Steppe',
    },
    name='Beidi  788 to 588 BC',
    id='5fb1b9f0e1af06001770a135',
    dateRange={
      startDate=-788,
      endDate=-588,
    },
  },
  g_base_definitions[g_str_68c995e7579163001588bc16_general],
  g_base_definitions[g_str_68c995e7579163001588bc16],
  g_base_definitions[g_str_68c995e7579163001588bc18],
  g_base_definitions[g_str_68c995e7579163001588bc1a],
  g_base_definitions[g_str_68c995e7579163001588bc1c],
  g_base_definitions[g_str_5fb1b9f0e1af06001770a135_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9f0e1af06001770a135"] = army["5fb1b9f0e1af06001770a135"]
if nil == armies["Mandate of Heaven"] then
  armies["Mandate of Heaven"] ={}
end
armies["Mandate of Heaven"]["Beidi  788 to 588 BC"] = army["5fb1b9f0e1af06001770a135"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Beidi  788 to 588 BC"] = army["5fb1b9f0e1af06001770a135"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9f0e1af06001770a135"] = {}
army_dates["5fb1b9f0e1af06001770a135"]["788 BC to 588 BC"] = {
  startDate=-788,
  endDate=-588
}
army_dates["5fb1b9f0e1af06001770a135"]["788 BC to 771 BC"] = {
  startDate=-788,
  endDate=-771
}
army_dates["5fb1b9f0e1af06001770a135"]["770 BC to 588 BC"] = {
  startDate=-770,
  endDate=-588
}
