-- 5fb1b9dee1af0600177096ba Galatian  227 to 65 BC

army['5fb1b9dee1af0600177096ba']={
  data={
    invasionRatings={
      4,
      1,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Arable',
    },
    name='Galatian  227 to 65 BC',
    id='5fb1b9dee1af0600177096ba',
    dateRange={
      startDate=-227,
      endDate=-65,
    },
  },
  g_base_definitions[g_str_68c995d857916300158892d7_general],
  g_base_definitions[g_str_68c995d857916300158892d7_general_mounted],
  g_base_definitions[g_str_68c995d857916300158892d7_general_dismounted],
  g_base_definitions[g_str_68c995d857916300158892d7],
  g_base_definitions[g_str_68c995d857916300158892d7_mounted],
  g_base_definitions[g_str_68c995d857916300158892d7_dismounted],
  g_base_definitions[g_str_68c995d857916300158892da_general],
  g_base_definitions[g_str_68c995d857916300158892da],
  g_base_definitions[g_str_68c995d857916300158892dc],
  g_base_definitions[g_str_68c995d857916300158892de],
  g_base_definitions[g_str_68c995d857916300158892e1],
  g_base_definitions[g_str_5fb1b9dee1af0600177096ba_camp],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9dee1af0600177096ba"] = army["5fb1b9dee1af0600177096ba"]
if nil == armies["Hellenistic World"] then
  armies["Hellenistic World"] ={}
end
armies["Hellenistic World"]["Galatian  227 to 65 BC"] = army["5fb1b9dee1af0600177096ba"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Galatian  227 to 65 BC"] = army["5fb1b9dee1af0600177096ba"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9dee1af0600177096ba"] = {}
army_dates["5fb1b9dee1af0600177096ba"]["227 BC to 65 BC"] = {
  startDate=-227,
  endDate=-65
}
