-- 5fb1b9eae1af060017709d9b Later Polish  1335 to 1515 AD

army['5fb1b9eae1af060017709d9b']={
  data={
    invasionRatings={
      1,
    },
    maneuverRatings={
      1,
    },
    homeTopographies={
      'Forest',
    },
    name='Later Polish  1335 to 1515 AD',
    id='5fb1b9eae1af060017709d9b',
    dateRange={
      startDate=1335,
      endDate=1515,
    },
  },
  g_base_definitions[g_str_68c995e2579163001588ac9e_general],
  g_base_definitions[g_str_68c995e2579163001588ac9e],
  g_base_definitions[g_str_68c995e2579163001588aca1_general],
  g_base_definitions[g_str_68c995e2579163001588aca1],
  g_base_definitions[g_str_68c995e2579163001588aca3],
  g_base_definitions[g_str_68c995e2579163001588aca3_mounted],
  g_base_definitions[g_str_68c995e2579163001588aca3_dismounted],
  g_base_definitions[g_str_68c995e2579163001588aca7],
  g_base_definitions[g_str_68c995e2579163001588aca9],
  g_base_definitions[g_str_68c995e2579163001588acab],
  g_base_definitions[g_str_68c995e2579163001588acab_mounted],
  g_base_definitions[g_str_68c995e2579163001588acab_dismounted],
  g_base_definitions[g_str_68c995e2579163001588acae],
  g_base_definitions[g_str_68c995e2579163001588acb1],
  g_base_definitions[g_str_68c995e2579163001588acb4],
  g_base_definitions[g_str_5fb1b9eae1af060017709d9b_camp],
  g_base_definitions[g_str_5fb1b9eae1af060017709d9b_prepared_defenses],
}
if nil == armies["Meshwesh id"] then
  armies["Meshwesh id"] ={}
end
armies["Meshwesh id"]["5fb1b9eae1af060017709d9b"] = army["5fb1b9eae1af060017709d9b"]
if nil == armies["Russian Princes"] then
  armies["Russian Princes"] ={}
end
armies["Russian Princes"]["Later Polish  1335 to 1515 AD"] = army["5fb1b9eae1af060017709d9b"]
if nil == armies["Baltic Powers"] then
  armies["Baltic Powers"] ={}
end
armies["Baltic Powers"]["Later Polish  1335 to 1515 AD"] = army["5fb1b9eae1af060017709d9b"]
if nil == armies["Holy Roman Empire"] then
  armies["Holy Roman Empire"] ={}
end
armies["Holy Roman Empire"]["Later Polish  1335 to 1515 AD"] = army["5fb1b9eae1af060017709d9b"]
if nil == armies["Plate and Handgonne"] then
  armies["Plate and Handgonne"] ={}
end
armies["Plate and Handgonne"]["Later Polish  1335 to 1515 AD"] = army["5fb1b9eae1af060017709d9b"]
if nil == armies["All"] then
  armies["All"] ={}
end
armies["All"]["Later Polish  1335 to 1515 AD"] = army["5fb1b9eae1af060017709d9b"]
if nil == army_dates then
  army_dates={}
end
army_dates["5fb1b9eae1af060017709d9b"] = {}
army_dates["5fb1b9eae1af060017709d9b"]["1335 AD to 1515 AD"] = {
  startDate=1335,
  endDate=1515
}
