--
-- This file will include non-related armies that use
-- the same base of 3D models, modified by Arkein.
--
-- These were the very first models and there are no
-- differences besides colors and flags.
-- We will replace 3D with Photogametry once we have
-- The proper models
--
-- Early Renaissance Swiss
army['5fb1b9e9e1af060017709d15'].data.has_models = true
army['5fb1b9e9e1af060017709d15'].data.base="tile_grass"
-- Later Swiss
army['5fb1b9e9e1af060017709d0d'].data.has_models = true
army['5fb1b9e9e1af060017709d0d'].data.base="tile_grass"
-- Burgundian Ordonnances
army['5fb1b9e8e1af060017709c95'].data.has_models = true
army['5fb1b9e8e1af060017709c95'].data.base="tile_grass"
-- Hapsburg Burgundian
army['5fb1b9e8e1af060017709c9d'].data.has_models = true
army['5fb1b9e8e1af060017709c9d'].data.base="tile_grass"
-- Transitional Renaissance Spanish
army['5fb1b9e7e1af060017709c19'].data.has_models = true
army['5fb1b9e7e1af060017709c19'].data.base="tile_grass"
-- Medieval Portuguese - latest representation
army['5fb1b9e7e1af060017709bfd'].data.has_models = true
army['5fb1b9e7e1af060017709bfd'].data.base="tile_grass"
-- Order of St. John
army['5fb1b9eee1af06001770a00c'].data.has_models = true
army['5fb1b9eee1af06001770a00c'].data.base="tile_grass"
-- Wars of the Roses English
army['5fb1b9e6e1af060017709b42'].data.has_models = true
army['5fb1b9e6e1af060017709b42'].data.base="tile_grass"
-- Tudor English
army['5fb1b9e6e1af060017709b49'].data.has_models = true
army['5fb1b9e6e1af060017709b49'].data.base="tile_grass"
-- French Ordonnance
army['5fb1b9e8e1af060017709c53'].data.has_models = true
army['5fb1b9e8e1af060017709c53'].data.base="tile_grass"
-- Later French Ordonnance
army['5fb1b9e8e1af060017709c5b'].data.has_models = true
army['5fb1b9e8e1af060017709c5b'].data.base="tile_grass"
--Later Medieval German Citystates
army['5fb1b9e8e1af060017709cdd'].data.has_models = true
army['5fb1b9e8e1af060017709cdd'].data.base="tile_grass"
-- Early Renaissance German Citystates
army['5fb1b9e8e1af060017709cd3'].data.has_models = true
army['5fb1b9e8e1af060017709cd3'].data.base="tile_grass"

-- Early Renaissance Swiss
-- 1478 AD to 1522 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e9e1af060017709d15/explore
-- As of: 20210420

    -- Crossbowmen on horses
    g_models[g_str_68c995e1579163001588aa03] = {
      {
        model_data = 'troop_horse_rider_swiss'
      }
    }

    --Crossbowmen on horses\nMid-battle dismounted from Bad Horse - Skirmishers
    g_models[g_str_68c995e1579163001588aa03_dismounted] = {
      {
        model_data = 'troop_crossbowman_swiss'
      }
    }

    --Crossbowmen on horses - Bad Horse
    g_models[g_str_68c995e1579163001588aa03_mounted] = g_models[g_str_68c995e1579163001588aa03]

    -- Pikemen mixed with some halberdiers - Pikes General
    g_models[g_str_68c995e1579163001588aa06_general] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_pikeman_swiss_inclined',
          [2] = 'troop_pikeman_swiss_bannerman',
          [3] = 'troop_pikeman_swiss_captain',
          [4] = 'troop_halberdier_swiss'
        }
      }
    }

    -- Pikemen mixed with some halberdiers - Pikes
    g_models[g_str_68c995e1579163001588aa06] = {
        {
        random_models = {
          'troop_pikeman_swiss_straight',
          'troop_halberdier_swiss',
          'troop_pikeman_swiss_straight',
          'troop_pikeman_swiss_straight',
          'troop_pikeman_swiss_straight'
        }
      },
      {
        random_models = {
          'troop_pikeman_swiss_inclined',
          'troop_halberdier_swiss',
          'troop_pikeman_swiss_inclined',
          'troop_pikeman_swiss_inclined',
          'troop_pikeman_swiss_inclined'
        }
      }
    }

    --Separately deployed halberdiers, some with armor - Raiders
    g_models[g_str_68c995e1579163001588aa08] = {
      {
        model_data = 'troop_halberdier_swiss'
      }
    }

    --Separately deployed halberdiers, some with armor - EF
    g_models[g_str_68c995e1579163001588aa09] = {
      {
        model_data = 'troop_halberdier_swiss'
      }
    }

    -- Skirmishing handgunners - Sk
    g_models[g_str_68c995e1579163001588aa0b] = {
      {
        loose = true,
        model_data = 'troop_handgunner_swiss'
      }
    }

    -- Skirmishing crossbowmen and handgunners - Sk
    g_models[g_str_68c995e1579163001588aa0d] = {
      {
        loose = true,
        random_models = {
          'troop_handgunner_swiss',
          'troop_crossbowman_swiss'
        }
      }
    }

    -- Early Renaissance Swiss Camp
    g_models[g_str_5fb1b9e9e1af060017709d15_camp] = {
      {
        n_models = 1,
        model_data = 'troop_camp_swiss'
      }
    }



-- Later Swiss
-- 1425 AD to 1477 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e9e1af060017709d0d/explore
-- As of: 20210420


    --Crossbowmen on horses - Bad Horse
    g_models[g_str_68c995e1579163001588a9ef] = g_models[g_str_68c995e1579163001588aa03]

    --Crossbowmen on horses\nMid-battle dismounted from Bad Horse - Skirmishers
    g_models[g_str_68c995e1579163001588a9ef_dismounted] = g_models[g_str_68c995e1579163001588aa03_dismounted]

    --Crossbowmen on horses - Bad Horse
    g_models[g_str_68c995e1579163001588a9ef_mounted] = g_models[g_str_68c995e1579163001588aa03]

    -- Pikemen mixed with some halberdiers - Pikes General
    g_models[g_str_68c995e1579163001588a9f2_general] = g_models[g_str_68c995e1579163001588aa06_general]

    -- Pikemen mixed with some halberdiers - Pikes
    g_models[g_str_68c995e1579163001588a9f2] = g_models[g_str_68c995e1579163001588aa06]

    --Separately deployed halberdiers, some with armor - Raiders
    g_models[g_str_68c995e1579163001588a9f4] = g_models[g_str_68c995e1579163001588aa08]

    --Separately deployed halberdiers, some with armor - EF
    g_models[g_str_68c995e1579163001588a9f5] = g_models[g_str_68c995e1579163001588aa09]

    -- Skirmishing handgunners - Sk
    g_models[g_str_68c995e1579163001588a9f7] = g_models[g_str_68c995e1579163001588aa0b]

    -- Skirmishing crossbowmen - Sk
    g_models[g_str_68c995e1579163001588a9f9] = g_models[g_str_68c995e1579163001588a9ef_dismounted]

    -- Captured Burgundian artillery - Arty
    g_models[g_str_68c995e1579163001588a9fc] = {
      {
        n_models = 3,
        fixed_models = {
            [1] = 'troop_artillery_crew_swiss',
            [2] = 'troop_artillery_pieces_swiss',
            [3] = 'troop_artillery_crew_swiss'
        }
      }
    }

    -- Early Renaissance Swiss Camp
    g_models[g_str_5fb1b9e9e1af060017709d0d_camp] = g_models[g_str_5fb1b9e9e1af060017709d15_camp]



-- Burgundian Ordonnances
-- 1471 AD to 1477 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e8e1af060017709c95/explore
-- As of: 20210420


    -- Ordonnance gendarmes and their coustilliers - Kn General
    g_models[g_str_68c995e0579163001588a7e6_general] = {
      {
        n_models = 3,
        fixed_models = {
            [1] = 'troop_knight_burgundian_ordonnances',
            [2] = 'troop_knight_burgundian_ordonnances_captain',
            [3] = 'troop_knight_burgundian_ordonnances_bannerman'
        },
      }
    }

    -- Ordonnance gendarmes and their coustilliers\nDeployment dismounted from Knights General - EF General
    g_models[g_str_68c995e0579163001588a7e6_general_dismounted] = {
      {
        n_models = 4,
        fixed_models = {
            [1] = 'troop_swordman_two_handed_burgundian_ordonnances',
            [2] = 'troop_pikeman_burgundian_ordonnances_bannerman',
            [3] = 'troop_pikeman_burgundian_ordonnances_captain',
            [4] = 'troop_swordman_two_handed_burgundian_ordonnances'
        },
      }
    }

    -- Ordonnance gendarmes and their coustilliers - Kn General
    g_models[g_str_68c995e0579163001588a7e6_general_mounted] = g_models[g_str_68c995e0579163001588a7e6_general]

    -- Ordonnance gendarmes and their coustilliers - Kn
    g_models[g_str_68c995e0579163001588a7e6] = {
      {
        model_data = 'troop_knight_burgundian_ordonnances'
      }
    }

    -- Ordonnance gendarmes and their coustilliers\nDeployment dismounted from Knights General - EF
    g_models[g_str_68c995e0579163001588a7e6_dismounted] = {
      {
        model_data = 'troop_swordman_two_handed_burgundian_ordonnances'
      }
    }

    -- Ordonnance gendarmes and their coustilliers - Kn
    g_models[g_str_68c995e0579163001588a7e6_mounted] = g_models[g_str_68c995e0579163001588a7e6]

    -- Organ guns, bombards, and various other pieces - Arty
    g_models[g_str_68c995e0579163001588a7e9] = {
      {
        n_models = 3,
        fixed_models = {
            [1] = 'troop_artillery_crew_burgundian_ordonnances',
            [2] = 'troop_artillery_pieces_burgundian_ordonnances',
            [3] = 'troop_artillery_crew_burgundian_ordonnances'
        }
      }
    }

    -- Ordonnance longbowmen and crossbowmen - Archers
    g_models[g_str_68c995e0579163001588a7eb] = {
      {
        model_data = 'troop_crossbowman_burgundian_ordonnances'
      },
      {
        model_data = 'troop_longbowman_burgundian_ordonnances'
      }
    }

    -- Ordonnance longbowmen and crossbowmen Dismounted- Archers
    g_models[g_str_68c995e0579163001588a7eb_dismounted_mobile_infantry] = g_models[g_str_68c995e0579163001588a7e6]

    -- Ordonnance longbowmen and crossbowmen Mounted- Archers
    g_models[g_str_68c995e0579163001588a7eb_mounted_mobile_infantry] = {
      {
        n_models = 4,
        model_data = 'troop_horse_rider_burgundian_ordonnances'
      }
    }

    -- Ordonnance pikemen - Pikes
    g_models[g_str_68c995e0579163001588a7ee] = {
      {
        model_data = 'troop_pikeman_burgundian_ordonnances_inclined'
      },
      {
        model_data = 'troop_pikeman_burgundian_ordonnances_straight'
      }
    }

    --mixed formations of pikemen and longbowmen - Pavisiers
    g_models[g_str_68c995e0579163001588a7ef] = {
      {
        n_models = 8,
        fixed_models = {
            [1] = 'troop_longbowman_burgundian_ordonnances',
            [2] = 'troop_longbowman_burgundian_ordonnances',
            [3] = 'troop_longbowman_burgundian_ordonnances',
            [4] = 'troop_longbowman_burgundian_ordonnances',
            [5] = 'troop_pikeman_burgundian_ordonnances_inclined',
            [6] = 'troop_pikeman_burgundian_ordonnances_inclined',
            [7] = 'troop_pikeman_burgundian_ordonnances_inclined',
            [8] = 'troop_pikeman_burgundian_ordonnances_inclined'
        },
      }
    }

    -- Ordonnance handgunners - Sk
    g_models[g_str_68c995e0579163001588a7f1] = {
      {
        loose = true,
        model_data = 'troop_handgunner_burgundian_ordonnances'
      }
    }

    -- Italian men-at-arms - Kn General
    g_models[g_str_68c995e0579163001588a7f3_general] = {
      {
        n_models = 3,
        fixed_models = {
            [1] = 'troop_knight_late_medieval',
            [2] = 'troop_knight_late_medieval_captain',
            [3] = 'troop_knight_italian_condotta_bannerman'
        },
      }
    }

    -- Italian men-at-arms - Kn
    g_models[g_str_68c995e0579163001588a7f3] = {
      {
        model_data = 'troop_knight_late_medieval'
      }
    }

    -- Italian Corssbowmen on horses - Bad Horse
    g_models[g_str_68c995e0579163001588a7f5] = {
      {
        model_data = 'troop_horse_rider_late_medieval'
      }
    }

    -- Italian Corssbowmen - Archers
    g_models[g_str_68c995e0579163001588a7f7] = {
      {
        model_data = 'troop_crossbowman_late_medieval'
      }
    }

    -- Low Countries pikemen - Pikes
    g_models[g_str_68c995e0579163001588a7f9] = {
      {
        model_data = 'troop_pikeman_late_medieval_inclined'
      },
      {
        model_data = 'troop_pikeman_late_medieval_straight'
      }
    }

    -- Burgundian Ordonnance Camp
    g_models[g_str_5fb1b9e8e1af060017709c95_camp] = {
      {
        n_models = 1,
        model_data = 'troop_camp_burgundian_ordonnances'
      }
    }

    -- Burgundian Ordonnance Camp Fort
    g_models[g_str_5fb1b9e8e1af060017709c95_camp_fortified] = {
      {
        overlay_models = { -- each of the models are placed on top of the base
          {
            model_data="troop_fortified_camp_outline_40x40",
            position={x=-0,y=0,z=0}, -- optional defaults to (0,0,0)
            rotation=0, -- optional defaults to 0
            scale=1, -- optional defaults t0 1
          },
          {
            model_data = 'troop_camp_burgundian_ordonnances',
            scale=0.7
          }
        }
      }
    }


-- Hapsburg Burgundian
-- 1478 AD to 1506 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e8e1af060017709c9d/explore
-- As of: 20210420


    -- Ordonnance gendarmes and their coustilliers - Kn General
    g_models[g_str_68c995e0579163001588a802_general] = g_models[g_str_68c995e0579163001588a7e6_general]

    -- Ordonnance gendarmes and their coustilliers\nDeployment dismounted from Knights General - EF General
    g_models[g_str_68c995e0579163001588a802_general_dismounted] = g_models[g_str_68c995e0579163001588a7e6_general_dismounted]

    -- Ordonnance gendarmes and their coustilliers - Kn General
    g_models[g_str_68c995e0579163001588a802_general_mounted] = g_models[g_str_68c995e0579163001588a802_general]

    -- Ordonnance gendarmes and their coustilliers - Kn
    g_models[g_str_68c995e0579163001588a802] = g_models[g_str_68c995e0579163001588a7e6]

-- TODO
--    -- Ordonnance gendarmes and their coustilliers\nDeployment dismounted from Knights General - EF
--    g_models[g_str_68c995e0579163001588a802_dismounted] = g_models[g_str_68c995e0579163001588a7e6_dismounted]
--
--    -- Ordonnance gendarmes and their coustilliers - Kn
--    g_models[g_str_68c995e0579163001588a802_mounted] = g_models[g_str_68c995e0579163001588a802]

    -- Organ guns, bombards, and various other pieces - Arty
    g_models[g_str_68c995e0579163001588a805] = g_models[g_str_68c995e0579163001588a7e9]

    -- Ordonnance longbowmen and crossbowmen - Archers
    g_models[g_str_68c995e0579163001588a807] = g_models[g_str_68c995e0579163001588a7eb]

    -- Ordonnance longbowmen and crossbowmen Dismounted- Archers
    g_models[g_str_68c995e0579163001588a807_dismounted_mobile_infantry] = g_models[g_str_68c995e0579163001588a807]

    -- Ordonnance longbowmen and crossbowmen Mounted- Archers
    g_models[g_str_68c995e0579163001588a807_mounted_mobile_infantry] = g_models[g_str_68c995e0579163001588a7eb_mounted_mobile_infantry]

    -- Ordonnance pikemen - Pikes
    g_models[g_str_68c995e0579163001588a80a_general] = {
      {
        n_models = 4,
        fixed_models = {
            [1] = 'troop_pikeman_burgundian_ordonnances_straight',
            [2] = 'troop_pikeman_burgundian_ordonnances_bannerman',
            [3] = 'troop_pikeman_burgundian_ordonnances_captain',
            [4] = 'troop_pikeman_burgundian_ordonnances_straight'
        }
      }
    }

    -- Ordonnance pikemen - Pikes
    g_models[g_str_68c995e0579163001588a80a] = g_models[g_str_68c995e0579163001588a7ee]

    -- Militia or mercenary crossbowmen - Archers
    g_models[g_str_68c995e0579163001588a80c] = {
      {
        random_models = {
          'troop_crossbowman_late_medieval',
          'troop_crossbowman_burgundian_ordonnances'
        }
      }
    }

    -- Militia or mercenary handgunners - Sk
    g_models[g_str_68c995e0579163001588a80e] = {
      {
        loose = true,
        random_models = {
          'troop_handgunner_late_medieval',
          'troop_handgunner_burgundian_ordonnances'
        }
      }
    }

    -- English longbowmen - Archers
    g_models[g_str_68c995e0579163001588a811] = {
      {
        model_data = 'troop_longbowman_late_medieval'
      }
    }

    -- Burgundian Ordonnance Camp
    g_models[g_str_5fb1b9e8e1af060017709c9d_camp] = g_models[g_str_5fb1b9e8e1af060017709c95_camp]

    -- Burgundian Ordonnance Camp Fort
    g_models[g_str_5fb1b9e8e1af060017709c9d_camp_fortified] = g_models[g_str_5fb1b9e8e1af060017709c95_camp_fortified]


-- Transitional Renaissance Spanish
-- 1495 AD to 1503 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e7e1af060017709c19/explore
-- As of: 20210420


    -- Men-at-arms - Kn General
    g_models[g_str_68c995df579163001588a600_general] = {
      {
        n_models = 3,
        fixed_models = {
            [1] = 'troop_knight_late_medieval',
            [2] = 'troop_knight_late_medieval_captain',
            [3] = 'troop_knight_medieval_spanish_bannerman'
        }
      }
    }

    -- Men-at-arms - Kn
    g_models[g_str_68c995df579163001588a600] = {
      {
        model_data = 'troop_knight_late_medieval'
      }
    }

    -- Jinetes - Jav Cav
    g_models[g_str_68c995df579163001588a602] = {
      {
        loose = true,
        model_data = 'troop_horse_rider_late_medieval'
      }
    }

    -- Pikemen - Light Spear
    g_models[g_str_68c995df579163001588a604] = {
      {
        random_models = {
          'troop_pikeman_late_medieval_straight',
          'troop_pikeman_late_medieval_inclined'
        }
      }
    }

    -- Sword-and-buckler men - Raiders
    g_models[g_str_68c995df579163001588a606] = {
      {
        loose = true,
        random_models = {
          'troop_swordman_late_medieval'
        }
      }
    }

    -- Ordonnance handgunners - Sk
    g_models[g_str_68c995df579163001588a608] = {
      {
        loose = true,
        random_models = {
          'troop_handgunner_late_medieval',
          'troop_crossbowman_late_medieval'
        }
      }
    }

    -- Organ guns, bombards, and various other pieces - Arty
    g_models[g_str_68c995df579163001588a60a] = {
      {
        n_models = 3,
        fixed_models = {
            [1] = 'troop_artillery_crew_late_medieval',
            [2] = 'troop_artillery_pieces_late_medieval',
            [3] = 'troop_artillery_crew_late_medieval'
        }
      }
    }

    -- Transitional Renaissance Spanish Camp
    g_models[g_str_5fb1b9e7e1af060017709c19_camp] = {
      {
        n_models = 1,
        model_data = 'troop_camp_burgundian_ordonnances'
      }
    }

    -- Transitional Renaissance Spanish Camp Pack Train
    g_models[g_str_5fb1b9e7e1af060017709c19_camp_pack_train] = g_models[g_str_5fb1b9e1e1af060017709849_camp_pack_train]


-- Medieval Portuguese
-- 1340 AD to 1515 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e7e1af060017709bfd/explore
-- As of: 20210420


    -- Men-at-arms - Kn General
    g_models[g_str_68c995df579163001588a590_general] = {
      {
        n_models = 3,
        fixed_models = {
          [1] = 'troop_knight_medieval_portuguese_bannerman',
          [2] = 'troop_knight_late_medieval_captain',
          [3] = 'troop_knight_late_medieval'
        }
      }
    }


    -- Men-at-arms\nDeployment dismounted from Knights General - EF General
    g_models[g_str_68c995df579163001588a590_general_dismounted] = {
      {
        n_models = 4,
        fixed_models = {
            [1] = 'troop_swordman_late_medieval',
            [2] = 'troop_pikeman_medieval_portuguese_bannerman',
            [3] = 'troop_pikeman_late_medieval_captain',
            [4] = 'troop_halberdier_late_medieval'
        }
      }
    }

    -- Men-at-arms\nDeployment dismounted from Knights General- Kn General
    g_models[g_str_68c995df579163001588a590_general_mounted] = g_models[g_str_68c995df579163001588a590_general]


    -- Men-at-arms - Kn
    g_models[g_str_68c995df579163001588a590] = g_models[g_str_68c995df579163001588a600]

    -- Men-at-arms\nDeployment dismounted from Knights - EF
    g_models[g_str_68c995df579163001588a590_dismounted] = {
      {
        model_data = 'troop_swordman_late_medieval'
      }
    }

    -- Men-at-arms\nDeployment dismounted from Knights- Kn
    g_models[g_str_68c995df579163001588a590_mounted] = g_models[g_str_68c995df579163001588a590]

    -- Ginetes - Jav Cav
    g_models[g_str_68c995df579163001588a593] = g_models[g_str_68c995df579163001588a602]

    -- Spearmen - Heavy Foot
    g_models[g_str_68c995df579163001588a595] = {
      {
        model_data = 'troop_spearman_late_medieval'
      }
    }

    -- Crossbow and bowmen - Bow Levy
    g_models[g_str_68c995df579163001588a597] = {
      {
        loose = true,
        random_models = {
          'troop_crossbowman_late_medieval',
          'troop_bowman_late_medieval'
        }
      }
    }

    -- Crossbow and bowmen - Archers
    g_models[g_str_68c995df579163001588a598] = {
      {
        model_data = 'troop_crossbowman_late_medieval'
      },
      {
        model_data = 'troop_bowman_late_medieval'
      }
    }

    -- Skirmishing slingers - Sk [not precisely slingers yet]
    g_models[g_str_68c995df579163001588a59b] = {
      {
        loose = true,
        model_data = 'troop_handgunner_late_medieval'
      }
    }

    -- Grenadine mercenaries - Jav Cav [not even close to grenadine]
    g_models[g_str_68c995df579163001588a59d] = g_models[g_str_68c995df579163001588a602]

    -- Javelinmen - LF
    g_models[g_str_68c995df579163001588a59f] = {
      {
        model_data = 'troop_spearman_no_shield_late_medieval'
      }
    }

    -- Peasants - Rabble
    g_models[g_str_68c995df579163001588a5a1] = {
      {
        model_data = 'troop_horde_late_medieval',
        loose = true
      }
    }

    -- Medieval Portuguese Camp
    g_models[g_str_5fb1b9e7e1af060017709bfd_camp] = {
      {
        n_models = 1,
        model_data = 'troop_camp_late_medieval'
      }
    }

    -- Medieval Portuguese Camp Pack Train
    g_models[g_str_5fb1b9e7e1af060017709bfd_camp_pack_train] = g_models[g_str_5fb1b9e1e1af060017709849_camp_pack_train]

-- Order of St. John
-- 1291 AD to 1522 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9eee1af06001770a00c/explore
-- As of: 20210420


    -- Brother men-at-arms, sergeants, and turcopoles - Kn General
    g_models[g_str_68c995e5579163001588b72c_general] = {
      {
        n_models = 3,
        fixed_models = {
          [1] = 'troop_knight_saint_john_bannerman',
          [2] = 'troop_knight_late_medieval_captain',
          [3] = 'troop_knight_late_medieval'
        }
      }
    }


    -- Brother men-at-arms, sergeants, and turcopoles\nDeployment dismounted from Knights General - EF General
    g_models[g_str_68c995e5579163001588b72c_general_dismounted] = {
      {
        n_models = 4,
        fixed_models = {
            [1] = 'troop_swordman_late_medieval',
            [2] = 'troop_pikeman_saint_john_bannerman',
            [3] = 'troop_pikeman_late_medieval_captain',
            [4] = 'troop_halberdier_late_medieval'
        }
      }
    }

    -- Brother men-at-arms, sergeants, and turcopoles\nDeployment dismounted from Knights General- Kn General
    g_models[g_str_68c995e5579163001588b72c_general_mounted] = g_models[g_str_68c995e5579163001588b72c_general]

    -- Men-at-arms - Kn
    g_models[g_str_68c995e5579163001588b72c] = g_models[g_str_68c995df579163001588a600]

    -- Men-at-arms\nDeployment dismounted from Knights - EF
    g_models[g_str_68c995e5579163001588b72c_dismounted] = g_models[g_str_68c995df579163001588a590_dismounted]

    -- Men-at-arms\nDeployment dismounted from Knights- Kn
    g_models[g_str_68c995e5579163001588b72c_mounted] = g_models[g_str_68c995df579163001588a590]

    -- Greek or colonist spearmen - HF General
    g_models[g_str_68c995e5579163001588b72f_general] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_spearman_late_medieval',
          [2] = 'troop_pikeman_saint_john_bannerman',
          [3] = 'troop_pikeman_late_medieval_captain',
          [4] = 'troop_spearman_late_medieval'
        }
      }
    }

    -- Greek or colonist spearmen - Heavy Foot
    g_models[g_str_68c995e5579163001588b72f] = {
      {
        model_data = 'troop_spearman_late_medieval'
      }
    }

    -- Greek bowmen and crossbowmen - Bow Levy General
    g_models[g_str_68c995e5579163001588b731_general] = {
      {
        n_models = 3,
        fixed_models = {
            [1] = 'troop_crossbowman_late_medieval',
            [2] = 'troop_pikeman_saint_john_bannerman',
            [3] = 'troop_bowman_late_medieval'
        },
      }
    }

    -- Greek bowmen and crossbowmen - Bow Levy
    g_models[g_str_68c995e5579163001588b731] = {
      {
        loose = true,
        random_models = {
          'troop_crossbowman_late_medieval',
          'troop_bowman_late_medieval'
        }
      }
    }

    -- Colonist crossbowmen - Archers General
    g_models[g_str_68c995e5579163001588b734_general] = {
      {
        n_models = 4,
        fixed_models = {
            [1] = 'troop_crossbowman_late_medieval',
            [2] = 'troop_pikeman_saint_john_bannerman',
            [3] = 'troop_pikeman_late_medieval_captain',
            [4] = 'troop_crossbowman_late_medieval'
        }
      }
    }

    -- Colonist crossbowmen - Archers
    g_models[g_str_68c995e5579163001588b734] = {
      {
        model_data = 'troop_crossbowman_late_medieval'
      }
    }

    -- Mercenary crossbowmen - Archers General
    g_models[g_str_68c995e5579163001588b736_general] = {
      {
        n_models = 4,
        fixed_models = {
            [1] = 'troop_crossbowman_swiss',
            [2] = 'troop_pikeman_saint_john_bannerman',
            [3] = 'troop_pikeman_swiss_captain',
            [4] = 'troop_crossbowman_swiss'
        }
      }
    }

    -- Mercenary crossbowmen - Archers
    g_models[g_str_68c995e5579163001588b736] = {
      {
        model_data = 'troop_crossbowman_swiss'
      }
    }

    -- Skirmishing Handgunners - Sk
    g_models[g_str_68c995e5579163001588b739] = {
      {
        loose = true,
        model_data = 'troop_handgunner_late_medieval'
      }
    }

    -- Mercenary halberdiers - EF General
    g_models[g_str_68c995e5579163001588b73c_general] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_halberdier_late_medieval',
          [2] = 'troop_pikeman_saint_john_bannerman',
          [3] = 'troop_pikeman_late_medieval_captain',
          [4] = 'troop_halberdier_late_medieval'
        }
      }
    }

    -- Mercenary halberdiers - EF
    g_models[g_str_68c995e5579163001588b73c] = {
      {
        model_data = 'troop_halberdier_late_medieval'
      }
    }

    -- Bombards and other guns - Arty
    g_models[g_str_68c995e5579163001588b73f] = g_models[g_str_68c995df579163001588a60a]

    -- Transitional Renaissance Spanish Camp
    g_models[g_str_5fb1b9eee1af06001770a00c_camp] = {
      {
        n_models = 1,
        model_data = 'troop_camp_burgundian_ordonnances'
      }
    }

-- Wars Of The Roses English
-- 1455 AD to 1488 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e6e1af060017709b42/explore
-- As of: 20220102


    -- Men-at-arms - Kn General
    g_models[g_str_68c995df579163001588a336_general] = {
      {
        n_models = 3,
        fixed_models = {
          [1] = 'troop_knight_english_wotr_a_bannerman',
          [2] = 'troop_knight_late_medieval_captain',
          [3] = 'troop_knight_late_medieval'
        }
      }
    }


    -- Men-at-arms\nDeployment dismounted from Knights General - EF General
    g_models[g_str_68c995df579163001588a336_general_dismounted] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_halberdier_late_medieval',
          [2] = 'troop_pikeman_english_wotr_a_bannerman',
          [3] = 'troop_pikeman_late_medieval_captain',
          [4] = 'troop_halberdier_late_medieval'
        }
      }
    }

    -- Men-at-arms\nDeployment dismounted from Knights General- Kn General
    g_models[g_str_68c995df579163001588a336_general_mounted] = g_models[g_str_68c995df579163001588a336_general]

    -- Men-at-arms - Kn
    g_models[g_str_68c995df579163001588a336] = g_models[g_str_68c995df579163001588a600]

    -- Men-at-arms\nDeployment dismounted from Knights - EF
    g_models[g_str_68c995df579163001588a336_dismounted] = g_models[g_str_68c995df579163001588a590_dismounted]

    -- Men-at-arms\nDeployment dismounted from Knights- Kn
    g_models[g_str_68c995df579163001588a336_mounted] = g_models[g_str_68c995df579163001588a590]

    -- Currours - JavCav
    g_models[g_str_68c995df579163001588a339] = g_models[g_str_68c995df579163001588a602]

    -- Retinue billmen - EF
    g_models[g_str_68c995df579163001588a33b] = g_models[g_str_68c995df579163001588a590_dismounted]

    -- Retinue billmen\nDismounted mobile infantry - EF
    g_models[g_str_68c995df579163001588a33b_dismounted_mobile_infantry] = g_models[g_str_68c995df579163001588a590_dismounted]
    
    -- Retinue billmen\nMounted mobile infantry - EF
    g_models[g_str_68c995df579163001588a33b_mounted_mobile_infantry] = {
      {
        model_data = 'troop_horse_rider_late_medieval'
      }
    }

    -- Retinue bowmen  - Archers
    g_models[g_str_68c995df579163001588a33f] = g_models[g_str_68c995e0579163001588a811]

    -- Retinue bowmen\nDismounted mobile infantry  - Archers
    g_models[g_str_68c995df579163001588a33f_dismounted_mobile_infantry] = g_models[g_str_68c995e0579163001588a811]

    -- Retinue bowmen\nMunted mobile infantry - Archers
    g_models[g_str_68c995df579163001588a33f_mounted_mobile_infantry] = g_models[g_str_68c995df579163001588a33b_mounted_mobile_infantry]

    -- Welsh spearmen - Light Spear
    g_models[g_str_68c995df579163001588a342] = {
      {
        model_data = 'troop_spearman_no_shield_late_medieval'
      }
    }

    -- Welsh bowmen  - Archers
    g_models[g_str_68c995df579163001588a346] = g_models[g_str_68c995e0579163001588a811]

    -- Irish kerns - LF
    g_models[g_str_68c995df579163001588a349] = {
      {
        model_data = 'troop_horde_late_medieval'
      }
    }

    -- Continental handgunners - Sk
    g_models[g_str_68c995df579163001588a34d] = {
      {
        model_data = 'troop_bowman_late_medieval'
      }
    }
    -- French crossbowmen - Sk
    g_models[g_str_68c995df579163001588a351] = {
      {
        model_data = 'troop_crossbowman_burgundian_ordonnances'
      }
    }

    -- Breton javelinmen
    g_models[g_str_68c995df579163001588a354] = g_models[g_str_68c995dd5791630015889fb7]

    -- Bombards
    g_models[g_str_68c995df579163001588a356] =  g_models[g_str_68c995df579163001588a60a]

    -- Camp
    g_models[g_str_5fb1b9e6e1af060017709b42_camp] =  g_models[g_str_5fb1b9e7e1af060017709bfd_camp]

    -- Shire Billmen - HF
    g_models[g_str_6153519603385c0016b84057] = g_models[g_str_68c995e1579163001588aa09]

    -- Shire bowmen - Archers
    g_models[g_str_6153519603385c0016b84059] = {
      {
        model_data = 'troop_bowman_late_medieval'
      }
    }

    -- Northern border staves - Jav Cav
    g_models[g_str_6153519603385c0016b84052] = g_models[g_str_68c995e1579163001588a9ef]

    -- Northern border infantry
    g_models[g_str_6153519603385c0016b84054] = g_models[g_str_68c995df579163001588a606]

-- Tudor English
-- 1489 AD to 1515 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e6e1af060017709b49/explore
-- As of: 20220102


    -- Men-at-arms - Kn General
    g_models[g_str_68c995df579163001588a360_general] = {
      {
        n_models = 3,
        fixed_models = {
          [1] = 'troop_knight_english_wotr_b_bannerman',
          [2] = 'troop_knight_late_medieval_captain',
          [3] = 'troop_knight_late_medieval'
        }
      }
    }


    -- Men-at-arms\nDeployment dismounted from Knights General - EF General
    g_models[g_str_68c995df579163001588a360_general_dismounted] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_halberdier_late_medieval',
          [2] = 'troop_pikeman_english_wotr_b_bannerman',
          [3] = 'troop_pikeman_late_medieval_captain',
          [4] = 'troop_halberdier_late_medieval'
        }
      }
    }

    -- Men-at-arms\nDeployment dismounted from Knights General- Kn General
    g_models[g_str_68c995df579163001588a360_general_mounted] = g_models[g_str_68c995df579163001588a336_general]

    -- Men-at-arms - Kn
    g_models[g_str_68c995df579163001588a360] = g_models[g_str_68c995df579163001588a336]

    -- Men-at-arms\nDeployment dismounted from Knights - EF
    g_models[g_str_68c995df579163001588a360_dismounted] = g_models[g_str_68c995df579163001588a336_dismounted]

    -- Men-at-arms\nDeployment dismounted from Knights- Kn
    g_models[g_str_68c995df579163001588a360_mounted] = g_models[g_str_68c995df579163001588a336]

    -- Retinue billmen - EF
    g_models[g_str_68c995df579163001588a363] = g_models[g_str_68c995e5579163001588b73c]

    -- Retinue billmen\nDismounted mobile infantry - EF
    g_models[g_str_68c995df579163001588a363_dismounted_mobile_infantry] = g_models[g_str_68c995df579163001588a363]
    
    -- Retinue billmen\nMounted mobile infantry - EF
    g_models[g_str_68c995df579163001588a363_mounted_mobile_infantry] = g_models[g_str_68c995df579163001588a33b_mounted_mobile_infantry]

    -- Retinue bowmen  - Archers
    g_models[g_str_68c995df579163001588a367] = g_models[g_str_68c995df579163001588a33f]

    -- Retinue bowmen\nDismounted mobile infantry  - Archers
    g_models[g_str_68c995df579163001588a367_mounted_mobile_infantry] = g_models[g_str_68c995df579163001588a33f]

    -- Retinue bowmen\nMunted mobile infantry - Archers
    g_models[g_str_68c995df579163001588a367_dismounted_mobile_infantry] = g_models[g_str_68c995df579163001588a33f_mounted_mobile_infantry]

    -- Shire Billmen - HF
    g_models[g_str_68c995df579163001588a36a] = g_models[g_str_6153519603385c0016b84057]

    -- Northern border staves - Jav Cav
    g_models[g_str_68c995df579163001588a36c] = g_models[g_str_6153519603385c0016b84052]

    -- Bombards
    g_models[g_str_68c995df579163001588a36e] =  g_models[g_str_68c995df579163001588a356]

    -- Camp
    g_models[g_str_5fb1b9e6e1af060017709b49_camp] =  g_models[g_str_5fb1b9e6e1af060017709b42_camp]

-- French Ordonnance
-- 1445 AD to 1480 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e8e1af060017709c53/explore
-- As of: 20220103


    -- Ordonnance gendarmes - Kn General
    g_models[g_str_68c995e0579163001588a6d7_general] = {
      {
        n_models = 3,
        fixed_models = {
          [1] = 'troop_knight_french_ordonnances_a_bannerman',
          [2] = 'troop_knight_late_medieval_captain',
          [3] = 'troop_knight_late_medieval'
        }
      }
    }


    -- Ordonnance gendarmes\nDeployment dismounted from Knights General - EF General
    g_models[g_str_68c995e0579163001588a6d7_general_dismounted] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_halberdier_late_medieval',
          [2] = 'troop_pikeman_french_ordonnances_a_bannerman',
          [3] = 'troop_pikeman_late_medieval_captain',
          [4] = 'troop_halberdier_late_medieval'
        }
      }
    }

    -- Ordonnance gendarmes\nDeployment dismounting as Elite Foot- Kn General
    g_models[g_str_68c995e0579163001588a6d7_general_mounted] = g_models[g_str_68c995e0579163001588a6d7_general]

    -- Men-at-arms - Kn
    g_models[g_str_68c995e0579163001588a6d7] = g_models[g_str_68c995df579163001588a336]

    -- Men-at-arms\nDeployment dismounted from Knights - EF
    g_models[g_str_68c995e0579163001588a6d7_dismounted] = g_models[g_str_68c995df579163001588a336_dismounted]

    -- Men-at-arms\nDeployment dismounted from Knights- Kn
    g_models[g_str_68c995e0579163001588a6d7_mounted] = g_models[g_str_68c995df579163001588a336]

    -- Retinue bowmen  - Archers
    g_models[g_str_68c995e0579163001588a6da] = g_models[g_str_68c995df579163001588a33f]

    -- Retinue bowmen\nDismounted mobile infantry  - Archers
    g_models[g_str_68c995e0579163001588a6da_dismounted_mobile_infantry] = g_models[g_str_68c995df579163001588a33f]

    -- Retinue bowmen\nMunted mobile infantry - Archers
    g_models[g_str_68c995e0579163001588a6da_mounted_mobile_infantry] = g_models[g_str_68c995df579163001588a33f_mounted_mobile_infantry]
    
    -- Men-at-arms - Kn General
    g_models[g_str_68c995e0579163001588a6dd_general] = g_models[g_str_68c995e0579163001588a6d7_general]

    -- Men-at-arms - Kn
    g_models[g_str_68c995e0579163001588a6dd] = g_models[g_str_68c995df579163001588a336]
    
    -- Arriere-ban, garrison, or militia voulgiers
    g_models[g_str_68c995e0579163001588a6df] = g_models[g_str_68c995df579163001588a606]

    -- Arriere-ban, garrison, or militia voulgiers\nDismounted mobile infantry
    g_models[g_str_68c995e0579163001588a6df_dismounted_mobile_infantry] = g_models[g_str_68c995df579163001588a606]

    -- Arriere-ban, garrison, or militia voulgiers\nMounted mobile infantry
    g_models[g_str_68c995e0579163001588a6df_mounted_mobile_infantry] = g_models[g_str_68c995e0579163001588a6da_mounted_mobile_infantry]

    -- 'Francs bowmen with some arriere-ban, garrison, or militia bowmen or crossbowmen  - Bow Levy
    g_models[g_str_615351ab03385c0016b870f9] =  g_models[g_str_68c995df579163001588a597]

    -- 'Francs bowmen with some arriere-ban, garrison, or militia bowmen or crossbowmen\nDismounted mobile infantry  - Bow Levy
    g_models[g_str_615351ab03385c0016b870f9_dismounted_mobile_infantry] = g_models[g_str_615351ab03385c0016b870f9]

    -- 'Francs bowmen with some arriere-ban, garrison, or militia bowmen or crossbowmen\nMunted mobile infantry - Bow Levy
    g_models[g_str_615351ab03385c0016b870f9_mounted_mobile_infantry] = g_models[g_str_68c995df579163001588a33f_mounted_mobile_infantry]

    -- Mercenary crossbowmen  - Archers
    g_models[g_str_68c995e0579163001588a6e9] = g_models[g_str_68c995e5579163001588b736]

    -- Mercenary crossbowmen\nDismounted mobile infantry  - Archers
    g_models[g_str_68c995e0579163001588a6e9_dismounted_mobile_infantry] = g_models[g_str_68c995e0579163001588a6e9]

    -- Mercenary crossbowmen\nMunted mobile infantry - Archers
    g_models[g_str_68c995e0579163001588a6e9_mounted_mobile_infantry] = g_models[g_str_68c995df579163001588a33f_mounted_mobile_infantry]
    
    -- Gascon bidets or Bretons - LF
    g_models[g_str_68c995e0579163001588a6ec] = g_models[g_str_68c995df579163001588a342]

    -- Handgunners - Sk
    g_models[g_str_68c995e0579163001588a6ee] = g_models[g_str_68c995e1579163001588aa0b]

    -- Bombards and other big guns
    g_models[g_str_68c995e0579163001588a6f0] =  g_models[g_str_68c995df579163001588a356]

    -- Camp
    g_models[g_str_5fb1b9e8e1af060017709c53_camp] =  g_models[g_str_5fb1b9e6e1af060017709b42_camp]


-- Later French Ordonnance
-- 1481 AD to 1494 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e8e1af060017709c5b/explore
-- As of: 20220103


    -- Ordonnance gendarmes - Kn General
    g_models[g_str_68c995e0579163001588a6f9_general] = {
      {
        n_models = 3,
        fixed_models = {
          [1] = 'troop_knight_french_ordonnances_b_bannerman',
          [2] = 'troop_knight_late_medieval_captain',
          [3] = 'troop_knight_late_medieval'
        }
      }
    }


    -- Ordonnance gendarmes\nDeployment dismounted from Knights General - EF General
    g_models[g_str_68c995e0579163001588a6f9_general_dismounted] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_halberdier_late_medieval',
          [2] = 'troop_pikeman_french_ordonnances_a_bannerman',
          [3] = 'troop_pikeman_late_medieval_captain',
          [4] = 'troop_halberdier_late_medieval'
        }
      }
    }

    -- Ordonnance gendarmes\nDeployment dismounting as Elite Foot- Kn General
    g_models[g_str_68c995e0579163001588a6f9_general_mounted] = g_models[g_str_68c995df579163001588a336_general]

    -- Men-at-arms - Kn
    g_models[g_str_68c995e0579163001588a6f9] = g_models[g_str_68c995df579163001588a336]

    -- Men-at-arms\nDeployment dismounted from Knights - EF
    g_models[g_str_68c995e0579163001588a6f9_dismounted] = g_models[g_str_68c995e0579163001588a6d7_general]

    -- Men-at-arms\nDeployment dismounted from Knights- Kn
    g_models[g_str_68c995e0579163001588a6f9_mounted] = g_models[g_str_68c995df579163001588a336]

    -- Ordonnance bowmen now fighting while mounted: mostly equipped with longbows, but some crossbows - Elite Cav
    g_models[g_str_68c995e0579163001588a6fc] = g_models[g_str_68c995e1579163001588aa03]
    
    -- Ordonnance bowmen now fighting while mounted: mostly equipped with longbows, but some crossbows\nDeployment dismounted from Elite Cavalry - Archers
    g_models[g_str_68c995e0579163001588a6fc_dismounted] = g_models[g_str_68c995e0579163001588a6da]

    -- Ordonnance bowmen now fighting while mounted: mostly equipped with longbows, but some crossbows\nDeployment dismounted from Elite Cavalry - Elite Cav
    g_models[g_str_68c995e0579163001588a6fc_mounted] = g_models[g_str_68c995e0579163001588a6fc]

    -- Savoyard, Italian, or Arriere-ban men-at-arms - Kn General
    g_models[g_str_68c995e0579163001588a6ff_general] = g_models[g_str_68c995e0579163001588a6f9_general]

    -- Savoyard, Italian, or Arriere-ban men-at-arms - Kn
    g_models[g_str_68c995e0579163001588a6ff] = g_models[g_str_68c995e0579163001588a6f9]

    -- Arriere-ban, garrison, or militia voulgiers
    g_models[g_str_68c995e0579163001588a701] = g_models[g_str_68c995df579163001588a606]

    -- Arriere-ban, garrison, or militia voulgiers\nDismounted mobile infantry
    g_models[g_str_68c995e0579163001588a701_dismounted_mobile_infantry] = g_models[g_str_68c995df579163001588a606]

    -- Arriere-ban, garrison, or militia voulgiers\nMounted mobile infantry
    g_models[g_str_68c995e0579163001588a701_mounted_mobile_infantry] = g_models[g_str_68c995e0579163001588a6da_mounted_mobile_infantry]

    -- Retrained Francs bowmen  - Pikes
    g_models[g_str_68c995e0579163001588a704] =  g_models[g_str_68c995e0579163001588a7f9]

    -- Aventurier crossbowmen  - Archers
    g_models[g_str_68c995e0579163001588a706] = {
        {
          model_data = 'troop_crossbowman_late_medieval'
        }
    }

    -- Aventurier crossbowmen  - Sk
    g_models[g_str_68c995e0579163001588a707] = {
        {
          model_data = 'troop_crossbowman_late_medieval'
        }
    }

    g_models[g_str_68c995e0579163001588a709] = g_models[g_str_68c995df579163001588a597]

    -- Mercenary crossbowmen  - Archers
    g_models[g_str_68c995e0579163001588a70c] = g_models[g_str_68c995e0579163001588a6e9]

    -- Mercenary crossbowmen\nDismounted mobile infantry  - Archers
    g_models[g_str_68c995e0579163001588a70c_dismounted_mobile_infantry] = g_models[g_str_68c995e0579163001588a70c]

    -- Mercenary crossbowmen\nMunted mobile infantry - Archers
    g_models[g_str_68c995e0579163001588a70c_mounted_mobile_infantry] = g_models[g_str_68c995df579163001588a33f_mounted_mobile_infantry]

    -- Gascon bidets or Bretons - LF
    g_models[g_str_68c995e0579163001588a70f] = g_models[g_str_68c995e0579163001588a6ec]

    -- Handgunners - Sk
    g_models[g_str_68c995e0579163001588a711] = g_models[g_str_68c995e1579163001588aa0b]

    -- Bombards and other big guns
    g_models[g_str_68c995e0579163001588a713] =  g_models[g_str_68c995df579163001588a356]

    -- Camp
    g_models[g_str_5fb1b9e8e1af060017709c5b_camp] =  g_models[g_str_5fb1b9e6e1af060017709b42_camp]

-- Later Medieval German Citystates
-- 1440 AD to 1493 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e8e1af060017709cd3/explore
-- As of: 20220104


    -- Deep mounted formations using men at arms with barding in front and less well equipped men-at-arms in rear ranks - Cataphracts General
    g_models[g_str_68c995e0579163001588a8ff_general] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_knight_late_medieval',
          [2] = 'troop_knight_late_medieval_captain',
          [3] = 'troop_knight_late_german_c_bannerman',
          [4] = 'troop_knight_late_medieval'
        }
      }
    }

    -- Deep mounted formations using men at arms with barding in front and less well equipped men-at-arms in rear ranks - Cataphract
    g_models[g_str_68c995e0579163001588a8ff] = {
      {
        model_data = 'troop_knight_late_medieval'
      }
    }

    -- Armored crossbowmen on horses - Bad Horse
    g_models[g_str_68c995e0579163001588a901] = g_models[g_str_68c995e0579163001588a7f5]

    -- City guard halberdiers or axemen - EF General
    g_models[g_str_68c995e0579163001588a903_general] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_pikeman_late_medieval_captain',
          [2] = 'troop_pikeman_late_german_d_bannerman',
          [3] = 'troop_halberdier_late_medieval',
          [4] = 'troop_halberdier_late_medieval'
        }
      }
    }
    
    -- City guard halberdiers or axemen - EF
    g_models[g_str_68c995e0579163001588a903] = g_models[g_str_68c995e5579163001588b73c]

    -- City militia crossbowmen, some with pavises or armor - Bow Levy
    g_models[g_str_68c995e0579163001588a905] = {
      {
        model_data = 'troop_crossbowman_late_medieval'
      }
    }
  
    -- City militia crossbowmen, some with pavises or armor - Archers General
    g_models[g_str_68c995e0579163001588a906_general] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_crossbowman_late_medieval',
          [2] = 'troop_pikeman_late_german_d_bannerman',
          [3] = 'troop_pikeman_late_medieval_captain',
          [4] = 'troop_crossbowman_late_medieval'
        }
      }
    }

    -- City militia crossbowmen, some with pavises or armor - Archers
    g_models[g_str_68c995e0579163001588a906] = g_models[g_str_68c995e5579163001588b734]

    -- City militia spearmen or pikemen - HF General
    g_models[g_str_68c995e0579163001588a909_general] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_spearman_late_medieval',
          [2] = 'troop_pikeman_late_german_d_bannerman',
          [3] = 'troop_spearman_late_medieval',
          [4] = 'troop_pikeman_late_medieval_captain'
        }
      }
    }
    
    -- City militia spearmen or pikemen - HF
    g_models[g_str_68c995e0579163001588a909] = g_models[g_str_68c995e5579163001588b72f]

    -- City militia spearmen or pikemen - Pikes General
    g_models[g_str_68c995e0579163001588a90a_general] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_pikeman_late_medieval_straight',
          [2] = 'troop_pikeman_late_german_d_bannerman',
          [3] = 'troop_pikeman_late_medieval_straight',
          [4] = 'troop_pikeman_late_medieval_captain'
        }
      }
    }
    
    -- City militia spearmen or pikemen - Pikes
    g_models[g_str_68c995e0579163001588a90a] = g_models[g_str_68c995e0579163001588a7f9]

    -- City militia skirmishing bowmen - Skirmishers
    g_models[g_str_68c995e0579163001588a90d] = g_models[g_str_68c995df579163001588a34d]

    -- Poorly equipped heerban - Horde
    g_models[g_str_68c995e0579163001588a910] = {
      {
        loose = true,
        model_data = 'troop_horde_late_medieval'
      }
    }
    -- Heerban armed with crossbow or bow - Bow Levy
    g_models[g_str_68c995e0579163001588a912] = g_models[g_str_68c995df579163001588a597]

    -- Heerban handgunners - Skirmishers
    g_models[g_str_68c995e0579163001588a915] = g_models[g_str_68c995e5579163001588b739]

    -- Mercenary axemen, swordsmen, and halberdiers - HF General
    g_models[g_str_68c995e0579163001588a917_general] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_halberdier_burgundian_ordonnances',
          [2] = 'troop_pikeman_late_german_d_bannerman',
          [3] = 'troop_halberdier_burgundian_ordonnances',
          [4] = 'troop_pikeman_late_medieval_captain'
        }
      }
    }
    
    -- Mercenary axemen, swordsmen, and halberdiers - HF
    g_models[g_str_68c995e0579163001588a917] = {
      {
        random_models = {
          'troop_swordman_late_medieval',
          'troop_swordman_two_handed_burgundian_ordonnances',
          'troop_halberdier_burgundian_ordonnances'
        }
      }
    }

    -- Mercenary pikemen - Pikes General
    g_models[g_str_68c995e0579163001588a91a_general] = g_models[g_str_68c995e0579163001588a90a_general]
    
    -- Mercenary pikemen - Pikes
    g_models[g_str_68c995e0579163001588a91a] = g_models[g_str_68c995e0579163001588a7ee]

    -- Swiss pikemen - Pikes General
    g_models[g_str_68c995e0579163001588a91d_general] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_pikeman_late_medieval_captain',
          [2] = 'troop_pikeman_swiss_straight',
          [3] = 'troop_pikeman_late_german_d_bannerman',
          [4] = 'troop_pikeman_swiss_straight'
        }
      }
    }

    -- Swiss pikemen - Pikes
    g_models[g_str_68c995e0579163001588a91d] = g_models[g_str_68c995e1579163001588aa06]

    -- Mercenary bowmen or crossbowmen or handgunners - Archers General
    g_models[g_str_68c995e0579163001588a91f_general] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_handgunner_burgundian_ordonnances',
          [2] = 'troop_pikeman_late_german_d_bannerman',
          [3] = 'troop_pikeman_late_medieval_captain',
          [4] = 'troop_handgunner_burgundian_ordonnances'
        }
      }
    }

    -- Mercenary bowmen or crossbowmen or handgunners - Archers
    g_models[g_str_68c995e0579163001588a91f] = {
      {
        
        model_data = 'troop_crossbowman_burgundian_ordonnances'
      },
      {
        model_data = 'troop_longbowman_burgundian_ordonnances'
      },
      {
        model_data = 'troop_handgunner_burgundian_ordonnances'
      }
    }

    -- Mercenary bowmen or crossbowmen or handgunners - Sk
    g_models[g_str_68c995e0579163001588a920] = {
      {
        loose = true,        
        random_models = {
          'troop_crossbowman_burgundian_ordonnances',
          'troop_longbowman_burgundian_ordonnances',
          'troop_handgunner_burgundian_ordonnances'
        }
      }
    }

    -- Bombards - Artillery
    g_models[g_str_68c995e0579163001588a923] = g_models[g_str_68c995df579163001588a60a]

    -- Camp
    g_models[g_str_5fb1b9e8e1af060017709cd3_camp] = {
      {
        n_models = 1,
        model_data = 'troop_camp_late_german_c'
      }
    }

    -- Camp Fortified
    g_models[g_str_5fb1b9e8e1af060017709cd3_camp_fortified] = {
      {
        overlay_models = { -- each of the models are placed on top of the base
          {
            model_data="troop_fortified_camp_outline_40x40",
            position={x=-0,y=0,z=0}, -- optional defaults to (0,0,0)
            rotation=0, -- optional defaults to 0
            scale=1, -- optional defaults t0 1
          },
          {
            model_data = 'troop_camp_late_german_c',
            scale=0.7
          }
        }
      }
    }

    -- Deep mounted formations using men at arms with barding in front and less well equipped men-at-arms in rear ranks - Cataphract
    g_models[g_str_6153519703385c0016b842e2] = g_models[g_str_68c995e0579163001588a8ff] 

    -- Feudal retainers or heerban - Horde
    g_models[g_str_6153519703385c0016b842e4] = g_models[g_str_68c995e0579163001588a910]

    -- Mercenary axemen, swordsmen, and halberdiers - HF
    g_models[g_str_6153519703385c0016b842e6] = {
      {
        model_data = 'troop_halberdier_swiss'
      }
    }

    -- Mercenary bowmen or crossbowmen or handgunners - Archers
    g_models[g_str_6153519703385c0016b842e8] = g_models[g_str_68c995e0579163001588a6e9]

    -- Mercenary bowmen or crossbowmen or handgunners - Sk
    g_models[g_str_6153519703385c0016b842e9] = g_models[g_str_68c995e1579163001588aa03_dismounted]

    -- Mercenary pikemen - Pikes
    g_models[g_str_6153519703385c0016b842eb] = g_models[g_str_68c995e0579163001588a91a]

-- Early Renaissance German Citystates
-- 1494 AD to 1518 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e8e1af060017709cdd/explore
-- As of: 20220104


    -- Deep mounted formations using men at arms with barding in front and less well equipped men-at-arms in rear ranks - Cataphracts General
    g_models[g_str_68c995e0579163001588a932_general] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_knight_late_medieval',
          [2] = 'troop_knight_late_medieval_captain',
          [3] = 'troop_knight_late_german_d_bannerman',
          [4] = 'troop_knight_late_medieval'
        }
      }
    }

    -- Deep mounted formations using men at arms with barding in front and less well equipped men-at-arms in rear ranks - Cataphract
    g_models[g_str_68c995e0579163001588a932] = g_models[g_str_68c995e0579163001588a8ff]

    -- Armored crossbowmen on horses - Bad Horse
    g_models[g_str_68c995e0579163001588a934] = g_models[g_str_68c995e0579163001588a7f5]

    -- City guard halberdiers or axemen - EF General
    g_models[g_str_68c995e0579163001588a936_general] = g_models[g_str_68c995e0579163001588a903_general]
    
    -- City guard halberdiers or axemen - EF
    g_models[g_str_68c995e0579163001588a936] = g_models[g_str_68c995e0579163001588a903]

    -- City militia handgunners - Skirmishers
    g_models[g_str_68c995e0579163001588a938] = g_models[g_str_68c995e0579163001588a915]
  
    -- City militia spearmen or pikemen - HF General
    g_models[g_str_68c995e0579163001588a93b_general] = g_models[g_str_68c995e0579163001588a909_general]
    
    -- City militia spearmen or pikemen - HF
    g_models[g_str_68c995e0579163001588a93b] = g_models[g_str_68c995e0579163001588a909]

    -- City militia spearmen or pikemen - Pikes General
    g_models[g_str_68c995e0579163001588a93c_general] = g_models[g_str_68c995e0579163001588a90a_general]
    
    -- City militia spearmen or pikemen - Pikes
    g_models[g_str_68c995e0579163001588a93c] = g_models[g_str_68c995e0579163001588a7f9]

    -- Heerban armed with glaive, axe, or similar polearms - HF General
    g_models[g_str_68c995e0579163001588a93f_general] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_spearman_late_medieval',
          [2] = 'troop_pikeman_late_german_d_bannerman',
          [3] = 'troop_pikeman_late_medieval_captain',
          [4] = 'troop_spearman_late_medieval'
        }
      }
    }

    -- Heerban armed with glaive, axe, or similar polearms - HF
    g_models[g_str_68c995e0579163001588a93f] = g_models[g_str_68c995df579163001588a595]
    
    -- Heerban handgunners - Skirmishers
    g_models[g_str_68c995e0579163001588a941] = g_models[g_str_68c995e5579163001588b739]

    -- Landsknecht pikemen; possibly up to 1/3 Swiss pikemen - Pikes General
    g_models[g_str_68c995e0579163001588a943_general] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_pikeman_late_medieval_captain',
          [2] = 'troop_pikeman_swiss_straight',
          [3] = 'troop_pikeman_late_german_d_bannerman',
          [4] = 'troop_pikeman_late_medieval_straight'
        }
      }
    }

    -- Landsknecht pikemen; possibly up to 1/3 Swiss pikemen - Pikes
    g_models[g_str_68c995e0579163001588a943] = {
      {   
        random_models = {
          'troop_pikeman_swiss_straight',
          'troop_pikeman_late_medieval_straight',
          'troop_pikeman_late_medieval_straight',
          'troop_pikeman_burgundian_ordonnances_straight'
        }
      },
      {   
        random_models = {
          'troop_pikeman_swiss_inclined',
          'troop_pikeman_late_medieval_inclined',
          'troop_pikeman_late_medieval_inclined',
          'troop_pikeman_burgundian_ordonnances_inclined'
        }
      }
    }

    -- Mercenary handgunners - Skirmishers
    g_models[g_str_68c995e0579163001588a945] = g_models[g_str_68c995e1579163001588aa0b]

    -- Spanish jinetes - Jav Cav
    g_models[g_str_68c995e0579163001588a947] = g_models[g_str_68c995df579163001588a602]

    -- Bombards - Artillery
    g_models[g_str_68c995e0579163001588a949] = g_models[g_str_68c995df579163001588a60a]

    -- Camp
    g_models[g_str_5fb1b9e8e1af060017709cdd_camp] = {
      {
        n_models = 1,
        model_data = 'troop_camp_late_german_d'
      }
    }

    -- Camp Fortified
    g_models[g_str_5fb1b9e8e1af060017709cdd_camp_fortified] = {
      {
        overlay_models = { -- each of the models are placed on top of the base
          {
            model_data="troop_fortified_camp_outline_40x40",
            position={x=-0,y=0,z=0}, -- optional defaults to (0,0,0)
            rotation=0, -- optional defaults to 0
            scale=1, -- optional defaults t0 1
          },
          {
            model_data = 'troop_camp_late_german_d',
            scale=0.7
          }
        }
      }
    }

    -- City militia handgunners - Skirmishers
    g_models[g_str_6153519703385c0016b842cc] = g_models[g_str_68c995e0579163001588a938]

    -- City militia spearmen or pikemen - HF
    g_models[g_str_6153519703385c0016b842ce] = g_models[g_str_68c995e0579163001588a93b]

    -- City militia spearmen or pikemen - Pikes
    g_models[g_str_6153519703385c0016b842cf] = g_models[g_str_68c995e0579163001588a93c]

    -- Landsknecht pikemen; possibly up to 1/3 Swiss pikemen - Pikes
    g_models[g_str_6153519703385c0016b842d1] = g_models[g_str_68c995e0579163001588a91d]

    -- Mercenary handgunners - Skirmishers
    g_models[g_str_6153519703385c0016b842d3] = g_models[g_str_68c995e0579163001588a945]

    -- Deep mounted formations using men at arms with barding in front and less well equipped men-at-arms in rear ranks - Cataphract
    g_models[g_str_6153519703385c0016b842ef] = g_models[g_str_6153519703385c0016b842e2] 

    -- Feudal retainers or heerban - Horde
    g_models[g_str_6153519703385c0016b842f1] = g_models[g_str_6153519703385c0016b842e4]

    -- Mercenary axemen, swordsmen, and halberdiers - HF
    g_models[g_str_6153519703385c0016b842f3] = g_models[g_str_6153519703385c0016b842e6]

    -- Mercenary handgunners - Skirmishers
    g_models[g_str_6153519703385c0016b842f5] = g_models[g_str_68c995e1579163001588aa0b]

    -- Landsknecht pikemen; possibly up to 1/3 Swiss pikemen - Pikes
    g_models[g_str_6153519703385c0016b842f7] = g_models[g_str_68c995e0579163001588a943]