-- Early Egyptian
army['5fb1b9d9e1af060017709335'].data.has_models = true
army['5fb1b9d9e1af060017709335'].data.base = "tile_grass"
-- Hyksos
army['5fb1b9d9e1af060017709366'].data.has_models = true
army['5fb1b9d9e1af060017709366'].data.base = "tile_grass"
-- Sea Peoples
army['5fb1b9d9e1af0600177093b4'].data.has_models = true
army['5fb1b9d9e1af0600177093b4'].data.base = "tile_grass"
-- Early Philistine
army['5fb1b9dae1af0600177093d1'].data.has_models = true
army['5fb1b9dae1af0600177093d1'].data.base = "tile_grass"


-- Early Egyptian
-- 3000 BC to 1541 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9d9e1af060017709335/explore
-- As of: 202104014

    -- Bodyguards armed with axe and large shield - EF General
    g_models[g_str_68c995d3579163001588851d_general] = {
      {
        n_models = 4,
        fixed_models = {
            [1] = 'troop_egyptian_musician',
            [2] = 'troop_egyptian_general',
            [3] = 'troop_egyptian_bearer',
            [4] = 'troop_egyptian_drummer'
        }
      }
    }

    -- Bodyguards armed with axe and large shield - EF
    g_models[g_str_68c995d3579163001588851d] = {
      {
        model_data = 'troop_egyptian_general'
      }
    }

    -- 2-horse chariots - Ch General
    g_models[g_str_68c995d35791630015888520_general] = {
      {
        n_models = 1,
        fixed_models = {
            [1] = 'troop_egyptian_lch_gen'
        }
      }
    }

    -- 2-horse chariots - Ch
    g_models[g_str_68c995d35791630015888520] = {
      {
        n_models = 1,
        fixed_models = {
            [1] = 'troop_egyptian_lch'
        }
      }
    }

    -- Bodyguards armed with axe and large shield - EF General
    g_models[g_str_68c995d35791630015888521_general] = g_models[g_str_68c995d3579163001588851d_general]

    -- Bodyguards armed with axe and large shield - EF
    g_models[g_str_68c995d35791630015888521] = g_models[g_str_68c995d3579163001588851d]

    -- Bowmen - Bow Levy
    g_models[g_str_68c995d35791630015888523] = {
      {
        model_data = 'troop_egyptian_bow'
      }
    }

    --Menfat - Raiders
    g_models[g_str_68c995d35791630015888526] = {
      {
        model_data = 'troop_egyptian_bd2'
      }
    }

    --Menfat - Heavy Foot
    g_models[g_str_68c995d35791630015888527] = {
      {
        model_data = 'troop_egyptian_bd1'
      }
    }

    --Conscripts - Horde
    g_models[g_str_68c995d35791630015888529] = {
      {
        model_data = 'troop_egyptian_horde_melee',
        loose = true
      }
    }

    --Javelinmen paired with quiver-carriers - Sk
    g_models[g_str_68c995d3579163001588852b] = {
      {
        n_models = 2,
        fixed_models = {
            [1] = 'troop_egyptian_skirmishers_javelin',
            [2] = 'troop_egyptian_skirmishers_javelin_carrier'
        },
        loose = true
      }
    }

    --Medjay and other Nubian bowmen - Archers
    g_models[g_str_68c995d3579163001588852d] = {
      {
        model_data = 'troop_libyan_bow_alt'
      }
    }

    --Medjay and other Nubian bowmen - Sk
    g_models[g_str_68c995d3579163001588852e] = {
      {
        model_data = 'troop_libyan_bow_alt',
        loose = true
      }
    }

    --Libyan javelinmen - Rabble
    g_models[g_str_68c995d35791630015888530] = {
      {
        model_data = 'troop_libyan_wb',
        loose = true
      }
    }

    --Bedouin slingers - Sk
    g_models[g_str_68c995d35791630015888532] = {
      {
        model_data = 'troop_egyptian_skirmishers_slinger',
        loose = true
      }
    }

    --Early Egyptian Camp
    g_models[g_str_5fb1b9d9e1af060017709335_camp] = {
      {
        n_models = 1,
        model_data = 'troop_egyptian_sphinx'
      }
    }
    --Early Egyptian Camp Pack Trains
    g_models[g_str_5fb1b9d9e1af060017709335_camp_pack_train] = g_models[g_str_5fb1b9d9e1af060017709335_camp_pack_train]


-- Hyksos
-- 1645 BC to 1537 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9d9e1af060017709366/explore
-- As of: 202104015

    -- 2-horse chariots - Ch General
    g_models[g_str_68c995d357916300158885ae_general] = {
      {
        n_models = 1,
        fixed_models = {
            [1] = 'troop_hyksos_lch_gen'
        }
      }
    }

    -- 2-horse chariots - Ch
    g_models[g_str_68c995d357916300158885ae] = {
      {
        n_models = 1,
        fixed_models = {
            [1] = 'troop_hyksos_lch'
        }
      }
    }

    --Retainers armed with axe or sickle sword and javelins - Raiders
    g_models[g_str_68c995d357916300158885b0] = g_models[g_str_68c995d35791630015888526]

    -- Retainers armed with bow - Archers
    g_models[g_str_68c995d357916300158885b2] = {
      {
        model_data = 'troop_egyptian_bow'
      }
    }

    --Light troops armed with javelin and shield - LF
    g_models[g_str_68c995d357916300158885b4] = {
      {
        model_data = 'troop_hyksos_bd1'
      }
    }

    --Light troops armed with javelin - Rabble
    g_models[g_str_68c995d357916300158885b6] = {
      {
        n_models = 3,
        fixed_models = {
            [1] = 'troop_egyptian_skirmishers_javelin',
            [2] = 'troop_egyptian_skirmishers_javelin_carrier',
            [3] = 'troop_egyptian_skirmishers_javelin',
        },
        loose = true
      }
    }


    --Light troops armed with bow or sling - Sk
    g_models[g_str_68c995d357916300158885b8] = g_models[g_str_68c995d35791630015888532]

    --Aamu nomads - Rabble
    g_models[g_str_68c995d357916300158885ba] = {
      {
        model_data = 'troop_egyptian_horde_melee',
        loose = true
      }
    }

    --Egyptian levies - Horde
    g_models[g_str_68c995d357916300158885bc] = g_models[g_str_68c995d35791630015888529]

    --Hyksos Camp
    g_models[g_str_5fb1b9d9e1af060017709366_camp] = g_models[g_str_5fb1b9d9e1af060017709335_camp]

    --Hyksos Camp Pack Trains
    g_models[g_str_5fb1b9d9e1af060017709366_camp_pack_train] = g_models[g_str_5fb1b9dde1af06001770961d_camp_pack_train]


-- Sea Peoples
-- 3000 BC to 2160 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9d9e1af0600177093b4/explore
-- As of: 202104015

    -- 2-wheeled battle platforms with teams of a driver and 2 javelinmen - Battle Taxi General
    g_models[g_str_68c995d357916300158886c1_general] = {
      {
        n_models = 1,
        fixed_models = {
            [1] = 'troop_seapeople_hch_general'
        }
      }
    }

    -- 2-wheeled battle platforms with teams of a driver and 2 javelinmen - Battle Taxi
    g_models[g_str_68c995d357916300158886c1] = {
      {
        n_models = 1,
        fixed_models = {
            [1] = 'troop_seapeople_lch_general'
        }
      }
    }

    -- Chieftains and their armored retinues - EF General
    g_models[g_str_68c995d357916300158886c3_general] = {
      {
        n_models = 4,
        model_data = 'troop_seapeople_bd_general'
      }
    }

    -- Chieftains and their armored retinues - EF
    g_models[g_str_68c995d357916300158886c3] = {
      {
        model_data = 'troop_seapeople_bd'
      }
    }

    -- Common tribesmen of most Sea Peoples nations - Raiders General
    g_models[g_str_68c995d357916300158886c5_general] = {
      {
        n_models = 4,
        model_data = 'troop_seapeople_bd_general'
      }
    }

    -- Common tribesmen of most Sea Peoples nations - Raiders
    g_models[g_str_68c995d357916300158886c5] = {
      {
        model_data = 'troop_egyptian_bd3'
      }
    }

    --Light troops armed with javelin - Rabble
    g_models[g_str_68c995d357916300158886c7] = {
      {
        model_data = 'troop_seapeople_ax',
        loose = true
      }
    }

    --Light troops armed with bow or sling - Sk
    g_models[g_str_68c995d357916300158886c9] = {
      {
        model_data = 'troop_seapeople_ps',
        loose = true
      }
    }

    --Egyptian levies - Horde
    g_models[g_str_68c995d357916300158886cb] = {
      {
        model_data = 'troop_seapeople_ax',
        loose = true
      }
    }
    --Sea Peoples Camp
    g_models[g_str_5fb1b9d9e1af0600177093b4_camp] = g_models[g_str_5fb1b9dce1af06001770959d_camp]

    --Sea Peoples Camp Fort
    g_models[g_str_5fb1b9d9e1af0600177093b4_camp_fortified] = g_models[g_str_5fb1b9dbe1af060017709528_camp_fortified]

-- Early Philistine
-- 1166 BC to 1100 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9dae1af0600177093d1/explore
-- As of: 202104015

    -- 2-wheeled battle platforms with teams of a driver and 2 javelinmen - Battle Taxi General
    g_models[g_str_68c995d35791630015888720_general] = g_models[g_str_68c995d357916300158886c1_general]

    -- 2-wheeled battle platforms with teams of a driver and 2 javelinmen - Battle Taxi
    g_models[g_str_68c995d35791630015888720] = {
      {
        n_models = 1,
        fixed_models = {
            [1] = 'troop_seapeople_lch'
        }
      }
    }

    -- Elite swordsmen - EF General
    g_models[g_str_68c995d35791630015888722_general] = g_models[g_str_68c995d357916300158886c3_general]

    -- Elite swordsmen - EF
    g_models[g_str_68c995d35791630015888722] = g_models[g_str_68c995d357916300158886c3]

    -- Swordsmen - Raiders
    g_models[g_str_68c995d35791630015888724] = g_models[g_str_68c995d357916300158886c5]

    --Light infantry armed with javelins, some with shields - Rabble
    g_models[g_str_68c995d35791630015888726] = g_models[g_str_68c995d357916300158886c7]

    --Javelinmen largely without shields - Rabble
    g_models[g_str_68c995d35791630015888728] = g_models[g_str_68c995d357916300158886c7]

    --Slingers - Sk
    g_models[g_str_68c995d3579163001588872a] = {
      {
        model_data = 'troop_seapeople_ps',
        loose = true
      }
    }

    --Bowmen - Bow Levy
    g_models[g_str_68c995d3579163001588872c] = {
      {
        model_data = 'troop_seapeople_ps',
        loose = true
      }
    }

    --Skirmishers - Kharu bowmen
    g_models[g_str_68c995d3579163001588872f] = {
      {
        model_data = 'troop_seapeople_ps',
        loose = true
      }
    }

    --Archers - Kharu bowmen
    g_models[g_str_68c995d35791630015888730] = {
      {
        model_data = 'troop_seapeople_ps'
      }
    }

    --Early Philistene Camp
    g_models[g_str_5fb1b9dae1af0600177093d1_camp] = g_models[g_str_5fb1b9d9e1af060017709335_camp]

    --Early Philistene Camp Fort
    g_models[g_str_5fb1b9dae1af0600177093d1_camp_pack_train] = g_models[g_str_5fb1b9dde1af06001770961d_camp_pack_train]
