-- Early German
army['5fb1b9e1e1af060017709849'].data.has_models = true
army['5fb1b9e1e1af060017709849'].data.base = "tile_grass"
-- Early German Marcomanni
army['5fb1b9e1e1af060017709857'].data.has_models = true
army['5fb1b9e1e1af060017709857'].data.base = "tile_grass"

-- Early German
-- 115 BC to 250 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e1e1af060017709849/explore
-- As of: 20210407

    --Horsemen - JavCav General
    g_models[g_str_68c995da57916300158898ba_general] = g_models[g_str_68c995d75791630015888e56_general]
    g_models[g_str_68c995da57916300158898ba_general_mounted] = g_models[g_str_68c995d75791630015888e56_general]

    --Horsemen - Warriors General Dismounting
    g_models[g_str_68c995da57916300158898ba_general_dismounted] = g_models[g_str_68c995d75791630015888e4e_general_dismounted]

    --Horsemen - JavCav
    g_models[g_str_68c995da57916300158898ba] = g_models[g_str_68c995d75791630015888e56]
    g_models[g_str_68c995da57916300158898ba_mounted] = g_models[g_str_68c995d75791630015888e56]

    --Horsemen - Warriors  Dismounting
    g_models[g_str_68c995da57916300158898ba_dismounted] = {
      {
        model_data = 'troop_gallic_warriors'
      }
    }
    -- Fierce fighters - Warriors General
    g_models[g_str_68c995da57916300158898bd_general] = g_models[g_str_68c995d75791630015888e4e_dismounted]

    -- Fierce fighters - Warriors
    g_models[g_str_68c995da57916300158898bd] = g_models[g_str_68c995da57916300158898ba_dismounted]

    -- Fighters armed with sword, shield, and wooden club - Raiders
    g_models[g_str_68c995da57916300158898bf] = {
      {
        model_data = 'troop_gallatian_bd'
      }
    }

    -- Foot skirmishers armed with many fire-hardened untipped throwing spears - Rabble
    g_models[g_str_68c995da57916300158898c1] = {
    {
      model_data = 'troop_gallic_ps_javelin',
      loose = true
    }
  }

    -- Skirmishing bowmen
    g_models[g_str_68c995da57916300158898c3] = {
    {
      model_data = 'troop_gallic_ps_archer',
      loose = true
    }
  }

    -- Early German Camp
    g_models[g_str_5fb1b9e1e1af060017709849_camp] = g_models[g_str_5fb1b9dce1af06001770959d_camp]

    -- Early German Camp Fortified
    g_models[g_str_5fb1b9e1e1af060017709849_camp_fortified] = g_models[g_str_5fb1b9dce1af06001770959d_camp_fortified]

    -- Early German Camp Pack Trains
    g_models[g_str_5fb1b9e1e1af060017709849_camp_pack_train] = g_models[g_str_5fb1b9e1e1af060017709849_camp_pack_train]

-- Early German Marcomanni
-- 9 BC to 19 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e1e1af060017709857/explore
-- As of: 20210407

    --Horsemen - JavCav General
    g_models[g_str_68c995da57916300158898e7_general] = g_models[g_str_68c995d75791630015888e56_general]
    g_models[g_str_68c995da57916300158898e7_general_mounted] = g_models[g_str_68c995d75791630015888e56_general]

    --Horsemen - Warriors General Dismounting
    g_models[g_str_68c995da57916300158898e7_general_dismounted] = g_models[g_str_68c995d75791630015888e4e_general_dismounted]

    --Horsemen - JavCav
    g_models[g_str_68c995da57916300158898e7] = g_models[g_str_68c995d75791630015888e56_general]
    g_models[g_str_68c995da57916300158898e7_mounted] = g_models[g_str_68c995d75791630015888e56_general]

    --Horsemen - Warriors  Dismounting
    g_models[g_str_68c995da57916300158898e7_dismounted] = g_models[g_str_68c995da57916300158898ba_dismounted]

    -- Fierce fighters - Warriors
    g_models[g_str_68c995da57916300158898ea] = g_models[g_str_68c995da57916300158898bd]

    -- Drilled foot tribesmen - HF
    g_models[g_str_68c995da57916300158898ec] = g_models[g_str_68c995d75791630015888e4e_dismounted]

    -- Foot skirmishers armed with many fire-hardened untipped throwing spears - Rabble
    g_models[g_str_68c995da57916300158898ee] = g_models[g_str_68c995da57916300158898c1]

    -- Skirmishing bowmen
    g_models[g_str_68c995da57916300158898f0] = g_models[g_str_68c995da57916300158898c3]

    -- Early German Camp
    g_models[g_str_5fb1b9e1e1af060017709857_camp] = g_models[g_str_5fb1b9dce1af06001770959d_camp]

    -- Early German Camp Fortified
    g_models[g_str_5fb1b9e1e1af060017709857_camp_fortified] = g_models[g_str_5fb1b9dce1af06001770959d_camp_fortified]

    -- Early German Camp Pack Trains
    g_models[g_str_5fb1b9e1e1af060017709857_camp_pack_train] = g_models[g_str_5fb1b9e1e1af060017709849_camp_pack_train]
