-- Viking
army['5fb1b9e5e1af060017709aae'].data.has_models = true
army['5fb1b9e5e1af060017709aae'].data.base="tile_grass"
-- Viking Raiders
army['5fb1b9e5e1af060017709aa8'].data.has_models = true
army['5fb1b9e5e1af060017709aa8'].data.base="tile_grass"
-- Dublin or Manx Vikings
army['5fb1b9e5e1af060017709ab6'].data.has_models = true
army['5fb1b9e5e1af060017709ab6'].data.base="tile_grass"
-- Viking West Frisia
army['5fb1b9e4e1af060017709a75'].data.has_models = true
army['5fb1b9e4e1af060017709a75'].data.base="tile_grass"
-- Pre-Viking Scandinavian
army['5fb1b9e5e1af060017709a95'].data.has_models = true
army['5fb1b9e5e1af060017709a95'].data.base="tile_grass"
-- Middle Anglo-Saxon
army['5fb1b9e5e1af060017709acf'].data.has_models = true
army['5fb1b9e5e1af060017709acf'].data.base="tile_grass"
-- Breton
army['5fb1b9e4e1af060017709a4c'].data.has_models = true
army['5fb1b9e4e1af060017709a4c'].data.base="tile_grass"
-- Anglo-Danish
army['5fb1b9e5e1af060017709ad5'].data.has_models = true
army['5fb1b9e5e1af060017709ad5'].data.base="tile_grass"

-- Viking
-- 850 AD to 1280 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e5e1af060017709aae/explore
-- As of: 20210416

    -- Huscarles - EF General
    g_models[g_str_68c995de579163001588a0db_general] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_viking_huscarls',
          [2] = 'troop_viking_general_2',
          [3] = 'troop_viking_general_1',
          [4] = 'troop_viking_huscarls'
        }
      }
    }

    -- Huscarles - EF
    g_models[g_str_68c995de579163001588a0db] = {
      {
        model_data = 'troop_viking_huscarls'
      }
    }

    -- Hird - Heavy Foot
    g_models[g_str_68c995de579163001588a0de] = {
      {
        model_data = 'troop_viking_hird_spear'
      }
    }

    -- Hird\nDismounted mobile infantry - Heavy Foot
    g_models[g_str_68c995de579163001588a0de_dismounted_mobile_infantry] = g_models[g_str_68c995de579163001588a0de]

    -- Hird\nmounted mobile infantry - Heavy Foot
    g_models[g_str_68c995de579163001588a0de_mounted_mobile_infantry] = {
      {
        model_data = 'troop_viking_rider_generic'
      }
    }

    -- Freelance marauders - Raiders
    g_models[g_str_68c995de579163001588a0e1] = {
      {
        model_data = 'troop_viking_warrior'
      }
    }

    -- Freelance marauders\nDismounted mobile infantry - Raiders
    g_models[g_str_68c995de579163001588a0e1_dismounted_mobile_infantry] = g_models[g_str_68c995de579163001588a0e1]

    -- Freelance marauders\nmounted mobile infantry - Raiders
    g_models[g_str_68c995de579163001588a0e1_mounted_mobile_infantry] = {
      {
        model_data = 'troop_viking_rider_generic'
      }
    }

    --Hird bowmen - Archers
    g_models[g_str_68c995de579163001588a0e4] = {
      {
        model_data = 'troop_viking_archers'
      }
    }

    --Hird bowmen - Sk
    g_models[g_str_68c995de579163001588a0e5] = {
      {
        model_data = 'troop_viking_archers',
        loose = true
      }
    }

    --Besirkir - Warband
    g_models[g_str_68c995de579163001588a0e8] = {
      {
        model_data = 'troop_viking_berserker'
      }
    }

    --Viking Camp
    g_models[g_str_5fb1b9e5e1af060017709aae_camp] = g_models[g_str_5fb1b9dce1af06001770959d_camp]
    --Viking Trains
    g_models[g_str_5fb1b9e5e1af060017709aae_camp_pack_train] = g_models[g_str_5fb1b9e1e1af060017709849_camp_pack_train]

-- Viking Raiders
-- 790 AD to 849 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e5e1af060017709aa8/explore
-- As of: 20210416

    -- Huscarles - EF General
    g_models[g_str_68c995de579163001588a0d2_general] = g_models[g_str_68c995de579163001588a0db_general]

    -- Huscarles - EF
    g_models[g_str_68c995de579163001588a0d2] = g_models[g_str_68c995de579163001588a0db]

    -- Undisciplined marauders - Raiders
    g_models[g_str_68c995de579163001588a0d4] = g_models[g_str_68c995de579163001588a0e1]

    -- Skirmishing bowmen - Sk
    g_models[g_str_68c995de579163001588a0d6] = g_models[g_str_68c995de579163001588a0e5]

    --Viking Raiders Camp
    g_models[g_str_5fb1b9e5e1af060017709aa8_camp] = g_models[g_str_5fb1b9e5e1af060017709aae_camp]

    --Viking Raiders Trains
    g_models[g_str_5fb1b9e5e1af060017709aa8_camp_pack_train] = g_models[g_str_5fb1b9e5e1af060017709aae_camp_pack_train]


-- Dublin or Manx Vikings
-- 842 AD to 1229 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e5e1af060017709ab6/explore
-- As of: 20210416

    -- Huscarles - EF General
    g_models[g_str_68c995de579163001588a0f6_general] = g_models[g_str_68c995de579163001588a0db_general]

    -- Huscarles - EF
    g_models[g_str_68c995de579163001588a0f6] = g_models[g_str_68c995de579163001588a0db]

    -- Hird - Heavy Foot
    g_models[g_str_68c995de579163001588a0f9] = g_models[g_str_68c995de579163001588a0de]

    -- Hird\nDismounted mobile infantry - Heavy Foot
    g_models[g_str_68c995de579163001588a0f9_dismounted_mobile_infantry] = g_models[g_str_68c995de579163001588a0de_dismounted_mobile_infantry]

    -- Hird\nmounted mobile infantry - Heavy Foot
    g_models[g_str_68c995de579163001588a0f9_mounted_mobile_infantry] = g_models[g_str_68c995de579163001588a0de_mounted_mobile_infantry]

    -- Freelance marauders - Raiders
    g_models[g_str_68c995de579163001588a0fc] = g_models[g_str_68c995de579163001588a0e1]

    -- Freelance marauders\nDismounted mobile infantry - Raiders
    g_models[g_str_68c995de579163001588a0fc_dismounted_mobile_infantry] = g_models[g_str_68c995de579163001588a0e1_dismounted_mobile_infantry]

    -- Freelance marauders\nmounted mobile infantry - Raiders
    g_models[g_str_68c995de579163001588a0fc_mounted_mobile_infantry] = g_models[g_str_68c995de579163001588a0e1_mounted_mobile_infantry]

    -- Hird bowmen - Archers
    g_models[g_str_68c995de579163001588a0ff] = g_models[g_str_68c995de579163001588a0e4]

    -- Hird bowmen - Sk
    g_models[g_str_68c995de579163001588a100] = g_models[g_str_68c995de579163001588a0e5]

    -- Irish mercenaries - Light Foot
    g_models[g_str_68c995de579163001588a103] = {
      {
        model_data = 'troop_viking_hird_javelin'
      }
    }

    -- Irish mercenaries\nDismounted mobile infantry - Light Foot
    g_models[g_str_68c995de579163001588a103_dismounted_mobile_infantry] = g_models[g_str_68c995de579163001588a0fc]

    -- Irish mercenaries\nmounted mobile infantry - Light Foot
    g_models[g_str_68c995de579163001588a103_mounted_mobile_infantry] = {
      {
        model_data = 'troop_viking_rider_generic'
      }
    }

    -- Besirkir - Warband
    g_models[g_str_68c995de579163001588a106] = g_models[g_str_68c995de579163001588a0e8]

    --Dublin or Manx Vikings Camp
    g_models[g_str_5fb1b9e5e1af060017709ab6_camp] = g_models[g_str_5fb1b9e5e1af060017709aae_camp]

    --Dublin or Manx Vikings Trains
    g_models[g_str_5fb1b9e5e1af060017709ab6_camp_pack_train] = g_models[g_str_5fb1b9e5e1af060017709aae_camp_pack_train]



-- Viking West Frisia
-- 840 to 885 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e4e1af060017709a75/explore
-- As of: 20210417

    -- Viking nobles and retainers - EF General
    g_models[g_str_68c995dd579163001588a043_general] = g_models[g_str_68c995de579163001588a0db_general]

    -- Viking nobles and retainers - EF
    g_models[g_str_68c995dd579163001588a043] = g_models[g_str_68c995de579163001588a0db]

    -- Irish mercenaries - Light Spear
    g_models[g_str_68c995dd579163001588a045] = {
      {
        model_data = 'troop_viking_hird_spear'
      }
    }

    -- Dardiers - Rabble
    g_models[g_str_68c995dd579163001588a047] = {
      {
        model_data = 'troop_viking_hird_javelin'
      }
    }

    -- Dardiers - Light Foot
    g_models[g_str_68c995dd579163001588a048] = g_models[g_str_68c995de579163001588a103]

    -- Javelinmen - Rabble
    g_models[g_str_68c995dd579163001588a04a] = g_models[g_str_68c995dd579163001588a047]

    -- Massed levy bowmen - Bow Levy
    g_models[g_str_68c995dd579163001588a04c] = {
      {
        model_data = 'troop_viking_archers'
      }
    }

    --Viking West Frisia Camp
    g_models[g_str_5fb1b9e4e1af060017709a75_camp] = g_models[g_str_5fb1b9e5e1af060017709aae_camp]

    --Viking West Frisia Fort
    g_models[g_str_5fb1b9e4e1af060017709a75_camp_fortified] = {
      {
        overlay_models = { -- each of the models are placed on top of the base
          {
            model_data="troop_fortified_camp_outline_40x40",
            position={x=-0,y=0,z=0}, -- optional defaults to (0,0,0)
            rotation=0, -- optional defaults to 0
            scale=1, -- optional defaults t0 1
          },
          {
            model_data = 'troop_campfire',
            scale=0.7
          }
        }
      }
    }



-- Pre-Viking Scandinavian
-- 450 AD to 789 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e5e1af060017709a95/explore
-- As of: 20210417

    -- Viking nobles and retainers - EF General
    g_models[g_str_68c995de579163001588a098_general] = g_models[g_str_68c995de579163001588a0db_general]

    -- Viking nobles and retainers - EF
    g_models[g_str_68c995de579163001588a098] = g_models[g_str_68c995de579163001588a0db]

    -- Hird - Heavy Foot
    g_models[g_str_68c995de579163001588a09a] = g_models[g_str_68c995de579163001588a0de]

    -- Bowmen - Sk
    g_models[g_str_68c995de579163001588a09c] = g_models[g_str_68c995de579163001588a0e5]

    -- Massed levy bowmen - Bow Levy
    g_models[g_str_68c995de579163001588a09d] = g_models[g_str_68c995dd579163001588a04c]

    -- Thralls, levy, and dregs - Horde
    g_models[g_str_68c995de579163001588a0a0] = {
      {
        loose = true,
        random_models = {
          'troop_viking_hird_javelin',
          'troop_viking_hird_spear',
          'troop_saxon_horde'
        }
      }
    }

    --Pre-Viking Scandinavian Camp
    g_models[g_str_5fb1b9e5e1af060017709a95_camp] = g_models[g_str_5fb1b9e5e1af060017709aae_camp]

-- Middle Anglo-Saxon
-- 617 AD to 1016 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e5e1af060017709acf/explore
-- As of: 20230112

    -- Hird - Warriors General
    g_models[g_str_68c995de579163001588a15f_general] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_viking_warrior',
          [2] = 'troop_viking_general_1',
          [3] = 'troop_viking_warrior',
          [4] = 'troop_viking_general_2'
        }
      }
    }

    -- Hird - Warriors 
    g_models[g_str_68c995de579163001588a15f] = {
      {
        model_data = 'troop_viking_warrior'
      }
    }

    -- Hird - Warriors  General
    g_models[g_str_68c995de579163001588a15f_general] = g_models[g_str_68c995de579163001588a15f_general]

    -- Hird - Warriors
    g_models[g_str_68c995de579163001588a15f] = g_models[g_str_68c995de579163001588a15f]

    -- Hird - HF  General
    g_models[g_str_68c995de579163001588a163_general] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_viking_general_1',
          [2] = 'troop_viking_hird_spear',
          [3] = 'troop_viking_general_2',
          [4] = 'troop_viking_hird_spear'
        }
      }
    }
  
    -- Hird - HF
    g_models[g_str_68c995de579163001588a163] = g_models[g_str_68c995de579163001588a0de]
    
    -- Saxon thegns - HF General
    g_models[g_str_68c995de579163001588a166_general] = g_models[g_str_68c995de579163001588a163_general]

    -- Saxon thegns - HF
    g_models[g_str_68c995de579163001588a166] = g_models[g_str_68c995de579163001588a163]

    -- Saxon thegns - EF General
    g_models[g_str_68c995de579163001588a167_general] = g_models[g_str_68c995de579163001588a0db_general]

    -- Saxon thegns - EF
    g_models[g_str_68c995de579163001588a167] =g_models[g_str_68c995de579163001588a0db]

    -- Select fyrd - HF General
    g_models[g_str_68c995de579163001588a169_general] = g_models[g_str_68c995de579163001588a163_general]

    -- Select fyrd - HF
    g_models[g_str_68c995de579163001588a169] = g_models[g_str_68c995de579163001588a163]

    -- Skirmishing bowmen - Sk
    g_models[g_str_68c995de579163001588a16b] = g_models[g_str_68c995de579163001588a0e5]

    --Scouts and javelinmen - Rabble
    g_models[g_str_68c995de579163001588a16d] = g_models[g_str_68c995dd579163001588a04a]

    --Great fyrd - Horde
    g_models[g_str_68c995de579163001588a16f] = g_models[g_str_68c995de579163001588a0a0]

    --Middle Anglo-Saxon Camp
    g_models[g_str_5fb1b9e5e1af060017709acf_camp] = g_models[g_str_5fb1b9dce1af06001770959d_camp]

-- Breton
-- 580 AD to 1072 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e4e1af060017709a4c/explore
-- As of: 20230112

    -- Horsemen - Jav Cav General
    g_models[g_str_68c995dd5791630015889f8a_general] = {
      {
        n_models = 2,
        fixed_models = {
          [1] = 'troop_viking_rider_generic_cape',
          [2] = 'troop_viking_general_1'
        }
      }
    }

    -- Horsemen - Jav Cav
    g_models[g_str_68c995dd5791630015889f8a] = {
      {
        model_data = 'troop_viking_rider_generic'
      }
    }

    -- Javelinmen - Light Foot
    g_models[g_str_68c995dd5791630015889f8c] = g_models[g_str_68c995de579163001588a103]

    -- Peasants - Horde
    g_models[g_str_68c995dd5791630015889f8e] = g_models[g_str_68c995de579163001588a0a0]

    -- Unarmoured Horsemen - Jav Cav General
    g_models[g_str_68c995dd5791630015889f91_general] = g_models[g_str_68c995dd5791630015889f8a_general]

    -- Unarmoured Horsemen - Jav Cav
    g_models[g_str_68c995dd5791630015889f91] = g_models[g_str_68c995dd5791630015889f8a]

    -- Disguised Saxons - Warriors 
    g_models[g_str_68c995dd5791630015889f94] = g_models[g_str_68c995de579163001588a15f]

    --Breaton Camp
    g_models[g_str_5fb1b9e4e1af060017709a4c_camp] = g_models[g_str_5fb1b9dce1af06001770959d_camp]
    
    --Breton Camp - Fortified
    g_models[g_str_5fb1b9e4e1af060017709a4c_camp_fortified] = {
      {
        overlay_models = { -- each of the models are placed on top of the base
          {
            model_data="troop_fortified_camp_outline_40x40",
            position={x=0,y=0,z=0}, -- optional defaults to (0,0,0)
            rotation=0, -- optional defaults to 0
            scale=1, -- optional defaults t0 1
          },
          {
            model_data = 'troop_campfire',
            scale=0.75,
          }
        }
      }
    }

-- Anglo-Danish
-- 1016 AD to 1075 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e5e1af060017709ad5/explore
-- As of: 20230112


    -- Huscarles or huscarles on horses - EF General
    g_models[g_str_68c995de579163001588a17f_general] = g_models[g_str_68c995de579163001588a0db_general]

    -- Huscarles or huscarles on horses - EF
    g_models[g_str_68c995de579163001588a17f] = g_models[g_str_68c995de579163001588a0db]

    -- Huscarles or huscarles on horses - Bad Horse General
    g_models[g_str_68c995de579163001588a180_general] = {
      {
        n_models = 3,
        fixed_models = {
          [1] = 'troop_viking_rider_generic_unarmoured',
          [2] = 'troop_viking_general_1',
          [3] = 'troop_viking_rider_generic_unarmoured'
        }
      }
    }

    -- Huscarles or huscarles on horses - Bad Horse
    g_models[g_str_68c995de579163001588a180] = {
      {
        model_data = 'troop_viking_rider_generic_unarmoured'
      }
    }

    -- Huscarles or huscarles on horses - Knights General
    g_models[g_str_68c995de579163001588a183_general] = {
      {
        n_models = 3,
        fixed_models = {
          [1] = 'troop_viking_rider_generic_cape',
          [2] = 'troop_viking_general_1',
          [3] = 'troop_viking_rider_generic_cape'
        }
      }
    }

    -- Huscarles or huscarles on horses - Knights
    g_models[g_str_68c995de579163001588a183] = {
      {
        model_data = 'troop_viking_rider_generic_cape'
      }
    }

    -- Select fyrd - HF
    g_models[g_str_68c995de579163001588a185] = g_models[g_str_68c995de579163001588a0de]

    -- Great fyrd - HF
    g_models[g_str_68c995de579163001588a188] = {
      {
        model_data = 'troop_viking_warrior'
      }
    }

    -- Peasants - Horde
    g_models[g_str_68c995de579163001588a18a] = g_models[g_str_68c995de579163001588a0a0]

    -- Hird bowmen - Sk
    g_models[g_str_68c995de579163001588a18c] = g_models[g_str_68c995de579163001588a0e5]

    -- Viking Camp
    g_models[g_str_5fb1b9e4e1af060017709a4c_camp] = g_models[g_str_5fb1b9dce1af06001770959d_camp]

    --Scouts and javelinmen - Rabble
    g_models[g_str_68c995de579163001588a18f] = g_models[g_str_68c995dd579163001588a04a]
    
    -- Breton Camp - Fortified
    g_models[g_str_5fb1b9e5e1af060017709ad5_camp] = g_models[g_str_5fb1b9dce1af06001770959d_camp]