-- Warlike Gallic
army['5fb1b9dce1af06001770959d'].data.has_models = true
army['5fb1b9dce1af06001770959d'].data.base="tile_grass"
-- Sedentary Gallic
army['5fb1b9dce1af0600177095a5'].data.has_models = true
army['5fb1b9dce1af0600177095a5'].data.base="tile_grass"

-- Warlike Gallic
-- 400 BC to 100 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9dce1af06001770959d/explore
-- As of: 20210404

    --2-horse battle platforms with champions who dismount to fight on foot - General
    g_models[g_str_68c995d75791630015888e4e_general] = {
      {
        n_models = 1,
        fixed_models = {
          [1] = 'troop_gallic_lch_gen'
        }
      }
    }
    g_models[g_str_68c995d75791630015888e4e_general_mounted] = g_models[g_str_68c995d75791630015888e4e_general]

    -- Fierce fighters - Warriors General
    g_models[g_str_68c995d75791630015888e4e_general_dismounted] = {
      {
        n_models = 4,
        model_data = 'troop_gallic_warband_general'
      }
    }

    --2-horse battle platforms with champions who dismount to fight on foot
    g_models[g_str_68c995d75791630015888e4e] = {
      {
        n_models = 1,
        fixed_models = {
          [1] = 'troop_gallic_lch'
        }
      }
    }
    g_models[g_str_68c995d75791630015888e4e_mounted] = g_models[g_str_68c995d75791630015888e4e]

    -- Fierce fighters - Warriors
    g_models[g_str_68c995d75791630015888e4e_dismounted] = {
      {
        n_models = 4,
        model_data = 'troop_gallic_warriors_2'
      }
    }

    g_models[g_str_68c995d75791630015888e4e_general] = g_models[g_str_68c995d75791630015888e4e_general]
    g_models[g_str_68c995d75791630015888e4e_general_mounted] = g_models[g_str_68c995d75791630015888e4e_general]
    g_models[g_str_68c995d75791630015888e4e_general_dismounted] = g_models[g_str_68c995d75791630015888e4e_general_dismounted]
    g_models[g_str_68c995d75791630015888e4e] = g_models[g_str_68c995d75791630015888e4e]
    g_models[g_str_68c995d75791630015888e4e_mounted] = g_models[g_str_68c995d75791630015888e4e]
    g_models[g_str_68c995d75791630015888e4e_dismounted] = g_models[g_str_68c995d75791630015888e4e_dismounted]

    --Noble horsemen - JavCav General
    g_models[g_str_68c995d75791630015888e56_general] = {
      {
        n_models = 2,
        fixed_models = {
          [1] = 'troop_gallic_cav',
          [2] = 'troop_gallic_cav_general'
        }
      }
    }

    --Noble horsemen - JavCav
    g_models[g_str_68c995d75791630015888e56] = {
      {
        model_data = 'troop_gallic_cav'
      }
    }

    --Horsemen - Bad Horse
    g_models[g_str_68c995d75791630015888e58] = {
      {
        model_data = 'troop_gallic_cav_bodyguard'
      }
    }
    -- Fierce fighters - Warriors and General
    g_models[g_str_68c995d75791630015888e5a_general] = g_models[g_str_68c995d75791630015888e4e_general_dismounted]
    g_models[g_str_68c995d75791630015888e5a] = g_models[g_str_68c995d75791630015888e4e_dismounted]

    --Poorly equipped and trained bowmen, slingers, and unshielded javelinmen - Rabble
    g_models[g_str_68c995d75791630015888e5c] = {
      {
        model_data = 'troop_gallic_ps'
      }
    }

    --Gaesati naked fighters - Warband
    g_models[g_str_68c995d75791630015888e5e] = {
      {
        model_data = 'troop_gallic_warband'
      }
    }

    --Gallic Camp
    --g_models[g_str_5fb1b9dce1af06001770959d_camp] = g_models[g_str_5fb1b9dce1af06001770959d_camp]

    --Gallic Camp Fortified
    -----------------
    --We will have to change this
    -----------------
    g_models[g_str_5fb1b9dce1af06001770959d_camp_fortified] = {
      {
        overlay_models = { -- each of the models are placed on top of the base
          {
            model_data="troop_fortified_camp_outline_40x40",
            position={x=-0,y=0,z=0}, -- optional defaults to (0,0,0)
            rotation=0, -- optional defaults to 0
            scale=1, -- optional defaults t0 1
          },
          {
            model_data = 'troop_campfire',
            scale=0.7
          }
        }
      }
    }

-- Sedentary Gallic
-- 99 BC to 50 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9dce1af0600177095a5/explore
-- As of: 20210407

    --Noble horsemen - JavCav General
    g_models[g_str_68c995d75791630015888e6a_general] = g_models[g_str_68c995d75791630015888e56_general]

    --Noble horsemen - JavCav
    g_models[g_str_68c995d75791630015888e6a] = g_models[g_str_68c995d75791630015888e56]

    --Unshielded (Not yet) Horsemen - Bad Horse
    g_models[g_str_68c995d75791630015888e6c] = g_models[g_str_68c995d75791630015888e58]

    -- Fierce fighters - Warriors General
    g_models[g_str_68c995d75791630015888e6e_general] = g_models[g_str_68c995d75791630015888e4e_general_dismounted]

    -- Fierce fighters - Warriors
    g_models[g_str_68c995d75791630015888e6e] = g_models[g_str_68c995d75791630015888e4e_dismounted]

    -- Sedentary infantry - Light Inf.
    g_models[g_str_68c995d75791630015888e70] = {
      {
        model_data = 'troop_gallic_warriors'
      }
    }

    -- Fierce fighters - Warriors
    g_models[g_str_68c995d75791630015888e72] = g_models[g_str_68c995d75791630015888e5c]

    -- Gallic Camp
    g_models[g_str_5fb1b9dce1af0600177095a5_camp] = g_models[g_str_5fb1b9dce1af06001770959d_camp]

    -- Gallic Camp Fortified
    g_models[g_str_5fb1b9dce1af0600177095a5_camp_fortified] = g_models[g_str_5fb1b9dce1af06001770959d_camp_fortified]
