require("Triumph_TTS/scripts/data/data_troops_sumerian")


-- Gilgamesh Era Sumerian
army['5fb1b9d8e1af0600177092b9'].data.has_models = true
army['5fb1b9d8e1af0600177092b9'].data.base="tile_grass"
-- Early Sumerian
army['5fb1b9d8e1af0600177092b3'].data.has_models = true
army['5fb1b9d8e1af0600177092b3'].data.base="tile_grass"
-- Great Revolt Sumerian
army['5fb1b9d8e1af0600177092bf'].data.has_models = true
army['5fb1b9d8e1af0600177092bf'].data.base="tile_grass"
-- Akkadian
army['5fb1b9d8e1af0600177092c5'].data.has_models = true
army['5fb1b9d8e1af0600177092c5'].data.base="tile_grass"
-- Third Dynasty of Ur
army['5fb1b9d8e1af0600177092e5'].data.has_models = true
army['5fb1b9d8e1af0600177092e5'].data.base="tile_grass"
-- Sumerian Successor States
army['5fb1b9d8e1af0600177092de'].data.has_models = true
army['5fb1b9d8e1af0600177092de'].data.base="tile_grass"
-- Nomadic Amurru
army['5fb1b9d8e1af0600177092ec'].data.has_models = true
army['5fb1b9d8e1af0600177092ec'].data.base="tile_grass"
-- Amurru and Early Aramaean
army['5fb1b9d8e1af0600177092f2'].data.has_models = true
army['5fb1b9d8e1af0600177092f2'].data.base="tile_grass"
-- Proto-Elamite
army['5fb1b9d8e1af0600177092fa'].data.has_models = true
army['5fb1b9d8e1af0600177092fa'].data.base="tile_grass"
-- Awan Dynasty Elamite
army['5fb1b9d8e1af060017709300'].data.has_models = true
army['5fb1b9d8e1af060017709300'].data.base="tile_grass"
-- Early Elam
army['5fb1b9d8e1af060017709306'].data.has_models = true
army['5fb1b9d8e1af060017709306'].data.base="tile_grass"
-- Guti
army['5fb1b9d9e1af060017709321'].data.has_models = true
army['5fb1b9d9e1af060017709321'].data.base="tile_grass"
-- Early Bronze Age Highlanders
army['5fb1b9d9e1af060017709327'].data.has_models = true
army['5fb1b9d9e1af060017709327'].data.base="tile_grass"
-- Early Syrian
army['5fb1b9d9e1af06001770932f'].data.has_models = true
army['5fb1b9d9e1af06001770932f'].data.base="tile_grass"
-- Later Amorite
army['5fb1b9d9e1af06001770935f'].data.has_models = true
army['5fb1b9d9e1af06001770935f'].data.base="tile_grass"

-- Gilgamesh Era Sumerian
-- 2799 BC to 2334 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9d8e1af0600177092b9/explore
-- As of: 20230122

    -- 4-wheeled battle cars - Chariots General
    g_models[g_str_68c995d2579163001588832b_general] = {
      {
        n_models = 1,
        model_data = 'troop_sumerian_chariot_general'
      }
    }

    -- 4-wheeled battle cars - Chariots
    g_models[g_str_68c995d2579163001588832b] = {
      {
        n_models = 1,
        model_data = 'troop_sumerian_chariot'
      }
    }

    -- Household axemen - Raiders
    g_models[g_str_68c995d2579163001588832d] = {
      {
        model_data = 'troop_sumerian_axeman'
      }
    }

    -- Martu mercenaries - Light Foot
    g_models[g_str_68c995d25791630015888330] = {
      {
        model_data = 'troop_sumerian_light_javelinman_shielded'
      }
    }

    -- Martu mercenaries - Light Foot
    g_models[g_str_68c995d25791630015888330] = g_models[g_str_68c995d25791630015888330]

    -- Household and militia bowmen - Bow Levy
    g_models[g_str_68c995d25791630015888335] = {
      {
        loose = true,
        model_data = 'troop_sumerian_archer'
      }
    }

    -- Household and militia speamen - Pikes
    g_models[g_str_68c995d25791630015888338] = {
      {
        n_models = 4,
        random_models = {
          'troop_sumerian_spearman_rectangular_shield_levy',
          'troop_sumerian_spearman_rectangular_shield_household'
        }
      }
    }

    -- Nomadic and levy javelinmen - Rabble
    g_models[g_str_68c995d2579163001588833a] = {
      {
        loose = true,
        model_data = 'troop_sumerian_javelinman'
      }
    }

    -- Nomadic and levy slingers and skirmishing bowmen - Skirmishers
    g_models[g_str_68c995d2579163001588833c] = {
      {
        loose = true,
        random_models = {
          'troop_sumerian_skirmisher_archer',
          'troop_sumerian_skirmisher_slinger'
        }
      }
    }

    -- Sumerian Camp
    g_models[g_str_5fb1b9d8e1af0600177092b9_camp] = g_models[g_str_5fb1b9dce1af06001770959d_camp]
    
    -- Sumerian Camp
    g_models[g_str_5fb1b9d8e1af0600177092b9_camp_pack_train] = g_models[g_str_5fb1b9e1e1af060017709849_camp_pack_train]



    -- Bowmen - Bow Levy
    g_models[g_str_6153518d03385c0016b83501] = g_models[g_str_68c995d25791630015888335]

    -- Household and militia speamen - Pikes
    g_models[g_str_6153518d03385c0016b83538] = {
      {
        n_models = 4,
        random_models = {
          'troop_sumerian_spearman_rectangular_shield_levy'
        }
      }
    }

    -- Household bowmen - Bow Levy
    g_models[g_str_6153518d03385c0016b8353a] = g_models[g_str_68c995d25791630015888335]

    -- Levy or militia bowmen - Bow Levy
    g_models[g_str_6153518d03385c0016b8353c] = {
      {
        loose = true,
        model_data = 'troop_sumerian_skirmisher_archer'
      }
    }

    -- Unshielded javelinmen - Rabble
    g_models[g_str_6153518d03385c0016b8353e] = g_models[g_str_68c995d2579163001588833a] 

    -- Javelinmen, some with shields - Rabble
    g_models[g_str_6153518d03385c0016b83540] = {
      {
        loose = true,
        model_data = 'troop_sumerian_light_javelinman'
      }
    }

    -- Javelinmen, some with shields - Light Foot
    g_models[g_str_6153518d03385c0016b83541] = {
      {
        random_models = {
          'troop_sumerian_light_javelinman',
          'troop_sumerian_light_javelinman_shielded'
        }
      }
    }


-- Early Sumerian
-- 3000 BC to 2800 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9d8e1af0600177092b3/explore
-- As of: 20230122

    -- Close-fighters - Raiders General
    g_models[g_str_68c995d25791630015888319_general] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_sumerian_axeman_two_hands',
          [2] = 'troop_sumerian_infantry_general',
          [3] = 'troop_sumerian_infantry_standard',
          [4] = 'troop_sumerian_axeman_two_hands'
        }
      }
    }

    -- Household axemen - Raiders
    g_models[g_str_68c995d25791630015888319] = {
      {
        model_data = 'troop_sumerian_axeman_two_hands'
      }
    }

    -- Household and militia bowmen - Bow Levy
    g_models[g_str_68c995d2579163001588831b] = g_models[g_str_68c995d25791630015888335]

    -- Nomadic and levy javelinmen - Rabble
    g_models[g_str_68c995d2579163001588831e] = g_models[g_str_68c995d2579163001588833a]

    -- Nomadic and levy slingers and skirmishing bowmen - Skirmishers
    g_models[g_str_68c995d25791630015888320] = g_models[g_str_68c995d2579163001588833c]

    -- Sumerian Camp
    g_models[g_str_5fb1b9d8e1af0600177092b3_camp] = g_models[g_str_5fb1b9d8e1af0600177092b9_camp]
    
    -- Sumerian Camp
    g_models[g_str_5fb1b9d8e1af0600177092b3_camp_pack_train] = g_models[g_str_5fb1b9d8e1af0600177092b9_camp_pack_train]

    -- Retainers and effective javelinmen - Light Foot
    g_models[g_str_6153518d03385c0016b834e4] = g_models[g_str_68c995d25791630015888330]

    -- Unshielded javelinmen - Rabble
    g_models[g_str_6153518d03385c0016b834e6] = g_models[g_str_6153518d03385c0016b83540]

    -- Slingers - Skirmishers
    g_models[g_str_6153518d03385c0016b834e8] = {
      {
        loose = true,
        model_data = 'troop_sumerian_skirmisher_slinger'
      }
    }

    -- Bowmen - Bow Levy
    g_models[g_str_6153518d03385c0016b834ea] = g_models[g_str_6153518d03385c0016b8353c]

    -- Bodyguards - Archers
    g_models[g_str_6153518d03385c0016b834eb] = {
      {
        model_data = 'troop_sumerian_archer'
      }
    }

    -- Bodyguards - Raiders
    g_models[g_str_6153518d03385c0016b8352c] = g_models[g_str_68c995d25791630015888319]


    -- Bodyguards - Archers
    g_models[g_str_6153518d03385c0016b8352d] = g_models[g_str_6153518d03385c0016b834eb]

    -- Unshielded javelinmen - Rabble
    g_models[g_str_6153518d03385c0016b8352f] = g_models[g_str_68c995d2579163001588833a]

    -- Javelinmen with shields - Light Foot
    g_models[g_str_6153518d03385c0016b83532] = g_models[g_str_68c995d25791630015888330]

    -- Bowmen - Bow Levy
    g_models[g_str_6153518d03385c0016b83534] = g_models[g_str_6153518d03385c0016b834ea]

    -- Bowmen - Bow Levy
    g_models[g_str_6153518d03385c0016b834fd] = g_models[g_str_68c995d25791630015888335]


-- Great Revolt Sumerian
-- 2250 BC 
-- https://meshwesh.wgcwar.com/armyList/5fb1b9d8e1af0600177092bf/explore
-- As of: 20230129

    -- 4-wheeled battle cars - Chariots General
    g_models[g_str_68c995d2579163001588834e_general] = g_models[g_str_68c995d2579163001588832b_general]

    -- 4-wheeled battle cars - Chariots
    g_models[g_str_68c995d2579163001588834e] = g_models[g_str_68c995d2579163001588832b]

    -- Household axemen - Raiders
    g_models[g_str_68c995d25791630015888350] = g_models[g_str_68c995d2579163001588832d]

    -- Household and militia bowmen - Bow Levy
    g_models[g_str_68c995d25791630015888352] = g_models[g_str_68c995d25791630015888335]

    -- Household and militia speamen - Pikes General
    g_models[g_str_68c995d25791630015888355_general] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_sumerian_spearman_rectangular_shield_household',
          [2] = 'troop_sumerian_spearman_rectangular_shield_household',
          [3] = 'troop_sumerian_infantry_general',
          [4] = 'troop_sumerian_infantry_standard'
        }
      }
    }

    -- Household and militia speamen - Pikes
    g_models[g_str_68c995d25791630015888355] = g_models[g_str_68c995d25791630015888338]

    -- Nomadic and levy javelinmen - Rabble
    g_models[g_str_68c995d25791630015888357] = g_models[g_str_68c995d2579163001588833a]

    -- Nomadic and levy slingers and skirmishing bowmen - Skirmishers
    g_models[g_str_68c995d25791630015888359] = g_models[g_str_68c995d2579163001588833c]

    -- Throng - Horde
    g_models[g_str_68c995d2579163001588835b] = {
      {
        loose = true,
        random_models = {
          'troop_sumerian_skirmisher_archer',
          'troop_sumerian_light_javelinman',
          'troop_sumerian_axeman_two_hands',
          'troop_sumerian_spearman_no_shield'
        }
      }
    }

    -- Sumerian Camp
    g_models[g_str_5fb1b9d8e1af0600177092bf_camp] = g_models[g_str_5fb1b9d8e1af0600177092b9_camp]
    
    -- Sumerian Camp
    g_models[g_str_5fb1b9d8e1af0600177092bf_camp_pack_train] = g_models[g_str_5fb1b9e1e1af060017709849_camp_pack_train]


    --Option 1: (Only Southern Coalition) Melukhkhan Allies 
    -- They are indian, models we don't have yet


-- Akkadian
-- 2334 BC to 2193 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9d8e1af0600177092c5/explore
-- As of: 20230129

    -- 4-wheeled battle cars - Chariots General
    g_models[g_str_68c995d25791630015888363_general] = g_models[g_str_68c995d2579163001588832b_general]

    -- 4-wheeled battle cars - Chariots
    g_models[g_str_68c995d25791630015888363] = g_models[g_str_68c995d2579163001588832b]

    -- Household axemen - Raiders
    g_models[g_str_68c995d25791630015888365] = g_models[g_str_68c995d2579163001588832d]

    -- Household speamen - Pikes
    g_models[g_str_68c995d25791630015888367] = {
      {
        model_data = 'troop_sumerian_spearman_rectangular_shield_household'
      }
    }

    -- Household speamen - Light Spear
    g_models[g_str_68c995d25791630015888368] = {
      {
        model_data = 'troop_sumerian_spearman_no_shield'
      }
    }

    -- Household bowmen - Archers
    g_models[g_str_68c995d2579163001588836a] = g_models[g_str_6153518d03385c0016b834eb]

    -- Household bowmen - Skirmishers
    g_models[g_str_68c995d2579163001588836b] = {
      {
        model_data = 'troop_sumerian_archer'
      }
    }

    -- Militia spearmen - Pikes
    g_models[g_str_68c995d2579163001588836e] = {
      {
        model_data = 'troop_sumerian_spearman_rectangular_shield_levy'
      }
    }

    -- Militia spearmen - Pikes
    g_models[g_str_68c995d2579163001588836e] = g_models[g_str_68c995d2579163001588836e]

    -- Militia spearmen - Light Spear
    g_models[g_str_68c995d25791630015888372] = g_models[g_str_68c995d25791630015888368]

    -- Highlander or Elamite bowme - Bow Levy
    g_models[g_str_68c995d25791630015888375] = g_models[g_str_6153518d03385c0016b8353c]

    -- Highlander levy javelinmen - Rabble
    g_models[g_str_68c995d25791630015888379] = g_models[g_str_6153518d03385c0016b83540]

    -- Nomadic and levy bowmen - Skirmishers
    g_models[g_str_68c995d2579163001588837b] = {
      {
        model_data = 'troop_sumerian_skirmisher_archer'
      }
    }

    -- Nomadic and levy javelinmen - Rabble
    g_models[g_str_68c995d2579163001588837d] = g_models[g_str_6153518d03385c0016b83540]

    -- Nomadic and levy slingers - Skirmishers
    g_models[g_str_68c995d2579163001588837f] = g_models[g_str_6153518d03385c0016b834e8]

    -- Sumerian Camp
    g_models[g_str_5fb1b9d8e1af0600177092c5_camp] = g_models[g_str_5fb1b9d8e1af0600177092b9_camp]
    
    -- Sumerian Camp
    g_models[g_str_5fb1b9d8e1af0600177092c5_camp_fortified] = g_models[g_str_5fb1b9dce1af06001770959d_camp_fortified]
    
    -- Sumerian Camp
    g_models[g_str_5fb1b9d8e1af0600177092c5_camp_pack_train] = g_models[g_str_5fb1b9e1e1af060017709849_camp_pack_train]

    -- 4-wheeled battle cars - Chariots
    g_models[g_str_6153518d03385c0016b83499] = g_models[g_str_68c995d2579163001588832b]

    -- Household and militia speamen - Pikes
    g_models[g_str_6153518d03385c0016b8349b] = g_models[g_str_68c995d25791630015888338]

    -- Nomadic and levy javelinmen - Rabble
    g_models[g_str_6153518d03385c0016b8349d] = g_models[g_str_6153518d03385c0016b83540]

    -- Nomadic and levy slingers and skirmishing bowmen - Skirmishers
    g_models[g_str_6153518d03385c0016b8349f] =  g_models[g_str_68c995d2579163001588833c]


-- Third Dynasty of Ur
-- 2112 BC to 2004 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9d8e1af0600177092e5/explore
-- As of: 20230130

    -- 4-wheeled battle platforms or straddle cars - Battle Taxi General
    g_models[g_str_68c995d257916300158883f7_general] = {
      {
        n_models = 1,
        model_data = 'troop_sumerian_chariot_general'
      }
    }

    -- 4-wheeled battle platforms or straddle cars - Battle Taxi
    g_models[g_str_68c995d257916300158883f7] = {
      {
        n_models = 1,
        model_data = 'troop_sumerian_chariot'
      }
    }

    -- Household bowmen - Archers General
    g_models[g_str_68c995d257916300158883f9_general] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_sumerian_infantry_standard',
          [2] = 'troop_sumerian_infantry_general',
          [3] = 'troop_sumerian_archer',
          [4] = 'troop_sumerian_archer'
        }
      }
    }

    -- Household bowmen - Archers
    g_models[g_str_68c995d257916300158883f9] = g_models[g_str_6153518d03385c0016b834eb]

    -- Household retinue - Raiders General
    g_models[g_str_68c995d257916300158883fb_general] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_sumerian_infantry_general',
          [2] = 'troop_sumerian_axeman',
          [3] = 'troop_sumerian_infantry_standard',
          [4] = 'troop_sumerian_axeman'
        }
      }
    }

    -- Household retinue - Raiders
    g_models[g_str_68c995d257916300158883fb] = g_models[g_str_68c995d2579163001588832d]

    -- Household or militia spearmen with large rectangular shield - Pikes
    g_models[g_str_68c995d257916300158883fe] = g_models[g_str_68c995d25791630015888338] 

    -- Household or militia spearmen with large rectangular shield - Light Spear
    g_models[g_str_68c995d257916300158883ff] = g_models[g_str_68c995d25791630015888368]

    -- Household or militia spearmen with Amorite shield - Heavy Foot
    g_models[g_str_68c995d25791630015888402] = {
      {
        model_data = 'troop_sumerian_amorite_spearman'
      }
    }

    -- Household or militia spearmen with large rectangular shield - Pikes
    g_models[g_str_68c995d257916300158883fe] = g_models[g_str_68c995d25791630015888367]

    -- Household or militia spearmen with large rectangular shield - Light Spear
    g_models[g_str_68c995d257916300158883ff] = g_models[g_str_68c995d257916300158883ff]
 
    -- Highlander or Elamite bowme - Bow Levy
    g_models[g_str_68c995d25791630015888408] = g_models[g_str_68c995d25791630015888375]

    -- Nomadic and levy bowmen and slingers - Skirmishers
    g_models[g_str_68c995d2579163001588840b] = g_models[g_str_68c995d2579163001588833c]

    -- Frontier troops, levy, or nomadic javelinmen - Rabble
    g_models[g_str_68c995d2579163001588840d] = g_models[g_str_6153518d03385c0016b83540]

    -- Amurru bedouin levies and effective frontier troops - Light Foot
    g_models[g_str_68c995d2579163001588840f] = g_models[g_str_68c995d25791630015888330]  

    -- Sumerian Camp
    g_models[g_str_5fb1b9d8e1af0600177092e5_camp] = g_models[g_str_5fb1b9d8e1af0600177092b9_camp]
    
    -- Sumerian Camp
    g_models[g_str_5fb1b9d8e1af0600177092e5_camp_fortified] = g_models[g_str_5fb1b9dce1af06001770959d_camp_fortified]
    
    -- Sumerian Camp
    g_models[g_str_5fb1b9d8e1af0600177092e5_camp_pack_train] = g_models[g_str_5fb1b9e1e1af060017709849_camp_pack_train]


-- Sumerian Successor States
-- 2028 BC to 1460 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9d8e1af0600177092de/explore
-- As of: 20230130

    -- 4-wheeled battle cars - Chariots General
    g_models[g_str_68c995d257916300158883d7_general] = g_models[g_str_68c995d2579163001588832b_general]

    -- 4-wheeled battle cars - Chariots
    g_models[g_str_68c995d257916300158883d7] = g_models[g_str_68c995d2579163001588832b]

    -- Household bowmen - Archers General
    g_models[g_str_68c995d257916300158883d8_general] = g_models[g_str_68c995d257916300158883f9_general] 

    -- Household bowmen - Archers
    g_models[g_str_68c995d257916300158883d8] = g_models[g_str_6153518d03385c0016b834eb]

    -- Household or militia spearmen with large rectangular shield - Pikes
    g_models[g_str_68c995d257916300158883da] = g_models[g_str_68c995d25791630015888338] 

    -- Household or militia spearmen with large rectangular shield - Light Spear
    g_models[g_str_68c995d257916300158883db] = g_models[g_str_68c995d25791630015888368]

    -- Household or militia spearmen with Amorite shield - Heavy Foot
    g_models[g_str_68c995d257916300158883dc] = {
      {
        model_data = 'troop_sumerian_amorite_spearman'
      }
    }

    -- Javelinmen - Rabble
    g_models[g_str_68c995d257916300158883de] = g_models[g_str_6153518d03385c0016b83540]

    -- Household bowmen - Skirmishers
    g_models[g_str_68c995d257916300158883e0] = {
      {
        model_data = 'troop_sumerian_archer'
      }
    }

    -- Highlander or Elamite bowmen - Bow Levy
    g_models[g_str_68c995d257916300158883e2] = g_models[g_str_6153518d03385c0016b8353c]

    -- Frontier troops, levy, or nomadic javelinmen - Rabble
    g_models[g_str_68c995d257916300158883e5] = g_models[g_str_6153518d03385c0016b83540]

    -- Amurru bedouin levies and effective frontier troops - Light Foot
    g_models[g_str_68c995d257916300158883e8] = g_models[g_str_68c995d25791630015888330]  

    -- Sumerian Camp
    g_models[g_str_5fb1b9d8e1af0600177092de_camp] = g_models[g_str_5fb1b9d8e1af0600177092b9_camp]

    -- Sumerian Camp
    g_models[g_str_5fb1b9d8e1af0600177092de_camp_pack_train] = g_models[g_str_5fb1b9e1e1af060017709849_camp_pack_train]

    -- Household bowmen - Archers
    g_models[g_str_6153518d03385c0016b83505] = g_models[g_str_6153518d03385c0016b834eb]

    -- Household retinue - Raiders
    g_models[g_str_6153518d03385c0016b83506] = g_models[g_str_68c995d2579163001588832d]

    -- Bowmen - Bow Levy
    g_models[g_str_6153518d03385c0016b83508] = g_models[g_str_6153518d03385c0016b8353c]

    -- Retinue armed with axe or sickle-sword - Raiders
    g_models[g_str_6153518e03385c0016b83566] = {
      {
        loose = true,
        random_models = {
          'troop_sumerian_axeman_two_hands',
          'troop_sumerian_amorite_warrior'
        }
      }
    }

    -- Sabum qallatum, some with shield - Light Foot
    g_models[g_str_6153518e03385c0016b83568] = {
      {
        loose = true,
        model_data = 'troop_sumerian_light_javelinman_shielded_amorite',
      }
    }

    -- Sabum qallatum, some with shield - Rabble
    g_models[g_str_6153518e03385c0016b83569] = g_models[g_str_6153518d03385c0016b83540]

    -- Sabum qallatum armed with bow or sling - Skirmishers
    g_models[g_str_6153518e03385c0016b8356b] = g_models[g_str_68c995d2579163001588833c]


-- Nomadic Amurru
-- 3000 BC to 2001 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9d8e1af0600177092ec/explore
-- As of: 20230130

    -- Retainers and effective javelinmen - Light Foot General
    g_models[g_str_68c995d2579163001588841b_general] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_sumerian_infantry_standard',
          [2] = 'troop_sumerian_infantry_general',
          [3] = 'troop_sumerian_light_javelinman_shielded',
          [4] = 'troop_sumerian_light_javelinman_shielded'
        }
      }
    }

    -- Retainers and effective javelinmen - Light Foot
    g_models[g_str_68c995d2579163001588841b] = g_models[g_str_68c995d25791630015888330]

    -- Unshielded javelinmen - Rabble
    g_models[g_str_68c995d2579163001588841d] = g_models[g_str_6153518d03385c0016b83540]

    -- Slingers - Skirmishers
    g_models[g_str_68c995d2579163001588841f] = g_models[g_str_6153518d03385c0016b834e8]

    -- Bowmen - Bow Levy
    g_models[g_str_68c995d25791630015888421] = g_models[g_str_68c995d25791630015888375]

    -- Bowmen - Archers
    g_models[g_str_68c995d25791630015888422] = {
      {
        model_data = 'troop_sumerian_skirmisher_archer'
      }
    }

    -- Nomadic Amurru Camp
    g_models[g_str_5fb1b9d8e1af0600177092ec_camp] = g_models[g_str_5fb1b9d8e1af0600177092b9_camp]

    -- Nomadic Amurru Camp
    g_models[g_str_5fb1b9d8e1af0600177092ec_camp_pack_train] = g_models[g_str_5fb1b9e1e1af060017709849_camp_pack_train]


-- Amurru and Early Aramaean
-- 2000 BC to 747 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9d8e1af0600177092f2/explore
-- As of: 20230131

    -- 4-wheeled battle cars - Chariots General
    g_models[g_str_68c995d25791630015888431_general] = {
      {
        n_models = 1,
        model_data = 'troop_sumerian_light_chariot_general'
      }
    }

    -- 4-wheeled battle cars - Chariots
    g_models[g_str_68c995d25791630015888431] = {
      {
        n_models = 1,
        model_data = 'troop_sumerian_light_chariot'
      }
    }

    -- Retainers and effective javelinmen - Light Foot General
    g_models[g_str_68c995d25791630015888432_general] = {
      {
        n_models = 3,
        fixed_models = {
          [1] = 'troop_sumerian_infantry_standard',
          [2] = 'troop_sumerian_infantry_general',
          [3] = 'troop_sumerian_amorite_warrior'
        }
      }
    }

    -- Retainers and effective javelinmen - Light Foot
    g_models[g_str_68c995d25791630015888432] = {
      {
        model_data = 'troop_sumerian_amorite_warrior'
      }
    }

    -- Retainers and effective javelinmen - Light Foot General
    g_models[g_str_68c995d25791630015888434_general] = {
      {
        n_models = 3,
        fixed_models = {
          [1] = 'troop_sumerian_light_javelinman_shielded_amorite',
          [2] = 'troop_sumerian_infantry_general',
          [3] = 'troop_sumerian_light_javelinman_shielded_amorite'
        }
      }
    }

    -- Retainers and effective javelinmen - Light Foot
    g_models[g_str_68c995d25791630015888434] = g_models[g_str_6153518e03385c0016b83568]

    -- Skirmishing bowmen - Skirmishers
    g_models[g_str_68c995d25791630015888438] = g_models[g_str_68c995d2579163001588837b]

    -- Unshielded javelinmen - Rabble
    g_models[g_str_68c995d2579163001588843b] = g_models[g_str_6153518d03385c0016b83540]

    -- Slingers - Skirmishers
    g_models[g_str_68c995d2579163001588843d] = g_models[g_str_6153518d03385c0016b834e8]

    -- Bowmen - Bow Levy
    g_models[g_str_68c995d2579163001588843f] = g_models[g_str_68c995d25791630015888375]

    -- Bowmen - Archers
    g_models[g_str_68c995d25791630015888440] = g_models[g_str_68c995d25791630015888422]

    -- Nomadic Amurru Camp
    g_models[g_str_5fb1b9d8e1af0600177092f2_camp] = g_models[g_str_5fb1b9d8e1af0600177092b9_camp]

    -- Nomadic Amurru Camp
    g_models[g_str_5fb1b9d8e1af0600177092f2_camp_pack_train] = g_models[g_str_5fb1b9e1e1af060017709849_camp_pack_train]


-- Proto-Elamite
-- 3000 BC to 2601 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9d8e1af0600177092fa/explore
-- As of: 20230131

    -- Retainers - Archers General
    g_models[g_str_68c995d2579163001588844d_general] = g_models[g_str_68c995d257916300158883d8_general]
    
    -- Retainers - Archers
    g_models[g_str_68c995d2579163001588844d] = g_models[g_str_6153518d03385c0016b834eb]

    -- Bowmen - Bow Levy
    g_models[g_str_68c995d2579163001588844f] = g_models[g_str_68c995d25791630015888375]

    -- Elamite Camp
    g_models[g_str_5fb1b9d8e1af0600177092fa_camp] = g_models[g_str_5fb1b9d8e1af0600177092b9_camp]

    -- Elamite Camp
    g_models[g_str_5fb1b9d8e1af0600177092fa_camp_pack_train] = g_models[g_str_5fb1b9e1e1af060017709849_camp_pack_train]


-- Awan Dynasty Elamite
-- 2600 BC to 2101 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9d8e1af060017709300/explore
-- As of: 20230131

    -- Retainers - Archers General
    g_models[g_str_68c995d25791630015888457_general] = g_models[g_str_68c995d257916300158883d8_general]
    
    -- Retainers - Archers
    g_models[g_str_68c995d25791630015888457] = g_models[g_str_6153518d03385c0016b834eb]

    -- Retainers - Light Spear General
    g_models[g_str_68c995d25791630015888458_general] = {
      {
        n_models = 3,
        fixed_models = {
          [1] = 'troop_sumerian_infantry_standard',
          [2] = 'troop_sumerian_infantry_general',
          [3] = 'troop_sumerian_spearman_no_shield'
        }
      }
    }

    -- Retainers - Light Spear
    g_models[g_str_68c995d25791630015888458] = g_models[g_str_68c995d25791630015888368]

    -- Household retinue - Raiders General
    g_models[g_str_68c995d25791630015888459_general] = g_models[g_str_68c995d257916300158883fb_general]

    -- Household retinue - Raiders
    g_models[g_str_68c995d25791630015888459] = g_models[g_str_68c995d2579163001588832d]

    -- 4-wheeled battle platforms or straddle cars - Battle Taxi General
    g_models[g_str_68c995d2579163001588845b_general] = g_models[g_str_68c995d257916300158883f7_general]

    -- 4-wheeled battle platforms or straddle cars - Battle Taxi
    g_models[g_str_68c995d2579163001588845b] = g_models[g_str_68c995d257916300158883f7]

    -- Household speamen - Pikes
    g_models[g_str_68c995d2579163001588845d] = g_models[g_str_68c995d25791630015888367]

    -- Bowmen - Bow Levy
    g_models[g_str_68c995d25791630015888462] = g_models[g_str_68c995d25791630015888375]

    -- Elamite Camp
    g_models[g_str_5fb1b9d8e1af060017709300_camp] = g_models[g_str_5fb1b9d8e1af0600177092b9_camp]

    -- Elamite Camp
    g_models[g_str_5fb1b9d8e1af060017709300_camp_pack_train] = g_models[g_str_5fb1b9e1e1af060017709849_camp_pack_train]


-- Early Elam
-- 2100 BC to 1401 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9d8e1af060017709306/explore
-- As of: 20230131

    -- Retainers - Archers General
    g_models[g_str_68c995d3579163001588846d_general] = g_models[g_str_68c995d257916300158883d8_general]
    
    -- Retainers - Archers
    g_models[g_str_68c995d3579163001588846d] = g_models[g_str_6153518d03385c0016b834eb]

    -- Household retinue - Raiders General
    g_models[g_str_68c995d3579163001588846e_general] = g_models[g_str_68c995d257916300158883fb_general]

    -- Household retinue - Raiders
    g_models[g_str_68c995d3579163001588846e] = g_models[g_str_68c995d2579163001588832d]

    -- 4-wheeled battle platforms or straddle cars - Battle Taxi General
    g_models[g_str_68c995d35791630015888470_general] = g_models[g_str_68c995d257916300158883f7_general]

    -- 4-wheeled battle platforms or straddle cars - Battle Taxi
    g_models[g_str_68c995d35791630015888470] = g_models[g_str_68c995d257916300158883f7]

    -- Bowmen - Bow Levy
    g_models[g_str_68c995d35791630015888472] = g_models[g_str_68c995d25791630015888375]

    -- Elamite Camp
    g_models[g_str_5fb1b9d8e1af060017709306_camp] = g_models[g_str_5fb1b9d8e1af0600177092b9_camp]

    -- Elamite Camp
    g_models[g_str_5fb1b9d8e1af060017709306_camp_pack_train] = g_models[g_str_5fb1b9e1e1af060017709849_camp_pack_train]

-- Guti
-- 2250 BC to 2112 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9d9e1af060017709321/explore
-- As of: 20230201

    -- Bodyguards - Raiders General
    g_models[g_str_68c995d357916300158884c6_general] = g_models[g_str_68c995d257916300158883fb_general]

    -- Bodyguards - Raiders
    g_models[g_str_68c995d357916300158884c6] = g_models[g_str_68c995d2579163001588832d]

    -- Bodyguards - Archers General
    g_models[g_str_68c995d357916300158884c7_general] = g_models[g_str_68c995d257916300158883d8_general]
    
    -- Bodyguards - Archers
    g_models[g_str_68c995d357916300158884c7] = g_models[g_str_6153518d03385c0016b834eb]

    -- Unshielded javelinmen - Rabble
    g_models[g_str_68c995d357916300158884c9] = g_models[g_str_6153518d03385c0016b83540]

    -- Unshielded javelinmen - Warband
    g_models[g_str_68c995d357916300158884ca] = {
      {
        model_data = 'troop_sumerian_light_javelinman'
      }
    }

    -- Bowmen - Bow Levy
    g_models[g_str_68c995d357916300158884cc] = g_models[g_str_68c995d25791630015888375]

    -- Slingers - Skirmishers
    g_models[g_str_68c995d357916300158884cf] = g_models[g_str_6153518d03385c0016b834e8]

    -- Sumero-Akkadian militia spearmen - Pikes
    g_models[g_str_68c995d357916300158884d2] = g_models[g_str_6153518d03385c0016b83538]

    -- Sumero-Akkadian militia spearmen - Light Spear
    g_models[g_str_68c995d357916300158884d3] = g_models[g_str_68c995d25791630015888368]

    -- Markhashian bowmen - Bow Levy
    g_models[g_str_68c995d357916300158884d6] = g_models[g_str_68c995d25791630015888375]

    -- Melukhkhan elite bowmen - Archers General
    g_models[g_str_68c995d357916300158884da_general] = g_models[g_str_68c995d257916300158883d8_general]
    
    -- Melukhkhan elite bowmen - Archers
    g_models[g_str_68c995d357916300158884da] = g_models[g_str_6153518d03385c0016b834eb]

    -- Makkanite close-combat fighters - Raiders General
    g_models[g_str_68c995d357916300158884dd_general] = g_models[g_str_68c995d257916300158883fb_general]

    -- Makkanite close-combat fighters - Raiders
    g_models[g_str_68c995d357916300158884dd] = g_models[g_str_68c995d2579163001588832d]

    -- Guti Camp
    g_models[g_str_5fb1b9d9e1af060017709321_camp] = g_models[g_str_5fb1b9d8e1af0600177092b9_camp]

    -- Guti Camp
    g_models[g_str_5fb1b9d9e1af060017709321_camp_pack_train] = g_models[g_str_5fb1b9e1e1af060017709849_camp_pack_train]

    -- Household speamen - Pikes
    g_models[g_str_6153518d03385c0016b834a5] = g_models[g_str_68c995d25791630015888367]

    -- Household speamen - Light Spear
    g_models[g_str_6153518d03385c0016b834a6] = g_models[g_str_68c995d25791630015888368]

    -- Militia spearmen - Pikes
    g_models[g_str_6153518d03385c0016b834a9] = g_models[g_str_68c995d2579163001588836e]

    -- Militia spearmen - Pikes
    g_models[g_str_6153518d03385c0016b834ac] = g_models[g_str_68c995d2579163001588836e]

    -- Militia spearmen - Light Spear
    g_models[g_str_6153518d03385c0016b834ad] = g_models[g_str_68c995d25791630015888368]

    -- Nomadic and levy bowmen - Skirmishers
    g_models[g_str_6153518d03385c0016b834af] = g_models[g_str_68c995d2579163001588837b]

    -- Nomadic and levy javelinmen - Rabble
    g_models[g_str_6153518d03385c0016b834b1] = g_models[g_str_68c995d2579163001588837d]

    -- Nomadic and levy slingers - Skirmishers
    g_models[g_str_6153518d03385c0016b834b3] = g_models[g_str_68c995d2579163001588837f]


-- Guti
-- 2250 BC to 2112 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9d9e1af060017709321/explore
-- As of: 20230201

    -- Bodyguards - Raiders General
    g_models[g_str_68c995d357916300158884c6_general] = g_models[g_str_68c995d257916300158883fb_general]

    -- Bodyguards - Raiders
    g_models[g_str_68c995d357916300158884c6] = g_models[g_str_68c995d2579163001588832d]

    -- Bodyguards - Archers General
    g_models[g_str_68c995d357916300158884c7_general] = g_models[g_str_68c995d257916300158883d8_general]
    
    -- Bodyguards - Archers
    g_models[g_str_68c995d357916300158884c7] = g_models[g_str_6153518d03385c0016b834eb]

    -- Unshielded javelinmen - Rabble
    g_models[g_str_68c995d357916300158884c9] = g_models[g_str_6153518d03385c0016b83540]

    -- Unshielded javelinmen - Warband
    g_models[g_str_68c995d357916300158884ca] = {
      {
        model_data = 'troop_sumerian_light_javelinman'
      }
    }

    -- Bowmen - Bow Levy
    g_models[g_str_68c995d357916300158884cc] = g_models[g_str_68c995d25791630015888375]

    -- Slingers - Skirmishers
    g_models[g_str_68c995d357916300158884cf] = g_models[g_str_6153518d03385c0016b834e8]

    -- Sumero-Akkadian militia spearmen - Pikes
    g_models[g_str_68c995d357916300158884d2] = g_models[g_str_6153518d03385c0016b83538]

    -- Sumero-Akkadian militia spearmen - Light Spear
    g_models[g_str_68c995d357916300158884d3] = g_models[g_str_68c995d25791630015888368]

    -- Markhashian bowmen - Bow Levy
    g_models[g_str_68c995d357916300158884d6] = g_models[g_str_68c995d25791630015888375]

    -- Melukhkhan elite bowmen - Archers General
    g_models[g_str_68c995d357916300158884da_general] = g_models[g_str_68c995d257916300158883d8_general]
    
    -- Melukhkhan elite bowmen - Archers
    g_models[g_str_68c995d357916300158884da] = g_models[g_str_6153518d03385c0016b834eb]

    -- Makkanite close-combat fighters - Raiders General
    g_models[g_str_68c995d357916300158884dd_general] = g_models[g_str_68c995d257916300158883fb_general]

    -- Makkanite close-combat fighters - Raiders
    g_models[g_str_68c995d357916300158884dd] = g_models[g_str_68c995d2579163001588832d]

    -- Guti Camp
    g_models[g_str_5fb1b9d9e1af060017709321_camp] = g_models[g_str_5fb1b9d8e1af0600177092b9_camp]

    -- Guti Camp
    g_models[g_str_5fb1b9d9e1af060017709321_camp_pack_train] = g_models[g_str_5fb1b9e1e1af060017709849_camp_pack_train]

    -- Household speamen - Pikes
    g_models[g_str_6153518d03385c0016b834a5] = g_models[g_str_68c995d25791630015888367]

    -- Household speamen - Light Spear
    g_models[g_str_6153518d03385c0016b834a6] = g_models[g_str_68c995d25791630015888368]

    -- Militia spearmen - Pikes
    g_models[g_str_6153518d03385c0016b834a9] = g_models[g_str_68c995d2579163001588836e]

    -- Militia spearmen - Pikes
    g_models[g_str_6153518d03385c0016b834ac] = g_models[g_str_68c995d2579163001588836e]

    -- Militia spearmen - Light Spear
    g_models[g_str_6153518d03385c0016b834ad] = g_models[g_str_68c995d25791630015888368]

    -- Nomadic and levy bowmen - Skirmishers
    g_models[g_str_6153518d03385c0016b834af] = g_models[g_str_68c995d2579163001588837b]

    -- Nomadic and levy javelinmen - Rabble
    g_models[g_str_6153518d03385c0016b834b1] = g_models[g_str_68c995d2579163001588837d]

    -- Nomadic and levy slingers - Skirmishers
    g_models[g_str_6153518d03385c0016b834b3] = g_models[g_str_68c995d2579163001588837f]

-- Early Bronze Age Highlanders
-- 3000 BC to 950 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9d9e1af060017709327/explore
-- As of: 20230202

    -- Bodyguards - Raiders General
    g_models[g_str_68c995d357916300158884ef_general] = g_models[g_str_68c995d25791630015888319_general]

    -- Bodyguards - Raiders
    g_models[g_str_68c995d357916300158884ef] = g_models[g_str_68c995d25791630015888319]

    -- Bodyguards - Archers General
    g_models[g_str_68c995d357916300158884f0_general] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_sumerian_skirmisher_archer',
          [2] = 'troop_sumerian_infantry_general',
          [3] = 'troop_sumerian_infantry_standard',
          [4] = 'troop_sumerian_skirmisher_archer'
        }
      }
    }
    
    -- Bodyguards - Archers
    g_models[g_str_68c995d357916300158884f0] = g_models[g_str_68c995d25791630015888422]

    -- Unshielded javelinmen - Rabble
    g_models[g_str_68c995d357916300158884f2] = g_models[g_str_6153518d03385c0016b83540]

    -- Javelinmen with shields - Light Foot
    g_models[g_str_68c995d357916300158884f5] = g_models[g_str_68c995d25791630015888330]

    -- Bowmen - Bow Levy
    g_models[g_str_68c995d357916300158884f7] = g_models[g_str_68c995d25791630015888375]

    -- Slingers - Skirmishers
    g_models[g_str_68c995d357916300158884fa] = g_models[g_str_6153518d03385c0016b834e8]

    -- Guti Camp
    g_models[g_str_5fb1b9d9e1af060017709327_camp] = g_models[g_str_5fb1b9d8e1af0600177092b9_camp]

    -- Guti Camp
    g_models[g_str_5fb1b9d9e1af060017709327_camp_pack_train] = g_models[g_str_5fb1b9e1e1af060017709849_camp_pack_train]

-- Early Syrian
-- 2700 BC to 2200 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9d9e1af06001770932f/explore
-- As of: 20230202

    -- 4-wheeled battle cars - Chariots General
    g_models[g_str_68c995d35791630015888500_general] = g_models[g_str_68c995d2579163001588832b_general]

    -- 4-wheeled battle cars - Chariots
    g_models[g_str_68c995d35791630015888500] = g_models[g_str_68c995d2579163001588832b]

    -- Spearmen - Pikes General
    g_models[g_str_68c995d35791630015888502_general] = g_models[g_str_68c995d25791630015888355_general]

    -- Household and militia speamen - Pikes
    g_models[g_str_68c995d35791630015888502] = g_models[g_str_68c995d25791630015888338]

    -- Axemen - Raiders General
    g_models[g_str_68c995d35791630015888504_general] = g_models[g_str_68c995d257916300158883fb_general]

    -- Axemen - Raiders
    g_models[g_str_68c995d35791630015888504] = g_models[g_str_68c995d257916300158883fb]

    -- Household bowmen - Bow Levy
    g_models[g_str_68c995d35791630015888506] = g_models[g_str_68c995d25791630015888335]

    -- Slingers - Skirmishers
    g_models[g_str_68c995d35791630015888509] = g_models[g_str_6153518d03385c0016b834e8]

    -- Levy or militia bowmen - Bow Levy
    g_models[g_str_68c995d3579163001588850b] = g_models[g_str_6153518d03385c0016b8353c]

    -- Unshielded javelinmen - Rabble
    g_models[g_str_68c995d3579163001588850e] = g_models[g_str_68c995d2579163001588833a]

    -- Javelinmen, some with shields - Rabble
    g_models[g_str_68c995d35791630015888510] = g_models[g_str_68c995d2579163001588833a]

    -- Javelinmen, some with shields - Light Foot
    g_models[g_str_68c995d35791630015888511] = g_models[g_str_68c995d25791630015888330]

    -- Syrian Camp
    g_models[g_str_5fb1b9d9e1af06001770932f_camp] = g_models[g_str_5fb1b9dce1af06001770959d_camp]
    
    -- Syrian Camp
    g_models[g_str_5fb1b9d9e1af06001770932f_camp_pack_train] = g_models[g_str_5fb1b9e1e1af060017709849_camp_pack_train]

-- Later Amorite
-- 1894 BC to 1595 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9d9e1af06001770935f/explore
-- As of: 20230202

    -- Retinue bowmen, or 4-equid platform cars or 2-horse chariot - Chariots General
    g_models[g_str_68c995d35791630015888599_general] = {
      {
        n_models = 1,
        random_models = {
          'troop_sumerian_chariot_general',
          'troop_sumerian_light_chariot_general'
        }
      }
    }

    -- Retinue bowmen, or 4-equid platform cars or 2-horse chariot - Chariots General
    g_models[g_str_68c995d35791630015888599] = {
      {
        n_models = 1,
        random_models = {
          'troop_sumerian_chariot',
          'troop_sumerian_light_chariot'
        }
      }
    }

    -- Retinue bowmen, or 4-equid platform cars or 2-horse chariot - Archers General
    g_models[g_str_68c995d3579163001588859a_general] = g_models[g_str_68c995d257916300158883f9_general]
    
    -- Retinue bowmen, or 4-equid platform cars or 2-horse chariot - Archers
    g_models[g_str_68c995d3579163001588859a] = g_models[g_str_68c995d25791630015888422]

    -- Retinue armed with axe or sickle-sword - Raiders
    g_models[g_str_68c995d3579163001588859c] = {
      {
        model_data = 'troop_sumerian_amorite_warrior'
      }
    }

    -- Sabum qallatum, some with shield - Light Foot
    g_models[g_str_68c995d3579163001588859e] = g_models[g_str_6153518e03385c0016b83568]

    -- Unshielded javelinmen - Rabble
    g_models[g_str_68c995d3579163001588859f] = g_models[g_str_68c995d2579163001588833a]

    -- Sabum qallatum armed with bow or sling - Skirmishers
    g_models[g_str_68c995d357916300158885a1] = g_models[g_str_68c995d2579163001588833c]

    -- Household bowmen - Bow Levy
    g_models[g_str_68c995d3579163001588859f] = g_models[g_str_68c995d25791630015888335]

    -- Slingers - Skirmishers
    g_models[g_str_68c995d357916300158885a1] = g_models[g_str_6153518d03385c0016b834e8]

    -- Levies and emergency reserves - Horde
    g_models[g_str_68c995d357916300158885a3] = g_models[g_str_68c995d2579163001588835b]

    -- Nomadic levies - Rabble
    g_models[g_str_68c995d357916300158885a5] = g_models[g_str_68c995d2579163001588833a]

    -- Nomadic and levy slingers and skirmishing bowmen - Skirmishers
    g_models[g_str_68c995d357916300158885a7] = g_models[g_str_68c995d2579163001588833c]

    -- Later Amorite Camp
    g_models[g_str_5fb1b9d9e1af06001770935f_camp] = g_models[g_str_5fb1b9d8e1af0600177092b9_camp]
    
    -- Later Amorite
    g_models[g_str_5fb1b9d9e1af06001770935f_camp_fortified] = g_models[g_str_5fb1b9dce1af06001770959d_camp_fortified]
    
    -- Later Amorite
    g_models[g_str_5fb1b9d9e1af06001770935f_camp_pack_train] = g_models[g_str_5fb1b9e1e1af060017709849_camp_pack_train]

