-- West Frankish
army['5fb1b9e4e1af060017709a53'].data.has_models = true
army['5fb1b9e4e1af060017709a53'].data.base = "tile_grass"
-- Duke William's Norman Invasion
army['5fb1b9e4e1af060017709a59'].data.has_models = true
army['5fb1b9e4e1af060017709a59'].data.base = "tile_grass"
-- Anglo-Norman
army['5fb1b9e5e1af060017709b08'].data.has_models = true
army['5fb1b9e5e1af060017709b08'].data.base = "tile_grass"

-- West Frankish
-- 888 AD to 1072 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e4e1af060017709a53/explore
-- As of: 20210418

    -- Milites - Kn General
    g_models[g_str_68c995dd5791630015889fa7_general] = {
      {
        n_models = 3,
        fixed_models = {
            [1] = 'troop_norman_knight_lance_pennat',
            [2] = 'troop_norman_knight_sword',
            [3] = 'troop_frank_knight_flag'
        }
      }
    }

    -- Milites\nDeployment dismounted from Knights General - EF General
    g_models[g_str_68c995dd5791630015889fa7_general_dismounted] = {
      {
        n_models = 4,
        fixed_models = {
            [1] = 'troop_norman_armor_foot_sword',
            [2] = 'troop_norman_armor_foot_sword',
            [3] = 'troop_frank_armor_foot_flag',
            [4] = 'troop_norman_armor_foot_sword'
        }
      }
    }

    -- Milites\nDeployment dismounting as Elite Foot - Kn General
    g_models[g_str_68c995dd5791630015889fa7_general_mounted] = {
      {
        n_models = 3,
        fixed_models = {
            [1] = 'troop_norman_knight_lance_pennat',
            [2] = 'troop_norman_knight_sword',
            [3] = 'troop_frank_knight_flag'
        }
      }
    }

    -- Milites - Kn
    g_models[g_str_68c995dd5791630015889fa7] = {
      {
        model_data = 'troop_norman_milite_mounted'
      }
    }

    -- Milites\nDeployment dismounted from Knights - EF
    g_models[g_str_68c995dd5791630015889fa7_dismounted] = {
      {
        model_data = 'troop_norman_armor_foot_sword'
      }
    }

    -- Milites\nDeployment dismounting as Elite Foot - Kn
    g_models[g_str_68c995dd5791630015889fa7_mounted] = {
      {
        model_data = 'troop_norman_milite_mounted'
      }
    }

    -- Milites - Kn General
    g_models[g_str_68c995dd5791630015889faa_general] = g_models[g_str_68c995dd5791630015889fa7_general]

    -- Milites - Kn
    g_models[g_str_68c995dd5791630015889faa] = g_models[g_str_68c995dd5791630015889fa7]

    -- Milites who removed their armor to scout - JavCav
    g_models[g_str_68c995dd5791630015889fab] = {
      {
        model_data = 'troop_norman_lightcav',
        loose = true
      }
    }

    -- Pedites - HF
    g_models[g_str_68c995dd5791630015889fad] = {
      {
        model_data = 'troop_norman_levy_shield'
      }
    }

    -- Mercenary spearmen - Spears
    g_models[g_str_68c995dd5791630015889faf] = {
      {
        model_data = 'troop_norman_pikemen'
      }
    }

    -- Massed levy bowmen - Bow Levy
    g_models[g_str_68c995dd5791630015889fb1] = {
      {
        model_data = 'troop_norman_archer'
      }
    }

    -- Crossbowmen or staff slingers - Archers
    g_models[g_str_68c995dd5791630015889fb4] = {
      {
        model_data = 'troop_norman_crossbow'
      }
    }

    -- Crossbowmen or staff slingers - Sk
    g_models[g_str_68c995dd5791630015889fb5] = {
      {
        model_data = 'troop_norman_crossbow'
      }
    }

    -- Cottereaux - LF
    g_models[g_str_68c995dd5791630015889fb7] = {
      {
        model_data = 'troop_norman_levy'
      }
    }
    -- THIS HAS TO BE CHANGED
    -- Sicilian Greek infantry - LF
    g_models[g_str_68c995dd5791630015889fba] = {
      {
        model_data = 'troop_norman_levy'
      }
    }

    -- Servants, grooms, or peasants - Horde
    g_models[g_str_68c995dd5791630015889fbc] = {
      {
        model_data = 'troop_norman_levy',
        loose = true
      }
    }

    --West Frankish Camp
    g_models[g_str_5fb1b9e4e1af060017709a53_camp] = g_models[g_str_5fb1b9dce1af06001770959d_camp]

    --West Frankish Pack Trains
    g_models[g_str_5fb1b9e4e1af060017709a53_camp_pack_train] = g_models[g_str_5fb1b9e1e1af060017709849_camp_pack_train]


-- Duke William's Norman Invasion
-- 1066 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e4e1af060017709a59/explore
-- As of: 20210418

    -- Milites - Kn General
    g_models[g_str_68c995dd5791630015889fca_general] = {
      {
        n_models = 3,
        fixed_models = {
          [1] = 'troop_norman_knight_lance_pennat',
          [2] = 'troop_norman_knight_sword',
          [3] = 'troop_norman_knight_flag'
        }
      }
    }

    -- Milites\nDeployment dismounted from Knights General - EF General
    g_models[g_str_68c995dd5791630015889fca_general_dismounted] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_norman_armor_foot_sword',
          [2] = 'troop_norman_armor_foot_sword',
          [3] = 'troop_norman_armor_foot_flag',
          [4] = 'troop_norman_armor_foot_sword'
        }
      }
    }

    -- Milites\nDeployment dismounting as Elite Foot - Kn General
    g_models[g_str_68c995dd5791630015889fca_general_mounted] = g_models[g_str_68c995dd5791630015889fca_general]

    -- Milites - Kn
    g_models[g_str_68c995dd5791630015889fca] = g_models[g_str_68c995dd5791630015889fa7]

    -- Milites\nDeployment dismounted from Knights - EF
    g_models[g_str_68c995dd5791630015889fca_dismounted] = g_models[g_str_68c995dd5791630015889fa7_dismounted]

    -- Milites\nDeployment dismounting as Elite Foot - Kn
    g_models[g_str_68c995dd5791630015889fca_mounted] = g_models[g_str_68c995dd5791630015889fca]

    -- Milites\nDeployment dismounted from Knights - EF
    g_models[g_str_68c995dd5791630015889fcd] = g_models[g_str_68c995dd5791630015889fca_dismounted]

    -- Milites - Kn General
    g_models[g_str_68c995dd5791630015889fcf_general] = g_models[g_str_68c995dd5791630015889fca_general]

    -- Milites - Kn
    g_models[g_str_68c995dd5791630015889fcf] = g_models[g_str_68c995dd5791630015889fca]

    -- Milites who removed their armor to scout - JavCav
    g_models[g_str_68c995dd5791630015889fd0] = g_models[g_str_68c995dd5791630015889fab]

    --THIS HAS TO BE CHANGED
    -- Breton horsemen - JavCav
    g_models[g_str_68c995dd5791630015889fd2] = g_models[g_str_68c995dd5791630015889fab]

    -- Pedites - HF
    g_models[g_str_68c995dd5791630015889fd4] = g_models[g_str_68c995dd5791630015889fad]

    -- Mercenary spearmen - Spears
    g_models[g_str_68c995dd5791630015889fd6] = g_models[g_str_68c995dd5791630015889faf]

    -- Massed levy bowmen - Bow Levy
    g_models[g_str_68c995dd5791630015889fd8] = g_models[g_str_68c995dd5791630015889fb1]

    -- Crossbowmen or staff slingers - Sk
    g_models[g_str_68c995dd5791630015889fdb] = g_models[g_str_68c995dd5791630015889fb5]

    -- Servants, grooms, or peasants - Horde
    g_models[g_str_68c995dd5791630015889fdd] = g_models[g_str_68c995dd5791630015889fbc]

    --West Frankish Camp
    g_models[g_str_5fb1b9e4e1af060017709a59_camp] = g_models[g_str_5fb1b9dce1af06001770959d_camp]

-- Anglo-Norman
-- 1072 AD to 1180 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e5e1af060017709b08/explore
-- As of: 20230109

    -- Men-at-arms and mounted sergeants - Kn General
    g_models[g_str_68c995de579163001588a25f_general] = g_models[g_str_68c995dd5791630015889fca_general]

    -- Men-at-arms and mounted sergeants\nDeployment dismounted from Knights General - EF General
    g_models[g_str_68c995de579163001588a25f_general_dismounted] = g_models[g_str_68c995dd5791630015889fca_general_dismounted]

    -- Men-at-arms and mounted sergeants\nDeployment dismounting as Elite Foot - Kn General
    g_models[g_str_68c995de579163001588a25f_general_mounted] = g_models[g_str_68c995de579163001588a25f_general]

    -- Men-at-arms and mounted sergeants - Kn
    g_models[g_str_68c995de579163001588a25f] = g_models[g_str_68c995dd5791630015889fca]

    -- Men-at-arms and mounted sergeants\nDeployment dismounted from Knights - EF
    g_models[g_str_68c995de579163001588a25f_dismounted] = g_models[g_str_68c995dd5791630015889fca_dismounted]

    -- Men-at-arms and mounted sergeants\nDeployment dismounting as Elite Foot - Kn
    g_models[g_str_68c995de579163001588a25f_mounted] = g_models[g_str_68c995de579163001588a25f]

    -- Sergeants, town militia, fyrd, and mercenaries - HF
    g_models[g_str_68c995de579163001588a262] = {
      {
        random_models = {
          'troop_norman_armor_foot_sword',
          'troop_norman_spear',
          'troop_norman_levy_shield'
        }
      }
    }

    -- Bowmen - Bow Levy
    g_models[g_str_68c995de579163001588a265] = g_models[g_str_68c995dd5791630015889fd8]

    -- Welsh bowmen - Archers
    g_models[g_str_68c995de579163001588a26a] = {
      {
        model_data = 'troop_norman_archer'
      }
    }

    -- Genoese or other mercenary crossbowmen - Archers
    g_models[g_str_68c995de579163001588a26d] = {
      {
        model_data = 'troop_norman_archer'
      }
    }

    -- Flemish mercenary pikemen - Pikes
    g_models[g_str_68c995de579163001588a270] = {
      {
        model_data = 'troop_norman_pikemen'
      }
    }

    --Anglo-Norman Camp
    g_models[g_str_5fb1b9e5e1af060017709b08_camp] = g_models[g_str_5fb1b9e4e1af060017709a59_camp]

    --Anglo-Norman Standard Wagon
    g_models[g_str_5fb1b9e5e1af060017709b08_camp_standard_wagon] = {
      {
        base = 'tile_grass_80x40',
        n_models = 1,
        model_data = 'troop_anglonorman_wagon'
      }
    }

    -- Muntatores - Jav Cav
    g_models[g_str_6153519603385c0016b83fea] = g_models[g_str_68c995dd5791630015889fd0] 

    -- Marcher Welshry - Light Foot
    g_models[g_str_6153519603385c0016b83fec] = {
      {
        random_models = {
          'troop_norman_levy',
          'troop_norman_levy_shield'
        }
      }
    }