-- Classical Indian
army['5fb1b9e0e1af06001770979e'].data.has_models = true
army['5fb1b9e0e1af06001770979e'].data.base="tile_grass"
-- Republican Indian
army['5fb1b9e0e1af0600177097b1'].data.has_models = true
army['5fb1b9e0e1af0600177097b1'].data.base="tile_grass"
-- Mountain Indian
army['5fb1b9e0e1af0600177097b8'].data.has_models = true
army['5fb1b9e0e1af0600177097b8'].data.base="tile_grass"

-- Classical Indian
-- 500 BC to 320 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e0e1af06001770979e/explore
-- As of: 20230116

    -- War elephants - Elephants General
    g_models[g_str_68c995d95791630015889664_general] = {
      {
        n_models = 1,
        model_data = 'troop_indian_el_general'
      }
    }

    -- War elephants - Elephants
    g_models[g_str_68c995d95791630015889664] = {
      {
        n_models = 1,
        model_data = 'troop_indian_el'
      }
    }

    -- 4-horse chariots with three crew - Chariots
    g_models[g_str_68c995d95791630015889668] = {
      {
        n_models = 1,
        model_data = 'troop_indian_hch'
      }
    }

    -- Chariots gradually being abandoned in favor of horsemen - Chariots
    g_models[g_str_68c995d9579163001588966b] = g_models[g_str_68c995d95791630015889668]


    -- Chariots gradually being abandoned in favor of horsemen - Bad Horse
    g_models[g_str_68c995d9579163001588966c] = {
      {
        model_data = 'troop_indian_cavalry'
      }
    }

    -- Horsemen - Bad Horse
    g_models[g_str_68c995d9579163001588966e] = g_models[g_str_68c995d9579163001588966c]

    -- Hereditary and mercenary bowmen - Bow Levy
    g_models[g_str_68c995d95791630015889670] = {
      {
        loose = true,
        model_data = 'troop_indian_bow'
      }
    }

    -- Hereditary and mercenary javelinmen - Heavy Foot
    g_models[g_str_68c995d95791630015889673] = {
      {
        model_data = 'troop_indian_auxilia'
      }
    }

    -- Hereditary and mercenary javelinmen\nPlaustrella - Heavy Foot
    g_models[g_str_68c995d95791630015889673_plaustrella] = g_models[g_str_68c995d95791630015889673]

    -- Hereditary and mercenary javelinmen\nElephant Screen - Heavy Foot
    g_models[g_str_68c995d95791630015889673_elephant_screen] = g_models[g_str_68c995d95791630015889673]
  
    -- Poor quality infantry - Horde
    g_models[g_str_68c995d95791630015889677] = {
      {
        loose = true,
        model_data = 'troop_indian_sp'
      }
    }

    -- Poor quality infantry - Horde
    g_models[g_str_68c995d95791630015889677_elephant_screen] = g_models[g_str_68c995d95791630015889677]

    -- Wild tribe bowmen - Skirmishers
    g_models[g_str_68c995d9579163001588967b] = {
      {
        loose = true,
        model_data = 'troop_indian_ps'
      }
    }

    -- Wild tribe bowmen - Rabble
    g_models[g_str_68c995d9579163001588967c] = {
      {
        loose = true,
        model_data = 'troop_indian_ps'
      }
    }

    -- Classical Indian Camp
    g_models[g_str_5fb1b9e0e1af06001770979e_camp] = {
      {
        n_models = 1,
        model_data = 'troop_indian_ganesh'
      }
    }
    -- Classical Indian Camp
    g_models[g_str_5fb1b9e0e1af06001770979e_camp_fortified] = {
      {
        overlay_models = { -- each of the models are placed on top of the base
          {
            model_data="troop_fortified_camp_outline_40x40",
            position={x=-0,y=0,z=0}, -- optional defaults to (0,0,0)
            rotation=0, -- optional defaults to 0
            scale=1, -- optional defaults t0 1
          },
          {
            model_data = 'troop_indian_ganesh',
            scale=0.7
          }
        }
      }
    }

    -- Classical Indian Camp
    g_models[g_str_5fb1b9e0e1af06001770979e_camp_pack_train] = g_models[g_str_5fb1b9e1e1af060017709849_camp_pack_train]

    -- Horsemen - Bad Horse
    g_models[g_str_6153519303385c0016b83c1c] = g_models[g_str_68c995d9579163001588966c]
  
    -- Citizen bowmen - Bow Levy
    g_models[g_str_6153519303385c0016b83c1e] = g_models[g_str_68c995d95791630015889670]

    -- Javelinmen - Heavy Foot
    g_models[g_str_6153519303385c0016b83c20] = g_models[g_str_68c995d95791630015889673]

-- Republican Indian
-- 500 BC to 321 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e0e1af0600177097b1/explore
-- As of: 20230116

    -- War elephants - Elephants General
    g_models[g_str_68c995d957916300158896a2_general] = g_models[g_str_68c995d95791630015889664_general]

    -- War elephants - Elephants
    g_models[g_str_68c995d957916300158896a2] = g_models[g_str_68c995d95791630015889664]

    -- 4-horse chariots with three crew - Chariots General
    g_models[g_str_68c995d957916300158896a5_general] = {
      {
        n_models = 1,
        model_data = 'troop_indian_hch_general'
      }
    }

    -- 4-horse chariots with three crew\nDeployment dismounted from Chariots General - Raider General
    g_models[g_str_68c995d957916300158896a5_general_dismounted] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_indian_maiden_guard',
          [2] = 'troop_indian_leader',
          [3] = 'troop_indian_maiden_guard',
          [4] = 'troop_indian_maiden_guard',
        }
      }
    }

    -- 4-horse chariots with three crew\nDeployment dismounting as Raider - Chariots General
    g_models[g_str_68c995d957916300158896a5_general_mounted] = g_models[g_str_68c995d957916300158896a5_general]

    -- 4-horse chariots with three crew - Chariots
    g_models[g_str_68c995d957916300158896a5] = g_models[g_str_68c995d95791630015889668]

    -- 4-horse chariots with three crew\nDeployment dismounted from Chariots General - Raider General
    g_models[g_str_68c995d957916300158896a5_dismounted] = g_models[g_str_68c995d957916300158896a5_general_dismounted]

    -- 4-horse chariots with three crew\nDeployment dismounting as Raider - Chariots General
    g_models[g_str_68c995d957916300158896a5_mounted] = g_models[g_str_68c995d95791630015889668]

    -- Horsemen - Bad Horse
    g_models[g_str_68c995d957916300158896a8] = g_models[g_str_68c995d9579163001588966c]

    -- Citizen bowmen - Bow Levy
    g_models[g_str_68c995d957916300158896aa] = g_models[g_str_68c995d95791630015889670]

    -- Javelinmen - Heavy Foot General
    g_models[g_str_68c995d957916300158896ad_general] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_indian_maiden_guard',
          [2] = 'troop_indian_leader',
          [3] = 'troop_indian_maiden_guard',
          [4] = 'troop_indian_maiden_guard',
        }
      }
    }
    -- Javelinmen\nElephant Screen - Heavy Foot General
    g_models[g_str_68c995d957916300158896ad_general_elephant_screen] ={
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_indian_maiden_guard',
          [2] = 'troop_indian_maiden_guard',
          [3] = 'troop_indian_leader',
          [4] = 'troop_indian_maiden_guard',
        }
      }
    }

    -- Javelinmen - Heavy Foot
    g_models[g_str_68c995d957916300158896ad] = g_models[g_str_68c995d95791630015889673]

    -- Javelinmen\nElephant Screen - Heavy Foot
    g_models[g_str_68c995d957916300158896ad_elephant_screen] = g_models[g_str_68c995d95791630015889673]

    -- Classical Indian Camp
    g_models[g_str_5fb1b9e0e1af0600177097b1_camp] = g_models[g_str_5fb1b9e0e1af06001770979e_camp] 


-- Mountain Indian
-- 500 BC to 170 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e0e1af0600177097b8/explore
-- As of: 20230116

    -- War elephants - Elephants General
    g_models[g_str_68c995d957916300158896b5_general] = g_models[g_str_68c995d95791630015889664_general]

    -- War elephants - Elephants
    g_models[g_str_68c995d957916300158896b5] = g_models[g_str_68c995d95791630015889664]

    -- Light horsemen - Jav Cav General
    g_models[g_str_68c995d957916300158896b8_general] = {
      {
        n_models = 2,
        fixed_models = {
          [1] = 'troop_indian_light_cavalry',
          [2] = 'troop_indian_cavalry'
        }
      }
    }

    -- Light horsemen - Jav Cav
    g_models[g_str_68c995d957916300158896b8] = {
      {
        model_data = 'troop_indian_light_cavalry'
      }
    }

    -- Spearmen with long spears - Light Spear General
    g_models[g_str_68c995d957916300158896ba_general] = {
      {
        n_models = 3,
        fixed_models = {
          [1] = 'troop_indian_pk',
          [2] = 'troop_indian_leader',
          [3] = 'troop_indian_pk'
        }
      }
    }

    -- Spearmen with long spears - Light Spear
    g_models[g_str_68c995d957916300158896ba] = {
      {
        model_data = 'troop_indian_pk'
      }
    }

    -- Spearmen with short spears - Light Foot
    g_models[g_str_68c995d957916300158896bc] = {
      {
        model_data = 'troop_indian_sp'
      }
    }

    -- Bowmen - Skirmishers
    g_models[g_str_68c995d957916300158896be] = g_models[g_str_68c995d9579163001588967b]
    
    -- Bowmen - Bow Levy
    g_models[g_str_68c995d957916300158896bf] = {
      {
        loose = true,
        n_models = 3,
        random_models = {
          'troop_indian_ps',
          'troop_indian_bow',
        }
       }
    }

    -- Bowmen - Archers
    g_models[g_str_68c995d957916300158896c0] = {
      {
        model_data = 'troop_indian_bow'
      }
    }

    -- Javelinmen - Heavy Foot
    g_models[g_str_68c995d957916300158896c3] = g_models[g_str_68c995d95791630015889673]

    -- Javelinmen - Heavy Foot
    g_models[g_str_68c995d957916300158896c3_elephant_screen] = g_models[g_str_68c995d95791630015889673]

    -- Classical Indian Camp
    g_models[g_str_5fb1b9e0e1af0600177097b8_camp] = g_models[g_str_5fb1b9e0e1af06001770979e_camp] 