-- Iberians
army['5fb1b9dce1af0600177095ab'].data.has_models = true
army['5fb1b9dce1af0600177095ab'].data.base = "tile_grass"
-- Celtiberians
army['5fb1b9dce1af0600177095b2'].data.has_models = true
army['5fb1b9dce1af0600177095b2'].data.base = "tile_grass"

-- Iberians
-- 240 to 20BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9dce1af0600177095ab/explore
-- As of: 20210407

    -- JavCav General
    g_models[g_str_68c995d75791630015888e7d_general] = {
      {
        n_models = 2,
        fixed_models = {
          [1] = 'troop_ancient_spanish_bearer',
          [2] = 'troop_ancient_spanish_general'
        }
      }
    }
    g_models[g_str_68c995d75791630015888e7d_general_mounted] = g_models[g_str_68c995d75791630015888e7d_general]

    -- Caetrati -  Light Foot General as dismounted javcav
    g_models[g_str_68c995d75791630015888e7d_general_dismounted] = {
      {
        n_models = 3,
        fixed_models = {
          [1] = 'troop_ancient_spanish_scutarii_banner',
          [2] = 'troop_ancient_spanish_scutarii_chief',
          [3] = 'troop_ancient_spanish_scutarii_musician'
      }
      }
    }

    -- JavCav
    g_models[g_str_68c995d75791630015888e7d] = {
      {
        model_data = 'troop_ancient_spanish_lh'
      }
    }
    g_models[g_str_68c995d75791630015888e7d_mounted] = g_models[g_str_68c995d75791630015888e7d]

    -- Caetrati -  Light Foot as dismounted javcav
    g_models[g_str_68c995d75791630015888e7d_dismounted] = {
      {
        model_data = 'troop_ancient_spanish_caetrati'
      }
    }

    -- Scutarii - Light Foot
    g_models[g_str_68c995d75791630015888e80] = {
      {
        model_data = 'troop_ancient_spanish_scutarii'
      }
    }

    -- Caetrati - Light Foot
    g_models[g_str_68c995d75791630015888e82] = g_models[g_str_68c995d75791630015888e7d_dismounted]

    -- Skirmishing Slingers
    g_models[g_str_68c995d75791630015888e84] = {
      {
        model_data = 'troop_ancient_spanish_slingers',
        loose = true
      }
    }

    -- Mercenaries Celtiberian Scutarii - Raiders
    g_models[g_str_68c995d75791630015888e86] = {
      {
        model_data = 'troop_ancient_spanish_scutarii'
      }
    }

    --Ancient Spanish Camp
    g_models[g_str_5fb1b9dce1af0600177095ab_camp] = {
      {
        n_models = 1,
        model_data = 'troop_ancient_spanish_camp'
      }
    }

    --Ancient Spanish Camp Pack Train
    g_models[g_str_5fb1b9dce1af0600177095ab_camp_pack_train] = g_models[g_str_5fb1b9e1e1af060017709849_camp_pack_train]

-- Celtiberians
-- 240 to 20BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9dce1af0600177095b2/explore
-- As of: 20210407

    -- JavCav General
    g_models[g_str_68c995d75791630015888e8d_general] = g_models[g_str_68c995d75791630015888e7d_general]
    g_models[g_str_68c995d75791630015888e8d_general_mounted] = g_models[g_str_68c995d75791630015888e7d_general]

    -- Scutarii -  Raider General as dismounted javcav
    g_models[g_str_68c995d75791630015888e8d_general_dismounted] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_ancient_spanish_scutarii_banner',
          [2] = 'troop_ancient_spanish_scutarii_chief',
          [3] = 'troop_ancient_spanish_scutarii_musician',
          [4] = 'troop_ancient_spanish_scutarii_variant',
        }
      }
    }

    -- JavCav
    g_models[g_str_68c995d75791630015888e8d] = g_models[g_str_68c995d75791630015888e7d]
    g_models[g_str_68c995d75791630015888e8d_mounted] = g_models[g_str_68c995d75791630015888e7d]

    -- Scutarii -  Raider as dismounted javcav
    g_models[g_str_68c995d75791630015888e8d_dismounted] = g_models[g_str_68c995d75791630015888e80]

    -- Scutarii -  Raider
    g_models[g_str_68c995d75791630015888e90] = g_models[g_str_68c995d75791630015888e80]

    -- Caetrati - Light Foot
    g_models[g_str_68c995d75791630015888e92] = g_models[g_str_68c995d75791630015888e7d_dismounted]

    -- Skirmishing Slingers
    g_models[g_str_68c995d75791630015888e94] = g_models[g_str_68c995d75791630015888e84]

    --Celtiberians Camp
    g_models[g_str_5fb1b9dce1af0600177095b2_camp] = g_models[g_str_5fb1b9dce1af0600177095ab_camp]

    --Celtiberians Camp Pack Train
    g_models[g_str_5fb1b9dce1af0600177095b2_camp_pack_train] = g_models[g_str_5fb1b9dce1af0600177095ab_camp_pack_train]
