require("Triumph_TTS/scripts/data/data_troops_greek_successors")

-- Rise of Macedon
army['5fb1b9dde1af06001770961d'].data.has_models = true
army['5fb1b9dde1af06001770961d'].data.base = "tile_grass"


  -- Rise of Macedon
  -- 359 BC to 336 BC
  -- https://meshwesh.wgcwar.com/armyList/5fb1b9dde1af06001770961d/explore
  -- As of: 20210411

    --Companions - Kn General
    g_models[g_str_68c995d75791630015889051_general] = {
      {
        n_models = 3,
        loose = true,
        fixed_models = {
            [1] = 'troop_successors_cavalry_bodyguard',
            [2] = 'troop_successors_cavalry_general_yellow',
            [3] = 'troop_successors_cavalry_bodyguard'
        }
      }
    }

    --Companions - Kn
    g_models[g_str_68c995d75791630015889051] = {
      loose = true,
      {
        model_data = 'troop_successors_cavalry_bodyguard'
      }
    }

    --Prodomoi - JavCav
    g_models[g_str_68c995d75791630015889053] = {
      loose = true,
      {
        model_data = 'troop_successors_cav'
      }
    }

    --Thessalian Horsemen - JavCav
    g_models[g_str_68c995d75791630015889055] = {
      {
        model_data = 'troop_thracian_cv'
      },
      loose = true,
    }

    --Hypaspists - Raiders
    g_models[g_str_68c995d75791630015889057] = {
      loose = true,
      {
        model_data = 'troop_successors_hypaspist_black'
      }
    }

    --Hypaspists - Pikes General
    g_models[g_str_68c995d75791630015889058_general] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_successors_pike1_black',
          [2] = 'troop_successors_pike2_black',
          [3] = 'troop_successors_cavalry_general',
          [4] = 'troop_successors_pike2_black'
      }
      }
    }

    --Hypaspists - Pikes
    g_models[g_str_68c995d75791630015889058] = {
      {
        model_data = 'troop_successors_pike2_black'
      }
    }

    --Phalanx - Pikes General
    g_models[g_str_68c995d7579163001588905b_general] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_successors_pike1',
          [2] = 'troop_successors_pike2',
          [3] = 'troop_successors_cavalry_general',
          [4] = 'troop_successors_pike1'
      }
      }
    }

    --Phalanx - Pikes
    g_models[g_str_68c995d7579163001588905b] = {
      {
        random_models = {
          'troop_successors_pike1',
          'troop_successors_pike2'
        }
      }
    }

    --Macedonian light infantry not yet trained with pike - LF
    g_models[g_str_68c995d7579163001588905e] = {
      {
        model_data = 'troop_successors_ax'
      }
    }

    --Cretan or Macedonian skirmishing bowmen - Sk
    g_models[g_str_68c995d75791630015889060] = {
      {
        model_data = 'troop_successors_skirmishers_archers'
      }
    }

    --Greek allied hoplites - HF
    g_models[g_str_68c995d75791630015889062] = {
      {
        random_models = {
          'troop_successors_spear2',
          'troop_successors_spear1',
          'troop_successors_spear2_black',
          'troop_successors_spear1_black',
          'troop_successors_spear2_red',
          'troop_successors_spear1_red',
          'troop_successors_spear2_blue',
          'troop_successors_spear1_blue',
          'troop_successors_spear2_green',
          'troop_successors_spear1_green',
          'troop_successors_spear2_yellow',
        }
      }
    }

    --Greek mercenary peltasts - LF
    g_models[g_str_68c995d75791630015889066] = {
      loose = true,
      {
        random_models = {
          'troop_successors_psiloi',
          'troop_successors_psiloi_black',
          'troop_successors_psiloi_red',
          'troop_successors_psiloi_blue',
          'troop_successors_psiloi_green'
        }
      }
    }

    --Bolt-shooters - Art
    g_models[g_str_68c995d75791630015889069] = {
      {
        n_models = 1,
        model_data = 'troop_successors_art'
      }
    }

    --Macedonian Camp
    g_models[g_str_5fb1b9dde1af06001770961d_camp] = g_models[g_str_5fb1b9dce1af06001770959d_camp]

    --Macedonian Camp Fort
    g_models[g_str_5fb1b9dde1af06001770961d_camp_fortified] = {
      {
        overlay_models = { -- each of the models are placed on top of the base
          {
            model_data="troop_fortified_camp_outline_40x40",
            position={x=0,y=0,z=0}, -- optional defaults to (0,0,0)
            rotation=0, -- optional defaults to 0
            scale=1, -- optional defaults t0 1
          },
          {
            model_data = 'troop_carthaginian_camp',
            scale=0.75,
          }
        }
      }
    }

    --Macedonian Camp Trains and Herds
    g_models[g_str_5fb1b9dde1af06001770961d_camp_pack_train] = g_models[g_str_5fb1b9e1e1af060017709849_camp_pack_train]

--

-- Alexandrian Macedonian
army['5fb1b9dde1af060017709623'].data.has_models = true
army['5fb1b9dde1af060017709623'].data.base = "tile_grass"
  -- Alexandrian Macedonian
  -- 335 BC to 319 BC
  -- https://meshwesh.wgcwar.com/armyList/5fb1b9dde1af060017709623/explore
  -- As of: 20210412

    --Companions - Kn General
    g_models[g_str_68c995d75791630015889073_general] = g_models[g_str_68c995d75791630015889051_general]

    --Companions - Kn
    g_models[g_str_68c995d75791630015889073] = g_models[g_str_68c995d75791630015889051]

    --Prodomoi - JavCav
    g_models[g_str_68c995d75791630015889075] = g_models[g_str_68c995d75791630015889053]

    --Thessalian Horsemen - JavCav
    g_models[g_str_68c995d75791630015889078] = {
      {
        model_data = 'troop_thracian_cv'
      }
    }
    --Allied or mercenary Greek horsemen - Bad Horse
    g_models[g_str_68c995d7579163001588907a] = {
      {
        n_models = 3,
        fixed_models = {
          [1] = 'troop_successors_cavalry_bodyguard',
          [2] = 'troop_successors_cavalry_general_black',
          [3] = 'troop_successors_cavalry_bodyguard'
      }
      }
    }

    --Thracian or Paionian horsemen - JavCav
    g_models[g_str_68c995d7579163001588907c] = {
      {
        model_data = 'troop_thracian_lh'
      }
    }

    --Hypaspists - Raiders
    g_models[g_str_68c995d7579163001588907f] = g_models[g_str_68c995d75791630015889057]

    --Hypaspists - Pikes
    g_models[g_str_68c995d75791630015889080] = g_models[g_str_68c995d75791630015889058]

    --Phalanx - Pikes
    g_models[g_str_68c995d75791630015889083] = g_models[g_str_68c995d7579163001588905b]

    --Cretan or Macedonian skirmishing bowmen - Sk
    g_models[g_str_68c995d75791630015889085] = g_models[g_str_68c995d75791630015889060]

    --Greek allied hoplites - HF
    g_models[g_str_68c995d75791630015889087] = g_models[g_str_68c995d75791630015889062]

    --Greek mercenary, Thracian, or Agrianian peltasts and javelinmen - LF
    g_models[g_str_68c995d7579163001588908a] = {
      {
        model_data = 'troop_successors_psiloi'
      },
      {
        random_models = {
          'troop_thracian_ax1',
          'troop_thracian_axgen'
        }
      }
    }

    --Bolt-shooters - Art
    g_models[g_str_68c995d7579163001588908c] = g_models[g_str_68c995d75791630015889069]

    --War elephants
    g_models[g_str_68c995d7579163001588908f] = {
        {
          n_models = 1,
          model_data = 'troop_successors_el'
        }
    }

    --Macedonian Camp
    g_models[g_str_5fb1b9dde1af060017709623_camp] = g_models[g_str_5fb1b9dde1af06001770961d_camp]

    --Macedonian Camp Fort
    g_models[g_str_5fb1b9dde1af060017709623_camp_fortified] = g_models[g_str_5fb1b9dde1af06001770961d_camp_fortified]

    --Macedonian Camp Trains and Herds - NOT YET
    g_models[g_str_5fb1b9dde1af060017709623_camp_pack_train] = g_models[g_str_5fb1b9dde1af06001770961d_camp_pack_train]


--
army_dates["5fb1b9dde1af060017709623"]["*Alexander - 335 BC to 329 BC"] ="5fb1b9dde1af060017709623_-335_-329"
army_dates["5fb1b9dde1af060017709623"]["*Antipatros - 321 BC to 319 BC"] ="5fb1b9dde1af060017709623_-321_-319"

-- Diadachoii in Macedon
army['5fb1b9dee1af060017709659'].data.has_models = true
army['5fb1b9dee1af060017709659'].data.base = "tile_grass"
  -- Diadachoii in Macedon
  -- 320 BC to 279 BC
  -- https://meshwesh.wgcwar.com/armyList/5fb1b9dee1af060017709659/explore
  -- As of: 20210412

    --Xystophoroi - Kn General
    g_models[g_str_68c995d8579163001588913b_general] =  {
      {
        n_models = 3,
        fixed_models = {
            [1] = 'troop_successors_cavalry_bodyguard_blue',
            [2] = 'troop_successors_cavalry_general_red',
            [3] = 'troop_successors_cavalry_bodyguard_blue'
        }
      }
    }

    --Xystophoroi - Kn
    g_models[g_str_68c995d8579163001588913b] =  {
      {
        model_data = 'troop_successors_cavalry_bodyguard_blue'
      }
    }

    --Greek mercenary horsemen - JavCav General
    g_models[g_str_68c995d8579163001588913d_general] ={
      loose = true,
      {
        n_models = 2,
        fixed_models = {
          [1] = 'troop_successors_lh_black',
          [2] = 'troop_successors_cavalry_general_red'
      }
      }
    }

    --Greek mercenary horsemen - JavCav
    g_models[g_str_68c995d8579163001588913d] ={
      loose = true,
      {
        random_models = {
          'troop_successors_lh',
          'troop_successors_lh_blue',
          'troop_successors_lh_red',
          'troop_successors_lh_black',
          'troop_successors_lh_yellow',
          'troop_successors_lh_green'
        }
      }
    }

    --Thessalian Horsemen - JavCav General
    g_models[g_str_68c995d85791630015889140_general] = {
      loose = true,
      {
        n_models = 2,
        fixed_models = {
          [1] = 'troop_successors_cavalry_general_red',
          [2] = 'troop_thracian_cv'
      }
      }
    }

    --Thessalian Horsemen - JavCav
    g_models[g_str_68c995d85791630015889140] = g_models[g_str_68c995d75791630015889055]

    --Phalanx - Pikes General
    g_models[g_str_68c995d85791630015889142_general] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_successors_pike1_blue',
          [2] = 'troop_successors_pike2_blue',
          [3] = 'troop_successors_cavalry_general',
          [4] = 'troop_successors_pike1_blue'
      }
      }
    }

    --Phalanx - Pikes
    g_models[g_str_68c995d85791630015889142] = {
      {
        random_models = {
          'troop_successors_pike1_blue',
          'troop_successors_pike2_blue'
        }
      }
    }

    --Mercenary peltasts - LF General
    g_models[g_str_68c995d85791630015889144_general] = {
      {
        n_models = 3,
        fixed_models = {
            [1] = 'troop_successors_psiloi',
            [2] = 'troop_successors_cavalry_general',
            [3] = 'troop_successors_psiloi'
        }
      }
    }

    --Mercenary peltasts - LF
    g_models[g_str_68c995d85791630015889144] = g_models[g_str_68c995d75791630015889066]

    --Thracian, Illyrian, or Paionian light infantry - LF General
    g_models[g_str_68c995d85791630015889146_general] = {
      loose = true,
      {
        n_models = 3,
        fixed_models = {
            [1] = 'troop_thracian_ax1',
            [2] = 'troop_successors_cavalry_general',
            [3] = 'troop_thracian_ax1'
        }
      },
      {
        n_models = 3,
        fixed_models = {
            [1] = 'troop_thracian_axgen',
            [2] = 'troop_successors_cavalry_general',
            [3] = 'troop_thracian_axgen'
        }
      }
    }

    --Thracian, Illyrian, or Paionian light infantry - LF
    g_models[g_str_68c995d85791630015889146] = {
      {
        random_models = {
          'troop_thracian_ax1',
          'troop_thracian_axgen'
        }
      },
      loose = true,
    }

    --Epeirote allied light infantry - LF General
    g_models[g_str_68c995d85791630015889149_general] = {
      loose = true,
      {
        n_models = 3,
        fixed_models = {
            [1] = 'troop_successors_ax_green',
            [2] = 'troop_successors_cavalry_general',
            [3] = 'troop_successors_ax_red'
        }
      },
      {
        n_models = 3,
        fixed_models = {
            [1] = 'troop_successors_cavalry_general',
            [2] = 'troop_successors_ax_blue',
            [3] = 'troop_successors_ax'
        }
      },
      {
        n_models = 3,
        fixed_models = {
            [1] = 'troop_successors_ax_black',
            [2] = 'troop_successors_ax',
            [3] = 'troop_successors_cavalry_general'
        }
      }
    }

    --Epeirote allied light infantry - LF
    g_models[g_str_68c995d85791630015889149] = {
      {
        random_models = {
          'troop_successors_ax_red',
          'troop_successors_ax_blue',
          'troop_successors_ax_green',
          'troop_successors_ax_black',
          'troop_successors_ax',
        }
      },
      loose = true,
    }

    --Greek subject hoplites - HF
    g_models[g_str_68c995d8579163001588914c] = g_models[g_str_68c995d75791630015889062]

    --Cretan or Macedonian skirmishing bowmen - Sk
    g_models[g_str_68c995d8579163001588914f] = g_models[g_str_68c995d75791630015889060]

    --War elephants
    g_models[g_str_68c995d85791630015889151_general] = {
      {
        n_models = 1,
        model_data = 'troop_successors_el_red'
      }
    }

    --War elephants
    g_models[g_str_68c995d85791630015889151] = {
        {
          n_models = 1,
          model_data = 'troop_successors_el_blue'
        }
    }

    --Bolt-shooters - Art
    g_models[g_str_68c995d85791630015889153] = g_models[g_str_68c995d75791630015889069]

    --Diadachoii Camp
    g_models[g_str_5fb1b9dee1af060017709659_camp] = g_models[g_str_5fb1b9dde1af06001770961d_camp]

    --Diadachoiin Camp Fort
    g_models[g_str_5fb1b9dee1af060017709659_camp_fortified] = g_models[g_str_5fb1b9dde1af06001770961d_camp_fortified]


--
army_dates["5fb1b9dee1af060017709659"]["*Olympias - 317 BC to 316 BC"] ="5fb1b9dee1af060017709659_Olympias"

    army['5fb1b9dee1af060017709659_Olympias']={
      data={
        name='Diadachoii in Macedon - Olympias - 317 BC to 316 BC',
        id='5fb1b9dee1af060017709659_Olympias',
        army_id='5fb1b9dee1af060017709659',
        base="tile_grass"
      },
      g_base_definitions[g_str_68c995d8579163001588913b_general],
      g_base_definitions[g_str_68c995d8579163001588913b],
      g_base_definitions[g_str_68c995d8579163001588913d_general],
      g_base_definitions[g_str_68c995d8579163001588913d],
      g_base_definitions[g_str_68c995d85791630015889144_general],
      g_base_definitions[g_str_68c995d85791630015889144],
      g_base_definitions[g_str_68c995d85791630015889146_general],
      g_base_definitions[g_str_68c995d85791630015889146],
      g_base_definitions[g_str_68c995d85791630015889149_general],
      g_base_definitions[g_str_68c995d85791630015889149],
      g_base_definitions[g_str_68c995d8579163001588914f],
      g_base_definitions[g_str_68c995d85791630015889151],
      g_base_definitions[g_str_68c995d85791630015889153],
      g_base_definitions[g_str_5fb1b9dee1af060017709659_camp],
      g_base_definitions[g_str_5fb1b9dee1af060017709659_camp_fortified],
    }

army_dates["5fb1b9dee1af060017709659"]["*Kassandros - 318 BC to 302 BC"] ="5fb1b9dee1af060017709659_Kassandros"
    army['5fb1b9dee1af060017709659_Kassandros']={
      data={
        name='Diadachoii in Macedon 315 BC to 302 BC',
        id='5fb1b9dee1af060017709659_Kassandros',
        army_id='5fb1b9dee1af060017709659',
        base="tile_grass"
      },
      g_base_definitions[g_str_68c995d8579163001588913b_general],
      g_base_definitions[g_str_68c995d8579163001588913b],
      g_base_definitions[g_str_68c995d8579163001588913d_general],
      g_base_definitions[g_str_68c995d8579163001588913d],
      g_base_definitions[g_str_68c995d85791630015889140_general],
      g_base_definitions[g_str_68c995d85791630015889140],
      g_base_definitions[g_str_68c995d85791630015889142_general],
      g_base_definitions[g_str_68c995d85791630015889142],
      g_base_definitions[g_str_68c995d85791630015889144_general],
      g_base_definitions[g_str_68c995d85791630015889144],
      g_base_definitions[g_str_68c995d85791630015889146_general],
      g_base_definitions[g_str_68c995d85791630015889146],
      g_base_definitions[g_str_68c995d8579163001588914c],
      g_base_definitions[g_str_68c995d8579163001588914f],
      g_base_definitions[g_str_68c995d85791630015889151],
      g_base_definitions[g_str_68c995d85791630015889153],
      g_base_definitions[g_str_5fb1b9dee1af060017709659_camp],
      g_base_definitions[g_str_5fb1b9dee1af060017709659_camp_fortified],
    }
army_dates["5fb1b9dee1af060017709659"]["*Kassandros - 320, 319 BC & 301 BC to 298 BC"] ="5fb1b9dee1af060017709659_Kassandros_2"
    army['5fb1b9dee1af060017709659_Kassandros_2']={
      data={
        name='Diadachoii in Macedon - *Kassandros - 320, 319 BC & 301 BC to 298 BC',
        id='5fb1b9dee1af060017709659_Kassandros_2',
        army_id='5fb1b9dee1af060017709659',
        base="tile_grass"
      },
      g_base_definitions[g_str_68c995d8579163001588913b_general],
      g_base_definitions[g_str_68c995d8579163001588913b],
      g_base_definitions[g_str_68c995d8579163001588913d_general],
      g_base_definitions[g_str_68c995d8579163001588913d],
      g_base_definitions[g_str_68c995d85791630015889140_general],
      g_base_definitions[g_str_68c995d85791630015889140],
      g_base_definitions[g_str_68c995d85791630015889142_general],
      g_base_definitions[g_str_68c995d85791630015889142],
      g_base_definitions[g_str_68c995d85791630015889144_general],
      g_base_definitions[g_str_68c995d85791630015889144],
      g_base_definitions[g_str_68c995d85791630015889146_general],
      g_base_definitions[g_str_68c995d85791630015889146],
      g_base_definitions[g_str_68c995d8579163001588914f],
      g_base_definitions[g_str_68c995d85791630015889151],
      g_base_definitions[g_str_68c995d85791630015889153],
      g_base_definitions[g_str_5fb1b9dee1af060017709659_camp],
      g_base_definitions[g_str_5fb1b9dee1af060017709659_camp_fortified],
    }

army_dates["5fb1b9dee1af060017709659"]["*Polyperchon - 320 BC to 298 BC"] ="5fb1b9dee1af060017709659_Polyperchon"
    army['5fb1b9dee1af060017709659_Polyperchon']={
      data={
        name='Diadachoii in Macedon - *Polyperchon - 320 BC to 298 BC',
        id='5fb1b9dee1af060017709659_Polyperchon',
        army_id='5fb1b9dee1af060017709659',
        base="tile_grass"
      },
      g_base_definitions[g_str_68c995d8579163001588913b_general],
      g_base_definitions[g_str_68c995d8579163001588913b],
      g_base_definitions[g_str_68c995d8579163001588913d_general],
      g_base_definitions[g_str_68c995d8579163001588913d],
      g_base_definitions[g_str_68c995d85791630015889140_general],
      g_base_definitions[g_str_68c995d85791630015889140],
      g_base_definitions[g_str_68c995d85791630015889142_general],
      g_base_definitions[g_str_68c995d85791630015889142],
      g_base_definitions[g_str_68c995d85791630015889144_general],
      g_base_definitions[g_str_68c995d85791630015889144],
      g_base_definitions[g_str_68c995d85791630015889146_general],
      g_base_definitions[g_str_68c995d85791630015889146],
      g_base_definitions[g_str_68c995d8579163001588914c],
      g_base_definitions[g_str_68c995d8579163001588914f],
      g_base_definitions[g_str_68c995d85791630015889151],
      g_base_definitions[g_str_68c995d85791630015889153],
      g_base_definitions[g_str_5fb1b9dee1af060017709659_camp],
      g_base_definitions[g_str_5fb1b9dee1af060017709659_camp_fortified],
    }
army_dates["5fb1b9dee1af060017709659"]["*Ptolemy - 320 BC to 279 BC"] ="5fb1b9dee1af060017709659_-297_-279"
--

-- Lysimachid
army['5fb1b9dee1af060017709671'].data.has_models = true
army['5fb1b9dee1af060017709671'].data.base = "tile_grass"
  --  Lysimachid
  -- 320 BC to 281 BC
  -- https://meshwesh.wgcwar.com/armyList/5fb1b9dee1af060017709671/explore
  -- As of: 20210412

    --Macedonian charging horsemen - Kn General
    g_models[g_str_68c995d857916300158891b8_general] =  {
      loose = true,
      {
        n_models = 3,
        fixed_models = {
            [1] = 'troop_successors_cavalry_bodyguard_yellow',
            [2] = 'troop_successors_cavalry_general_blue',
            [3] = 'troop_successors_cavalry_bodyguard_yellow'
        }
      }
    }

    --Macedonian charging horsemen - Kn
    g_models[g_str_68c995d857916300158891b8] =  {
      loose = true,
      {
        model_data = 'troop_successors_cavalry_bodyguard_yellow'
      }
    }

    --Paionian, Greek, or Thracian horsemen - JavCav
    g_models[g_str_68c995d857916300158891ba] ={
      loose = true,
      {
        model_data = 'troop_thracian_cv'
      },
      {
        random_models = {
          'troop_successors_lh',
          'troop_successors_lh_blue',
          'troop_successors_lh_red',
          'troop_successors_lh_black',
          'troop_successors_lh_yellow',
          'troop_successors_lh_green'
        }
      },
      {
        model_data = 'troop_thracian_lh'
      }
    }

    --Phalanx - Pikes
    g_models[g_str_68c995d857916300158891bc] = {
      {
        random_models = {
          'troop_successors_pike1_yellow',
          'troop_successors_pike2_yellow'
        }
      }
    }

    --Macedonian Phalanx - Pikes
    g_models[g_str_68c995d857916300158891bf] = g_models[g_str_68c995d7579163001588905b]

    --Mercenary Greek foot - LF
    g_models[g_str_68c995d857916300158891c1] = g_models[g_str_68c995d85791630015889149]

    --Greek coastal city hoplites - HF
    g_models[g_str_68c995d857916300158891c3] = g_models[g_str_68c995d75791630015889062]

    --Mercenary skirmishing bowmen and slingers - Sk
    g_models[g_str_68c995d857916300158891c6] = {
      loose = true,
      {
        random_models = {
          'troop_successors_skirmishers',
          'troop_successors_skirmishers_archers'
        },
        loose = true,
      }
    }
    --Thracian peltasts - LF
    g_models[g_str_68c995d857916300158891c8] = g_models[g_str_68c995d85791630015889146]

    --Illyrian or Paionian javelinmen - LF
    g_models[g_str_68c995d857916300158891ca] = g_models[g_str_68c995d75791630015889066]

    --Captured Antigonid war elephants
    g_models[g_str_68c995d857916300158891cd] = {
        {
          n_models = 1,
          model_data = 'troop_successors_el_yellow'
        }
    }

    --Lykian or Pamphylian vassal javelinmen - LF
    g_models[g_str_68c995d857916300158891d0] =  {
      {
        model_data = 'troop_ancient_spanish_caetrati'
      }
    }

    --Lysimachid Camp
    g_models[g_str_5fb1b9dee1af060017709671_camp] = g_models[g_str_5fb1b9dde1af06001770961d_camp]

    --Lysimachid Camp Fort
    g_models[g_str_5fb1b9dee1af060017709671_camp_fortified] = g_models[g_str_5fb1b9dde1af06001770961d_camp_fortified]


--

-- Antigonid
army['5fb1b9dee1af060017709665'].data.has_models = true
army['5fb1b9dee1af060017709665'].data.base = "tile_grass"
  -- Antigonid
  -- 320 BC to 285 BC
  -- https://meshwesh.wgcwar.com/armyList/5fb1b9dee1af060017709665/explore
  -- As of: 20210412

    --Xystophoroi - Kn General
    g_models[g_str_68c995d85791630015889176_general] =  {
      {
        n_models = 3,
        fixed_models = {
            [1] = 'troop_successors_cavalry_bodyguard_black',
            [2] = 'troop_successors_cavalry_general_green',
            [3] = 'troop_successors_cavalry_bodyguard_black'
        }
      }
    }

    --Xystophoroi - Kn
    g_models[g_str_68c995d85791630015889176] =  {
      {
        model_data = 'troop_successors_cavalry_bodyguard_black'
      }
    }

    --Macedonian Phalanx - Pikes General
    g_models[g_str_68c995d85791630015889178_general] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_successors_pike1',
          [2] = 'troop_successors_pike2',
          [3] = 'troop_successors_cavalry_general_green',
          [4] = 'troop_successors_pike1'
      }
      }
    }

    --Macedonian Phalanx - Pikes
    g_models[g_str_68c995d85791630015889178] = g_models[g_str_68c995d7579163001588905b]

    --War elephants
    g_models[g_str_68c995d8579163001588917a] = {
      {
        n_models = 1,
        model_data = 'troop_successors_el_black'
      }
    }

    --Persian or Thracian horsemen armed with javelins - JavCav General
    g_models[g_str_68c995d8579163001588917d_general] ={
      {
        n_models = 2,
        fixed_models = {
          [1] = 'troop_successors_lh_black',
          [2] = 'troop_successors_cavalry_general_green'
      }
      }
    }

    --Persian or Thracian horsemen armed with javelins - JavCav
    g_models[g_str_68c995d8579163001588917d] = g_models[g_str_68c995d8579163001588913d]

    --Pantodapoi phalanx - Pikes General
    g_models[g_str_68c995d8579163001588917f_general] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_successors_pike1_black',
          [2] = 'troop_successors_pike1_black',
          [3] = 'troop_successors_cavalry_general_green',
          [4] = 'troop_successors_pike1_black'
      }
      }
    }

    --Pantodapoi phalanx - Pikes General with Elephant Screen
    g_models[g_str_68c995d8579163001588917f_general_elephant_screen] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_successors_pike1_black',
          [2] = 'troop_successors_pike1_black',
          [3] = 'troop_successors_cavalry_general_green',
          [4] = 'troop_successors_pike1_black'
      }
      }
    }

    --Pantodapoi phalanx - Pikes
    g_models[g_str_68c995d8579163001588917f] = {
      {
        random_models = {
          'troop_successors_pike1_black',
          'troop_successors_pike2_black'
        }
      }
    }

    --Pantodapoi phalanx - Pikes with Elephant Screen
    g_models[g_str_68c995d8579163001588917f_elephant_screen] = g_models[g_str_68c995d8579163001588917f]

    --Mercenary peltasts - LF General
    g_models[g_str_68c995d85791630015889144_general] = {
      loose = true,
      {
        n_models = 3,
        fixed_models = {
            [1] = 'troop_successors_psiloi',
            [2] = 'troop_successors_cavalry_general',
            [3] = 'troop_successors_psiloi'
        }
      }
    }

    --Greek mercenary peltasts - LF
    g_models[g_str_68c995d85791630015889182] = g_models[g_str_68c995d75791630015889066]

    --Greek mercenary hoplites - HF
    g_models[g_str_68c995d85791630015889184] = g_models[g_str_68c995d75791630015889062]

    --Macedonian or mercenary skirmishing bowmen and slingers - Sk
    g_models[g_str_68c995d85791630015889187] = g_models[g_str_68c995d857916300158891c6]

    --Akontistai - Rabble
    g_models[g_str_68c995d85791630015889189] = {
      loose = true,
      {
        random_models = {
          'troop_successors_ax_red',
          'troop_successors_ax_blue',
          'troop_successors_ax_green',
          'troop_successors_ax_black',
          'troop_successors_ax',
        }
      }
    }

    --Lykian or Pamphylian foot - Rabble
    g_models[g_str_68c995d8579163001588918c] = {
      {
        loose = true,
        model_data = 'troop_ancient_spanish_caetrati'
      }
    }
    --Greek allies hoplites - HF
    g_models[g_str_68c995d8579163001588918f] = {
      {
        random_models = {
          'troop_successors_hypaspist',
          'troop_successors_hypaspist_black',
          'troop_successors_hypaspist_blue',
          'troop_successors_hypaspist_green',
          'troop_successors_hypaspist_yellow',
        }
      }
    }

    --Stone throwers and ballistae - Art
    g_models[g_str_68c995d85791630015889193] = g_models[g_str_68c995d75791630015889069]

    --Antigonid Camp
    g_models[g_str_5fb1b9dee1af060017709665_camp] = g_models[g_str_5fb1b9dde1af06001770961d_camp]

    --Antigonid Camp Fort
    g_models[g_str_5fb1b9dee1af060017709665_camp_fortified] = g_models[g_str_5fb1b9dde1af06001770961d_camp_fortified]


--
army_dates["5fb1b9dee1af060017709665"]["*Antigonos - 320 BC to 301 BC"] ="5fb1b9dee1af060017709665_-320_-316"
army_dates["5fb1b9dee1af060017709665"]["*Demetrios - 315 BC to 285 BC"] ="5fb1b9dee1af060017709665_Demetrios"
  army['5fb1b9dee1af060017709665_Demetrios']={
    data={
      name='Antigonid - *Demetrios - 300 BC to 285 BC',
      id='5fb1b9dee1af060017709665_Demetrios',
      army_id='5fb1b9dee1af060017709665',
      base="tile_grass"
    },
    g_base_definitions[g_str_68c995d85791630015889176_general],
    g_base_definitions[g_str_68c995d85791630015889176],
    g_base_definitions[g_str_68c995d85791630015889178],
    g_base_definitions[g_str_68c995d8579163001588917a],
    g_base_definitions[g_str_68c995d8579163001588917d_general],
    g_base_definitions[g_str_68c995d8579163001588917d],
    g_base_definitions[g_str_68c995d8579163001588917f],
    g_base_definitions[g_str_68c995d8579163001588917f_elephant_screen],
    g_base_definitions[g_str_68c995d85791630015889182],
    g_base_definitions[g_str_68c995d85791630015889184],
    g_base_definitions[g_str_68c995d85791630015889187],
    g_base_definitions[g_str_68c995d85791630015889189],
    g_base_definitions[g_str_68c995d8579163001588918f],
    g_base_definitions[g_str_68c995d85791630015889193],
    g_base_definitions[g_str_5fb1b9dee1af060017709665_camp],
    g_base_definitions[g_str_5fb1b9dee1af060017709665_camp_fortified],
  }
--

-- Early Ptolemaic
army['5fb1b9dfe1af06001770970f'].data.has_models = true
army['5fb1b9dfe1af06001770970f'].data.base = "tile_grass"

  -- Early Ptolemaic
  -- 320 BC to 275 BC
  -- https://meshwesh.wgcwar.com/armyList/5fb1b9dfe1af06001770970f/explore
  -- As of: 20210414

    --Xystophoroi - Kn General
    g_models[g_str_68c995d9579163001588943d_general] =  {
      loose = true,
      {
        n_models = 3,
        fixed_models = {
            [1] = 'troop_successors_cavalry_bodyguard_red',
            [2] = 'troop_successors_cavalry_general_black',
            [3] = 'troop_successors_cavalry_bodyguard_red'
        }
      }
    }

    --Xystophoroi\nDeployment dismounted from Knights General - Pikes General
    g_models[g_str_68c995d9579163001588943d_general_dismounted] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_successors_pike1_red',
          [2] = 'troop_successors_pike1_red',
          [3] = 'troop_successors_cavalry_general_black',
          [4] = 'troop_successors_pike1_red'
        }
      }
    }

    --Xystophoroi\nDeployment dismounting as Pikes - Kn General
    g_models[g_str_68c995d9579163001588943d_general_mounted] =  {
      {
        n_models = 3,
        fixed_models = {
            [1] = 'troop_successors_cavalry_bodyguard_red',
            [2] = 'troop_successors_cavalry_general_black',
            [3] = 'troop_successors_cavalry_bodyguard_red'
        }
      }
    }

    --Xystophoroi - Kn
    g_models[g_str_68c995d9579163001588943d] =  {
      {
        model_data = 'troop_successors_cavalry_bodyguard_red'
      }
    }

    --Xystophoroi\nDeployment dismounted from Knights - Pikes
    g_models[g_str_68c995d9579163001588943d_dismounted] =  {
      {
        model_data = 'troop_successors_pike1_red'
      }
    }

    --Xystophoroi\nDeployment dismounting as Pikes - Kn
    g_models[g_str_68c995d9579163001588943d_mounted] =  {
      {
        model_data = 'troop_successors_cavalry_bodyguard_red'
      }
    }

    --Greek mercenaries, Tarentines, or similar horsemen - JavCav General
    g_models[g_str_68c995d95791630015889440_general] ={
      loose = true,
      {
        n_models = 2,
        fixed_models = {
          [1] = 'troop_successors_lh_red',
          [2] = 'troop_successors_cavalry_general_black'
       }
      }
    }

    --Greek mercenaries, Tarentines, or similar horsemen - JavCav
    g_models[g_str_68c995d95791630015889440] = {
      loose = true,
      {
        model_data = 'troop_successors_lh_red'
      }
    }

    --Phalanx - Pikes General
    g_models[g_str_68c995d95791630015889442_general] = {
      {
        n_models = 4,
        fixed_models = {
          [1] = 'troop_successors_pike1_black',
          [2] = 'troop_successors_pike1_black',
          [3] = 'troop_successors_cavalry_general_green',
          [4] = 'troop_successors_pike1_black'
        }
      }
    }

    --Phalanx - Pikes General with Elephant Screen
    g_models[g_str_68c995d95791630015889442_general_elephant_screen] =  g_models[g_str_68c995d95791630015889442_general]

    --Phalanx - Pikes
    g_models[g_str_68c995d95791630015889442] = {
      {
        model_data = 'troop_successors_pike1_black'
      }
    }

    --Phalanx - Pikes with Elephant Screen
    g_models[g_str_68c995d95791630015889442_elephant_screen] = g_models[g_str_68c995d95791630015889442]

    --Mercenary peltasts - LF General
    g_models[g_str_68c995d95791630015889445_general] = g_models[g_str_68c995d85791630015889144_general]

    --Greek mercenary peltasts - LF
    g_models[g_str_68c995d95791630015889445] = g_models[g_str_68c995d75791630015889066]

    --Thracian light infantry - LF
    g_models[g_str_68c995d95791630015889447_general] = {
      {
        n_models = 3,
        fixed_models = {
            [1] = 'troop_thracian_ax1',
            [2] = 'troop_successors_cavalry_general_black',
            [3] = 'troop_thracian_ax1'
        }
      },
      {
        n_models = 3,
        fixed_models = {
            [1] = 'troop_thracian_axgen',
            [2] = 'troop_successors_cavalry_general_black',
            [3] = 'troop_thracian_axgen'
        }
      }
    }
    --Thracian light infantry - LF
    g_models[g_str_68c995d95791630015889447] = g_models[g_str_68c995d85791630015889146]

    --Indian war elephants
    g_models[g_str_68c995d9579163001588944a] = {
      {
        n_models = 1,
        model_data = 'troop_carthaginian_elephant'
      }
    }

    --Cretan skirmishing bowmen - Sk
    g_models[g_str_68c995d9579163001588944d] = g_models[g_str_68c995d75791630015889060]

    --Akontistai - Rabble
    g_models[g_str_68c995d9579163001588944f] = g_models[g_str_68c995d85791630015889189]

    --Bolt-shooters - Art
    g_models[g_str_68c995d95791630015889451] = g_models[g_str_68c995d75791630015889069]

    --Early Ptolemaic Camp
    g_models[g_str_5fb1b9dfe1af06001770970f_camp] = g_models[g_str_5fb1b9dde1af06001770961d_camp]

    --Early Ptolemaic Camp Fort
    g_models[g_str_5fb1b9dfe1af06001770970f_camp_fortified] = g_models[g_str_5fb1b9dde1af06001770961d_camp_fortified]

    --Early Ptolemaic Camp  Trains
    g_models[g_str_5fb1b9dfe1af06001770970f_camp_pack_train] = g_models[g_str_5fb1b9dde1af06001770961d_camp_pack_train]


--

-- Eumenes
army['5fb1b9dee1af06001770966b'].data.has_models = true
army['5fb1b9dee1af06001770966b'].data.base = "tile_grass"
  -- Eumenes
  -- 320 BC to 316 BC
  -- https://meshwesh.wgcwar.com/armyList/5fb1b9dee1af06001770966b/explore
  -- As of: 20210414

    --Xystophoroi - Kn General
    g_models[g_str_68c995d8579163001588919b_general] =  {
      loose = true,
      {
        n_models = 3,
        fixed_models = {
            [1] = 'troop_successors_cavalry_bodyguard_green',
            [2] = 'troop_successors_cavalry_general_red',
            [3] = 'troop_successors_cavalry_bodyguard_green'
        }
      }
    }

    --Xystophoroi - Kn
    g_models[g_str_68c995d8579163001588919b] =  {
      loose = true,
      {
        model_data = 'troop_successors_cavalry_bodyguard_green'
      }
    }

    --Persian or Thracian horsemen armed with javelins - JavCav General
    g_models[g_str_68c995d8579163001588919d_general] ={
      loose = true,
      {
        n_models = 2,
        fixed_models = {
          [1] = 'troop_successors_lh_green',
          [2] = 'troop_successors_cavalry_general_red'
      }
      }
    }

    --Persian or Thracian horsemen armed with javelins - JavCav
    g_models[g_str_68c995d8579163001588919d] = g_models[g_str_68c995d8579163001588913d]


    --Agyraspids and Hypaspists - Pikes
    g_models[g_str_68c995d8579163001588919f] = {
      {
        random_models = {
          'troop_successors_pike1_blue',
          'troop_successors_pike2_blue'
        }
      }
    }

    --Pantodapoi phalanx - Pikes
    g_models[g_str_68c995d857916300158891a1] = {
      {
        random_models = {
          'troop_successors_pike1_green',
          'troop_successors_pike2_green'
        }
      }
    }

    --Pantodapoi phalanx - Pikes with Elephant Screen
    g_models[g_str_68c995d857916300158891a1_elephant_screen] =  g_models[g_str_68c995d857916300158891a1]

    --Greek mercenary peltasts - LF
    g_models[g_str_68c995d857916300158891a4] = g_models[g_str_68c995d75791630015889066]

    --Greek mercenary hoplites - HF
    g_models[g_str_68c995d857916300158891a6] = g_models[g_str_68c995d75791630015889062]

    --Macedonian or mercenary skirmishing bowmen and slingers - Sk
    g_models[g_str_68c995d857916300158891a9] = g_models[g_str_68c995d857916300158891c6]

    --Persian skirmising bowmen and slingers - Sk
    g_models[g_str_615351a303385c0016b85c45] = {
      {
        loose = true,
        model_data = 'troop_ancient_spanish_slingers'
      }
    }
    --Akontistai - Rabble
    g_models[g_str_68c995d857916300158891ad] = g_models[g_str_68c995d85791630015889189]

    --Indian War elephants
    g_models[g_str_68c995d857916300158891b0] = {
      {
        n_models = 1,
        model_data = 'troop_successors_el_green'
      },
      {
        n_models = 1,
        model_data = 'troop_carthaginian_elephant'
      }
   }
    --Eumenes Camp
    g_models[g_str_5fb1b9dee1af06001770966b_camp] = g_models[g_str_5fb1b9dde1af06001770961d_camp]

    --Eumenes Camp Fort
    g_models[g_str_5fb1b9dee1af06001770966b_camp_fortified] = g_models[g_str_5fb1b9dde1af06001770961d_camp_fortified]


--

-- Alketas
army['5fb1b9dee1af06001770965f'].data.has_models = true
army['5fb1b9dee1af06001770965f'].data.base = "tile_grass"
  -- Alketas
  -- 320 BC
  -- https://meshwesh.wgcwar.com/armyList/5fb1b9dee1af06001770965f/explore
  -- As of: 20210414

    --Xystophoroi - Kn General
    g_models[g_str_68c995d85791630015889161_general] =  {
      {
        n_models = 3,
        fixed_models = {
            [1] = 'troop_successors_cavalry_bodyguard_green',
            [2] = 'troop_successors_cavalry_general_yellow',
            [3] = 'troop_successors_cavalry_bodyguard_green'
        }
      }
    }

    --Xystophoroi - Kn
    g_models[g_str_68c995d85791630015889161] = g_models[g_str_68c995d8579163001588919b]

    --Persian or Thracian horsemen armed with javelins - JavCav General
    g_models[g_str_68c995d85791630015889163_general] ={
      {
        n_models = 2,
        fixed_models = {
          [1] = 'troop_successors_lh_green',
          [2] = 'troop_successors_cavalry_general_yellow'
      }
      }
    }

    --Persian or Thracian horsemen armed with javelins - JavCav
    g_models[g_str_68c995d85791630015889163] = g_models[g_str_68c995d8579163001588913d]

    --Pantodapoi phalanx - Pikes
    g_models[g_str_68c995d85791630015889165] = {
      {
        random_models = {
          'troop_successors_pike1_green',
          'troop_successors_pike2_green'
        }
      }
    }

    --Greek mercenary peltasts - LF
    g_models[g_str_68c995d85791630015889167] = g_models[g_str_68c995d75791630015889066]

    --Greek mercenary hoplites - HF
    g_models[g_str_68c995d85791630015889169] = g_models[g_str_68c995d75791630015889062]

    --Macedonian or mercenary skirmishing bowmen and slingers - Sk
    g_models[g_str_68c995d8579163001588916c] = g_models[g_str_68c995d857916300158891c6]

    --Akontistai - Rabble
    g_models[g_str_68c995d8579163001588916e] = g_models[g_str_68c995d85791630015889189]

    --Psidian peltasts - LF
    g_models[g_str_68c995d85791630015889170] = g_models[g_str_68c995d857916300158891d0]

    --Alketas Camp
    g_models[g_str_5fb1b9dee1af06001770965f_camp] = g_models[g_str_5fb1b9dde1af06001770961d_camp]

    --Alketas Camp Fort
    g_models[g_str_5fb1b9dee1af06001770965f_camp_fortified] = g_models[g_str_5fb1b9dde1af06001770961d_camp_fortified]



--

-- Phyrric
army['5fb1b9dee1af060017709677'].data.has_models = true
army['5fb1b9dee1af060017709677'].data.base="tile_grass"

  -- Phyrric
  -- 300 BC to 272 BC
  -- https://meshwesh.wgcwar.com/armyList/5fb1b9dee1af060017709677/explore
  -- As of: 20210412

    --Epeirot or Macedonian horsemen - Kn General
    g_models[g_str_68c995d857916300158891dd_general] = g_models[g_str_68c995d75791630015889051_general]

    --Epeirot or Macedonian horsemen - Kn
    g_models[g_str_68c995d857916300158891dd] = g_models[g_str_68c995d75791630015889051]

    --Thessalian, Oscan, or Greek ally horsemen - JavCav General
    g_models[g_str_68c995d857916300158891e0_general] = {
      loose = true,
      {
        n_models = 2,
        fixed_models = {
          [1] = 'troop_successors_cavalry_general',
          [2] = 'troop_thracian_cv'
        }
      }
    }

    --Thessalian, Oscan, or Greek ally horsemen - JavCav
    g_models[g_str_68c995d857916300158891e0] = g_models[g_str_68c995d75791630015889078]

    --Thessalian, Oscan, or Greek ally horsemen - Bad Horse
    g_models[g_str_68c995d857916300158891e1] = g_models[g_str_68c995d7579163001588907c]

    --Horsemen with shields in Tarentine style - JavCav General
    g_models[g_str_68c995d857916300158891e4_general] = {
      loose = true,
      {
        n_models = 2,
        fixed_models = {
          [1] = 'troop_successors_lh',
          [2] = 'troop_successors_cavalry_general'
        }
      }
    }

    --Horsemen with shields in Tarentine style - JavCav
    g_models[g_str_68c995d857916300158891e4] = {
      loose = true,
      {
        model_data = 'troop_successors_lh'
      }
    }

    --Phalanx - Pikes
    g_models[g_str_68c995d857916300158891e6] = g_models[g_str_68c995d7579163001588905b]

    --Phalanx - Pikes with Elephant Screen
    g_models[g_str_68c995d857916300158891e6_elephant_screen] =  g_models[g_str_68c995d7579163001588905b]

    --Skirmishing bowmen and slingers - Sk
    g_models[g_str_68c995d857916300158891e9] = g_models[g_str_68c995d857916300158891c6]

    --Greek, Italiote, or Oscan javelinmen - LF
    g_models[g_str_68c995d857916300158891eb] = g_models[g_str_68c995d75791630015889066]

    --War elephants
    g_models[g_str_68c995d857916300158891ee] = {
        {
          n_models = 1,
          model_data = 'troop_successors_el'
        },
        {
          n_models = 1,
          model_data = 'troop_carthaginian_elephant'
        }
    }
    --Galatian fierce fighters - Warriors
    g_models[g_str_68c995d857916300158891f2] = g_models[g_str_68c995d75791630015888e4e_dismounted]

    --Phyrric Camp
    g_models[g_str_5fb1b9dee1af060017709677_camp] = g_models[g_str_5fb1b9dde1af06001770961d_camp]

    --Phyrric Camp Fort
    g_models[g_str_5fb1b9dee1af060017709677_camp_fortified] = g_models[g_str_5fb1b9dde1af06001770961d_camp_fortified]

    --Phyrric Camp Trains and Herds - NOT YET
    g_models[g_str_5fb1b9dee1af060017709677_camp_pack_train] = g_models[g_str_5fb1b9dde1af06001770961d_camp_pack_train]

--
