-- Early Hoplite Greek: Sparta
army['5fb1b9dbe1af060017709502'].data.has_models = true
army['5fb1b9dbe1af060017709502'].data.base="tile_grass"

  -- Early Hoplite Greek: Sparta
  -- 669 to 449 BC
  -- https://meshwesh.wgcwar.com/armyList/5fb1b9dbe1af060017709502/explore
  -- As of: 20210608

    --Spartiates - Elite Foot General
    g_models[g_str_68c995d55791630015888bbc_general] = {
      {
        n_models = 4,
        fixed_models = {
            [1] = 'troop_spartan_elite_hoplite',
            [2] = 'troop_spartan_general_hoplite_01',
            [3] = 'troop_spartan_elite_hoplite',
            [4] = 'troop_spartan_elite_hoplite'
        }
      }
    }

    --Spartiates - Elite Foot
    g_models[g_str_68c995d55791630015888bbc] = {
      {
        n_models = 4,
        model_data = 'troop_spartan_elite_hoplite'
      }
    }

    --Hoplites - Heavy Foot
    g_models[g_str_68c995d55791630015888bbf] = {
      {
        n_models = 4,
        model_data = 'troop_carthaginian_allied_greek_spear'
      }
    }

    --Skirmishing bowmen and slingers - Sk
    g_models[g_str_68c995d55791630015888bc1] = {
      {
        n_models = 2,
        model_data = 'troop_successors_skirmishers',
        loose = true
      }
    }

    --Javelinmen - Rabble
    g_models[g_str_68c995d55791630015888bc3] = {
      {
        n_models = 3,
        random_models = {
          'troop_successors_psiloi',
          'troop_successors_psiloi_black',
          'troop_successors_psiloi_red',
          'troop_successors_psiloi_blue',
          'troop_successors_psiloi_green'
        },
        loose = true
      }
    }

    --Massed helots armed with javelins -- Horde
    g_models[g_str_68c995d55791630015888bc6] = {
      {
        n_models = 7,
        model_data = 'troop_ancient_spanish_caetrati',
        loose = true
      }
    }

    --Massed helots armed with javelins -- Rabble
    g_models[g_str_68c995d55791630015888bc7] = {
      {
        n_models = 3,
        model_data = 'troop_ancient_spanish_caetrati',
        loose = true
      }
    }

    --Spartan Camp
    g_models[g_str_5fb1b9dbe1af060017709502_camp] = {
      {
        n_models = 1,
        model_data = 'troop_carthaginian_camp'
      }
    }
--

-- Later Hoplite Spartan
army['5fb1b9dde1af0600177095dc'].data.has_models = true
army['5fb1b9dde1af0600177095dc'].data.base="tile_grass"

  -- Later Hoplite Spartan
    -- 448 BC to 225 BC
    -- https://meshwesh.wgcwar.com/armyList/5fb1b9dde1af0600177095dc/explore
    -- As of: 20210616

      --Spartiates - Elite Foot General
      g_models[g_str_68c995d75791630015888f38_general] = g_models[g_str_68c995d55791630015888bbc_general]

      --Spartiates - Elite Foot
      g_models[g_str_68c995d75791630015888f38] = g_models[g_str_68c995d55791630015888bbc]

      --Hoplites - Heavy Foot
      g_models[g_str_68c995d75791630015888f3c] = g_models[g_str_68c995d55791630015888bbf]

      --Psiloi armed with javelins - Rabble
      g_models[g_str_68c995d75791630015888f3f] = g_models[g_str_68c995d55791630015888bc7]

      --Spartan horsemen - Bad Horse
      g_models[g_str_68c995d75791630015888f41] = {
        {
          n_models = 3,
          model_data = 'troop_successors_cav_red',
          loose = true
        }
      }

      --Cretan or other skirmishing mercenary bowmen - Sk
      g_models[g_str_68c995d75791630015888f43] = {
        {
          n_models = 2,
          model_data = 'troop_successors_skirmishers_archers',
          loose = true
        }
      }

      --Skirmishing slingers - Sk
      g_models[g_str_68c995d75791630015888f45] = g_models[g_str_68c995d55791630015888bc1]

      --Thracian infantry -- LF
      g_models[g_str_68c995d75791630015888f47] = {
        {
          n_models = 3,
          random_models = {
            'troop_thracian_ax1',
            'troop_thracian_axgen'
          },
          loose = true
        }
      }

      --Mercenary peltasts -- LF
      g_models[g_str_68c995d75791630015888f49] = {
        {
          n_models = 3,
          random_models = {
            'troop_successors_psiloi',
            'troop_successors_psiloi_black',
            'troop_successors_psiloi_red',
            'troop_successors_psiloi_blue',
            'troop_successors_psiloi_green'
          },
          loose = true
        }
      }

      --Akarnanians -- LF
      g_models[g_str_68c995d75791630015888f4d] = {
        {
          n_models = 3,
          random_models = {
            'troop_successors_psiloi',
            'troop_successors_psiloi_black',
            'troop_successors_psiloi_red',
            'troop_successors_psiloi_blue',
            'troop_successors_psiloi_green'
          },
          loose = true
        }
      }

      --Spartan Camp
      g_models[g_str_5fb1b9dde1af0600177095dc_camp] = {
        {
          n_models = 1,
          model_data = 'troop_carthaginian_camp'
        }
      }

      --Spartan Camp Pack Train
      g_models[g_str_5fb1b9dde1af0600177095dc_camp_pack_train] = g_models[g_str_5fb1b9e1e1af060017709849_camp_pack_train]
--
