-- Camillan Roman
-- 400 BC to 276 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9dce1af060017709543/explore
-- As of: 20210402

-- Camillan Roman
army['5fb1b9dce1af060017709543'].data.has_models = true
army['5fb1b9dce1af060017709543'].data.base = "tile_grass"

--data = {
--  Invasion = 3,
--  maneuver = 2,
--  terrain = 'Arable',
--  list = 'Mandatory: 3 x Elite Foot, 3 x Heavy Foot, 2 x Rabble, 1 x Light Foot.',
--  general = 'General: Javelin Cavalry. Otherwise: Bad Horse. Otherwise: Elite Foot.',
--  manufacturer = 'Xyston and Essex miniatures'
--},

    -- Roman and better ally horsemen - JavCav
    g_models[g_str_68c995d65791630015888ce8] = {
      {
        model_data = 'troop_camillan_roman_bodyguard'
      }
    }
    -- Italian ally horsemen - BadHorse
    g_models[g_str_68c995d65791630015888cea] = {
      {
        model_data = 'troop_camillan_roman_cavalry'
      }
    }

    -- Triarii, principes, and better-equipped hastati
    g_models[g_str_68c995d65791630015888cec] = {
      {
        model_data = 'troop_camillan_roman_spear'
      },
      {
        model_data = 'troop_camillan_roman_blade'
      }
    }

    -- Hastati, or Latin ally heavy infantry
    g_models[g_str_68c995d65791630015888cef] = {
      {
        model_data = 'troop_camillan_roman_blade_plain_shield'
      }
    }

    -- Leves and rorarii
    g_models[g_str_68c995d65791630015888cf1] = {
      {
        loose = true,
        model_data = 'troop_camillan_roman_psiloi'
      }
    }

    -- Accensi
    g_models[g_str_68c995d65791630015888cf3] = {
      {
        model_data = 'troop_camillan_roman_accensi'
      }
    }

    -- Italian allied infantry
    g_models[g_str_68c995d65791630015888cf5] = {
      {
        model_data = 'troop_camillan_roman_allied_spear'
      }
    }

    -- Javelin Cavalry General
    g_models[g_str_68c995d65791630015888ce8_general] = {
      {
        n_models = 2,
        fixed_models = {
            [1] = 'troop_camillan_roman_bodyguard',
            [2] = 'troop_camillan_roman_general'
        }
      }
    }

    -- Bad Horse General
    g_models[g_str_68c995d65791630015888cea_general] = {
      {
        n_models = 3,
        fixed_models = {
            [1] = 'troop_camillan_roman_cavalry',
            [2] = 'troop_camillan_roman_general',
            [3] = 'troop_camillan_roman_cavalry'
        }
      }
    }

    -- Elite Foot General
    g_models[g_str_68c995d65791630015888cec_general] = {
        {
          n_models = 4,
          fixed_models = {
            [1] = 'troop_camillan_roman_spear',
            [2] = 'troop_camillan_roman_general',
            [3] = 'troop_camillan_roman_spear',
            [4] = 'troop_camillan_roman_spear'
        }
      }
    }

    -- Roman Camp
    g_models[g_str_5fb1b9dce1af060017709543_camp] = g_models[g_str_5fb1b9dce1af06001770959d_camp]

    -- Roman Camp Fortified
    g_models[g_str_5fb1b9dce1af060017709543_camp_fortified] = {
      {
        overlay_models = { -- each of the models are placed on top of the base
          {
            model_data="troop_fortified_camp_outline_40x40",
            position={x=-0,y=0,z=0}, -- optional defaults to (0,0,0)
            rotation=0, -- optional defaults to 0
            scale=1, -- optional defaults t0 1
          },
          {
            model_data = 'troop_camillan_roman_camp',
            scale=0.7
          }
        }
      }
    }

    -- Roman Camp pack trains
    g_models[g_str_5fb1b9dce1af060017709543_camp_pack_train] = g_models[g_str_5fb1b9e1e1af060017709849_camp_pack_train]

-- Polybian Roman
-- 275 to 105 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9dde1af0600177095c0/explore
-- As of: 20210403

--data = {
 -- Invasion = 3,
 -- maneuver = 2,
--  terrain = 'Arable, Hilly',
--  list = 'Mandatory: 1 x Javelin Cavalry, 4 x Elite Foot, 1 x Rabble, 1 x Light Foot.',
 -- general = 'General: Javelin Cavalry.',
 -- manufacturer = 'Xyston, Essex and Corvus Belli miniatures'
--},

-- Polybian Roman
army['5fb1b9dde1af0600177095c0'].data.has_models = true
army['5fb1b9dde1af0600177095c0'].data.base = "tile_grass"


    -- Roman, Gallic, Spanish, and effective allied horsemen - JavCav
    g_models[g_str_68c995d75791630015888eb1] = {
      {
        model_data = 'troop_camillan_roman_bodyguard'
      },
      {
        model_data = 'troop_gallic_cav'
      },
      {
        model_data = 'troop_ancient_spanish_lh'
      }
    }

    -- Legionaries
    g_models[g_str_68c995d75791630015888eb3] = g_models[g_str_68c995d65791630015888cec]

    -- Raw, mutinous, or recently recruited legionaries
    -- &
    -- Large numbers of recently recruited legionaries
    g_models[g_str_68c995d75791630015888eb6] = g_models[g_str_68c995d65791630015888cef]
    g_models[g_str_68c995d75791630015888eb9] = g_models[g_str_68c995d65791630015888cef]

    -- Leves - Rabble
    g_models[g_str_68c995d75791630015888ebc] = g_models[g_str_68c995d65791630015888cf1]

    -- Velites - Light Foot
    g_models[g_str_68c995d75791630015888ebf] = {
      {
        model_data = 'troop_camillan_roman_psiloi'
      }
    }

    -- Italian allied horsemen or hamippoi (light foot mixed with cavalry)
    g_models[g_str_68c995d75791630015888ec1] = {
      {
        model_data = 'troop_camillan_roman_cavalry'
      },
      {
        n_models = 3,
        fixed_models = {
            [1] = 'troop_camillan_roman_cavalry',
            [2] = 'troop_ancient_spanish_caetrati',
            [3] = 'troop_camillan_roman_cavalry'
        }
      },
      {
        n_models = 3,
        fixed_models = {
          [1] = 'troop_camillan_roman_cavalry',
          [2] = 'troop_successors_psiloi',
          [3] = 'troop_camillan_roman_cavalry'
      }
      }
    }

    -- Italian allied light infantry
    g_models[g_str_68c995d75791630015888ec3] = {
      {
        model_data = 'troop_camillan_roman_accensi'
      }
    }

    -- Skirmishing bowmen and slingers
    g_models[g_str_68c995d75791630015888ec5] = g_models[g_str_68c995d75791630015888e84]

    -- Spanish or Illyrian light infantry
    g_models[g_str_68c995d75791630015888ec7] = {
      {
        model_data = 'troop_ancient_spanish_caetrati'
      },
      {
        model_data = 'troop_successors_psiloi'
      }
    }

    -- Gallic tribesmen - Warriors
    g_models[g_str_68c995d75791630015888eca] = {
      {
        random_models = {
          'troop_gallic_warriors',
          'troop_gallic_warriors_2'
        }
      }
    }

    -- Roman, Gallic, Spanish, and effective allied horsemen - JavCav General
    g_models[g_str_68c995d75791630015888eb1_general] = {
      {
        n_models = 2,
        fixed_models = {
            [1] = 'troop_camillan_roman_bodyguard',
            [2] = 'troop_camillan_roman_general'
        }
      },
      {
        n_models = 2,
        fixed_models = {
            [1] = 'troop_camillan_roman_general',
            [2] = 'troop_gallic_cav'
        }
      },
      {
        n_models = 2,
        fixed_models = {
            [1] = 'troop_ancient_spanish_lh',
            [2] = 'troop_camillan_roman_general'
        }
      }
    }

    -- Roman Camp
    g_models[g_str_5fb1b9dde1af0600177095c0_camp] = g_models[g_str_5fb1b9dce1af060017709543_camp]

    -- Roman Camp Fort
    g_models[g_str_5fb1b9dde1af0600177095c0_camp_fortified] = g_models[g_str_5fb1b9dce1af060017709543_camp_fortified]

    -- Roman Camp pack trains
    g_models[g_str_5fb1b9dde1af0600177095c0_camp_pack_train] = g_models[g_str_5fb1b9dce1af060017709543_camp_pack_train]


-- Marian Roman
-- 105 BC to 25 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9e1e1af06001770980d/explore
-- As of: 20210618

-- Marian Roman
army['5fb1b9e1e1af06001770980d'].data.has_models = true
army['5fb1b9e1e1af06001770980d'].data.base = "tile_grass"


    -- Allied veteran horsemen - JavCav Gen
    g_models[g_str_68c995da57916300158897d1_general] = {
      {
        n_models = 2,
        fixed_models = {
          [1] = 'troop_marian_roman_cv_bearer',
          [2] = 'troop_marian_roman_cv_gen',
        }
      }
    }

    -- Allied veteran horsemen - JavCav
    g_models[g_str_68c995da57916300158897d1] = {
      {
        model_data = 'troop_marian_roman_cv'
      }
    }

    -- Legionaries - EF Gen
    g_models[g_str_68c995da57916300158897d3_general] = {
      {
        n_models = 4,
        model_data = 'troop_marian_roman_bd_gen'
      }
    }
    -- Legionaries - EF
    g_models[g_str_68c995da57916300158897d3] = {
      {
        n_models = 4,
        model_data = 'troop_marian_roman_bd_elite'
      }
    }
    -- Unreliable or raw Gallic or other horsemen - Bad Horse
    g_models[g_str_68c995da57916300158897d6] = {
      {
        model_data = 'troop_gallic_cav'
      }
    }

    -- Raw Legionaries - HF
    g_models[g_str_68c995da57916300158897d8] = {
      {
        n_models = 4,
        model_data = 'troop_marian_roman_bd'
      }
    }

    -- Skirmishing slingers or bowmen -- Sk
    g_models[g_str_68c995da57916300158897da] = {
      {
        model_data = 'troop_carthaginian_slingers'
      }
    }

    -- Velites or allied javelinmen - LF
    g_models[g_str_68c995da57916300158897dc] = {
      {
        model_data = 'troop_camillan_roman_psiloi'
      }
    }

    -- Thureophoroi or peltasts - LF
    g_models[g_str_68c995da57916300158897de] = {
      {
        model_data = 'troop_successors_psiloi'
      }
    }

    -- Bolt shooters - Art
    g_models[g_str_68c995da57916300158897e0] = {
      {
        n_models = 1,
        model_data = 'troop_successors_art'
      }
    }

-- TODO
    -- Thracian or client horse archers - Horse Bow
--    g_models[g_str_5fb1ba0de1af06001770acb3] = {
--      {
--        model_data = 'troop_marian_roman_lh'
--      }
--    }

    -- Client foot bowmen - Archers
--    g_models[g_str_5fb1ba0de1af06001770acb5] = {
--      {
--        model_data = 'troop_gallic_ps_archer'
--      }
--    }
--
--    -- Client foot bowmen - Bow Levy
--    g_models[g_str_5fb1ba0de1af06001770acb6] = {
--      {
--        model_data = 'troop_gallic_ps_archer'
--      }
--    }

    -- Roman Camp
    g_models[g_str_5fb1b9e1e1af06001770980d_camp] = g_models[g_str_5fb1b9dce1af060017709543_camp]

    -- Marian Roman Camp Fort
    g_models[g_str_5fb1b9e1e1af06001770980d_camp_fortified] = {
      {
        n_models = 1,
        model_data = 'troop_marian_roman_camp'
      }
    }
    -- Marian Roman Camp pack trains
    g_models[g_str_5fb1b9e1e1af06001770980d_camp_pack_train] = g_models[g_str_5fb1b9dce1af060017709543_camp_pack_train]

-- Campanian
-- 420 BC to 341 BC
-- https://meshwesh.wgcwar.com/armyList/5fb1b9dbe1af06001770952e/explore
-- As of: 20210618

-- Campanian
army['5fb1b9dbe1af06001770952e'].data.has_models = true
army['5fb1b9dbe1af06001770952e'].data.base = "tile_grass"


    -- Horsemen - JavCav Gen
    g_models[g_str_68c995d65791630015888cb7_general] = {
      {
        n_models = 3,
        model_data = 'troop_campanian_roman_cv_gen'
      }
    }

    -- Horsemen - JavCav
    g_models[g_str_68c995d65791630015888cb7] = {
      {
        model_data = 'troop_campanian_roman_cv'
      }
    }

    -- Velites or allied javelinmen - LF
    g_models[g_str_68c995d65791630015888cb9] = {
      {
        model_data = 'troop_successors_psiloi_green'
      }
    }

    -- Javelinmen without shields or disinterested foot -- Rabble
    g_models[g_str_68c995d65791630015888cbb] = {
      {
        model_data = 'troop_successors_ax_green'
      }
    }

    -- Hoplites - HF
    g_models[g_str_68c995d65791630015888cbd] = {
      {
        n_models = 4,
        random_models = {
          'troop_successors_spear1_green',
          'troop_successors_spear2_green'
        }

      }
    }

    -- Campanian Camp
    g_models[g_str_5fb1b9dbe1af06001770952e_camp] = g_models[g_str_5fb1b9dce1af060017709543_camp]

    -- Campanian Camp pack trains
    g_models[g_str_5fb1b9dbe1af06001770952e_camp_pack_train] = g_models[g_str_5fb1b9dce1af060017709543_camp_pack_train]
