-- Numidian or Early Moorish
-- 215 BC to 25 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9dce1af060017709591/explore
-- As of: 20230102

-- Numidian or Early Moorish
army['5fb1b9dce1af060017709591'].data.has_models = true
army['5fb1b9dce1af060017709591'].data.base = "tile_grass"

-- Later Libyan
army['5fb1b9dce1af060017709581'].data.has_models = true
army['5fb1b9dce1af060017709581'].data.base = "tile_grass"

--},

    -- Numidian general with spanish bodyguard - JavCav General
    g_models[g_str_68c995d75791630015888e25_general] = g_models[g_str_68c995d65791630015888c8b_general]

    -- Numidian horsemen - JavCav
    g_models[g_str_68c995d75791630015888e25] = g_models[g_str_68c995d65791630015888c9f]
    
    -- Javelinmen - LF
    g_models[g_str_68c995d75791630015888e27] = g_models[g_str_68c995d65791630015888c8e]
    
    -- Rabble javelinmen unshielded
    g_models[g_str_68c995d75791630015888e28] = {
        {
          random_models = {
            'troop_egyptian_skirmishers_javelin_carrier'
          },
          loose = true
        }
      }

    -- Skirmishing bowmen or slingers - Sk
    g_models[g_str_68c995d75791630015888e2a] = g_models[g_str_68c995d65791630015888c97]
    
    -- African forest elephant - El
    g_models[g_str_68c995d75791630015888e2c] = {
        {
          n_models = 1,
          model_data = 'troop_carthaginian_elephant_2'
        }
      }
    
    -- Roman-trained light infantry - LF
    g_models[g_str_68c995d75791630015888e2f] = g_models[g_str_68c995d75791630015888ec3]
    
    -- Imitation legionaries - HF
    g_models[g_str_68c995d75791630015888e32] = g_models[g_str_68c995da57916300158897d8]


    g_models[g_str_5fb1b9dce1af060017709591_camp] = g_models[g_str_5fb1b9dce1af060017709543_camp]

    g_models[g_str_5fb1b9dce1af060017709591_camp_pack_train] = g_models[g_str_5fb1b9dce1af060017709543_camp_pack_train]


-- Later Libyan
-- 664 BC to 70 AD
-- https://meshwesh.wgcwar.com/armyList/5fb1b9dce1af060017709581/explore
-- As of: 20230102

--},

    -- 4-horse battle platforms with javelin crew - Battle Taxi General
    g_models[g_str_68c995d75791630015888e09_general] = g_models[g_str_68c995d65791630015888c83_general]

    -- 4-horse battle platforms with javelin crew - Battle Taxi
    g_models[g_str_68c995d75791630015888e09] = g_models[g_str_68c995d65791630015888c83]
    
    -- Libyan heavy infantry with large shields and spears - HF
    g_models[g_str_68c995d75791630015888e0b] = g_models[g_str_68c995d65791630015888c90]
    
    -- Tribesmen armed with javelins, throwing sticks, and clubs - Rabble
    g_models[g_str_68c995d75791630015888e0d] = g_models[g_str_68c995d75791630015888e28]

    -- Skirmishing bowmen - Rabble
    g_models[g_str_68c995d75791630015888e0f] = g_models[g_str_68c995d75791630015888e28]

    g_models[g_str_5fb1b9dce1af060017709581_camp] = g_models[g_str_5fb1b9dce1af060017709543_camp]

    g_models[g_str_5fb1b9dce1af060017709581_camp_pack_train] = g_models[g_str_5fb1b9dce1af060017709543_camp_pack_train]


    